/**
 * audio/nameVoice — champ-select CONFIRM speaks the champion's 稱號 AND 全名
 * (task #35; the call-out became title+name in task #57).
 *
 * Data contract (`content/assets/audio/voices/names/MANIFEST.json`, generated by
 * `tools/tts-gen/src/build-champ-names.mjs`):
 *
 *   { champions: { [champId]: { zhName, zhTitle, zhFullName, spokenLine, lang,
 *                               voice, segments?, jaTitle, jaName, reading,
 *                               confidence, evidence, clip } } }
 *
 * This layer only needs `clip`; the rest is provenance that keeps the DISPLAY
 * text and the SPOKEN text from drifting. Most clips are the Apple voice Kyoko,
 * but a call-out whose 稱號 is untranslatable Taiwanese is spoken by Tingting and
 * handed to Kyoko mid-clip, and four English-named ones are wholly Karen — so do
 * NOT reintroduce a "must be Japanese/Kyoko" assumption here.
 *
 * The doc lives under `content/assets/` (NOT `content/config/`) on purpose:
 * `config/*` is a schema-validated, `_index.json`-indexed collection, so a new
 * doc id there would have to land in the shared zod union + every rebuilt index
 * at once. Assets are served verbatim from the same `/content/` mount, so this
 * file is fetched directly and 404s degrade to silence.
 *
 * PLAYBACK IS DELIBERATELY OFF THE WEBAUDIO GRAPH. The name call-out rides its
 * OWN `HTMLAudioElement` (one, reused: a new call-out replaces the previous, so
 * two names can never overlap) instead of `audioSystem.playClip`, which keeps
 * this module additive — it only READS the mixer's public surface
 * (`audioSystem.isUnlocked` / `audioSystem.volumes()` and the pure
 * `effectiveGain`) for the unlock + master/SFX mute/volume state, and never
 * touches the AudioSystem or its buses.
 *
 * Gates, in order: no champId → mixer still autoplay-locked → master or SFX
 * muted → the same champion inside the ~1 s double-fire guard. Any of them is a
 * silent `false`; the mute gate deliberately does NOT burn the guard.
 */
import { AUDIO_CONTENT_BASE, audioSystem } from "./AudioSystem";
import { effectiveGain, type VolumeState } from "./audioSelect";

/** Path of the generated name-VO manifest, relative to the content mount. */
export const NAME_VO_MANIFEST_PATH = "assets/audio/voices/names/MANIFEST.json";
/** Directory the per-champion clips live in (fallback path derivation). */
export const NAME_VO_CLIP_DIR = "assets/audio/voices/names";
/** Re-confirming the SAME champion inside this window is a no-op (double-fire). */
export const NAME_VO_GUARD_MS = 1000;
/** Clip gain, multiplied onto the master × SFX mixer level. */
export const NAME_VO_GAIN = 0.95;

/** How sure we are the Japanese reading is the canonical one. */
export type NameConfidence = "high" | "medium" | "low";

export interface ChampionNameEntry {
  /** the authored Chinese champion name, whole string incl. 稱號 (review aid) */
  zhName: string;
  /**
   * EXACTLY what the clip says: 稱號, a beat, then 全名. "‖" separates fragments
   * spoken by different voices. Empty only on pre-#57 (name-only) manifests.
   */
  spokenLine: string;
  /** the katakana 全名; EMPTY for the English-named champions (Sela, Thorne, …) */
  jaName: string;
  /** romaji of the Japanese fragments (review aid) */
  reading: string;
  confidence: NameConfidence;
  evidence: string;
  /** content-relative mp3 path */
  clip: string;
}

export interface ChampionNamesManifest {
  champions: Record<string, ChampionNameEntry>;
}

function str(v: unknown): string {
  return typeof v === "string" ? v : "";
}

/** Tolerant parse of the name manifest; null = not usable (→ silence). */
export function championNamesFromDoc(doc: unknown): ChampionNamesManifest | null {
  if (!doc || typeof doc !== "object") return null;
  const champs = (doc as { champions?: unknown }).champions;
  if (!champs || typeof champs !== "object") return null;
  const out: Record<string, ChampionNameEntry> = {};
  for (const [id, raw] of Object.entries(champs as Record<string, unknown>)) {
    if (!raw || typeof raw !== "object") continue;
    const o = raw as Record<string, unknown>;
    const spokenLine = str(o["spokenLine"]);
    const jaName = str(o["jaName"]);
    // An entry with NEITHER has nothing to say. `spokenLine` is the authority
    // since #57: the four English-named call-outs (Sela, Thorne, Johnnie Walker,
    // Wolverine) are spoken by an English voice and carry no jaName at all, so
    // gating on jaName alone would silently drop them. `jaName` on its own still
    // admits pre-#57 name-only manifests.
    if (!spokenLine && !jaName) continue;
    const confidence = o["confidence"];
    out[id] = {
      zhName: str(o["zhName"]),
      spokenLine,
      jaName,
      reading: str(o["reading"]),
      confidence:
        confidence === "high" || confidence === "medium" || confidence === "low"
          ? confidence
          : "low",
      evidence: str(o["evidence"]),
      clip: str(o["clip"]) || `${NAME_VO_CLIP_DIR}/${id}.mp3`,
    };
  }
  return { champions: out };
}

/**
 * Normalize a manifest clip path onto the content mount ("assets/…"): strips a
 * leading "/content/", "content/" or bare "/" so both spellings resolve to the
 * same URL. (Same normalization the champion-voice layer applies.)
 */
export function normalizeNameClipPath(path: string | null | undefined): string | null {
  if (typeof path !== "string") return null;
  let s = path.trim();
  if (s.startsWith("/content/")) s = s.slice("/content/".length);
  else if (s.startsWith("content/")) s = s.slice("content/".length);
  else if (s.startsWith("/")) s = s.slice(1);
  return s.length > 0 ? s : null;
}

/** Clip path for a champion: the manifest entry, else null (unmapped = silent). */
export function nameClipFor(
  manifest: ChampionNamesManifest | null,
  champId: string,
): string | null {
  const entry = manifest?.champions[champId];
  if (!entry) return null;
  return normalizeNameClipPath(entry.clip) ?? `${NAME_VO_CLIP_DIR}/${champId}.mp3`;
}

/** The slice of the mixer this layer READS (the process AudioSystem satisfies it). */
export interface NameVoiceAudioPort {
  readonly isUnlocked: boolean;
  volumes(): VolumeState;
}

/** The slice of HTMLAudioElement this layer uses (stubbed in tests). */
export interface NameVoiceElement {
  src: string;
  volume: number;
  currentTime: number;
  play(): Promise<void> | void;
  pause(): void;
}

function defaultFetch(url: string): Promise<Response> {
  if (typeof fetch !== "function") return Promise.reject(new Error("no fetch"));
  return fetch(url);
}

/** `new Audio()` when the DOM has it; null in node/vitest (→ silent no-op). */
function defaultCreateAudio(): NameVoiceElement | null {
  try {
    const g = globalThis as unknown as { Audio?: new () => HTMLAudioElement };
    return g.Audio ? (new g.Audio() as unknown as NameVoiceElement) : null;
  } catch {
    return null;
  }
}

export interface ChampionNameVoiceOptions {
  audio?: NameVoiceAudioPort;
  /** content mount base, default AUDIO_CONTENT_BASE ("/content/") */
  baseUrl?: string;
  fetchFn?: (url: string) => Promise<Response>;
  /** ms clock for the double-fire guard */
  now?: () => number;
  guardMs?: number;
  gain?: number;
  createAudio?: () => NameVoiceElement | null;
  warn?: (msg: string, err?: unknown) => void;
}

export class ChampionNameVoice {
  private readonly audio: NameVoiceAudioPort;
  private readonly baseUrl: string;
  private readonly fetchFn: (url: string) => Promise<Response>;
  private readonly now: () => number;
  private readonly guardMs: number;
  private readonly gain: number;
  private readonly createAudio: () => NameVoiceElement | null;
  private readonly warn: (msg: string, err?: unknown) => void;

  private manifestPromise: Promise<ChampionNamesManifest | null> | null = null;
  private el: NameVoiceElement | null = null;
  private elCreated = false;
  /** champId → last play timestamp (`now()` clock) */
  private readonly lastPlay = new Map<string, number>();

  constructor(opts: ChampionNameVoiceOptions = {}) {
    this.audio = opts.audio ?? audioSystem;
    this.baseUrl = opts.baseUrl ?? AUDIO_CONTENT_BASE;
    this.fetchFn = opts.fetchFn ?? defaultFetch;
    this.now =
      opts.now ?? (() => (typeof performance !== "undefined" ? performance.now() : Date.now()));
    this.guardMs = opts.guardMs ?? NAME_VO_GUARD_MS;
    this.gain = opts.gain ?? NAME_VO_GAIN;
    this.createAudio = opts.createAudio ?? defaultCreateAudio;
    this.warn = opts.warn ?? ((msg, err) => console.warn(`[nameVo] ${msg}`, err ?? ""));
  }

  /** Cached single-flight fetch of the manifest; null = missing (silence). */
  load(): Promise<ChampionNamesManifest | null> {
    if (!this.manifestPromise) {
      this.manifestPromise = this.fetchJson(NAME_VO_MANIFEST_PATH).then(championNamesFromDoc);
    }
    return this.manifestPromise;
  }

  /**
   * Speak `champId`'s Japanese full name — ONE clip per confirm. Silent `false`
   * when the mixer is autoplay-locked, master/SFX is muted, the same champion
   * is inside the ~1 s guard, the champion has no mapping, or the DOM has no
   * Audio element. The guard slot is reserved SYNCHRONOUSLY (before the async
   * manifest resolution) so a same-tick double confirm can never start two.
   */
  async play(champId: string): Promise<boolean> {
    if (!champId || !this.audio.isUnlocked) return false;
    const v = this.audio.volumes();
    const volume = effectiveGain(v, "sfx", this.gain);
    if (volume <= 0) return false; // muted: no fetch, no guard burn
    const t = this.now();
    const last = this.lastPlay.get(champId);
    if (last !== undefined && t - last < this.guardMs) return false;
    this.lastPlay.set(champId, t);

    const manifest = await this.load();
    const clip = nameClipFor(manifest, champId);
    if (!clip) return false;
    const el = this.element();
    if (!el) return false;

    try {
      el.pause(); // a new call-out replaces the previous one — never two voices
      el.src = this.url(clip);
      el.currentTime = 0;
      el.volume = volume;
      const p = el.play();
      if (p && typeof (p as Promise<void>).catch === "function") {
        void (p as Promise<void>).catch((err: unknown) => {
          this.warn(`playback blocked for ${champId} (silent)`, err);
        });
      }
      return true;
    } catch (err) {
      this.warn(`playback failed for ${champId} (silent)`, err);
      return false;
    }
  }

  /** Lazily create the single reused element (once — null result is cached). */
  private element(): NameVoiceElement | null {
    if (!this.elCreated) {
      this.elCreated = true;
      this.el = this.createAudio();
    }
    return this.el;
  }

  private url(path: string): string {
    return this.baseUrl.endsWith("/") ? this.baseUrl + path : `${this.baseUrl}/${path}`;
  }

  /** Fetch a JSON doc under the content mount; null on 404 / bad JSON / error. */
  private async fetchJson(path: string): Promise<unknown> {
    try {
      const res = await this.fetchFn(this.url(path));
      if (!res.ok) return null; // 404 = pack not generated — silence
      return (await res.json()) as unknown;
    } catch (err) {
      this.warn(`${path} failed to load (silent)`, err);
      return null;
    }
  }

  /** Drop the cached manifest + guards (tests / content live-reload). */
  reset(): void {
    this.manifestPromise = null;
    this.lastPlay.clear();
  }
}

/** Process-wide name-VO layer, reading the process-wide mixer state. */
export const championNameVoice = new ChampionNameVoice();

/** Warm the name manifest (cached; safe to call from any boot path). */
export function loadChampionNames(): Promise<ChampionNamesManifest | null> {
  return championNameVoice.load();
}

/** Speak a champion's Japanese full name (see ChampionNameVoice.play). */
export function playChampionNameVo(champId: string): Promise<boolean> {
  return championNameVoice.play(champId);
}
