"""extract_transform_forms.py — the 變身 (transform) census, task #249.

WHAT THIS RECOVERS
------------------
26 abilities in the UNPROTECTED source map carry the WC3 **Metamorphosis** field
pair on ability level 1:

    Eme1  the NORMAL-form unit rawcode      (data column 1)
    Emeu  the ALTERNATE-form unit rawcode   (data column 0)

Every champion transform in GoDieEX22s uses that one pattern, so each second
form is a COMPLETE second unit definition in war3map.w3u — its own model, scale,
movement speed, ability list and stat block — not a buff on the first.

THE IMPORTER NEVER SAW THIS. `w3xlib/stats.py` / `src_objects.py` read a
WHITELIST of ~30 of the map's 180 w3u field codes (task #56), and `Eme1`/`Emeu`
are not on it, so the base⇄alt relationship was dropped on import. The
consequence shipped: 10 of the 50 first-open-roster slots were the ALTERNATE
body, offered as if it were the hero (see apps/platform/internal/curation/
starter.go and docs/todo/champion-transform-forms.md).

WHY LEVEL 1 IS THE AUTHORITY, and reading any other level is a BUG
------------------------------------------------------------------
`Eme1`/`Emeu` are LEVELED ability fields. The map author cloned abilities freely
and only ever re-pointed level 1, so levels 2-4 of a cloned entry still hold the
DONOR's rawcodes:

    A10N 11-002 武裝色霸氣   lvl1 Udre->U01U  (correct: 索隆)
                             lvl2..4 E00K->E00Z  (leftovers from 安云's A0SZ)
    A0LN 79-04 卍解         lvl1 H01N->H01O  (correct: 黑崎一護)
                             lvl4 H01L->H01M  (a stale pair)

A "last writer wins" read of the mod list therefore produces a table that is
wrong on ~9 of the 26 pairs and silently cross-links unrelated heroes. Always
`entry.get("Eme1", 1)`.

THE DIRECTION PROOF (26/26)
---------------------------
Which of the two is the base is not inferred from the field names alone — the
map states it. Every hero unit carries a `unsf` sub-name: the base unit's is the
bare 編號 「(NN)」 and the alternate's names the form 「(NN變身名)」, e.g.
Hgam「(90)」 -> H02R「(90 妙蛙花)」, H02V「(92)」 -> H02U「(92 臥草)」. This holds
for all 26 pairs, so `Eme1` = base and `Emeu` = alternate is corroborated, not
assumed. The emitted JSON carries both sub-names so the pin test can re-check it.

DURATION comes from `ahdu` (HERO duration), not `adur`.

STOCK INHERITANCE — WHY READING THE w3a ALONE IS NOT ENOUGH
-----------------------------------------------------------
A w3a entry is a DIFF against `entry.base_id`, not a full record. Every
(field, level) the author left alone keeps Blizzard's value, and "the map is
silent" is NOT "the value is absent" — but in the w3a they look identical.

Three abilities carry no `ahdu` mod at all, and this file used to call all
three a recovered fact. Two of them are:

    A0DZ 20-01 風王結界   base ANrg, stock HeroDur1..4 = 0
    A0O6 70-00 紮根       base ANrg, stock HeroDur1   = 0

— toggles, the form persists until re-cast, and the stock row agrees (0).

The third was WRONG. `Aphx` 61-00 百連我殺 IS Blizzard's Phoenix rawcode
(`comments = "Phoenix"`, `DataA1 = hphx` the phoenix, `UnitID1 = hpxe` the
phoenix EGG — and the map's `Emeu` U011 is 「(61 鳳凰蛋)」, the same egg). Its
stock row says `HeroDur1 = 10`. The egg lasts ten seconds; the map never
disagreed, it just never spoke, and this extractor turned that silence into
`durationSecByLevel: {}`. The empty map then propagated into
`packages/shared/src/content/championForms.ts` with a comment rationalising it
("death-state morph, no hero duration") and into the pin test, which compared
the empty table to the empty fixture and passed. Four layers, all consistent,
all wrong.

So `ahdu`/`adur`/`amcs` now fall back, per LEVEL, to the base row in
`out/stock/STOCK_ABILITIES.json` (generated by `stock_ability_data.py` from the
retail MPQs). Direction is one-way: a value the map writes ALWAYS wins, stock
only fills a cell the map never wrote. Each emitted level carries its origin in
`provenance` — `"map"` or `"stock"`.

The fallback is BOUNDED BY THE ABILITY'S REAL LEVEL COUNT (`alev`, else the
stock row's `levels`), so it cannot invent levels. That bound matters: 13 of
the 26 write no `alev` and therefore have ONE level in game, yet carry mods on
levels 2-4 — the donor leftovers described above. Those stale levels are still
emitted (removing them is a separate decision) but nothing is inherited into
them.

`acdn` (cooldown) is deliberately NOT inherited here. It has the same gap —
A0DZ writes no `acdn` and stock ANrg says `Cool1..4 = 1` — but changing a
cooldown is a balance decision, not a transcription fix, so it is reported
rather than applied. See the task #249 write-up.

Output: out/GoDieEX22s-src/TRANSFORM_FORMS.json — the fixture
packages/shared/src/content/championForms.test.ts pins the shipped table
against. Re-run after any re-extract; it reads raw/war3map.{w3a,w3u,wts} plus
the checked-in out/stock/STOCK_ABILITIES.json.
"""

from __future__ import annotations

import json
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
if HERE not in sys.path:
    sys.path.insert(0, HERE)

from w3xlib.objdata import parse_object_file  # noqa: E402
from src_text import parse_wts_full, resolve, strip_codes  # noqa: E402

RAW_DIR = os.path.join(HERE, "out", "GoDieEX22s-src", "raw")
OUT_PATH = os.path.join(HERE, "out", "GoDieEX22s-src", "TRANSFORM_FORMS.json")
STOCK_PATH = os.path.join(HERE, "out", "stock", "STOCK_ABILITIES.json")

# WC3 Metamorphosis: the normal-form unit and the alternate-form unit.
NORMAL_FIELD = "Eme1"
ALTERNATE_FIELD = "Emeu"

# w3a field code -> the stock SLK column stem it inherits from. `acdn`/`Cool`
# is deliberately absent; see the module docstring.
INHERITED: dict[str, str] = {"ahdu": "HeroDur", "adur": "Dur", "amcs": "Cost"}

_SUB_NAME_NUMBER = re.compile(r"\(\s*(\d{2,3})")


def _entries(path: str, has_levels: bool) -> list:
    with open(path, "rb") as fh:
        tables = parse_object_file(fh.read(), has_levels)
    return tables["original"] + tables["custom"]


def load_stock() -> dict[str, dict]:
    """The checked-in Blizzard ability table. Missing it is FATAL.

    Falling back to "no stock" would silently restore the exact bug this
    inheritance exists to fix, and every downstream layer would agree with it.
    """
    if not os.path.exists(STOCK_PATH):
        raise SystemExit(
            f"FATAL: {STOCK_PATH} is missing.\n"
            "  Regenerate it with `python3 tools/w3x-import/stock_ability_data.py`\n"
            "  (needs the retail MPQs at the repo root; the file is checked in\n"
            "   precisely because *.mpq is not). Refusing to run without it —\n"
            "  every inherited value would silently look absent again."
        )
    with open(STOCK_PATH, encoding="utf-8") as fh:
        doc = json.load(fh)
    abilities = doc.get("abilities") or {}
    if not abilities:
        raise SystemExit(f"FATAL: {STOCK_PATH} carries no abilities.")
    return abilities


def _level_count(entry, stock_row: dict | None) -> int:
    """How many levels the ability really has: `alev`, else the base's."""
    alev = entry.get("alev")
    if isinstance(alev, (int, float)) and alev >= 1:
        return int(alev)
    if stock_row:
        levels = stock_row.get("levels")
        if isinstance(levels, (int, float)) and levels >= 1:
            return int(levels)
    return 1


def _levels(
    entry,
    code: str,
    stock_row: dict | None = None,
    level_count: int = 0,
) -> tuple[dict[str, float], dict[str, str]]:
    """`({levelString: value}, {levelString: "map"|"stock"})`, dropping zeros.

    A level the map wrote comes from the map, ALWAYS — stock only fills a level
    the map never wrote, and only within the ability's real level count. Pass
    no `stock_row` to read the map alone (the pre-inheritance behaviour).
    """
    written = entry.levels(code)
    stem = INHERITED.get(code) if stock_row else None
    candidates = set(written)
    if stem:
        candidates |= set(range(1, level_count + 1))

    out: dict[str, float] = {}
    provenance: dict[str, str] = {}
    for level in sorted(candidates):
        if level in written:
            value, source = written[level], "map"
        elif stem:
            value, source = stock_row.get(f"{stem}{level}"), "stock"
        else:
            continue
        if not isinstance(value, (int, float)) or value <= 0:
            continue
        out[str(level)] = round(float(value), 4)
        provenance[str(level)] = source
    return out, provenance


def build() -> dict:
    stock = load_stock()
    abilities = _entries(os.path.join(RAW_DIR, "war3map.w3a"), True)
    units = _entries(os.path.join(RAW_DIR, "war3map.w3u"), False)
    with open(os.path.join(RAW_DIR, "war3map.wts"), "rb") as fh:
        strings = parse_wts_full(fh.read())[0]

    by_rawcode = {u.obj_id.upper(): u for u in units}

    def text(value) -> str | None:
        if not isinstance(value, str):
            return None
        return strip_codes(resolve(value, strings)).strip() or None

    def unit_view(rawcode: str) -> dict:
        unit = by_rawcode.get(rawcode)
        champion_id = f"godie-{rawcode.lower()}"
        return {
            "rawcode": rawcode,
            "championId": champion_id,
            "subName": text(unit.get("unsf")) if unit else None,
            "properName": text(unit.get("upro")) if unit else None,
            "model": unit.get("umdl") if unit else None,
            "scale": unit.get("usca") if unit else None,
            "moveSpeed": unit.get("umvs") if unit else None,
            "inW3u": unit is not None,
        }

    pairs: list[dict] = []
    for entry in abilities:
        # LEVEL 1 ONLY — see the module docstring; higher levels hold donor data.
        normal = entry.get(NORMAL_FIELD, 1)
        alternate = entry.get(ALTERNATE_FIELD, 1)
        if not normal or not alternate:
            continue
        base = unit_view(str(normal).upper())
        alt = unit_view(str(alternate).upper())
        sub = base["subName"] or ""
        match = _SUB_NAME_NUMBER.search(sub)

        # The row this entry is a DIFF against; None when the base is itself a
        # map object (no stock row), in which case nothing can be inherited.
        stock_row = stock.get(entry.base_id)
        level_count = _level_count(entry, stock_row)
        # ahdu = HERO duration, the field that governs a hero's morph.
        duration, duration_src = _levels(entry, "ahdu", stock_row, level_count)
        # adur is the non-hero duration; kept for the 3 no-ahdu entries.
        unit_duration, unit_duration_src = _levels(entry, "adur", stock_row, level_count)
        mana, mana_src = _levels(entry, "amcs", stock_row, level_count)
        # acdn is NOT inherited — a balance decision, not a transcription fix.
        cooldown, _ = _levels(entry, "acdn")

        pairs.append(
            {
                "heroNumber": match.group(1) if match else None,
                "abilityRawcode": entry.obj_id,
                "abilityBase": entry.base_id,
                "abilityName": text(entry.get("anam")),
                "normalUnit": base,
                "alternateUnit": alt,
                "durationSecByLevel": duration,
                "cooldownSecByLevel": cooldown,
                "manaCostByLevel": mana,
                "unitDurationSecByLevel": unit_duration,
                # Where every emitted level came from: "map" (the w3a wrote it)
                # or "stock" (inherited from `abilityBase` in the MPQ table).
                "provenance": {
                    "durationSecByLevel": duration_src,
                    "cooldownSecByLevel": {k: "map" for k in cooldown},
                    "manaCostByLevel": mana_src,
                    "unitDurationSecByLevel": unit_duration_src,
                },
                "stockBase": {
                    "alias": entry.base_id,
                    "inStockTable": stock_row is not None,
                    "levelCount": level_count,
                },
            }
        )

    pairs.sort(key=lambda p: (p["heroNumber"] or "zz", p["abilityRawcode"]))
    return {
        "schema": "w3x-transform-forms@1",
        "source": "src_gogodieEX227s.w3x — war3map.w3a Eme1/Emeu (level 1) + war3map.w3u",
        "generatedBy": "tools/w3x-import/extract_transform_forms.py",
        "mechanism": (
            "WC3 Metamorphosis family: ability field Eme1 = normal-form unit rawcode, "
            "Emeu = alternate-form unit rawcode. Read at LEVEL 1 only — cloned abilities "
            "keep the donor's rawcodes on levels 2-4."
        ),
        "directionProof": (
            "every normal unit's `unsf` sub-name is the bare 編號 「(NN)」 and every "
            "alternate's names the form 「(NN變身名)」 — 26/26."
        ),
        "inheritance": {
            "stockTable": "tools/w3x-import/out/stock/STOCK_ABILITIES.json",
            "fields": dict(INHERITED),
            "rule": (
                "a w3a entry is a DIFF against `abilityBase`: a (field, level) "
                "the map writes ALWAYS wins, and stock fills only a cell the "
                "map never wrote, bounded by the ability's real level count "
                "(`alev`, else the base row's `levels`) so no level is invented."
            ),
            "notInherited": (
                "`acdn` (cooldown) has the same gap — A0DZ writes none and stock "
                "ANrg says Cool1..4 = 1 — but changing a cooldown is a balance "
                "decision, not a transcription fix, so it is reported not applied."
            ),
        },
        "count": len(pairs),
        "pairs": pairs,
    }


def main() -> None:
    doc = build()
    with open(OUT_PATH, "w", encoding="utf-8") as fh:
        json.dump(doc, fh, ensure_ascii=False, indent=2)
        fh.write("\n")
    print(f"{doc['count']} transform pairs -> {OUT_PATH}")


if __name__ == "__main__":
    main()
