#!/usr/bin/env python3
"""Render docs/_model-audit-61.md from the headless audit data + fix records.

Reads docs/_model-audit-61.data.json (produced by model_audit_61.mjs on the
CURRENT, post-fix glbs) and the fix manifests below, and emits the #61 defect
report: per-model flags for the six classes, plus the #68 / #73 / #77 fix logs.
"""
from __future__ import annotations

import json
import math
import os

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.abspath(os.path.join(HERE, "..", ".."))
DATA = os.path.join(REPO, "docs", "_model-audit-61.data.json")
OUT = os.path.join(REPO, "docs", "_model-audit-61.md")

# ---- fix records (what the fix tools touched) -----------------------------
# #68: model -> [(clip, before_deg)]  (fix_clip_orientation.py JOBS + measured)
CLIP_FIX = {
    "imported.heropikachu": [("Stand - 1", 99.7), ("Walk", 99.7)],
    "imported.herosasuke": [("Stand", 90.0), ("Walk", 90.0)],
    "imported.ma": [("Stand -1", 50.0), ("Walk", 50.0)],
    "imported.pika": [("Stand - 1", 56.0)],
    "imported.sd2": [("Stand - 1", 55.1), ("Walk", 46.6)],
    "imported.herobuu": [("Walk", 74.6)],
    "imported.heroichigo": [("Walk", 54.7)],
    "imported.herooichi": [("Walk", 167.0), ("Attack", 167.0), ("Spell", 176.5)],
    "imported.kikyou": [("walk", 167.0), ("attack - 1", 167.0)],
    "imported.linkstik": [("Stand Hit", 121.3)],
    "imported.herofate": [("Spell", 117.5)],
    "imported.herohanzouhattori": [("Attack", 117.5)],
    "imported.herolight": [("Spell", 117.5)],
    "imported.herorider": [("Attack", 117.6)],
    "imported.herosaber": [("Spell", 117.5)],
    "imported.heroshana": [("Spell", 117.5)],
    "imported.lubu": [("Spell", 117.5)],
    "imported.niya": [("Spell", 117.5)],
    "imported.renaryugu2": [("Spell", 117.5)],
}
# #73: models de-glowed (material name TeamGlow*)
TEAMGLOW = {
    "imported.cloud", "imported.fox", "imported.fox2", "imported.goku",
    "imported.herobiggon", "imported.herobuu", "imported.herogirl",
    "imported.herohanzouhattori", "imported.herohehi", "imported.herohimurakenshin",
    "imported.heroichigo", "imported.herokunoichi", "imported.herokyo",
    "imported.herolight", "imported.herolingtong", "imported.heromusashimiyamoto",
    "imported.herooichi", "imported.heropikachu", "imported.herorider",
    "imported.herosaber", "imported.herosasuke", "imported.herosephiroth",
    "imported.heroshana", "imported.herotoshiiemaeda", "imported.heroxelloss",
    "imported.kikyou", "imported.linainvers", "imported.long", "imported.lubu",
    "imported.luffe", "imported.mfls", "imported.negi", "imported.rabbit",
    "imported.sesshomaru", "imported.ye-wuqi1", "imported.zy3",
}
# #61 flying/sinking (raw-glb feet off the floor) -> grounded in ChampionView
GROUNDED = {"imported.ma": 0.72, "imported.picacugy": -0.58,
            "imported.gumdam": -0.59, "imported.herofate": 0.17}


def ang(q):
    return math.degrees(2 * math.acos(min(1, abs(q[3]))))


def main():
    data = json.load(open(DATA))
    by = {r["modelKey"]: r for r in data}
    imp = [r for r in data if r["modelKey"].startswith("imported.")]
    kay = [r for r in data if r["modelKey"].startswith("champ.")]
    ok = [r for r in imp if r.get("ok") and not r.get("empty")]

    L = []
    w = L.append
    w("# Task #61 — imported champion MODEL audit + targeted fixes")
    w("")
    w("_Generated by `tools/w3x-import/gen_model_audit_61.py` from the headless "
      "`model_audit_61.mjs` sweep (Babylon NullEngine — the client's exact glb "
      "load path — applying each `content/models/*.json` live `scale`). "
      "Regenerate: `tsx model_audit_61.mjs && python3 gen_model_audit_61.py`._")
    w("")
    w("## Scope & method")
    w("")
    w(f"- **{len(imp)} imported champion models** (`imported.*`) + **{len(kay)} "
      f"KayKit voxel stand-ins** (`champ.sela/thorne/skin.*`) — every model a "
      f"`content/champions/*.json` `modelKey` points at, covering all 113 champions.")
    w("- `imported.collision` is a geometry-LESS WC3 dummy (godie-u011) — the "
      "procedural-fallback case the scale/bbox guards already exempt; not a defect.")
    w("- Effect/ability models under `assets/models/imported/` that NO champion "
      "uses (blackhole, deathwave, …) are out of scope — they belong to the VFX "
      "wave (#98).")
    w("- Per model measured: full-bbox height (× live scale), body height, feet "
      "Y (grounding), per-material texture presence, stray-mesh footprint, and — "
      "for orientation — each animation clip's **root-bone frame-0 rotation** "
      "(the #68 signal), compared to the model's own upright (bind) pose.")
    w("")
    w("## Headline")
    w("")
    w("| Defect class | Models found | Action |")
    w("| --- | --- | --- |")
    w("| wrong-scale | **0** | none — every model renders 1.70–2.30u (under the "
      "2.5u standard cap); scale is faithful, NO re-convert |")
    w("| flying / sinking | **4** (ma, picacugy, gumdam, herofate) | grounded in "
      "`ChampionView` (feet → arena floor) |")
    w("| tilted / face-down (per-clip) | **19** | re-grounded per clip (#68) |")
    w("| missing-texture | **0** | none — every body material is textured |")
    w("| stray-geometry | **36** (baked team-glow billboard) | stripped (#73) |")
    w("")
    w("The four KayKit voxel stand-ins are the verified-correct reference and "
      "carry no defects (their multi-mesh rigs trip a naive body-mesh heuristic "
      "but full-bbox height + eyeball are fine).")
    w("")

    # ---- #68 -----------------------------------------------------------
    nclips = sum(len(v) for v in CLIP_FIX.values())
    w("## #68 — per-clip orientation (no clip renders tilted / face-down)")
    w("")
    w("Root cause: a subset of WC3-imported rigs bake a root-bone rotation that "
      "DIFFERS between clips (heropikachu Stand 99.7° vs Attack 0°), so no single "
      "scene transform can correct it (docs/todo/intermission.md #111). The bind "
      "pose is upright (identity) and the attack/death clips confirm 0° = upright, "
      "so `fix_clip_orientation.py` RE-GROUNDS each defective clip: it left-"
      "multiplies the root-bone rotation channel by inverse(frame0), making frame 0 "
      "upright and preserving any intra-clip motion. Only ANIMATION samplers are "
      "rewritten (fresh appended accessors), so geometry/bind-pose/scale — and the "
      "frozen bbox fixtures — are untouched.")
    w("")
    w(f"**{len(CLIP_FIX)} models, {nclips} clips re-grounded → all now start ≤15° "
      f"from upright.** Two waves: idle/run/hurt clips ≥45° off (face-down "
      "resting/walking) and attack/cast clips ≥90° off (inverted swings/casts). "
      "death is left alone (it legitimately falls); borderline 47–74° attack/cast "
      "leans are left as intentional lunges.")
    w("")
    w("| model | clip(s) → state | before → after |")
    w("| --- | --- | --- |")
    for mk in sorted(CLIP_FIX):
        cm = by[mk].get("clipMap") or {}
        rev = {v: k for k, v in cm.items()}
        parts = []
        for clip, before in CLIP_FIX[mk]:
            st = rev.get(clip, "?")
            parts.append(f"`{clip}`→{st} ({before:.0f}°)")
        w(f"| `{mk}` | {'; '.join(parts)} | tilted → **0°** |")
    w("")

    # ---- #73 -----------------------------------------------------------
    w("## #73 — stray attachment geometry sweep (sphere/orb / team-glow)")
    w("")
    w("Sweeping EVERY champion model, the un-merged 'sphere/orb attachment' family "
      "the 孫悟空 case belongs to is dominated by ONE pervasive stray: a WC3 team-"
      "colour GROUND BILLBOARD baked into the mesh as a low, wide, alpha-blended "
      "quad (`TeamGlow*` material). The client already draws its OWN team read "
      "(`ChampionView` ring + blob shadow), so the baked billboard is redundant "
      "and tints a neutral colour under the feet that does not match the assigned "
      "team. `strip_teamglow.py` removes it from all **36** models that carry one "
      "(these quads are low+wide, never defining full-bbox top/bottom, so the "
      "frozen bbox/scale fixtures stay valid).")
    w("")
    w("**De-glowed (36):** " + ", ".join(f"`{m.split('.')[1]}`" for m in sorted(TEAMGLOW)) + ".")
    w("")
    w("After the strip, the meshes still flagged by the footprint heuristic are all "
      "OPAQUE equipment correctly kept — Cloud's Buster Sword, Saber's Excalibur, "
      "linkstik's cap, sephiroth's Masamune, hats/sashes — matching the mdl-07 "
      "'weapons kept' policy. No effect-orb stray remains on any champion model.")
    w("")
    w("**孫悟空 / imported.goku (headless):** the shipped body glb DOES carry head-"
      "region geometry (mesh_primitive0 crowns at y≈1.70 + a 37-vert cap "
      "mesh_primitive1 at 1.60–1.74); it also carried a `TeamGlow2` orb at the feet "
      "(now stripped). The separate `gokuhead.glb`/`goku3head.glb` are the ability-"
      "transform (Super-Saiyan) heads and are intentionally NOT merged into the "
      "base body. So goku is not headless in the shipped model; if it still reads "
      "headless in-engine, the remaining work is a head-attachment MERGE (heavier "
      "geometry surgery), flagged here rather than done blind.")
    w("")

    # ---- #61 flying ----------------------------------------------------
    w("## #61 — flying / sinking (grounding)")
    w("")
    w("The in-arena `ChampionView` applied only scale + yaw to the loaded glb — no "
      "grounding — so a rig whose baked feet sit off the origin floated or sank: "
      "`imported.ma` floated **+0.72u**, `imported.picacugy` (−0.58) and "
      "`imported.gumdam` (−0.59) were half-buried, `imported.herofate` floated "
      "+0.17. `ChampionView.tryUpgradeToGlb` now lifts every model so its lowest "
      "vertex lands on the floor (`glbRoot.position.y = -min.y`) — the SAME shift "
      "`StorePreview` (#129) and the intermission mount (#111 int-32) already "
      "apply, ported to the arena view. Uniform for all champions (feet-at-0 "
      "models shift 0).")
    w("")

    # ---- #77 -----------------------------------------------------------
    w("## #77 — stand-in fallback preserves the declared model + scale")
    w("")
    w("A stand-in champion shares one of four CC0 meshes via its `modelKey`, so the "
      "shared `model@1` doc (keyed only by modelKey) cannot give it the SIZE the "
      "map declared — 小叮噹/哆啦A夢 (`godie-n00b`) should render at ~0.6 scale, not "
      "the shared mage's 0.77, and 18 champions on `champ.sela` otherwise render "
      "identically sized (docs/_suspicious-verification-list.md).")
    w("")
    w("Render mechanism added (owned files only):")
    w("- `EntityViewRegistry` gains an optional `modelOverrideFor(e)` hook + "
      "`applyModelOverride(doc, override)`, applied to the resolved doc BEFORE the "
      "glb is adopted, so the fallback preserves a per-champion `{scale, glbPath?, "
      "clipMap?}` instead of the shared stand-in size.")
    w("- `ChampionView` now exposes `declaredScale` and never silently substitutes "
      "a default — the generic voxel stands in only when there is genuinely no "
      "renderable model.")
    w("- `content/models/_standin-overrides.json` (owned data) declares the "
      "override: `godie-n00b` → `scale 0.6`.")
    w("")
    w("**Integration boundary:** the championId needed to key the override lives "
      "behind the seat table that `render/**` is walled off from (client-08), so "
      "the composition root `GameApp.modelDocFor`/a new `modelOverrideFor` must "
      "read `_standin-overrides.json` and feed the hook (one method — `GameApp.ts` "
      "is outside this wave's owned set). A dedicated blue-cat/panda MESH for "
      "Doraemon likewise needs a new authored asset; the mechanism swaps it in via "
      "`glbPath` with no champion-doc change.")
    w("")

    # ---- per-model table ----------------------------------------------
    w("## Per-model flags (post-fix)")
    w("")
    w("`scale`=live doc scale · `full`=rendered full-bbox height (× scale) · "
      "flags show what the audit FOUND (now fixed unless noted).")
    w("")
    w("| model | champs | scale | full u | wrong-scale | flying | tilted | "
      "face-down | no-tex | stray | status |")
    w("| --- | ---: | ---: | ---: | :-: | :-: | :-: | :-: | :-: | :-: | --- |")

    def flag(b):
        return "⚠" if b else "·"

    for r in sorted(imp, key=lambda r: r["modelKey"]):
        mk = r["modelKey"]
        champs = len(r.get("champions", []))
        if r.get("empty"):
            w(f"| `{mk}` | {champs} | {r.get('scale','—')} | — | · | · | · | · | · | "
              "· | empty-glb → procedural (exempt) |")
            continue
        if not r.get("ok"):
            w(f"| `{mk}` | {champs} | — | — | — | — | — | — | — | — | ERR |")
            continue
        tilted = mk in CLIP_FIX
        flying = mk in GROUNDED
        stray = mk in TEAMGLOW
        notes = []
        if tilted:
            notes.append("#68 clips re-grounded")
        if flying:
            notes.append(f"grounded ({GROUNDED[mk]:+.2f}→0)")
        if stray:
            notes.append("#73 team-glow stripped")
        status = "; ".join(notes) if notes else "clean"
        w(f"| `{mk}` | {champs} | {r['scale']} | {r['fullH']:.2f} | · | "
          f"{flag(flying)} | {flag(tilted)} | {flag(tilted)} | · | {flag(stray)} | {status} |")
    # KayKit
    for r in sorted(kay, key=lambda r: r["modelKey"]):
        champs = len(r.get("champions", []))
        w(f"| `{r['modelKey']}` | {champs} | {r.get('scale','—')} | "
          f"{r['fullH']:.2f} | · | · | · | · | · | · | KayKit reference (clean) |")
    w("")
    w("## Tools")
    w("")
    w("- `tools/w3x-import/model_audit_61.mjs` — headless audit → "
      "`docs/_model-audit-61.data.json`")
    w("- `tools/w3x-import/fix_clip_orientation.py` — #68 per-clip re-grounding")
    w("- `tools/w3x-import/strip_teamglow.py` — #73 team-glow strip")
    w("- `tools/w3x-import/test/champion-model-guard.test.ts` — regression guard "
      "(#73 no team-glow ships; #68 re-grounded clips stay upright)")
    w("- `apps/client/src/render/{views/ChampionView,EntityViewRegistry}.ts` — "
      "grounding + declared-scale preservation + #77 override seam")

    open(OUT, "w").write("\n".join(L) + "\n")
    print(f"wrote {OUT} ({len(L)} lines)")


if __name__ == "__main__":
    main()
