#!/usr/bin/env python3
"""Render docs/_model-size-audit-150.md from the headless size-audit data.

Reads docs/_model-size-audit-150.data.json (produced by model_size_audit_150.mjs
via the client's exact Babylon NullEngine load path) and emits the #150 champion
render-SIZE report: the per-champion BEFORE→AFTER rendered-height table proving
the pre-#150 spread tightened to the target band, with the intentional
relativeScale exceptions listed.

Regenerate: `node_modules/.bin/tsx tools/w3x-import/model_size_audit_150.mjs \
             && python3 tools/w3x-import/gen_model_size_audit_150.py`
"""
from __future__ import annotations

import json
import os
import statistics

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.abspath(os.path.join(HERE, "..", ".."))
DATA = os.path.join(REPO, "docs", "_model-size-audit-150.data.json")
OUT = os.path.join(REPO, "docs", "_model-size-audit-150.md")


def main() -> None:
    blob = json.load(open(DATA, encoding="utf8"))
    target = blob["target"]
    rows = blob["rows"]

    sized = [r for r in rows if isinstance(r.get("curRendered"), (int, float))]
    empty = [r for r in rows if r.get("empty")]
    errs = [r for r in rows if r.get("error")]
    sized.sort(key=lambda r: r["curRendered"])

    curs = [r["curRendered"] for r in sized]
    med = statistics.median(curs)
    cur_lo, cur_hi = min(curs), max(curs)

    dflt = [r for r in sized if r["relMult"] == 1]
    exc = [r for r in sized if r["relMult"] != 1]
    exc.sort(key=lambda r: r["normRendered"])
    norm_lo = min(r["normRendered"] for r in sized)
    norm_hi = max(r["normRendered"] for r in sized)

    L: list[str] = []
    L.append("# Task #150 — champion render-SIZE audit + height-normalization")
    L.append("")
    L.append(
        "_Generated by `tools/w3x-import/gen_model_size_audit_150.py` from the headless "
        "`model_size_audit_150.mjs` sweep (Babylon NullEngine — the client's exact glb load "
        "path: `instantiateModelsToScene` + the same `getHierarchyBoundingVectors` measure "
        "`ChampionView` grounds by). Regenerate: `tsx model_size_audit_150.mjs && python3 "
        "gen_model_size_audit_150.py`._"
    )
    L.append("")
    L.append("## Problem")
    L.append("")
    L.append(
        "`ChampionView.tryUpgradeToGlb` used to set `glbRoot.scaling.setAll(doc.scale)` and "
        "ground the feet, but did NO height-normalization — so the rendered size was "
        "`doc.scale × the glb's native mesh height`, which varies wildly per champion. The #61 "
        "audit only checked the 2.5u ceiling, never RELATIVE consistency between champions."
    )
    L.append("")
    L.append(
        f"Measured across the roster, the on-screen full-silhouette height (what the player sees, "
        f"what grounding uses) spanned **{cur_lo:.2f}u..{cur_hi:.2f}u** "
        f"(**{cur_hi / cur_lo:.2f}× spread**, median {med:.2f}u). The four shared CC0 stand-in "
        f"meshes are the oversized group — **champ.sela renders {cur_hi:.2f}u** (小叮噹/godie-n00b "
        f"and 17 others, the user's '小叮噹 too big') — while imported heroes such as "
        f"**imported.heroshana render 1.70u** (夏娜/godie-e008), reading small next to them."
    )
    L.append("")
    L.append("## Fix")
    L.append("")
    L.append(
        f"`ChampionView` now HEIGHT-NORMALIZES every loaded glb: it measures the native "
        f"full-silhouette height and scales the model so it stands ≈ **TARGET_HEIGHT = {target}u** "
        f"tall, REPLACING the raw-`doc.scale`-as-absolute. A per-champion **`relativeScale`** "
        f"multiplier (default 1.0; `content/models/_standin-overrides.json`, keyed by championId, "
        f"threaded through `EntityViewRegistry.modelOverrideFor` → "
        f"`ChampionView.tryUpgradeToGlb`) then intentionally shrinks lore-small "
        f"creatures / enlarges giants. #77's grounding + declared-scale reporting are preserved; "
        f"`doc.scale` is kept only as a fallback for a degenerate (unmeasurable) glb."
    )
    L.append("")
    L.append("## Result")
    L.append("")
    L.append(
        f"| | rendered-height spread | note |"
    )
    L.append("| --- | --- | --- |")
    L.append(
        f"| **BEFORE** | {cur_lo:.2f}u .. {cur_hi:.2f}u ({cur_hi / cur_lo:.2f}×) | median {med:.2f}u; inconsistent |"
    )
    L.append(
        f"| **AFTER** (default population, {len(dflt)}) | **{target:.2f}u flat** | every non-exception champion reads the same size |"
    )
    L.append(
        f"| **AFTER** (incl. {len(exc)} intentional exceptions) | {norm_lo:.2f}u .. {norm_hi:.2f}u | the only remaining spread is deliberate |"
    )
    L.append("")
    if empty:
        L.append(
            "_Exempt (empty-glb → procedural voxel fallback, no glb size): "
            + ", ".join(r["id"] for r in empty)
            + "._"
        )
        L.append("")

    L.append("### Intentional size exceptions (`relativeScale`)")
    L.append("")
    L.append("| championId | name | relativeScale | rendered (u) |")
    L.append("| --- | --- | --- | --- |")
    for r in exc:
        L.append(f"| `{r['id']}` | {r['name']} | {r['relMult']} | {r['normRendered']:.2f} |")
    L.append("")
    L.append("### Spot-checks")
    L.append("")
    for cid in ("godie-e008", "godie-n00b"):
        r = next((x for x in sized if x["id"] == cid), None)
        if not r:
            continue
        L.append(
            f"- **{r['name']}** (`{cid}`, {r['modelKey']}): native {r['nativeH']:.2f}u → "
            f"BEFORE {r['curRendered']:.2f}u (scale {r['curScale']}) → AFTER {r['normRendered']:.2f}u "
            f"(relativeScale {r['relMult']})."
        )
    L.append("")

    L.append("## Per-champion table (sorted by BEFORE rendered height)")
    L.append("")
    L.append("`nativeH` = glb full-silhouette height at scale 1 (the normalization basis). "
             "`BEFORE` = nativeH × current doc.scale (renders today). "
             "`AFTER` = TARGET × relativeScale.")
    L.append("")
    L.append("| championId | name | modelKey | nativeH | doc.scale | BEFORE | relMult | AFTER |")
    L.append("| --- | --- | --- | ---: | ---: | ---: | ---: | ---: |")
    for r in sized:
        flag = ""
        if r["curRendered"] < 0.7 * med:
            flag = " ⬇"
        elif r["curRendered"] > 1.3 * med:
            flag = " ⬆"
        L.append(
            f"| `{r['id']}` | {r['name']}{flag} | `{r['modelKey']}` | {r['nativeH']:.2f} | "
            f"{r['curScale']} | {r['curRendered']:.2f} | {r['relMult']} | {r['normRendered']:.2f} |"
        )
    if empty:
        for r in empty:
            L.append(
                f"| `{r['id']}` | {r['name']} | `{r['modelKey']}` | — | — | — | — | procedural (exempt) |"
            )
    if errs:
        L.append("")
        L.append("### Errors")
        for r in errs:
            L.append(f"- `{r['id']}` ({r.get('modelKey')}): {r['error']}")
    L.append("")

    open(OUT, "w", encoding="utf8").write("\n".join(L))
    print(f"wrote {OUT} ({len(sized)} sized, {len(empty)} exempt, {len(errs)} errors)")


if __name__ == "__main__":
    main()
