from pathlib import Path
import collections,datetime,hashlib,json,shutil,struct
R=Path('/Users/Takuro/Dropbox/我的 Mac (Moriya.local)/Documents/ABxVFX_EDIT/GGD-Asset-Library/intake/public-models-20260910/fate-unlimited-codes-mod-models-batch7');assert not (R/'control/handoff.json').exists();now=datetime.datetime.now(datetime.timezone.utc).isoformat()
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def put(p,x):p.write_text(json.dumps(x,ensure_ascii=False,indent=2)+'\n')
def ref(p,root=R):return {'path':str(p.relative_to(root)),'bytes':p.stat().st_size,'sha256':sha(p)}
for slug in ['kotomine-kirei','dark-sakura']:
 r=R/slug;v=json.loads((r/'analysis/khronos-validation.json').read_text())
 for x in v['results']:
  assert x['report']['issues']['numErrors']==0 and x['report']['issues']['numWarnings']==0 and not x['report']['issues']['truncated'];assert x['sha256']==sha(r/x['path'])
 k=r/'download-receipts.json';assert all(x['curlExitCode']==0 and x['md5Match'] and x['sizeMatch'] for x in json.loads(k.read_text()))
k=R/'kotomine-kirei';s=R/'dark-sakura';motion=json.loads((k/'motion-index.json').read_text());seq=json.loads((k/'analysis/native-mdl-sequences.json').read_text());cpu=json.loads((k/'analysis/cpu-playback-verification.json').read_text());model=k/'converted/kotomine-kirei-standard.glb';assert cpu['modelSha256']==sha(model) and cpu['entriesWithSampledGeometryChanges']==336
b=model.read_bytes();n=struct.unpack_from('<I',b,12)[0];g=json.loads(b[20:20+n]);c={'candidateId':'fuc-mod-kotomine-kirei-sven','sourceId':'gamebanana-fuc-kotomine-kirei-291438','character':'Kotomine Kirei / 言峰綺禮','heroIds':[],'sourceGame':'Fate/unlimited codes','sourcePlatform':'unknown','platformEvidence':'Author and package identify Fate/UC but not original PSP versus PS2. Actual target model is Sven Co-op/GoldSrc MDL v10.','sourceClass':'mod-community-port','model':str(model.relative_to(k)),**{key:value for key,value in ref(model,k).items() if key!='path'},'meshCount':len(g['meshes']),'primitiveCount':sum(len(x['primitives']) for x in g['meshes']),'jointCounts':[len(x['joints']) for x in g['skins']],'sourceSkeletonBoneCount':22,'animationEntryCount':349,'timeVaryingMotionEntries':336,'sourceSequenceCount':191,'sourceMovingSequenceCount':182,'singleFramePoseEntries':9,'staticMultiFramePoseEntries':4,'textureCount':4,'sourceSkeleton':'Sven Co-op/GoldSrc MOD rig','motionOrigin':'Sven Co-op/GoldSrc MOD','originalFateAnimationsProven':False,'motionIndex':'motion-index.json','readyStage':'standard-glb-candidate','khronosValidation':'0 errors; 0 warnings; unlimited issue collection; not truncated','runtimeReady':False,'backendSelectionVerified':False,'defaultChanged':False,'manualVisualReview':'3 clips x 4 actual mesh frames inspected: standing/running/waving coherent, dark robe/hair/face textured','unitStatus':'Retained native model coordinates; metric scale not established or normalized to a hero height.','limitations':['Original platform PSP/PS2 not proven.','MOD sequence events, controller mixing and root linear-movement behavior are preserved as metadata, not executed.','GoldSrc additive/chrome/shading semantics are not fully recreated by base-color PBR.','Sven model bodypart metadata is preserved in the original and Assimp nodes; backend bodygroup selection is not integrated.']}
put(k/'candidate-manifest.json',{'schema':'ggd.model-candidates.intake@1','localRoot':str(k),'candidates':[c]})
put(k/'audioFileIndex.json',{'schema':'ggd.audio-file-index.intake@1','localRoot':str(k),'sourceId':c['sourceId'],'files':[],'audioGroups':[],'fileCount':0,'totalSeconds':0,'status':'no-audio-in-package'})
sc=json.loads((s/'candidate-manifest.json').read_text());assert len(sc['candidates'])==2
for c2 in sc['candidates']:
 c2['manualVisualReview']='CPU static skinned render inspected; complete clothed model, purple hair, black/red versus white/red outfit.';c2['khronosValidation']='0 errors; 0 warnings; unlimited issue collection; not truncated';c2['sourceOutfitEntriesRetained']=True
put(s/'candidate-manifest.json',sc)
sv=json.loads((s/'validation.json').read_text());sv.update(modelCandidates=2,sourceOutfitEntries=4,distinctStandardModelBytes=2,khronosValidation='0 errors / 0 warnings for both distinct candidates; maxIssues=0',freezeStatus='verified-for-frozen-intake');put(s/'validation.json',sv)
audio=json.loads((s/'audioFileIndex-frozen-v1.json').read_text());assert len(audio['files'])==15 and sha(s/'audioFileIndex-frozen-v1.json')=='f1c977fcd10ae56c892097181b7688548aa03cbbbb6998954fd3ee427d7e7f60'
for f in audio['files']:
 p=s/f['path'];assert p.stat().st_size==f['bytes'] and sha(p)==f['sha256']
put(s/'analysis/visual-inspection.json',{'status':'two-distinct-model-renders-inspected','previews':[ref(s/'preview/01-p1.png',s),ref(s/'preview/02-p2.png',s)],'observation':'Clothed Dark Sakura canonical red-mark motif, long purple hair and two palette variants; no missing body segments observed.','runtimePlayed':False,'sourceIdentity':'author-declared; original platform unknown'})
put(k/'analysis/visual-inspection.json',{'status':'three-clips-twelve-frames-inspected','preview':ref(k/'preview/kirei-motion-contact-sheet.png',k),'clips':['look_idle','run2','action_wave'],'observation':'Dark robe, textured face and hair present. Running and waving change limbs coherently.','allMotionPlaybackCheck':'349 entries x 5 samples = 1745 finite CPU-skinned frames; 336 change mesh positions.','runtimePlayed':False})
sourceRows=[]
for slug,ident,target,authors in [('kotomine-kirei',291438,'Sven Co-op / GoldSrc',['NicholaiParadox','Type-Moon (credited original)']),('dark-sakura',492607,'Bomb Rush Cyberfunk / Unity CrewBoom',['7Negative_Creep','MEKMKII','anonymous credited contributor'])]:
 r=R/slug;entry={'sourceId':'gamebanana-fuc-'+slug+'-'+str(ident),'sourceUrl':f'https://gamebanana.com/mods/{ident}','sourceGame':'Fate/unlimited codes','sourcePlatform':'unknown','targetModGame':target,'authors':authors,'class':'mod-community-port','status':'acquired-extracted-standard-candidates-verified','localRoot':str(r),'originalArchives':json.loads((r/'download-receipts.json').read_text()),'sourcePage':str((R/'receipts'/(slug+'-source-page.json')).relative_to(R)),'extractionManifest':'extraction.json','candidateManifest':'candidate-manifest.json','audioFileIndex':'audioFileIndex-frozen-v1.json' if slug=='dark-sakura' else 'audioFileIndex.json','fateNativePlatformVerified':False,'nativeFucPackages':0,'licenseStatus':'credit and permissions require source-specific review; no broader grant assumed'}
 sourceRows.append(entry);put(r/'source-manifest.json',{'schema':'ggd.source-manifest.intake@1','sources':[entry]})
put(R/'source-manifest.json',{'schema':'ggd.source-manifest.intake@1','localRoot':str(R),'sources':sourceRows,'newCompletePublicArchives':2,'nativeFucPspPackages':0})
put(R/'source-search-followup.json',{'schema':'ggd.source-search-audit@1','checkedAt':now,'deduplication':'Central download-sources.json inspected before download; source IDs 291438 and 492607 not present; existing Shirou/Rin/Zero-Lancer avoided.','acquiredSources':[x['sourceUrl'] for x in sourceRows],'otherRoutes':[{'url':'https://steamcommunity.com/sharedfiles/filedetails/?id=2223113301','status':'public listing states removed; no download attempted'},{'url':'https://www.nexusmods.com/honkaistarrail/mods/6?tab=description','status':'search describes composite Illya/FGO Arcade mod; page open failed, not acquired'},{'url':'https://paradoxmodding.blogspot.com','status':'linked in actual Kirei Readme; web tool non-retryable URL rejection; stopped, no alternate access'}],'priorRejectedSourcesRetried':False,'newNativePspProof':False})
(R/'control/tooling').mkdir(parents=True,exist_ok=True)
for name in ['ggd-fuc-batch7-download.py','ggd-fuc-batch7-extract.py','ggd-fuc-batch7-process-sakura.py','ggd-fuc-batch7-validate.cjs','ggd-fuc-batch7-kirei.py','ggd-fuc-batch7-kirei-playback.py','ggd-fuc-batch7-sakura-preview.py','ggd-fuc-batch7-freeze.py']:
 shutil.copyfile(Path('/private/tmp')/name,R/'control/tooling'/name)
converter=R.parent/'fate-unlimited-codes-psp-second-batch/control/tooling/ggd-fuc-convert-unity-outfit.py';shutil.copyfile(converter,R/'control/tooling/ggd-fuc-convert-unity-outfit.py')
put(R/'control/tool-dependencies.json',{'sourceExtractionHelper':str(R.parents[3]/'GGD-hero-model-options/tools/hero-model-library/extract_public_sources.py'),'unityConverter':ref(R/'control/tooling/ggd-fuc-convert-unity-outfit.py'),'assimp':'6.0.0','UnityPy':'1.25.3','KhronosValidator':'gltf-validator@2.0.0-dev.3.10; maxIssues=0','execution':'No archive-provided code, game, MOD assembly or script was executed. Parsing/conversion tools only.','frozenToolCaveat':'Converters retain task-local path assumptions. Reuse by adapting copied tools in a new batch; never regenerate into this frozen root.'})
(R/'README.md').write_text('''# Fate 角色 3D 本體 MOD：第七批凍結交付

本批取得兩個此前未登記的完整作者附件，原包、全部內含檔、來源收據、解析與轉換結果全部保留。本機即可透過 source-manifest.json、各角色 candidate-manifest.json、motion-index.json、audioFileIndex-frozen-v1.json 查詢。中央、Git、S3 與舊批均未修改。

| 來源 | 實際取得與標準候選 | 範圍 |
| --- | --- | --- |
| GameBanana 291438，NicholaiParadox 言峰綺禮 | 1 個 MDL、4 張內嵌貼圖、1 個標準 GLB、191 個原始序列 | Sven Co-op／GoldSrc MOD；原本 PSP 或 PS2 平台未知 |
| GameBanana 492607，7Negative_Creep／MEKMKII 黑櫻 | Unity 原包、2 個不同配色 GLB、15 段 PCM WAV／16.209 秒 | Bomb Rush Cyberfunk MOD；作者指稱模型和語音來自 Fate/UC，但原平台未知 |

言峰 RAR 1,105,055 bytes，SHA-256 8f9434471e43d6b10b826b41d154ae66e948841b99e02385ab979210ddbc63ef。黑櫻 7z 598,429 bytes，SHA-256 890b71eae085035e68dd3bcb60437acdc74c602e1fa3f2ba955f8939da5a3ecc。兩包均 HTTP 200，來源大小與 MD5 符合，系統 libarchive 完整安全解包。

言峰原 MDL 為 IDST v10、22 個唯一骨架節點、191 sequences，其中 55 loop、186 多幀與 5 單幀。每段原始 FPS 保留，範圍 4–40，不猜統一播放率。Assimp 展開成 349 個 blend entries，其中 336 隨時間變化、9 單幀 pose、4 多幀静態 pose；有 182 個來源 sequence 確實會動。不能把 349 個匯入項全算成 349 個有效動作，更不能算 Fate 原生動作。

所有每幀／骨架／通道展開值（1,005,312 個 DOF 樣本，包含靜態預設值）已從原 MDL RLE 解析，原量化 int16 與骨架預設值、scale 留在 analysis/source-motion-keys.npz。22 骨架命名／階層、各段 FPS／frames／loop／events／blend metadata 與 GLB TR 通道核對。最大位置誤差 3.82e-6、quaternion 誤差 2.91e-7、時間誤差 3.82e-7 秒。349 項各 5 幀，共 1745 幀 CPU 蒙皮全有限，336 項有頂點位移；站立、跑步、揮手的 12 張實際模型畫面已目視檢查。

Assimp 原始匯出把 4 張 image/rgba8888 貼圖截斷為 width bytes。本批從原 MDL 完整索引像素與 RGB palette 重建 PNG，保留原不標準 GLB作解析證據；只有 kotomine-kirei-standard.glb 是候選。同時修正 inverse bind matrix 最後一列約 1e-7 的舍入誤差，保留修正紀錄。三個不同 GLB 全數 Khronos maxIssues=0 驗證：0 error、0 warning、未截斷。

黑櫻來源有 4 個 outfit entries，但轉出的 P1/P2 各重複一次，已按完整 GLB SHA 合併成 2 個下拉候選；4 份原轉出檔與引用全部保留。每個候選有 57 個 skin joints、1 mesh，原包沒有 AnimationClip／ParticleSystem。MOD 動態頭髮／骨架控制資料留在完整 bundle／解析 JSON，未執行，也未冒充 GLB 動畫。15 WAV 已檢查 PCM frame payload 並全部 FFmpeg 解碼，角色身分與語音用途按作者／MOD 標籤保留，未逐段人工聆聽。

限制：Fate PSP 原生 FPK／GMO／動作缺口仍存在。言峰保留原 GoldSrc 座標，公尺尺度與英雄統一尺寸未定；事件、混合控制器、根位移語意與 shader 不等同原引擎實作。候選可供索引及後續整合，runtimeReady=false，未做 GGD 引擎／後台 E2E。原包與非標準中間檔不能冒充可用成品；參照 candidate-manifest.json 指定路徑。
''')
summary={'schema':'ggd.source-handoff@1','frozen':True,'frozenAt':now,'localRoot':str(R),'sourceManifest':'source-manifest.json','fileManifest':'files.sha256.json','newCompleteArchives':2,'sourceArchiveBytes':1703484,'newStandardModelCandidates':3,'nativeFucPspPackages':0,'platform':'unknown original PSP/PS2; MOD targets explicitly identified','models':[{'sourceId':x['sourceId'],'localRoot':x['localRoot'],'candidateManifest':'candidate-manifest.json'} for x in sourceRows],'audio':{'localRoot':str(s),'audioFileIndex':'audioFileIndex-frozen-v1.json','files':15,'seconds':audio['totalSeconds']},'motion':{'localRoot':str(k),'index':'motion-index.json','sourceSequences':191,'sourceMovingSequences':182,'blendEntries':349,'movingBlendEntries':336,'singleFramePoseEntries':9,'staticMultiFramePoseEntries':4,'origin':'Sven Co-op/GoldSrc MOD, not Fate native','cpuSampledFrames':1745},'validation':'All 3 distinct GLBs: Khronos 0 errors / 0 warnings, maxIssues=0, truncated=false. All original packages and converted audio fully verified.','runtimeReady':False,'centralWrites':False,'gitWrites':False,'s3Writes':False,'previousBatchWrites':False}
put(R/'control/handoff.json',summary)
files=[ref(p) for p in sorted(R.rglob('*')) if p.is_file() and p!=R/'files.sha256.json'];put(R/'files.sha256.json',{'schema':'ggd.file-sha256-manifest@1','localRoot':str(R),'frozenAt':now,'files':files,'fileCount':len(files),'totalBytes':sum(x['bytes'] for x in files),'selfExcluded':True})
for f in files:
 p=R/f['path'];assert p.stat().st_size==f['bytes'] and sha(p)==f['sha256']
report={'status':'frozen-all-files-readback-pass','localRoot':str(R),'handoff':ref(R/'control/handoff.json'),'fileManifest':ref(R/'files.sha256.json'),'verifiedFiles':len(files),'filesIncludingManifest':len(files)+1,'totalBytesExcludingManifest':sum(x['bytes'] for x in files),'standardModelCandidates':3,'originalModelSourcePackages':2,'audioFiles':15,'audioSeconds':audio['totalSeconds'],'nativeFucPspPackages':0,'motionSourceSequences':191,'motionMovingBlendEntries':336,'motionPoseEntries':13,'khronos':'3/3 distinct models pass 0 errors / 0 warnings, maxIssues=0','audioIndexFrozen':ref(s/'audioFileIndex-frozen-v1.json'),'runningSessions':[]}
put(Path('/private/tmp/ggd-fuc-mod-models-batch7-report.json'),report);print(json.dumps(report,ensure_ascii=False,indent=2))
