from pathlib import Path
import hashlib,json,shutil
ROOT=Path(__file__).resolve().parents[1]
SRC=ROOT.parents[1]/'public-models-20260911/parallel-palworld-jetragon'
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def save(p,x):p.write_text(json.dumps(x,ensure_ascii=False,indent=2)+'\n')
mapping=json.loads((ROOT/'evidence/material-mapping.json').read_text());inspect=json.loads((ROOT/'evidence/ggd-inspect.json').read_text());preserved=json.loads((ROOT/'evidence/preservation.json').read_text());render=json.loads((ROOT/'webgl-256-v1/proof.json').read_text())
original_receipt=Path('/private/tmp/ggd-jetragon-source-s3-backup.json');source_backup=json.loads(original_receipt.read_text());assert source_backup['sourceRoot']==str(SRC)
for x in source_backup['members']:
 p=SRC/x['path'];assert p.stat().st_size==x['bytes'] and sha(p)==x['sha256']
shutil.copyfile(original_receipt,ROOT/'evidence/frozen-original-source-receipt.json')
candidates=[]
for variant,row in zip(['native-res','256'],inspect['rows']):
 model=ROOT/'models'/('jetragon-materials-'+variant+'.glb');k=json.loads((ROOT/'evidence'/('khronos-'+variant+'.json')).read_text());assert k['issues']['numErrors']==0
 candidates.append({'id':'opgg-palworld-jetragon.material-bound-'+variant+'-v1','candidateId':'opgg-palworld-jetragon.material-bound-'+variant+'-v1','sourceId':'opgg-palworld-jetragon','name':'空渦龍 Jetragon OP.GG '+variant+' PBR／29動作（SSS待支援）','character':'空渦龍 / Jetragon','aliases':['空渦龍','空涡龙','Jetragon','JetDragon','SK_JetDragon'],'sourceWork':'Palworld / 幻獸帕魯','modelPath':str(model),'path':str(model),'bytes':model.stat().st_size,'sha256':sha(model),'format':'glb','existsLocal':True,'sourceClass':'original-game-extraction-community-repackage','resourceRole':'character-body','nativeAnimationCount':29,'uniqueAnimationContentCount':28,'proceduralAnimationCount':0,'boneCount':75,'triangleCount':8468,'drawPrimitiveCount':3,'sourceTextureCount':8,'embeddedTextureCount':9,'standardMaterialSourceTexturesActive':7,'sourceSSSMapRetainedInExtras':True,'readiness':'material-bound-source-candidate-pending-hero-contract','automaticEligible':False,'defaultEligible':False,'backendIntegration':{'status':'pending-hero-state-mapping-and-SSS','runtimeSelectable':False,'defaultChanged':False},'ggdInspectPassed':row['inspectPassed'],'ggdBudget':row['budget'],'khronos':{k:v for k,v in k['issues'].items() if k!='messages'},'sourceModelSha256':mapping['sourceModelSha256'],'nativeRigAndAnimationsPreserved':True,'conversionReceiptPath':str(ROOT/'evidence/material-mapping.json'),'preservationReceiptPath':str(ROOT/'evidence/preservation.json'),'webglProofPath':str(ROOT/('webgl-'+variant+'-v1')/'proof.json'),'sourceUrl':'https://op.gg/zh-tw/palworld/pals/jetragon','limitations':['SSS edge-scatter stored with original map and parameters, not executed by standard glTF.','No confirmed source Death clip and no complete GGD six-state model.json.','All29 source names preserved; no fabricated native/procedural animations.']})
save(ROOT/'candidate-additions.json',{'schema':'ggd.character-model-candidate-additions@1','candidates':candidates})
limitations=['Both GLB variants are playable material-bound source candidates, not a finalized six-state GGD hero.','Source SSS custom edge term unsupported in plain glTF; retained exactly in extras plus image.','Source polygon-offset/depthWrite/alpha-to-coverage behavior not fully expressible in glTF core.','No source-native Death clip. Six-state prepare would discard unselected source clips; deliberately not called.','Khronos warnings:2 runtime tangent-space generation,1 original nonroot skinned node. Original unused normals views retained.','Only selected9 action/view images and6 resolution comparison panels visually reviewed; all29 clips actually rendered and sampled numerically.','No collision, combat semantics, terrain contact, feet sliding, runtime load or performance claim.']
delivery={'schema':'ggd.jetragon.material-conversion-delivery@1','root':str(ROOT),'status':'frozen-material-bound-source-candidates','frozenOriginalSourceIntakeUnchanged':True,'frozenOriginalVerifiedFiles':len(source_backup['members']),'candidates':candidates,'motionVerification':{'sourceAnimationEntries':29,'uniqueDecodedMotionContents':28,'duplicateNames':['Carrying','Carrying_Start'],'all4712AnimationAccessorsAndBinaryUnchanged':True,'all29WebglClipsFiniteAndMoving':all(x['finite'] and x['changedVertices']>0 for x in render['motion']),'skinVertices':render['motion'][0]['vertices'],'sampledMaxVertexDeltaRange':[min(x['maxVertexDelta'] for x in render['motion']),max(x['maxVertexDelta'] for x in render['motion'])],'liveIdle':render['livePlayback'],'nativeMotion':True,'proceduralMotion':False},'materialVerification':{'sourceMaterialsExactNames':True,'sourcePrimitiveMaterialMapping':[8204,200,64],'all8WebpSavedAndConvertedToPixelExactPng':True,'embeddedPngCount':9,'additionalDerivedImage':'MROS alpha -> sRGB gray RGB for specularColor; source mask is constant255, linear conversion error0.','SSSActiveInStandardRenderer':False,'currentSpecularColorFactor':[.2,.2,.2],'sourceMROSAlphaConstant255PixelCount':4194304,'noNormalYFlip':True,'colorCorrectionNotAppliedBySourceViewer':True},'visualEvidence':{'webgl256Images':60,'webglNativeResolutionImages':4,'contactSheet':str(ROOT/'evidence/contact-256.jpg'),'comparison':str(ROOT/'evidence/contact-native-vs-256.jpg'),'visualFinding':'Selected front/side/back and6action contact panels show consistent cyan body/pink crystal/eye placement and no obvious detached/offset body parts;256 preserves large features with reduced fine texture detail.','SSSParityClaimed':False},'tools':[{ 'path':str(p),'sha256':sha(p)} for p in sorted((ROOT/'tools').glob('*')) if p.is_file()],'replay':{'bindingSecondRunIdentical':True,'preservationPassed':True,'khronosScriptReplayPassed':True,'commandNotes':'README.md'},'limitations':limitations,'centralChanged':False,'gitChanged':False,'contentChanged':False,'defaultsChanged':False,'backupStatus':'pending-parent-authorized-S3-backup','sourceArchive':source_backup['s3Uri']}
save(ROOT/'delivery.json',delivery)
manifest=[]
for p in sorted(ROOT.rglob('*')):
 if p.is_file() and p.name!='files-sha256.json':
  assert not p.is_symlink();manifest.append({'path':str(p.relative_to(ROOT)),'bytes':p.stat().st_size,'sha256':sha(p)})
save(ROOT/'files-sha256.json',{'schema':'ggd.frozen-conversion-files@1','files':manifest,'excluded':[]})
print(json.dumps({'candidates':len(candidates),'files':len(manifest)+1,'bytesWithoutManifest':sum(x['bytes'] for x in manifest),'deliverySha256':sha(ROOT/'delivery.json')}))
