import {readFileSync,writeFileSync,readdirSync,statSync,existsSync} from 'node:fs';
import {join,basename,resolve} from 'node:path';
import {createHash} from 'node:crypto';
import {execFileSync} from 'node:child_process';
const W='/Users/Takuro/Dropbox/我的 Mac (Moriya.local)/Documents/ABxVFX_EDIT',repo=join(W,'GGD-hero-model-options'),content=join(repo,'content'),lib=join(repo,'materials/hero-model-library');
const {ModelVersions}=await import(join(repo,'apps/content-api/src/modelVersions.ts'));
const {contentSha256}=await import(join(repo,'packages/shared/src/content/import/jcs.ts'));
const {zModelDoc}=await import(join(repo,'packages/shared/src/content/schema/model.ts'));
const {preferredModelVersion,modelSelectionClass}=await import(join(repo,'packages/shared/src/content/schema/championModelVersions.ts'));
const {effectiveYawOffsetDeg}=await import(join(repo,'packages/shared/src/content/glbYaw.ts'));
const service=new ModelVersions(content),hash=(b:Uint8Array|string)=>createHash('sha256').update(b).digest('hex'),inputs=new Map<string,string>(),fileCache=new Map<string,{sha256:string,bytes:number}>(),failures:any[]=[],warnings:any[]=[];
function bytes(p:string){const b=readFileSync(p);inputs.set(p,hash(b));return b;}
function read(p:string){return JSON.parse(bytes(p).toString('utf8'));}
function file(p:string){if(!fileCache.has(p)){const b=bytes(p);fileCache.set(p,{sha256:hash(b),bytes:b.length})}return fileCache.get(p)!;}
function test(value:any,code:string,detail:any){if(!value)failures.push({code,...detail});return !!value;}
const gitHead=execFileSync('git',['rev-parse','HEAD'],{cwd:repo,encoding:'utf8'}).trim(),registration=read(join(lib,'priority-registration.json')),first=read(join(lib,'priority-evidence/registration-first-pass.json')),workflow=read(join(lib,'workflow-model-options.json')),runtime=read(join(lib,'priority-runtime-options.json')),priority=read(join(lib,'priority-15-model-readiness.json')),policy=read(join(lib,'default-policy.json')),derivatives=read(join(lib,'derivative-validation.json')),withdrawal=read(join(lib,'priority-evidence/unpublished-v2-withdrawal.json'));
test(registration.heroes.length===81,'ROSTER_COUNT',{actual:registration.heroes.length});
const firstBy=new Map(first.heroes.map((r:any)=>[r.heroId,r])),runtimeIds=new Set(registration.heroes.map((r:any)=>r.runtimeHeroId)),groupCounts={first37:registration.heroes.filter((r:any)=>r.heroId.startsWith('community-review-')).length,second37:registration.heroes.filter((r:any)=>r.heroId.startsWith('b2-')).length,additional7:registration.heroes.filter((r:any)=>r.heroId.startsWith('example:')).length};
test(groupCounts.first37===37&&groupCounts.second37===37&&groupCounts.additional7===7,'ROSTER_37_37_7',groupCounts);test(runtimeIds.size===81,'DUPLICATE_RUNTIME_IDS',{size:runtimeIds.size});
const withdrawnKeys=new Set(withdrawal.files.filter((x:any)=>x.previousRepoPath.startsWith('content/models/version.body.')).map((x:any)=>basename(x.previousRepoPath,'.json')));
const withdrawalProof=withdrawal.files.map((r:any)=>{const f=file(r.preservedLocalPath);test(f.sha256===r.sha256&&f.bytes===r.bytes,'WITHDRAWAL_BACKUP_MISMATCH',{path:r.preservedLocalPath});return {...r,actualSha256:f.sha256,verified:f.sha256===r.sha256&&f.bytes===r.bytes}});
const versions=new Map<string,any>();
function verifyVersion(v:any){
 if(versions.has(v.modelKey)){const prior=versions.get(v.modelKey);test(prior.modelSha256===v.modelSha256&&prior.binarySha256===v.binarySha256,'VERSION_PIN_CONFLICT',{modelKey:v.modelKey});return prior;}
 const result:any={modelKey:v.modelKey,modelSha256:v.modelSha256,binarySha256:v.binarySha256,sourceModelKey:v.sourceModelKey};
 try{service.verify(v);const p=join(content,'models',v.modelKey+'.json'),raw=read(p),doc=zModelDoc.parse(raw),glb=join(content,doc.glbPath),f=file(glb),canonical=contentSha256(doc).slice(7);Object.assign(result,{document:p,documentFileSha256:file(p).sha256,documentCanonicalSha256:canonical,glb,glbSha256:f.sha256,glbBytes:f.bytes,source: v.source,clipMap:doc.clipMap,verified:canonical===v.modelSha256&&f.sha256===v.binarySha256,actualModelVersionsVerifyPassed:true});test(result.verified,'VERSION_PIN_MISMATCH',result)}catch(e){result.verified=false;result.error=String(e);failures.push({code:'VERSION_VERIFY_FAILED',...result})}
 versions.set(v.modelKey,result);return result;
}
const heroes:any[]=[],champions=new Map<string,any>();
for(const r of registration.heroes){
 const p=join(content,'champions',r.runtimeHeroId+'.json'),doc=read(p);champions.set(r.runtimeHeroId,doc);const state=service.state(r.runtimeHeroId),current=doc.modelVersions??[],before:any=firstBy.get(r.heroId),missing=(before?.after.versions??[]).filter((v:any)=>!current.some((c:any)=>c.modelKey===v.modelKey));
 test(doc.id===r.runtimeHeroId,'CHAMPION_ID_MISMATCH',{heroId:r.heroId});test(r.failed.length===0,'REGISTRATION_FAILED',{heroId:r.heroId,failed:r.failed});test(contentSha256(state)===contentSha256(r.after),'REGISTRATION_RECEIPT_STALE',{heroId:r.heroId,expected:r.after.expectedHash,actual:state.expectedHash});test(current.length>0,'NO_DROPDOWN_VERSIONS',{heroId:r.heroId});test(current.some((v:any)=>v.modelKey===doc.modelKey),'ACTIVE_VERSION_MISSING',{heroId:r.heroId,modelKey:doc.modelKey});
 for(const v of current)verifyVersion(v);
 const unapprovedMissing=missing.filter((v:any)=>!withdrawnKeys.has(v.modelKey));test(unapprovedMissing.length===0,'UNEXPLAINED_VERSION_REMOVAL',{heroId:r.heroId,modelKeys:unapprovedMissing.map((v:any)=>v.modelKey)});
 const selected=current.find((v:any)=>v.modelKey===doc.modelKey),preferred=preferredModelVersion(current);
 if((doc.modelSelectionMode??'automatic')==='automatic')test(preferred?.modelKey===doc.modelKey,'AUTOMATIC_SELECTION_ORDER_MISMATCH',{heroId:r.heroId,actual:doc.modelKey,preferred:preferred?.modelKey});
 heroes.push({heroId:r.heroId,runtimeHeroId:doc.id,name:doc.name,championFile:p,championFileSha256:file(p).sha256,selectionMode:doc.modelSelectionMode??'automatic',activeModelKey:doc.modelKey,preferredModelKey:preferred?.modelKey,selectedSourceModelKey:selected?.sourceModelKey,selectedSource:selected?.source,versions:current.map((v:any)=>({modelKey:v.modelKey,sourceModelKey:v.sourceModelKey,modelSha256:v.modelSha256,binarySha256:v.binarySha256,verified:versions.get(v.modelKey)?.verified})),registrationReceiptMatches:true,explicitUnpublishedWithdrawals:missing.filter((v:any)=>withdrawnKeys.has(v.modelKey)).map((v:any)=>v.modelKey)});
}
const modelIndexes:any[]=[],optionRegistration:any[]=[];
for(const [indexName,index]of [['workflow-model-options.json',workflow],['priority-runtime-options.json',runtime]]as const){
 for(const r of index.models){const p=join(content,'models',r.modelKey+'.json');try{const d=read(p),f=file(join(content,d.glbPath)),docf=file(p);test(r.sha256===f.sha256&&r.bytes===f.bytes,'INDEX_BINARY_MISMATCH',{indexName,sourceId:r.id,modelKey:r.modelKey});if(r.documentSha256)test(r.documentSha256===docf.sha256,'INDEX_DOCUMENT_FILE_HASH_MISMATCH',{indexName,sourceId:r.id,modelKey:r.modelKey,expected:r.documentSha256,actual:docf.sha256});test(d.glbPath===r.glbPath,'INDEX_GLB_PATH_MISMATCH',{indexName,sourceId:r.id});modelIndexes.push({indexName,sourceId:r.id,modelKey:r.modelKey,glbPath:d.glbPath,bytes:f.bytes,sha256:f.sha256,documentFileSha256:docf.sha256,verified:f.sha256===r.sha256&&docf.sha256===r.documentSha256})}catch(e){failures.push({code:'INDEX_FILE_ERROR',indexName,modelKey:r.modelKey,error:String(e)})}}
 for(const r of index.heroes){const id=r.runtimeHeroId??workflow.aliases?.[r.id]??r.id;const d=champions.get(id);if(!d)continue;for(const option of r.options??[]){const matches=(d.modelVersions??[]).filter((v:any)=>v.sourceModelKey===option.sourceModelKey&&contentSha256(v.source)===contentSha256(option.source));test(matches.length>0,'INDEX_OPTION_NOT_REGISTERED',{indexName,heroId:r.id,sourceId:option.sourceId,sourceModelKey:option.sourceModelKey});optionRegistration.push({indexName,heroId:r.id,runtimeHeroId:id,sourceId:option.sourceId,sourceModelKey:option.sourceModelKey,versionKeys:matches.map((v:any)=>v.modelKey),retainedInDropdown:matches.length>0})}}
}
const priority15=priority.heroes.map((p:any)=>{const d=champions.get(p.heroId);if(!d){test(false,'PRIORITY_HERO_MISSING',{heroId:p.heroId});return {heroId:p.heroId,missing:true}}const selected=d.modelVersions.find((v:any)=>v.modelKey===d.modelKey),available=optionRegistration.filter(r=>r.runtimeHeroId===p.heroId),activeIndex=available.filter(r=>r.versionKeys.includes(d.modelKey));test(activeIndex.length>0,'PRIORITY_SELECTION_NOT_IN_CURRENT_SOURCE_OPTIONS',{heroId:p.heroId,modelKey:d.modelKey,source:selected?.source});return {heroId:p.heroId,name:p.name,activeModelKey:d.modelKey,sourceModelKey:selected?.sourceModelKey,source:selected?.source,selectionMode:d.modelSelectionMode??'automatic',selectionClass:selected?modelSelectionClass(selected.source):null,automaticEligible:selected?.automaticEligible,modelSha256:selected?.modelSha256,binarySha256:selected?.binarySha256,selectedSourceIds:activeIndex.map(r=>r.sourceId),retainedOptionCount:available.length,versionCount:d.modelVersions.length,modelMotionLimitations:runtime.models.find((r:any)=>r.modelKey===selected?.sourceModelKey)?.limitations??workflow.models.find((r:any)=>r.modelKey===selected?.sourceModelKey)?.limitations??[],identityNotReclassifiedByThisAudit:true}});
const manual:any[]=[];
for(const n of readdirSync(join(content,'champions')).filter(n=>n.endsWith('.json'))){const p=join(content,'champions',n),now=JSON.parse(readFileSync(p,'utf8'));if(now.modelSelectionMode!=='manual')continue;const raw=execFileSync('git',['show',`${gitHead}:content/champions/${n}`],{cwd:repo}),before=JSON.parse(raw.toString('utf8'));bytes(p);const same=before.modelSelectionMode===now.modelSelectionMode&&before.modelKey===now.modelKey&&contentSha256(before.modelVersions)===contentSha256(now.modelVersions);test(same,'MANUAL_DEFAULT_CHANGED',{heroId:now.id,before:before.modelKey,after:now.modelKey});for(const v of now.modelVersions??[])verifyVersion(v);manual.push({heroId:now.id,name:now.name,baselineCommit:gitHead,baselineChampionFileSha256:hash(raw),currentChampionFileSha256:file(p).sha256,beforeModelKey:before.modelKey,afterModelKey:now.modelKey,modelSelectionMode:'manual',versionsUnchanged:contentSha256(before.modelVersions)===contentSha256(now.modelVersions),defaultUnchanged:same})}
test(manual.length===15,'MANUAL_BASELINE_COUNT',{actual:manual.length});
function binding(d:any){const {id,glbPath,bodyVersion,voxel,...b}=zModelDoc.parse(d);return {...b,yawOffsetDeg:effectiveYawOffsetDeg(d)}}
const derivativeRows:any[]=[];test(policy.approvedDerivatives.length===11,'DERIVATIVE_POLICY_COUNT',{actual:policy.approvedDerivatives.length});
for(const a of policy.approvedDerivatives){const d=champions.get(a.heroId),selected=d?.modelVersions?.find((v:any)=>v.modelKey===d.modelKey),prior:any=firstBy.get(a.heroId),validation=derivatives.entries.find((r:any)=>r.derivativeId===a.sourceId),frozen=selected?read(join(content,'models',selected.modelKey+'.json')):null,source=read(join(content,'models',a.modelKey+'.json'));const matches=!!selected&&selected.sourceModelKey===a.modelKey&&selected.binarySha256===a.sha256&&validation?.sha256===a.sha256&&selected.source.reference===a.sourceId&&prior?.before.activeModelKey===a.modelKey&&contentSha256(binding(source))===contentSha256(binding(frozen));test(matches,'DERIVATIVE_DEFAULT_NOT_PRESERVED',{heroId:a.heroId,expectedModel:a.modelKey,actualSource:selected?.sourceModelKey,expectedSha:a.sha256,actualSha:selected?.binarySha256});derivativeRows.push({heroId:a.heroId,name:a.name,sourceId:a.sourceId,approvedModelKey:a.modelKey,approvedSha256:a.sha256,beforeActiveModelKey:prior?.before.activeModelKey,currentFrozenModelKey:d?.modelKey,currentSourceModelKey:selected?.sourceModelKey,currentSha256:selected?.binarySha256,selectionClass:selected?modelSelectionClass(selected.source):null,automaticEligible:selected?.automaticEligible,bindingScaleCollisionAndClipMapPreserved:!!frozen&&contentSha256(binding(source))===contentSha256(binding(frozen)),defaultContentPreserved:matches})}
const endHead=execFileSync('git',['rev-parse','HEAD'],{cwd:repo,encoding:'utf8'}).trim();if(endHead!==gitHead)warnings.push({code:'HEAD_CHANGED_DURING_READ',start:gitHead,end:endHead,note:'Manual baseline remains explicitly pinned to start commit; all checked files individually SHA pinned.'});
const drift=[...inputs].filter(([p,sha])=>hash(readFileSync(p))!==sha).map(([path,before])=>({path,before,after:hash(readFileSync(path))}));test(drift.length===0,'INPUT_CHANGED_DURING_AUDIT',{files:drift});
const report={schema:'ggd-final-priority-integrity@1',readOnly:true,centralWrites:false,productionDeployedClaim:false,auditCompletedAt:new Date().toISOString(),gitBaseline:gitHead,gitHeadAtEnd:endHead,status:failures.length?'failed':'passed',counts:{heroCount:heroes.length,...groupCounts,versionReferences:heroes.reduce((s,r)=>s+r.versions.length,0),uniqueVersionDocuments81:new Set(heroes.flatMap(r=>r.versions.map((v:any)=>v.modelKey))).size,totalUniqueVersionsIncludingManual:versions.size,priorityHeroes:priority15.length,manualDefaults:manual.length,approvedDerivatives:derivativeRows.length,modelsInCurrentSourceIndexes:modelIndexes.length,indexedRegisteredOptions:optionRegistration.length,explicitWithdrawnVersionCount:withdrawnKeys.size,failures:failures.length,warnings:warnings.length},heroes,priority15,manualDefaults:manual,approvedDerivatives:derivativeRows,currentSourceModels:modelIndexes,currentSourceOptions:optionRegistration,frozenVersions:[...versions.values()],unpublishedWithdrawalBackups:withdrawalProof,inputFiles:[...inputs].map(([path,sha256])=>({path,sha256})),inputFilesStableDuringAudit:drift.length===0,failures,warnings,limitations:['This verifies local registry/file SHA, bindings and selection provenance; production deployment, every animation, artistic identity and gameplay are separate checks.','ModelVersions.verify is actual production implementation; canonical document SHA differs deliberately from raw document file SHA.','Only three documented never-published invalid v2 versions may be absent from first-pass after state; every withdrawn file is still locally hashed.']};
writeFileSync('/private/tmp/ggd-final-priority-integrity.json',JSON.stringify(report,null,2)+'\n',{flag:'wx'});console.log(JSON.stringify({status:report.status,counts:report.counts,failures,warnings,priority15:priority15.map((r:any)=>({hero:r.name,source:r.sourceModelKey,selectedSourceIds:r.selectedSourceIds})),report:'/private/tmp/ggd-final-priority-integrity.json',sha256:hash(readFileSync('/private/tmp/ggd-final-priority-integrity.json'))},null,2));
