import json,pathlib,hashlib,collections,datetime
ROOT=pathlib.Path(__file__).resolve().parents[1]
WS=ROOT.parents[3]
R=WS/'GGD-hero-model-options'
def load(p):return json.loads(p.read_text())
def meta(p,relative=False):
 b=p.read_bytes();return {'path':str(p.relative_to(ROOT) if relative else p),'bytes':len(b),'sha256':hashlib.sha256(b).hexdigest()}
def write(name,d):
 p=ROOT/name;p.write_text(json.dumps(d,ensure_ascii=False,indent=2)+'\n');return meta(p)
hero=load(R/'content/champions/godie-ubal.json')
opts=load(R/'materials/hero-model-library/workflow-model-options.json')
def walk(x):
 if isinstance(x,dict):
  yield x
  for v in x.values():yield from walk(v)
 elif isinstance(x,list):
  for v in x:yield from walk(v)
proxies=[]
for x in walk(opts):
 if x.get('id') in ['ou99:457883','ou99:472035'] and x.get('gitPath'):
  p=R/x['gitPath'];proxies.append({'sourceId':x['id'],'sourceCharacter':x['sourceCharacter'],'identityStatus':x['identityStatus'],'evidence':meta(p),'clipMap':x.get('clipMap'),'notVearnExactIdentity':True})
input_paths=[R/'content/champions/godie-ubal.json',R/'materials/hero-model-library/workflow-model-options.json',R/'materials/hero-model-library/download-sources.json']
prior=WS/'GGD-Asset-Library/intake/public-models-20260910/parallel-infinity-strash-body-source-audit-20260910/source-report.json'
input_paths.append(prior)
tree=load(ROOT/'evidence/dqtact-repository-tree.json')
assets={'model':0,'skeleton':0,'motion':0,'vfx':0,'sfx':0,'voice':0,'textures':0}
zero={'acquiredAssetPayloadCount':0,'assetCounts':assets,'modelCandidates':[],'audioFileIndex':[],'defaultEligible':False,'acquisitionStatus':'research-only-no-model-or-audio-package-obtained'}
routes=[
 {'id':'infinity-strash-official-tgs-vearn','urls':['https://steamcommunity.com/app/1895810/allnews/','https://steamcommunity.com/gid/103582791473687350/announcements/detail/3703704711972736125','https://www.square-enix-games.com/en_US/home/infinity-strash-dragon-quest-adventure-dai-out-now'],'status':'official-inclusion-evidence-only','findings':'Publisher announcement dated 2023-09-27 names Vearn among TGS game reveals. Story coverage alone cannot imply absence of a Temple of Recollection bonus boss. Public pages provide no character package. Individual Steam announcement web open was non-retryable URL-safety rejection; not retried via shell/alternate endpoint. All-news page independently read successfully before that rejection.','evidencePaths':['evidence/steam-official-news.html','evidence/square-enix-story-coverage.html']},
 {'id':'infinity-strash-vearn-gameplay-guide','urls':['https://www.dragonquest-fan.com/forum/index.php?subjectID=14968','https://www.dragonquest-fan.com/imgs/userfiles/1/Infinity%20Strash_vearn.jpg'],'status':'screenshot-only','author':'Poppu, Dragon Quest Fan administrator','published':'2023-10-08','findings':'Guide explains Vearn as Temple of Recollection boss. Downloaded and visually inspected screenshot: old man with wrinkles, long white hair/beard, horned crown, blue robe and staff. Confirms elderly Vearn presentation, not young true-body mesh. Screenshot is evidence only, not reusable model texture.','evidencePaths':['evidence/dragonquest-fan-vearn-boss.jpg']},
 {'id':'gematsu-tgs-vearn-announcement','urls':['https://www.gematsu.com/2023/09/infinity-strash-dragon-quest-the-adventure-of-dai-adds-dark-king-vearn-boss-battle'],'status':'article-only-image-403','published':'2023-09-23','author':'Sal Romano','findings':'Reports official TGS announcement placing Vearn in deepest Temple of Recollection. Public image URL returned actual HTTP403; stopped with no alternate image size/host attempt. No game/stream downloaded.','blockedResource':'https://www.gematsu.com/wp-content/uploads/2023/09/Infinity-Strash-TGS-Stage_09-23-23_001-320x180.jpg'},
 {'id':'dqtact-public-repository-vearn','urls':['https://dq-tact.github.io/units/truedarkkingvearn.html','https://api.github.com/repos/DQ-Tact/DQ-Tact.github.io/git/trees/main?recursive=1'],'status':'complete-tree-has-no-vearn-asset-package','repositoryTreeSha':tree['sha'],'truncated':tree['truncated'],'treeEntryCount':len(tree['tree']),'characterPaths':[x['path'] for x in tree['tree'] if 'vearn' in x['path'].lower()],'findings':'Old and True Dark King Vearn appear as data pages, JavaScript stats and PNG portraits. No model, native skeleton/motion, VFX or audio candidate in this tree. Fifteen .clip files are named under images backgrounds/attack icons; they were not downloaded or parsed and are not counted as animation clips. Source directory/file names alone do not prove native 3D game data.','evidencePaths':['evidence/dqtact-repository-tree.json','evidence/dqtact-repository.json','evidence/dqtact-true-vearn.html']},
 {'id':'cults-vearn-duongkhuong-2254947','urls':['https://cults3d.com/en/3d-model/art/vearn-dragon-quest-the-adventure-of-dai-3d-print'],'status':'paid-not-acquired','author':'DuongKhuong','advertised':'US$11; DAU AN RONG THIENG.zip containing 7 STL pieces; no advertised rig or native motion/audio. Form not visually established in this audit.','findings':'No purchase or download attempted; not a free source.'},
 {'id':'cults-vearn-thelegend-4601945','urls':['https://cults3d.com/en/3d-model/game/vearn-thelegend'],'status':'paid-ai-sculpt-not-acquired','author':'theLEGEND','advertised':'US$1.75; 1 STL, AI assisted design. Form and resemblance unverified.','findings':'No purchase; not a native game resource and no rig/motion evidence.'},
 {'id':'creality-vearn-khuongtainang','urls':['https://www.crealitycloud.com/es/model-detail/66d70beed164d01a74e934ca'],'status':'paid-sculpt-no-free-package-established','author':'KHUONGTAINANG','findings':'Search listing describes Vearn 3D print; same sculpt author family as DuongKhuong route. No normal free asset URL established; no account/paywall attempt.'},
 {'id':'official-hoshidora-vearn-army-event','urls':['https://www.dragonquest.jp/hoshidora/raid_event3/'],'status':'official-event-page-only','author':'Square Enix','published':'2017-12-25 event start','findings':'Official event page for Vearn army and Sovereign Rock Castle. Page has campaign images, not downloadable character model or sound package. Does not prove both Vearn bodies in this intake.','evidencePaths':['evidence/official-hoshidora-vearn-event.html']}
]
for x in routes:x.update({'acquiredAssetPayloadCount':0})
priorExcluded=[{'id':'lead-vearn-mmd-sketchfab-a264ddd','url':'https://sketchfab.com/3d-models/dragon-quest-mmd-a264ddd01e1a416abd6ec2fd17ab7bf2','status':'prior-research-only-not-retried','note':'鯖缶 v0.87, secondary uploader tellgamestory. Author distribution bowlroll.net/up/dl37061 previously non-retryable URL-safety blocked; no bypass. Sketchfab download requires normal author/account route; no public asset archive obtained. Form remains unverified.'}]
forms=[{'form':'elderly','nameZh':'老年巴恩','heroIds':['godie-ubal'],'gameInclusion':'Infinity Strash official Vearn announcement plus actual old-form gameplay screenshot','acquiredNativeModel':False,'acquiredNativeMotion':False,'acquiredNativeAudio':False,'sourceLeads':['infinity-strash-official-tgs-vearn','infinity-strash-vearn-gameplay-guide']},{'form':'young-true-body','nameZh':'年輕真身巴恩','heroIds':['godie-ubal'],'gameInclusion':'Not established for Infinity Strash. DQ Tact public data page confirms character listing only, no mesh.','acquiredNativeModel':False,'acquiredNativeMotion':False,'acquiredNativeAudio':False,'sourceLeads':['dqtact-public-repository-vearn','lead-vearn-mmd-sketchfab-a264ddd']}]
report={'schema':'ggd.vearn-priority-source-audit@1','generatedAt':datetime.datetime.now(datetime.timezone.utc).isoformat(),'localRoot':str(ROOT),'scope':'Vearn old + young true body; bounded normal public-source round; read-only central repo','character':{'nameZh':'巴恩大魔王','name':'Vearn','nameJa':'バーン','workZh':'勇者鬥惡龍 達伊的大冒險／神龍之謎','heroIds':['godie-ubal'],'notAliases':['Baran','巴蘭','バラン'],'forms':forms},'heroDefinitionEvidence':{'file':meta(R/'content/champions/godie-ubal.json'),'modelKey':hero['modelKey'],'transform':hero.get('transform'),'QDescription':hero['abilities']['Q']['description'],'RDescription':hero['abilities']['R']['description'],'note':'R prose explicitly requires sealed youthful body, but champion transform metadata is null. No new heroId invented; skill prose is not proof of implemented model swap.'},'existingModelProxies':proxies,'inputs':[meta(p) for p in input_paths],'sourceRoutes':routes,'previousBlockedRoutesNotRetried':priorExcluded,'actualNewAcquisition':zero,'gameInclusionConclusion':'Infinity Strash contains an elderly Vearn boss despite main-story arc limit. Young true-body inclusion remains unproven. No Vearn body/animation/VFX/audio package acquired this round.','nextFeasibleAcquisition':'Obtain an author-public unencrypted Infinity Strash Vearn skeletal mesh package and its dependencies, or reuse a user-provided local installation/extraction with authorization. For youthful Vearn, obtain an explicitly identified author model or extracted original-game source; do not reinterpret the two existing unrelated OU99 proxies as exact bodies. No purchase or game-image acquisition performed.','handoffToOtherAgent':{'target':'ns_models_motion_sources','daiPublicAttachment':'https://www.patreon.com/file?h=66623597&m=153675691','page':'https://www.patreon.com/posts/dai-for-g8m-and-66623597','status':'handed-off-without-download; original web fetch cache-miss only; separate agent owns acquisition'},'restrictionsHonored':['no central/content/Git/S3 edit','no paid purchase','no login,403,URL-safety or DRM bypass','no unauthorized full game images','no downloaded game/program executed','all evidence files distinguished from acquired game assets']}
write('source-report.json',report)
entry={'id':'parallel-vearn-priority-source-audit-20260911','target':'巴恩大魔王：老年與年輕真身','heroIds':['godie-ubal'],'sourceGame':'Infinity Strash: DRAGON QUEST The Adventure of Dai; alternate community leads separately identified','platform':'mixed-leads-not-acquired','sourceKind':'research-only','localRoot':str(ROOT),'sourcePage':'https://steamcommunity.com/app/1895810/allnews/','sourceReport':str(ROOT/'source-report.json'),'verification':report['gameInclusionConclusion'],'defaultEligible':False,'modelCandidates':[],'audioFileIndex':[],'acquiredAssetPayloadCount':0}
write('public-source-entry.json',entry)
write('model-candidates.json',{'schema':'ggd.model-candidates@1','candidates':[],'reason':report['gameInclusionConclusion']})
write('audio-file-index.json',{'schema':'ggd.audio-file-index@1','files':[],'reason':'No new Vearn audio acquired; existing W3X proxy sounds are not Vearn voice identity.'})
files=[meta(p,True) for p in sorted(ROOT.rglob('*')) if p.is_file() and p.name not in ['file-manifest.json','delivery-receipt.json']]
fm=write('file-manifest.json',{'schema':'ggd.source-file-manifest@1','localRoot':str(ROOT),'files':files,'fileCount':len(files),'bytes':sum(x['bytes'] for x in files),'note':'All files in this delivery are research/evidence/scripts. Zero downloaded game asset packages.'})
receipt={'schema':'ggd.frozen-delivery@1','localRoot':str(ROOT),'frozen':True,'manifest':fm,'sourceReport':meta(ROOT/'source-report.json'),'sourceEntry':meta(ROOT/'public-source-entry.json'),'acquiredAssetPayloadCount':0,'assetCounts':assets}
write('delivery-receipt.json',receipt)
out=pathlib.Path('/private/tmp/ggd-vearn-priority-source-report.json');out.write_text(json.dumps(receipt,ensure_ascii=False,indent=2)+'\n');print(json.dumps(receipt,ensure_ascii=False,indent=2))
