from pathlib import Path
import json,hashlib,datetime,shutil
BASE=Path('/Users/Takuro/Dropbox/我的 Mac (Moriya.local)/Documents/ABxVFX_EDIT')
P=BASE/'GGD-Asset-Library/intake/public-models-20260911'; now=datetime.datetime.now(datetime.timezone.utc).isoformat()
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def write(p,d):p.write_text(json.dumps(d,ensure_ascii=False,indent=2)+'\n')
def file(p,root):return {'path':str(p.relative_to(root)),'bytes':p.stat().st_size,'sha256':sha(p)}
blocked=[{'url':'https://www.mediafire.com/folder/n1qka5sixonyc/Palworld','status':'web-tool-safety-non-retryable; not retried'},{'url':'https://models.spriters-resource.com/pc_computer/palworld/asset/352024','status':'403; not retried'},{'url':'https://www.voicy.network/sounds/UsJRY6Q6GEGlcsTrEnMx9A-cattiva','status':'page fetch 403; no media obtained'},{'url':'https://palworld.gamevault.in/paldex/cattiva/','status':'audio public and acquired; model value explicitly protected, no attempt to decode model'}]
entries=[]
for slug,title,url,author in [('atlasforge','AtlasForge Cattiva rigged idle model','https://atlasforge.gg/palworld/pals/cattiva','ATLAS FORGE LLC / upstream model author not named'),('opgg','OP.GG Cattiva model and 33 source animations','https://op.gg/palworld/pals/cattiva','OP.GG / upstream exporter not named'),('gamevault','GameVault Cattiva six creature cries','https://palworld.gamevault.in/paldex/cattiva/','GameVault / original game Pocketpair')]:
 root=P/('parallel-palworld-cattiva-'+slug)
 sid='palworld-cattiva-'+slug
 entry={'id':sid,'target':title,'heroIds':[],'ownerEntryIds':[],'url':url,'author':author,'sourceGame':'Palworld','sourceWork':'Palworld / 幻獸帕魯','platform':'Public web-export; source game build/platform not pinned by source','sourceClass':'original-game-extraction-community-repackage','discoveryChannel':'public-community-resource-viewer' if slug!='gamevault' else 'public-community-soundboard','accessStatus':'public-direct-download','checkedAt':now,'acquisitionStatus':'downloaded-verified','readiness':'pending-standardization','localPath':str(root.relative_to(BASE)),'defaultEligible':False,'backendIntegration':{'required':True,'state':'not-registered','selectionVerified':False},'publicationStatus':'local-only-pending-legacy-backup','license':'Game assets belong to Pocketpair; no additional redistribution license verified.','limitations':['Source game build/version is unpinned.','No paid source, credentials, login bypass, DRM bypass, game or MOD executable used.','No GGD backend selection or runtime acceptance performed.']}
 if slug!='gamevault':
  a=json.loads((root/'analysis/static-analysis.json').read_text())
  native=root/('original/PinkCat.viewer-model' if slug=='atlasforge' else 'original/model.glb')
  output=root/('standardized/cattiva.glb' if slug=='atlasforge' else 'decoded/cattiva-quantization-declared.glb')
  count=a['animationCount'];duration=sum(x['durationSeconds'] for x in a['animations']);candidate={'id':sid+'.body','candidateId':sid+'.body','character':'Cattiva','nativeCharacter':'Cattiva','aliases':['搗蛋貓','ツッパニャン','PinkCat'],'sourceWork':entry['sourceWork'],'sourceGame':'Palworld','heroIds':[],'resourceRole':'character-body','sourceModel':str(native.relative_to(root)),'sourceModelSha256':sha(native),'convertedPath':str(output.relative_to(root)),'sha256':sha(output),'bytes':output.stat().st_size,'identityEvidence':'Public source page labels Cattiva; internal model/animation/material names PinkCat, ZukanIndex 002. Visual runtime acceptance pending.','readiness':'pending-standardization' if slug=='atlasforge' else 'pending-material-binding-and-GGD-standardization','boneCount':43,'sourceSuppliedAnimationCount':count,'nativeAnimationCount':count,'proceduralAnimationCount':0,'animationOriginEvidence':'Source-supplied original-game names and material paths; raw Unreal animation assets were not acquired.','animations':[{k:x[k] for k in ['name','durationSeconds'] if k in x} for x in a['animations']],'analysisPath':str(root/'analysis/static-analysis.json'),'textureCount':3 if slug=='atlasforge' else 5,'audioCount':0,'vfxCount':0,'backendIntegration':entry['backendIntegration']}
  entry.update(assetKinds=['model','skeleton','texture','material','animation'],format='GLB + WebP; original public payload retained',resourceRole='character-body',modelCount=1,modelCandidates=[candidate],nativeAnimationCount=count,proceduralAnimationCount=0,audioCount=0,vfxCount=0,modelCandidateIndexPath=str(root/'model-candidates.json'),files=[file(native,root),file(output,root)])
  if slug=='opgg':entry['limitations']+=a['limitations']
  else:entry['limitations']+=['Source GLB includes only one idle clip; no attack/run/death library in this version.','Draco decode uses installed Blender library; EXT_texture_webp preserved.','Standard GLB validator: 0 errors, 1 source hierarchy warning.']
  write(root/'model-candidates.json',{'schema':'ggd.source-model-candidates@1','sourceId':sid,'modelCandidates':[candidate]})
  write(root/'audio-index.json',{'schema':'ggd.source-audio@1','audioFileCount':0,'files':[],'note':'Audio is independently acquired under palworld-cattiva-gamevault; not present in this source.'})
  if slug=='atlasforge':write(root/'acquisition.json',{'sourceUrl':url,'downloadUrl':'https://palworld.atlasforge.gg/data/pals/models/PinkCat','files':[file(native,root)],'publicViewerMethod':'Saved viewer code restores four GLB magic bytes; original bytes retained and geometry codec decoded independently without executing site scripts.'})
 else:
  a=json.loads((root/'analysis/audio-analysis.json').read_text());fs=[{'path':x['decodedRelativePath'],'bytes':x['decodedBytes'],'sha256':x['decodedSha256'],'seconds':x['seconds'],'event':x['event'],'classification':x['classification'],'sampleRate':x['sampleRate'],'channels':x['channels'],'reportedLanguage':None,'originalPath':x['path'],'originalSha256':x['sha256']} for x in a['files']]
  index={'schema':'ggd.source-audio-files@1','localRoot':str(root),'files':fs,'audioGroups':[{'character':'Cattiva','nativeId':'PinkCat','sourceWork':entry['sourceWork'],'reportedLanguage':None,'pathPrefixes':['decoded/'],'count':6,'classification':'creature-cry-source-labelled-unreviewed','events':[x['event'] for x in fs]}]}
  write(root/'audio-file-index.json',index)
  entry.update(assetKinds=['audio','sfx','creature-voice'],format='MP3 source / WAV PCM Float32 44100Hz mono',modelCount=0,modelCandidates=[],audioCount=6,nativeAnimationCount=0,vfxCount=0,audioGroups=index['audioGroups'],audioFileIndex={'reportPath':'audio-file-index.json','reportSha256':sha(root/'audio-file-index.json')},files=[file(root/x['path'],root) for x in a['files']],audioSeconds=a['seconds'])
  entry['limitations']+=['Six source-labelled creature cries, not spoken dialogue or a speech-synthesis dataset.','Event labels are author/site labels; no individual listening review. No human language asserted.','Public MP3 are source exports, not original Wwise containers; native Wwise bank not acquired.','Protected model payload was not accessed or decoded.']
  write(root/'model-candidates.json',{'schema':'ggd.source-model-candidates@1','sourceId':sid,'modelCandidates':[]})
  write(root/'audio-index.json',index)
 write(root/'source-entry.json',entry);write(root/'evidence/discovery-and-limits.json',{'sourceUrl':url,'otherSourceAttempts':blocked,'scope':'Only Cattiva; retain every acquired source/version. No new heroes/defaults registered.'})
 (root/'README.md').write_text('# 搗蛋貓 Cattiva：'+title+'\n\n來源：'+url+'\n\n原包、解析及轉換版本分開保留。請讀 `source-entry.json`、`analysis/` 與逐檔 SHA 清單。角色別名：搗蛋貓／ツッパニャン／Cattiva／PinkCat。\n\n'+('\n'.join('- '+x for x in entry['limitations']))+'\n',encoding='utf8')
 shutil.copy2(__file__,root/'tools/prepare-delivery.py')
 entries.append(entry)
out=Path('/private/tmp/ggd-cattiva-source-entries-local.json');write(out,{'schema':'ggd.cattiva.delivery@1','createdAt':now,'entries':entries});print(out,sha(out));print([(x['id'],x['modelCount'],x.get('nativeAnimationCount'),x['audioCount']) for x in entries])
