import { createHash } from "node:crypto";
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

import { HERO_MODEL_ADOPTION_POLICY, HERO_MODEL_BUDGET } from "../../packages/shared/src/content/modelUpload/budget";
import { MODEL_UPLOAD_EXTENSIONS, MODEL_UPLOAD_IMAGE_MIME_TYPES, MODEL_UPLOAD_LIMITS } from "../../packages/shared/src/content/modelUpload/glb";
import { HERO_MODEL_STATES } from "../../packages/shared/src/content/modelUpload/heroModelSchema";
import { GENERATED_COMBAT_FX_AUDIO_POLICY } from "../../packages/shared/src/content/audioAssetPolicy";
import {
  AUDIO_CAST_LAYER_MAX,
  AUDIO_CAST_LAYER_MIN,
  AUDIO_SFX_COOLDOWN_MS_MIN,
  AUDIO_SFX_MAX_CONCURRENT_MIN,
} from "../../packages/shared/src/content/schema/config/audioMap";
import {
  AUDIO_MIX_OTHERS_GAIN_MAX,
  AUDIO_MIX_OTHERS_GAIN_MIN,
  AUDIO_MIX_ROUND_END_MIN_GAP_SEC_MAX,
} from "../../packages/shared/src/content/schema/audioMixDoc";
import { DEFAULT_COOLDOWN_MS, DEFAULT_MAX_CONCURRENT } from "../../apps/client/src/audio/audioSelect";
import { CAST_LAYER_ORDER } from "../../apps/client/src/audio/sfxLayerCap";
import { GATES } from "./limits";

const HERE = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(HERE, "../..");
const OUT = path.join(ROOT, "materials/asset-library/模型動作特效上架限制.md");
const FOUR_DAY_REPORT = path.join(ROOT, "materials/hero-model-library/近四日新增模型動作特效清單.md");
const REPORT_START = "<!-- generated:model-policy-summary:start -->";
const REPORT_END = "<!-- generated:model-policy-summary:end -->";
const SOURCES = [
  "packages/shared/src/content/modelUpload/adoptionPolicy.json",
  "packages/shared/src/content/modelUpload/budget.ts",
  "packages/shared/src/content/modelUpload/glb.ts",
  "content/config/model-lod.json",
  "content/config/vfx-budget.json",
  "content/config/vfx-cleanup.json",
  "content/config/audio-map.json",
  "content/config/audio-mix.json",
  "packages/shared/src/content/schema/config/audioMap.ts",
  "packages/shared/src/content/schema/audioMixDoc.ts",
  "packages/shared/src/content/audioAssetPolicy.ts",
  "apps/client/src/audio/audioSelect.ts",
  "apps/client/src/audio/sfxLayerCap.ts",
  "tools/model-budget/limits.ts",
] as const;

function readJson(rel: string): Record<string, unknown> {
  return JSON.parse(fs.readFileSync(path.join(ROOT, rel), "utf8")) as Record<string, unknown>;
}

function n(value: number): string {
  return value.toLocaleString("en-US");
}

function mib(bytes: number): string {
  return (bytes / 1024 / 1024).toFixed(2);
}

function fingerprint(): string {
  const hash = createHash("sha256");
  for (const rel of SOURCES) {
    hash.update(rel);
    hash.update("\0");
    hash.update(fs.readFileSync(path.join(ROOT, rel)));
    hash.update("\0");
  }
  return hash.digest("hex");
}

function render(): string {
  const vfx = GATES.find((gate) => gate.role === "vfx-model");
  if (!vfx) throw new Error("missing vfx-model gate");
  const gateRows = GATES.map((gate) =>
    `| \`${gate.role}\` | ${gate.simultaneous} | ${n(gate.tris.warn)} / ${n(gate.tris.limit)} | ${n(gate.meshes.warn)} / ${n(gate.meshes.limit)} | ${n(gate.texEdge.warn)} / ${n(gate.texEdge.limit)} px | ${n(gate.channels.warn)} / ${n(gate.channels.limit)} |`,
  ).join("\n");
  const lod = readJson("content/config/model-lod.json") as {
    platformPolicy: { minDevice: string; tabletFpsCap: number; phone: string };
  };
  const particles = readJson("content/config/vfx-budget.json") as {
    maxParticlesPerSystem: number; maxRatePerSystem: number;
    maxConcurrentAdditive: number; additiveOverflowBrightness: number;
  };
  const cleanup = readJson("content/config/vfx-cleanup.json") as {
    maxOneShotEmitters: number; maxActiveRibbons: number; ribbonFadeBudgetSec: number;
    vfxFadeOutMaxSec: number; vfxDissipateMaxSec: number;
    vfxHardMaxLifeSec: number; vfxHardCapScope: string;
  };
  const audioMap = readJson("content/config/audio-map.json") as {
    sfx: Record<string, { files: string[]; gain?: number; cooldownMs?: number; maxConcurrent?: number }>;
    castLayerCap: { enabled: boolean; maxLayers: number; whitelist: string[] };
  };
  const audioMix = readJson("content/config/audio-mix.json") as {
    voice: { othersGain: number; roundEndMachineVoice: string; roundEndMinGapSec: number };
  };
  const cueEntries = Object.values(audioMap.sfx);
  const cueCooldowns = cueEntries.flatMap((entry) => entry.cooldownMs === undefined ? [] : [entry.cooldownMs]);
  const cueConcurrent = cueEntries.flatMap((entry) => entry.maxConcurrent === undefined ? [] : [entry.maxConcurrent]);
  const explicitCooldownCount = cueCooldowns.length;
  const explicitConcurrentCount = cueConcurrent.length;
  if (cueEntries.length === 0 || cueCooldowns.length === 0 || cueConcurrent.length === 0) {
    throw new Error("audio-map must contain SFX cue throttling values");
  }
  const states = HERO_MODEL_STATES.map((state) => `\`${state}\``).join("、");
  return `<!-- GENERATED by tools/model-budget/generate_policy_doc.ts. DO NOT EDIT BY HAND. -->
# 模型、動作、特效與音訊上架限制

這份文件由正式程式常數與設定檔即時產生。修改數值時必須先改下方「資料來源」，再執行 \`pnpm modelpolicy:build\`；\`pnpm modelpolicy:check\` 會阻止文件與實際檢查器不同步。

來源指紋：\`${fingerprint()}\`

## 英雄模型：正式採用與執行期預算

| 層級 | 三角面規則 | 意義 |
|---|---:|---|
| 正式採用 | 來源超過 **${n(HERO_MODEL_ADOPTION_POLICY.decimateWhenTrianglesAbove)}** 時，必須另產生不超過 **${n(HERO_MODEL_ADOPTION_POLICY.decimatedTargetTrianglesMax)}** 的候選 | 這是素材庫／後台選項的有效採用門檻；原始檔保留本機並備份到 S3 legacy，候選通過骨架及視覺 A/B 後才可進 Git |
| 執行期容量警戒 | ${n(HERO_MODEL_BUDGET.tris.warn)} | 場景容量診斷；不能用來跳過上列正式採用規則 |
| 執行期絕對上限 | ${n(HERO_MODEL_BUDGET.tris.limit)} | Renderer 安全上限；不能用來宣稱模型已驗收或可上架 |

視覺 A/B 的亮像素差門檻為 **${HERO_MODEL_ADOPTION_POLICY.visualLitPixelDeltaPctMax}%**，並且仍需肉眼確認角色輪廓、薄片、武器與材質沒有損壞。

| 項目 | 警戒 | 硬上限 | 量法 |
|---|---:|---:|---|
| Mesh／draw call | ${n(HERO_MODEL_BUDGET.meshes.warn)} | ${n(HERO_MODEL_BUDGET.meshes.limit)} | 匯出後每個 node × primitive；材質拆分通常會增加 primitive |
| 貼圖最長邊 | ${n(HERO_MODEL_BUDGET.texEdge.warn)} px | ${n(HERO_MODEL_BUDGET.texEdge.limit)} px | 每張內嵌貼圖的 max(width, height) |
| 單段動畫通道 | ${n(HERO_MODEL_BUDGET.channels.warn)} | ${n(HERO_MODEL_BUDGET.channels.limit)} | 所有 clip 中最重的一段；不是全部 clips 相加 |
| 貼圖 VRAM | ${mib(HERO_MODEL_BUDGET.vramBytes.warn)} MiB | ${mib(HERO_MODEL_BUDGET.vramBytes.limit)} MiB | 每張 寬×高×4（RGBA8）×4/3（mip）全部加總；PNG/JPEG 壓縮不減少 VRAM。每張都過最長邊的模型，張數多了仍會超線 |
| GLB 單檔 | — | ${n(MODEL_UPLOAD_LIMITS.fileBytes / 1024 / 1024)} MiB | 完整、自含的 glTF 2.0 GLB |

最低支援目標由設定檔指定為 **${lod.platformPolicy.minDevice}／${lod.platformPolicy.tabletFpsCap} fps**；手機政策是 \`${lod.platformPolicy.phone}\`。

## 各類模型的執行期 gate

下表全部直接由 \`GATES\` 產生，數字格式為「警戒 / 硬上限」。\`champion\` 的三角面欄是執行期容量診斷；正式採用仍必須先遵守上方的減面規則。

| role | 同畫面份數 | 三角面 | Mesh／draw call | 貼圖最長邊 | 單段動畫通道 |
|---|---:|---:|---:|---:|---:|
${gateRows}

貼圖路徑例外由 \`TEX_EDGE_EXEMPT\` 明列並以出貨鏡頭像素量測支撐；未列入者不得自行放寬。場景、道具與 VFX 也不能以「不是英雄」為由跳過貼圖上限。

## GLB 與六項動作

- GLB 必須使用 glTF 2.0、單一內嵌 buffer、內嵌 ${MODEL_UPLOAD_IMAGE_MIME_TYPES.map((mime) => `\`${mime}\``).join("／")} 貼圖，不得引用外部 URI。
- 可接受的 glTF extensions：${MODEL_UPLOAD_EXTENSIONS.map((extension) => `\`${extension}\``).join("、")}；其他 extensions 會在解析階段拒絕。
- 英雄必須有 skin，所有可見 primitive 必須有蒙皮權重；整組貼圖只有 8×8 會判為疑似遺失貼圖。
- 六項用途為 ${states}；同一 clip 可以重複指定。
- 動作長度必須大於 0 且不超過 ${n(MODEL_UPLOAD_LIMITS.clipSeconds)} 秒。

| GLB 解析安全界線 | 上限 |
|---|---:|
| JSON 區段 | ${n(MODEL_UPLOAD_LIMITS.jsonBytes / 1024 / 1024)} MiB |
| JSON 值總數 | ${n(MODEL_UPLOAD_LIMITS.jsonValues)} |
| JSON 深度 | ${n(MODEL_UPLOAD_LIMITS.depth)} |
| Nodes | ${n(MODEL_UPLOAD_LIMITS.nodes)} |
| Clips | ${n(MODEL_UPLOAD_LIMITS.clips)} |
| Accessors | ${n(MODEL_UPLOAD_LIMITS.accessors)} |
| Accessor values | ${n(MODEL_UPLOAD_LIMITS.accessorValues)} |
| 單 clip channels | ${n(MODEL_UPLOAD_LIMITS.clipChannels)} |
| 全檔 channels | ${n(MODEL_UPLOAD_LIMITS.channels)} |

這些是防止解析器處理無界資料的安全上限，不是採用品質目標；英雄採用仍看前述單段動畫通道 gate。

## 技能／特效粒子

VFX GLB 的模型、mesh、貼圖與通道限制見上表 \`vfx-model\` 列；以下是粒子及回收限制。

- 每個 particle system 最多 ${n(particles.maxParticlesPerSystem)} 顆，發射率最多 ${n(particles.maxRatePerSystem)}／秒。
- 同時 additive 系統最多 ${n(particles.maxConcurrentAdditive)}；溢出亮度係數 ${particles.additiveOverflowBrightness}。
- 一次性 emitter 池最多 ${n(cleanup.maxOneShotEmitters)}，active ribbon 最多 ${n(cleanup.maxActiveRibbons)}。
- Ribbon fade 預算 ${cleanup.ribbonFadeBudgetSec} 秒；一般 fade-out 與 dissipate 尾段上限分別為 ${cleanup.vfxFadeOutMaxSec}／${cleanup.vfxDissipateMaxSec} 秒。
- \`${cleanup.vfxHardCapScope}\` 範圍的一般 VFX 最長 ${cleanup.vfxHardMaxLifeSec} 秒後強制回收；明列常駐豁免另依設定檔處理。

## 音效與語音

音訊分成「素材格式／存在性」與「播放併發／混音」兩層。以下數字直接取自出貨設定；逐 cue 的值會隨 \`audio-map.json\` 變動，不是寫在 Markdown 的另一份規格。

| 項目 | 現行值 | 程式界線／意義 |
|---|---:|---|
| 已登記 SFX cue | ${n(cueEntries.length)} | 每個 cue 至少一個 \`assets/\` 相對路徑；出貨資源測試驗證檔案存在、非空且為 MP3 或 RIFF |
| cue cooldown | ${n(Math.min(...cueCooldowns))}–${n(Math.max(...cueCooldowns))} ms | ${n(explicitCooldownCount)} / ${n(cueEntries.length)} 個 cue 明寫；schema 下限為 ${AUDIO_SFX_COOLDOWN_MS_MIN}，未寫時 runtime 預設 ${DEFAULT_COOLDOWN_MS} |
| cue 同時播放數 | ${n(Math.min(...cueConcurrent))}–${n(Math.max(...cueConcurrent))} | ${n(explicitConcurrentCount)} / ${n(cueEntries.length)} 個 cue 明寫；schema 下限為 ${AUDIO_SFX_MAX_CONCURRENT_MIN}，未寫時 runtime 預設 ${DEFAULT_MAX_CONCURRENT} |
| 單次施法聲音層數 | ${audioMap.castLayerCap.enabled ? audioMap.castLayerCap.maxLayers : "停用"} | schema 可設 ${AUDIO_CAST_LAYER_MIN}–${AUDIO_CAST_LAYER_MAX}；順序為 ${CAST_LAYER_ORDER.join("、")}；目前白名單 ${n(audioMap.castLayerCap.whitelist.length)} 支 |
| 其他角色語音音量 | ${audioMix.voice.othersGain} | 相對本人語音倍率，schema 範圍 ${AUDIO_MIX_OTHERS_GAIN_MIN}–${AUDIO_MIX_OTHERS_GAIN_MAX} |
| 回合結束機械語音 | \`${audioMix.voice.roundEndMachineVoice}\` | \`off\`／\`fallback\`／\`on\` |
| 同角色回合結束語音間隔 | ${audioMix.voice.roundEndMinGapSec} 秒 | schema 範圍 0–${AUDIO_MIX_ROUND_END_MIN_GAP_SEC_MAX} 秒 |

- 目前合成戰鬥 FX 的成品 gate 是 ${GENERATED_COMBAT_FX_AUDIO_POLICY.channels === 1 ? "mono" : `${GENERATED_COMBAT_FX_AUDIO_POLICY.channels} channels`} ${GENERATED_COMBAT_FX_AUDIO_POLICY.codec}、${GENERATED_COMBAT_FX_AUDIO_POLICY.sampleRateHz / 1000} kHz、不超過 ${GENERATED_COMBAT_FX_AUDIO_POLICY.bitrateKbpsMax} kbps；\`audioAssets.test.ts\` 會直接讀出貨 bytes 驗證。
- 來源容器與母檔仍依素材庫規則原樣保存；上述 MP3 gate 是遊戲使用成品的標準化檢查，不是刪除原始 WAV／WEM／BNK 的理由。
- 現行 schema 沒有全域音檔位元組數或秒數上限；個別 boss 音效等另有內容用途測試。沒有程式 gate 的數字不能從舊文件推成新的上架限制。

## 可重現檢查與自動處理

\`\`\`bash
# 單件英雄：正式採用門檻 + 執行期預算
pnpm modelbudget:guard /path/model.glb --role champion

# 超過正式採用門檻時，預設從政策讀取減面目標並輸出到獨立目錄
pnpm modelbudget:optimize /path/model.glb --role champion --geometry
pnpm modelbudget:optimize /path/model.glb --role champion --geometry --apply --babylon-verify

# GLB 結構與 Babylon 實載
pnpm exec tsx tools/w3x-import/validate_glb.mts /path/glb-directory

# 全模型樹、LOD、VFX 與音訊
pnpm modelbudget:check
pnpm model:intake:check
pnpm models:check
pnpm lod:check
pnpm vfxassets:check
pnpm vfxbind:check
pnpm vfxforge:check:release
pnpm vfx:review:temporal
pnpm sfxbind:check
pnpm --filter @ggd/shared exec vitest run src/content/audioMap.test.ts src/content/audioAssets.test.ts
pnpm --filter @ggd/client exec vitest run src/audio/audioSelect.test.ts src/audio/sfxLayerCap.test.ts src/audio/voiceOtherGain.test.ts src/audio/roundEndVoice.test.ts
\`\`\`

匯入正規化會安全合併同渲染狀態 primitive、移除 0 秒 clip，並在宿主提供縮圖器時把貼圖縮到上限。減面會保留來源檔、寫到獨立輸出樹並驗證 rig；最終採用仍要有人檢查視覺 A/B。超標 draw call、骨架簡化、動畫重烘焙及語意配對不能由批次程式自行裁決。

## 資料來源

${SOURCES.map((source) => `- \`${source}\``).join("\n")}
`;
}

function renderReportBlock(): string {
  const vfx = GATES.find((gate) => gate.role === "vfx-model");
  if (!vfx) throw new Error("missing vfx-model gate");
  return `${REPORT_START}

上架限制文件由正式程式常數與設定檔生成：\`materials/asset-library/模型動作特效上架限制.md\`。現行英雄正式採用規則是來源超過 ${n(HERO_MODEL_ADOPTION_POLICY.decimateWhenTrianglesAbove)} 面時，另產生低於 8,000 面的候選（程式上限 ${n(HERO_MODEL_ADOPTION_POLICY.decimatedTargetTrianglesMax)}）並重做骨架與視覺 A/B；${n(HERO_MODEL_BUDGET.tris.warn)}／${n(HERO_MODEL_BUDGET.tris.limit)} 是 runtime 容量警戒／硬上限，不能代替正式採用規則。英雄另有 ${n(HERO_MODEL_BUDGET.meshes.warn)}／${n(HERO_MODEL_BUDGET.meshes.limit)} draw calls、${n(HERO_MODEL_BUDGET.texEdge.warn)}／${n(HERO_MODEL_BUDGET.texEdge.limit)}px 貼圖最長邊、${n(HERO_MODEL_BUDGET.channels.warn)}／${n(HERO_MODEL_BUDGET.channels.limit)} 單段動畫通道；VFX 模型為 ${n(vfx.tris.warn)}／${n(vfx.tris.limit)} 面、${n(vfx.meshes.warn)}／${n(vfx.meshes.limit)} draw calls、${n(vfx.texEdge.limit)}px、${n(vfx.channels.warn)}／${n(vfx.channels.limit)} 通道。

${REPORT_END}`;
}

function expectedFourDayReport(): string {
  const actual = fs.readFileSync(FOUR_DAY_REPORT, "utf8");
  const block = renderReportBlock();
  if (actual.includes(REPORT_START) || actual.includes(REPORT_END)) {
    if ((actual.match(new RegExp(REPORT_START, "g")) ?? []).length !== 1 || (actual.match(new RegExp(REPORT_END, "g")) ?? []).length !== 1) {
      throw new Error("model policy report markers are ambiguous");
    }
    const begin = actual.indexOf(REPORT_START);
    const finish = actual.indexOf(REPORT_END, begin) + REPORT_END.length;
    return actual.slice(0, begin) + block + actual.slice(finish);
  }
  const header = "## 八、限制與自動化工具\n\n";
  const boundary = "\n\n可重現入口：";
  const begin = actual.indexOf(header);
  const finish = actual.indexOf(boundary, begin + header.length);
  if (begin < 0 || finish < 0) throw new Error("model policy report insertion boundaries are missing");
  return actual.slice(0, begin + header.length) + block + actual.slice(finish);
}

function main(): void {
  const expected = render();
  const expectedReport = expectedFourDayReport();
  if (process.argv.includes("--check")) {
    const actual = fs.existsSync(OUT) ? fs.readFileSync(OUT, "utf8") : "";
    const actualReport = fs.readFileSync(FOUR_DAY_REPORT, "utf8");
    if (actual !== expected || actualReport !== expectedReport) {
      process.stderr.write(`model policy document is stale: ${path.relative(ROOT, OUT)}\nrun: pnpm modelpolicy:build\n`);
      process.exit(1);
    }
    process.stdout.write(`model policy document is current (${path.relative(ROOT, OUT)})\n`);
    return;
  }
  fs.mkdirSync(path.dirname(OUT), { recursive: true });
  fs.writeFileSync(OUT, expected);
  fs.writeFileSync(FOUR_DAY_REPORT, expectedReport);
  process.stdout.write(`wrote ${path.relative(ROOT, OUT)} and ${path.relative(ROOT, FOUR_DAY_REPORT)}\n`);
}

main();
