/** Freeze and then run real public v2 entry checks. Answers never enter infer(). */
import fs from 'node:fs';import path from 'node:path';import assert from 'node:assert/strict';import {fileURLToPath} from 'node:url';import {isDeepStrictEqual as equal} from 'node:util';
import {digest} from './dataset.mjs';import {fileHash} from './precision-diagnostic.mjs';import {prepare,infer} from './research-inference-v2.mjs';
const dir=path.dirname(fileURLToPath(import.meta.url)),read=p=>JSON.parse(fs.readFileSync(p));
export function freeze(root){
 const manifest=read(path.join(root,'dataset-manifest.json')),outputs=path.dirname(root),r3=manifest.parent,r4=manifest.previousRegression,ext=manifest.extension,out=path.join(root,'manual-entry-v1');assert(!fs.existsSync(out));
 const old=path.join(outputs,'forge-contrastive-r5-20260906/recovered-checkpoint-eval-v1/manual-entry-check-v1'),comp=path.join(ext,'recovered-r5-follow-on-v1/manual-composition-inputs-v1'),specs=[],answers=[],files=[path.join(old,'cases.private.json'),path.join(comp,'EXPECTED.private.json')];
 function add(id,spec,acceptedValues,reason){const built=prepare(spec);specs.push({id,spec,built});answers.push({id,acceptedValues,reason,requests:built.requests.length});}
 const singleCatalog=path.join(r3,'main-catalog-review-v4.json'),vfxCatalog=path.join(outputs,'forge-classification-reviewed-r2-20260906/catalog.json'),stackCatalog=path.join(root,'catalog.json');
 for(const c of read(path.join(old,'cases.private.json'))){const file=path.join(old,c.id+'-request.json'),req=read(file);files.push(file);const kind=c.task==='vfx'?'vfx':'single',catalog=kind==='vfx'?vfxCatalog:singleCatalog;add(c.id,{kind,catalog:{path:catalog,sha256:digest(read(catalog))},input:kind==='vfx'?{id:c.id,task:'vfx',request:req.sourceRequest}:req.input},[[c.expected]],'Original known semantic pattern; new zero-penalty public entry, not new generalization.');}
 for(const c of read(path.join(comp,'EXPECTED.private.json')).cases){const file=path.join(comp,c.input),input=read(file);files.push(file);add(input.id,{kind:'stack',catalog:{path:stackCatalog,sha256:digest(read(stackCatalog))},input},c.acceptedTargets.map(t=>[t]),'Known composition integration pattern; refuse incomplete active-window hooks and preserve duplicate strikes.');}
 const heroFile=path.join(r4,'standalone-hero-request.json'),oldHero=read(heroFile),heroSource=oldHero.resolution.source,heroPayload=JSON.parse(oldHero.request.messages[1].content);files.push(heroFile);
 add('hero-identity',{kind:'source',input:{id:'hero-identity',task:'hero-source',source:heroSource,claim:heroPayload.claim}},[[{verdict:'supported'}]],'Explicit resolved main source: Saber, Shirou and Fate. Not alias resolution or live roster proof.');
 const snapshotFile=path.join(r3,'source-snapshot.json'),snapshot=read(snapshotFile),s=snapshot.sources.find(s=>s.id==='godie-h01u.r');files.push(snapshotFile);
 add('owner-unknown-cooldown',{kind:'source',input:{id:'owner-unknown-cooldown',task:'owner-mechanism',source:{id:s.id,name:s.name,version:'historical-owner-tsv-20260808',text:s.ownerOriginal,sha256:digest(s.ownerOriginal)},claim:'攻擊與受傷兩個觸發共用同一個內部冷卻。'}},[[{verdict:'not-stated'}]],'Known reviewed TRAIN pattern. Original gives two event chances, not shared cooldown. Integration only.');
 const fidelityFile=path.join(r4,'standalone-fidelity-plan.json'),legacy=read(fidelityFile),source=snapshot.sources.find(s=>s.id===legacy.sourceLock.id),proposal=JSON.parse(legacy.requests[0].messages[1].content).claim;files.push(fidelityFile);
 add('owner-full-checklist',{kind:'fidelity',input:{task:'owner-mechanism',source:{id:source.id,name:source.name,version:legacy.sourceLock.version,text:source.ownerOriginal,sha256:digest(source.ownerOriginal)},proposal,requirements:legacy.requirements,requirementsSourceSha256:digest(source.ownerOriginal),requirementsCoverage:'partial'}},[legacy.requests.map(()=>({verdict:'supported'}))],'Original 8-check historical Owner proposal. Source reading does not imply current mark-stack runtime can delay heal.');
 assert.equal(specs.length,10);fs.mkdirSync(out);const put=(n,x)=>fs.writeFileSync(path.join(out,n),JSON.stringify(x,null,2)+'\n',{flag:'wx'});
 for(const s of specs){put(s.id+'.json',s.spec);put(s.id+'-prepared.json',s.built);files.push(path.join(out,s.id+'.json'),path.join(out,s.id+'-prepared.json'));}
 put('EXPECTED.private.json',{trainingAllowed:false,selectionAllowed:false,cases:answers});files.push(path.join(out,'EXPECTED.private.json'),singleCatalog,vfxCatalog,stackCatalog,...['r7-entry.mjs','research-inference-v2.mjs','dataset.mjs','precision-diagnostic.mjs','composition-client.mjs','current-template-client.mjs','classification-client.mjs','r3-fidelity-client.mjs','r3-data.mjs','reviewed-curriculum.mjs','worker.py'].map(n=>path.join(dir,n)));
 put('preparation.json',{preparedAt:new Date().toISOString(),ids:specs.map(s=>s.id),pins:[...new Set(files)].map(p=>({path:p,sha256:fileHash(p)})),trainingAllowed:false,selectionAllowed:false,decodingPresencePenalty:0,scope:'10 real public entry calls, 17 model claims total, all known integration patterns. No independent quality or physical16GB claim.'});return{out,entries:specs.length,requests:specs.reduce((n,s)=>n+s.built.requests.length,0)};
}
function isAlive(pid){try{process.kill(pid,0);return true;}catch(e){assert.equal(e.code,'ESRCH');return false;}}
export function canRun(core,coreAlive,post,postAlive,busy){
 assert(['running','complete-research-only'].includes(core.status),'CORE_FAILED');assert(['waiting-for-core','running','complete-research-evidence'].includes(post.status),'POST_FAILED');
 if(core.status==='running')assert(coreAlive,'CORE_DIED');if(post.status!=='complete-research-evidence')assert(postAlive,'POST_DIED');
 return core.status==='complete-research-only'&&!coreAlive&&post.status==='complete-research-evidence'&&!postAlive&&!busy;
}
async function run(root,python,runtime){
 const out=path.join(root,'manual-entry-v1'),prep=read(path.join(out,'preparation.json')),expected=read(path.join(out,'EXPECTED.private.json')),manifest=read(path.join(root,'dataset-manifest.json')),policy=read(path.join(root,'experiment-policy.json')),cutoff=Date.parse(policy.deadline)-policy.reportReserveSeconds*1000;assert(!fs.existsSync(path.join(out,'state.json')),'REFUSE_RESTART');
 const put=(n,x)=>{const p=path.join(out,n);fs.writeFileSync(p+'.tmp',JSON.stringify(x,null,2)+'\n');fs.renameSync(p+'.tmp',p);},state={status:'waiting-for-core-and-post',pid:process.pid,startedAt:new Date().toISOString(),stages:[]};let reason=null;const onSignal=()=>{reason??='SIGNAL';};process.on('SIGTERM',onSignal);process.on('SIGINT',onSignal);
 function guard(){assert(!reason,reason);assert(Date.now()<cutoff,'GPU_CUTOFF');for(const p of [root,out,manifest.extension])assert(!fs.existsSync(path.join(p,'CANCEL')),'CANCEL');for(const p of prep.pins)assert.equal(fileHash(p.path),p.sha256,'PIN_CHANGED:'+p.path);}
 guard();put('state.json',state);
 const watchdog=setInterval(()=>{try{guard();}catch(e){if(!reason){reason=String(e);process.emit('SIGTERM');}}},2000);
 try{
  while(true){guard();const core=read(path.join(root,'run-state.json')),post=read(path.join(root,'post-v1/state.json'));if(canRun(core,isAlive(core.pid),post,isAlive(post.pid),fs.existsSync(path.join(runtime,'gpu.lock'))))break;await new Promise(r=>setTimeout(r,10000));}
  const nativePath=path.join(root,'native-reference.json'),native=read(nativePath),selection=read(path.join(root,'selection.json'));assert.equal(selection.testUsed,false);assert.equal(selection.selected.step,native.selectedStep);assert.equal(fileHash(path.join(native.adapter,'adapters.safetensors')),native.adapterSha256);
  const results=[];
  for(const id of prep.ids){guard();state.status='running';state.stage=id;put('state.json',state);const specPath=path.join(out,id+'.json'),spec=read(specPath);assert.deepEqual(JSON.parse(JSON.stringify(prepare(spec))),read(path.join(out,id+'-prepared.json')),'PUBLIC_PREPARATION_DRIFT');const exp=expected.cases.find(c=>c.id===id);
   // infer receives no expected values or review reason.
   const result=await infer(specPath,nativePath,python,runtime,path.join(out,id+'-result'),new Date(cutoff).toISOString()),values=result.values.map(v=>v.value),semanticMatch=result.contractPass&&exp.acceptedValues.some(xs=>equal(xs,values));results.push({id,contractPass:result.contractPass,semanticMatch,values:result.values,metadata:result.metadata,adapterSha256:result.adapterSha256,physical16GBMachineTested:false});state.stages.push({id,completedAt:new Date().toISOString(),contractPass:result.contractPass,semanticMatch});put('state.json',state);put('partial-summary.json',{selectedStep:native.selectedStep,results,releaseQualified:false});console.log(JSON.stringify(state.stages.at(-1)));
  }
  put('summary.json',{selectedStep:native.selectedStep,adapterSha256:native.adapterSha256,results,totalEntries:results.length,semanticPassed:results.filter(r=>r.semanticMatch).length,allContractsPass:results.every(r=>r.contractPass),allSemanticsPass:results.every(r=>r.semanticMatch),scope:prep.scope,decodingPresencePenalty:0,trainingAllowed:false,selectionAllowed:false,releaseQualified:false,activation:false});state.status='complete-research-evidence';state.completedAt=new Date().toISOString();put('state.json',state);
 }catch(e){state.status='failed';state.error=String(e);put('state.json',state);console.error(e);process.exitCode=1;}
 finally{clearInterval(watchdog);process.off('SIGTERM',onSignal);process.off('SIGINT',onSignal);}
}
if(process.argv[1]&&path.resolve(process.argv[1])===fileURLToPath(import.meta.url)){const [mode,root,python,runtime]=process.argv.slice(2);if(mode==='prepare')console.log(JSON.stringify(freeze(root)));else{assert.equal(mode,'run');await run(root,python,runtime);}}
