/** One bounded joint run. No automatic restart, publication or activation. */
import fs from 'node:fs';import path from 'node:path';import assert from 'node:assert/strict';import {spawn} from 'node:child_process';import {fileURLToPath} from 'node:url';
import {verify} from './r6-verify.mjs';import {digest} from './dataset.mjs';import {fileHash} from './precision-diagnostic.mjs';import {summarize,preservation,rank,eligible,compare,render} from './r6-score.mjs';
import {assertPriorFinished} from './r7-prepare-v2.mjs';
const [root,python,runtime]=process.argv.slice(2);for(const p of [root,python,runtime])assert(p&&path.isAbsolute(p));
const dir=path.dirname(fileURLToPath(import.meta.url)),read=p=>JSON.parse(fs.readFileSync(p)),get=n=>read(path.join(root,n)),put=(n,x)=>{const p=path.join(root,n);fs.writeFileSync(p+'.tmp',JSON.stringify(x,null,2)+'\n');fs.renameSync(p+'.tmp',p);};
assert(!fs.existsSync(path.join(root,'run-state.json')),'REFUSE_RESTART');verify(root);
const ablation=assertPriorFinished(root,runtime);
const policy=get('experiment-policy.json'),manifest=get('dataset-manifest.json'),cases=get('cases.private.json'),native=read(path.join(manifest.parent,'native-reference.json')),authPath=path.join(manifest.extension,'AUTHORIZATION.json'),auth=read(authPath);
assert.equal(policy.schema,'ggd-joint-source-stack-experiment@6');assert.equal(policy.deadline,auth.deadline);assert.equal(policy.reportReserveSeconds,auth.reportReserveSeconds);assert.equal(policy.trainRows,466);assert.equal(policy.trainingEpochs,1);assert.equal(policy.learningRate,2.5e-6);assert.equal(policy.presencePenalty,0);assert.equal(policy.gradientAccumulation,4);assert.equal(policy.saveEverySteps,16);assert.deepEqual(policy.evaluateSteps,[48,96]);assert.equal(policy.evaluateLastCompletedCheckpoint,true);
for(const k of ['cloudGpu','cloudFallback','externalTeacher','publish','activateInEditor','thinking'])assert.equal(policy[k],false);assert.equal(policy.cloudGpuSpendLimit,0);
assert(Date.parse(policy.trainingCutoff)<Date.parse(policy.trainingStopAt));assert(Date.parse(policy.trainingStopAt)<Date.parse(policy.trainingHardStopAt));assert(Date.parse(policy.trainingHardStopAt)<Date.parse(auth.gpuCutoff));assert(Date.now()<Date.parse(policy.trainingCutoff));
assert.equal(fileHash(path.join(native.adapter,'adapters.safetensors')),policy.initialAdapterSha256);assert.equal(native.adapterSha256,policy.initialAdapterSha256);
const rows=s=>cases.filter(c=>c.split===s),policyPath=path.join(root,'experiment-policy.json'),baseReceiptPath=path.join(path.dirname(native.base),'NATIVE_REFERENCE.json'),baseReceipt=read(baseReceiptPath),baseFiles=baseReceipt.files.filter(f=>f.name.startsWith('base/'));
assert.equal(baseFiles.length,13);assert.equal(baseReceipt.baseRevision,'851bf6e806efd8d0a36b00ddf55e13ccb7b8cd0a');
const files=[...manifest.sourceFiles.map(p=>p.path),...['r7-run-v2.mjs','r6-verify.mjs','r6-train.py','r6-score.mjs','worker.py','r3-score.mjs','classification-score.mjs','precision-diagnostic.mjs'].map(n=>path.join(dir,n)),...['experiment-policy.json','PRETRAIN_REVIEW.md','dataset-manifest.json','cases.private.json','train.jsonl','catalog.json','verification.json','owner-unknown-review.json','stack-new-review.json','excluded-legacy-mechanism-training.json',...['train','dev','test'].flatMap(s=>[s+'-requests.json',s+'-token-budget.json'])].map(n=>path.join(root,n)),authPath,baseReceiptPath,path.join(manifest.parent,'native-reference.json'),path.join(native.adapter,'adapters.safetensors'),path.join(native.adapter,'adapter_config.json')];
const pins=[...new Set(files)].map(p=>({path:p,sha256:fileHash(p)})),cutoff=Date.parse(auth.gpuCutoff),lock=path.join(runtime,'gpu.lock');
for(const p of [path.join(dir,'r7-prepare-v2.mjs'),path.join(root,'ablation-preparation.json')])pins.push({path:p,sha256:fileHash(p)});
fs.writeFileSync(lock,JSON.stringify({pid:process.pid,kind:'r7-low-lr-joint',root}),{flag:'wx'});
const state={status:'running',pid:process.pid,startedAt:new Date().toISOString(),stage:'preflight-base-bytes',stages:[]};put('run-state.json',state);put('run-pins.json',{pins,base:native.base,initialAdapter:native.adapter,initialAdapterSha256:native.adapterSha256,policySha256:fileHash(policyPath),releaseQualified:false});
let child=null,reason=null,killTimer;
function stop(why){if(reason)return;reason=why;if(child?.pid){try{process.kill(-child.pid,'SIGTERM');}catch{}killTimer=setTimeout(()=>{try{process.kill(-child.pid,'SIGKILL');}catch{}},3000);}}
function guard(){assert(!reason,reason);assert(Date.now()<cutoff,'GPU_CUTOFF');assert(!fs.existsSync(path.join(root,'CANCEL'))&&!fs.existsSync(path.join(manifest.extension,'CANCEL')),'CANCEL');for(const p of pins)assert.equal(fileHash(p.path),p.sha256,'PIN_CHANGED:'+p.path);}
process.on('SIGTERM',()=>stop('SIGNAL'));process.on('SIGINT',()=>stop('SIGNAL'));
function verifyBase(){guard();const checked=baseFiles.map(f=>{const p=path.join(path.dirname(native.base),f.name);assert.equal(fs.statSync(p).size,f.bytes);assert.equal(fileHash(p),f.sha256,'BASE_CHANGED:'+f.name);return f;});guard();return{verifiedAt:new Date().toISOString(),files:checked,revision:baseReceipt.baseRevision};}
async function execute(stage,args){
 guard();state.stage=stage;put('run-state.json',state);const log=fs.openSync(path.join(root,stage+'.log'),'wx');child=spawn(python,args,{stdio:['ignore',log,log],detached:true});fs.closeSync(log);put('worker-lease.json',{pid:child.pid,parent:process.pid,stage});
 const timer=setInterval(()=>{try{guard();if(stage==='train')assert(Date.now()<Date.parse(policy.trainingHardStopAt),'TRAINING_HARD_STOP');}catch(e){stop(String(e));}},2000);let code;
 try{code=await new Promise((resolve,reject)=>{child.once('error',reject);child.once('exit',resolve);});}finally{clearInterval(timer);clearTimeout(killTimer);child=null;put('worker-lease.json',{pid:null,stage});}
 assert(!reason&&code===0,reason??'WORKER_EXIT:'+stage+':'+code);guard();state.stages.push({stage,completedAt:new Date().toISOString()});put('run-state.json',state);console.log(JSON.stringify(state.stages.at(-1)));
}
async function evaluate(stage,split,adapter){
 const output=path.join(root,stage+'.json'),args=[path.join(dir,'worker.py'),'eval','--model',native.base,'--policy',policyPath,'--data',path.join(root,split+'-requests.json'),'--output',output];if(adapter)args.push('--adapter',adapter);
 await execute(stage,args);const raw=read(output);assert.equal(raw.metadata.modelPath,native.base);assert.equal(raw.metadata.adapter,adapter??null);const score=summarize(rows(split),raw);put(stage+'-score.json',score);return{raw,score};
}
try{
 put('base-before.json',verifyBase());
 const baseDev=await evaluate('base-dev','dev',null),controlDev=await evaluate('r3-dev','dev',native.adapter);
 put('baseline-dev-report.json',compare(rows('dev'),[{name:'base',raw:baseDev.raw},{name:'r3',raw:controlDev.raw}]));
 await execute('doctor',[path.join(dir,'worker.py'),'doctor','--model',native.base,'--adapter',native.adapter,'--policy',policyPath,'--data',path.join(root,'train.jsonl'),'--output',path.join(root,'doctor.json')]);
 const candidates=[{step:0,label:'unchanged-r3-control',adapter:native.adapter,adapterSha256:native.adapterSha256,score:controlDev.score,preservation:preservation(controlDev.score,controlDev.score)}];
 const adapterRoot=path.join(runtime,path.basename(root)+'-adapter');await execute('train',[path.join(dir,'r6-train.py'),'--model',native.base,'--adapter',native.adapter,'--policy',policyPath,'--data',path.join(root,'train.jsonl'),'--output',adapterRoot]);
 const training=read(path.join(adapterRoot,'training-run.json'));assert.equal(training.restoredAllTrainableValuesExactly,true);assert.equal(training.preparedExamples,466);assert.equal(training.recipe.epochs,1);put('training-run.json',training);
 const metrics=fs.readFileSync(path.join(adapterRoot,'metrics.jsonl'),'utf8').trim().split('\n').map(JSON.parse),order=read(path.join(adapterRoot,'training-order.json'));assert.equal(order.length,466);assert.deepEqual(order.slice().sort(),rows('train').map(c=>c.id).sort());
 assert.deepEqual(order,read(path.join(ablation.previousRun,'checkpoint-archive/training-order.json')),'TRAIN_ORDER_DIFFERS_FROM_R6');
 for(const [i,m] of metrics.entries()){assert.equal(m.example,i+1);assert.equal(m.id,order[i]);assert(Number.isFinite(m.loss)&&Number.isFinite(m.seconds));}
 const archive=path.join(root,'checkpoint-archive');fs.cpSync(adapterRoot,archive,{recursive:true,errorOnExist:true,force:false});
 for(const c of training.checkpoints){assert.equal(fileHash(path.join(c.adapter,'adapters.safetensors')),c.sha256);assert.equal(fileHash(path.join(archive,'step-'+c.step,'adapters.safetensors')),c.sha256);assert.equal(metrics[c.examplesSeen-1].step,c.step);assert.equal(metrics[c.examplesSeen-1].committedExamples,c.examplesSeen);}
 put('checkpoint-archive-receipt.json',{createdAt:new Date().toISOString(),source:adapterRoot,archive,checkpoints:training.checkpoints,trainingComplete:training.trainingComplete,optimizerResumeAvailable:false});
 const last=training.checkpoints.at(-1),evaluated=training.checkpoints.filter(c=>policy.evaluateSteps.includes(c.step)||c.step===last.step);assert(evaluated.length>0&&evaluated.length<=3);
 for(const cp of evaluated){const durable=path.join(archive,'step-'+cp.step),{raw,score}=await evaluate('dev-step-'+cp.step,'dev',durable);candidates.push({step:cp.step,label:'r7-low-lr-step-'+cp.step,adapter:durable,adapterSha256:cp.sha256,score,preservation:preservation(controlDev.score,score)});const previous=path.join(ablation.previousRun,'dev-step-'+cp.step+'.json');if(fs.existsSync(previous))put('lr-matched-step-'+cp.step+'.json',{learningRates:{r6:1e-5,r7:2.5e-6},sameStep:cp.step,report:compare(rows('dev'),[{name:'r6',raw:read(previous)},{name:'r7',raw}]),selectionAllowed:false});}
 candidates.sort(rank);const selected=candidates[0];assert.equal(selected.preservation.pass,true,'CONTROL_MUST_BE_AVAILABLE');put('selection.json',{selected,allCandidates:candidates,selectedAt:new Date().toISOString(),selectionUses:'frozen 158 dev only; strict per-case preservation and earlier/control tie-break',testUsed:false,eligible:eligible(selected.score),trainingComplete:training.trainingComplete});
 const keep=path.join(root,'selected-adapter');fs.mkdirSync(keep);for(const n of ['adapters.safetensors','adapter_config.json'])fs.copyFileSync(path.join(selected.adapter,n),path.join(keep,n),fs.constants.COPYFILE_EXCL);assert.equal(fileHash(path.join(keep,'adapters.safetensors')),selected.adapterSha256);
 put('native-reference.json',{base:native.base,adapter:keep,adapterSha256:selected.adapterSha256,selectedStep:selected.step,source:selected.step?'R3 exact-weight warm-start; joint reviewed source/current-plan curriculum, dev-selected':'Unchanged R3 won guarded dev selection; no new fine-tune gain',trainingComplete:training.trainingComplete,decoding:{presencePenalty:0,thinking:false},releaseQualified:false});
 const selectedDev=selected.step?get('dev-step-'+selected.step+'.json'):controlDev.raw,devReport=compare(rows('dev'),[{name:'base',raw:baseDev.raw},{name:'r3',raw:controlDev.raw},{name:'selected',raw:selectedDev}]);put('dev-report.json',devReport);fs.writeFileSync(path.join(root,'DEV_REPORT.md'),render(devReport),{flag:'wx'});
 const testBase=await evaluate('base-test','test',null),testR3=await evaluate('r3-test','test',native.adapter),testSelected=await evaluate('selected-test','test',keep),testReport=compare(rows('test'),[{name:'base',raw:testBase.raw},{name:'r3',raw:testR3.raw},{name:'selected',raw:testSelected.raw}]);put('test-report.json',testReport);fs.writeFileSync(path.join(root,'TEST_REPORT.md'),render(testReport),{flag:'wx'});
 put('base-after.json',verifyBase());put('comparison.json',{selectedStep:selected.step,newAdapterSelected:selected.step!==0,trainingComplete:training.trainingComplete,devEligible:eligible(selected.score),testEligible:eligible(testSelected.score),testScores:Object.fromEntries(Object.entries(testReport.scores).map(([n,s])=>[n,{total:s.total,passed:s.passed,unsafe:s.unsafe,tasks:s.tasks}])),requiredPostStillPending:true,releaseQualified:false,activation:false});
 state.status='complete-research-only';state.completedAt=new Date().toISOString();put('run-state.json',state);console.log(JSON.stringify({status:state.status,selectedStep:selected.step,trainingComplete:training.trainingComplete,requiredPostStillPending:true}));
}catch(e){state.status='failed';state.error=String(e);put('run-state.json',state);console.error(e);process.exitCode=1;}
finally{clearTimeout(killTimer);if(fs.existsSync(lock)&&read(lock).pid===process.pid)fs.unlinkSync(lock);put('worker-lease.json',{pid:null,reason,endedAt:new Date().toISOString()});}
