from pathlib import Path
import json,hashlib,urllib.parse,gzip,collections,datetime
from PIL import Image
ROOT=Path(__file__).resolve().parents[1]
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def dump(name,x):(ROOT/name).write_text(json.dumps(x,ensure_ascii=False,indent=2)+'\n')
def statf(p):return {'path':str(p),'relativePath':str(p.relative_to(ROOT)),'bytes':p.stat().st_size,'sha256':sha(p)}
a=json.loads((ROOT/'archive-manifest.json').read_text());s=json.loads((ROOT/'static-analysis.json').read_text());arc=ROOT/'original/Dai V2.zip'
old=json.loads((ROOT/'evidence/download-receipt.json').read_text())
dump('evidence/download-receipt-final.json',{'schema':'ggd.public-download-receipt.v1','sourceUrl':old['sourceUrl'],'downloadUrl':old['downloadUrl'],'method':'GET /usr/bin/curl with normal system TLS verification; no authentication/cookies supplied','httpStatus':200,'mimeType':'application/zip','complete':True,'downloadedBytes':17352966,'archive':statf(arc),'earlierAttempt':{'result':'local-python-ca-configuration-error','recordPath':'evidence/download-receipt.json','permissionRejected':False},'zipCrcAllMembersPassed':True})
dump('evidence/source-page-observations.json',{'url':old['sourceUrl'],'title':'Dai for G8M and G8.1M','author':'Shinteo','publishedAt':'2022-05-19','updatedAt':'2022-05-20','checkedAt':datetime.datetime.now(datetime.timezone.utc).isoformat(),'publicAccessEvidence':'The post describes prior 31-day member early access and now exposes the Dai V2.zip download attachment to a non-authenticated read. HTTP 200 confirms public download.','authorUpdateParaphrase':'V2 repairs rigging of the torn clothing.','publicAttachmentUrl':old['downloadUrl'],'sourceGameEvidence':'Post uses Dragon Quest tag; actual archive preset folders are named Jump Force. Original game extraction source, platform and fidelity remain unverified.','rightsEvidence':'Public download observed. No separate redistribution or interactive-game license text was found in this source page or archive; do not claim rights were cleared.'})
images=[]
for p in sorted((ROOT/'extracted').rglob('*')):
 if p.suffix.lower() not in ['.jpg','.png']:continue
 with Image.open(p) as im:
  im.load(); images.append(statf(p)|{'width':im.width,'height':im.height,'mode':im.mode,'role':'source-texture' if '/Runtime/Textures/' in str(p) else 'preset-preview'})
dump('image-index.json',{'images':images,'sourceTextureCount':sum(i['role']=='source-texture' for i in images),'previewImageCount':sum(i['role']=='preset-preview' for i in images),'allDecodePassed':True})
missing=collections.defaultdict(set)
for r in s['missingNonFragmentReferences']:
 path=urllib.parse.unquote(r['reference'].split('#',1)[0]);missing[path].update(r['usedBy'])
dump('dependency-index.json',{'missingExternalFileCount':len(missing),'missingReferenceCount':len(s['missingNonFragmentReferences']),'files':[{'path':p,'usedBy':sorted(users),'existsInArchive':False} for p,users in sorted(missing.items())],'criticalBaseFiles':['/data/DAZ 3D/Genesis 8/Male/Genesis8Male.dsf','/data/Daz 3D/Genesis 8/Male 8_1/Genesis8_1Male.dsf'],'targetedWorkspaceCheck':{'roots':['GGD-Asset-Library','outputs'],'glob':['*Genesis8*','*genesis8*'],'foundFiles':0,'scope':'filenames only in those workspace asset/output trees; not an exhaustive computer-wide search'},'preventsCompleteIndependentCharacter':True})
parts=[]
for d in s['dsonFiles']:
 if '/data/shinteo5/' not in d['path'] or not d.get('geometries'):continue
 p=ROOT/d['path'];g=d['geometries'][0];isweapon=not d.get('skins')
 parts.append({'id':'dai-daz-v2-component-'+str(len(parts)+1).zfill(2),'name':g['id'],'resourceRole':'weapon-or-prop' if isweapon else 'skinned-appearance-component','source':statf(p),'nativeFormat':'Daz DSON DSF','geometry':g,'boneDefinitions':d['nodeTypes'].get('bone',0),'skinModifiers':d['skins'],'nativeAnimationCount':0,'standaloneCharacterBody':False,'readiness':'native-component-reserve-not-converted','formIdentityUnverified':True})
presets=[]
for d in s['dsonFiles']:
 if '/Jump Force/Jump Force Dai' not in d['path']:continue
 p=ROOT/d['path'];presets.append({'id':'dai-daz-v2-g8.1m' if 'G8.1M' in p.name else 'dai-daz-v2-g8m','name':'達伊／小呆 JUMP FORCE 造型（Daz G8.1M）' if 'G8.1M' in p.name else '達伊／小呆 JUMP FORCE 造型（Daz G8M）','source':statf(p),'readiness':'reserved-pending-dependencies','missingBodyBase':True,'standaloneCharacterBody':False,'nativeAnimationCount':0,'sourceClass':'community-adaptation','GGDTargetHeroIds':['godie-nbbc'],'dragonFormTargetHeroIdsNotAssigned':['godie-n01c']})
dump('model-candidates.json',{'schema':'ggd.dai-daz-component-candidates.v1','character':'小呆／達伊 Dai','work':'勇者鬥惡龍 達伊的大冒險','presets':presets,'components':parts,'fullIndependentCharacterBodyCount':0,'sourcePresetCount':len(presets),'nativeComponentGeometryFileCount':len(parts),'inlineEyeAndEyebrowGeometryDefinitions':'2 per character/wearable DUF, repeated in three presets; preserved in those originals, not three new characters.','nativeGameMotionCount':0,'newAudioCount':0,'newStandaloneVfxCount':0,'variantsPreserved':['Papnican Clothes','Papnican Clothes Torn','Dai Hair Without Crown','Dai Hair With Crown','Dai Hair Dragon Aura','Sword of Dai','Sword of Dai Back','Sword of Dai Sheath'],'dragonAuraHairIsNotVerifiedDragonDemonFullBody':True})
dump('audio-index.json',{'schema':'ggd.dai-source-audio-index.v1','sourceId':'patreon-shinteo-dai-daz-v2','newAudioFiles':[],'newAudioCount':0,'nativeAudioBanks':0,'existingSeparateAudio':{'sourceId':'parallel-ps-jumpforce-audio','groupId':'parallel-ps-jumpforce-audio:JForce_Dai','fileCount':261,'newThisAcquisition':False,'indexPath':str(ROOT.parents[3]/'GGD-hero-model-options/materials/hero-model-library/voice-index.json')},'note':'No audio in this ZIP. Existing Jump Force audio is not counted as newly downloaded.'})
entry={'id':'patreon-shinteo-dai-daz-v2','target':'小呆／達伊：JUMP FORCE 造型 Daz G8M/G8.1M 改作，待人體基底','heroIds':['godie-nbbc'],'sourceWork':'Dragon Quest: The Adventure of Dai / 勇者鬥惡龍 達伊的大冒險','sourceGame':'JUMP FORCE (archive folder label; source extraction fidelity not independently verified)','sourceClass':'community-mod-adaptation','sourcePlatform':'Daz Studio Genesis 8 Male / Genesis 8.1 Male','url':old['sourceUrl'],'downloadUrl':old['downloadUrl'],'author':'Shinteo','uploader':'Shinteo','sourceVersion':'V2 / 2022-05-20','format':'ZIP / DSON DUF+DSF / JPG textures / PNG previews','acquisitionStatus':'downloaded-verified','accessStatus':'public-download-no-login','resourceRole':'clothing-weapon-morph','assetKinds':['clothing','character-morph','model-component','skeleton-component','texture','material','weapon'],'modelCount':0,'fullIndependentCharacterBodyCount':0,'presetCandidateCount':2,'modelComponentCount':len(parts),'nativeAnimationCount':0,'audioCount':0,'standaloneVfxCount':0,'readiness':'reserved-pending-dependencies','backendIntegration':{'required':True,'state':'pending-dependencies','selectionVerified':False},'defaultEligible':False,'automaticEligible':False,'publicationStatus':'local-only-not-uploaded','localPath':str(ROOT.relative_to(ROOT.parents[3])),'localRoot':str(ROOT),'modelCandidateIndexPath':str(ROOT/'model-candidates.json'),'audioIndexPath':str(ROOT/'audio-index.json'),'files':[{'path':'original/Dai V2.zip','bytes':arc.stat().st_size,'sha256':sha(arc)}],'missingDependenciesIndexPath':str(ROOT/'dependency-index.json'),'license':'No explicit downstream game/redistribution grant established; source attribution retained.','limitations':['Both presets depend on missing Genesis8Male/Genesis8_1Male geometry and supporting morphs. No independent complete character body acquired.','587 bone definitions across repeated presets and garments are not 587 unique body joints.','20 stored geometry blocks include repeated inline eyes/brows; 14 DSF component geometry files are not 14 characters.','Dragon Aura hair is preserved but is not proof of the godie-n01c canonical Dragon Demon full-body transformation.','No original Infinity Strash body, motions, SFX or VFX acquired.','Existing 261 Jump Force Dai audio files are separate and not new.']}
dump('public-source-entry.json',entry)
(ROOT/'README.md').write_text('''# 小呆／達伊 Dai：Shinteo 公開 Daz V2 原包\n\n已正常下載完整原包，HTTP 200、ZIP CRC 全通過。117 檔全部保留。\n\n這是 JUMP FORCE 造型的 Daz G8M/G8.1M 社群改作，不是 Infinity Strash 原生本體。兩個人物預設依賴未附帶的 Genesis 人體基底，不能當完整獨立人物或可上架成品。\n\n已保存：完整／破損服装、三種頭髮（含 Dragon Aura）、劍、劍鞘、身體／頭部 morph、35 JPG 貼圖及22 PNG預覽。0 原生動作、0 音訊、0 獨立 VFX。Dragon Aura 頭髮不等於已確認龍魔人全身形態。\n\n查詢入口：public-source-entry.json、model-candidates.json、dependency-index.json、image-index.json、audio-index.json、archive-manifest.json、static-analysis.json。\n\n靜態解析：python3 tools/analyze_archive.py；交付分析：python3 tools/freeze_delivery.py（需要 Pillow）。所有腳本只解析檔案，不執行作者內容。\n\n本批未修改中央／Git／S3／預設。原來源的權利條件未完成下游使用確認。\n''')
manifest=[statf(p) for p in sorted(ROOT.rglob('*')) if p.is_file() and p.name not in ['file-manifest.json','delivery-receipt.json']]
dump('file-manifest.json',{'schema':'ggd.frozen-intake-files.v1','files':manifest,'excludeSelfAndDeliveryReceipt':True})
receipt={'schema':'ggd.dai-source-delivery.v1','localRoot':str(ROOT),'status':'acquired-components-with-explicit-body-dependency-gap','sourceEntry':statf(ROOT/'public-source-entry.json'),'fileManifest':statf(ROOT/'file-manifest.json'),'archive':statf(arc),'sourceMemberCount':117,'completeZipCrcVerified':True,'nativePresetCandidates':2,'independentBodyModels':0,'nativeDsfComponents':len(parts),'sourceTextures':35,'previewImages':22,'nativeAnimations':0,'newAudio':0,'standaloneVfx':0,'centralChanged':False,'gitChanged':False,'s3Changed':False,'originalPackagePreserved':True,'remainingBlocker':'Complete character requires Genesis8Male.dsf or Genesis8_1Male.dsf, not in source archive or targeted current asset/output trees. No login/DRM/paid download attempted for missing bases.','noNewSearchAfterFreeze':True}
dump('delivery-receipt.json',receipt)
Path('/private/tmp/ggd-dai-shinteo-source-delivery.json').write_text(json.dumps(receipt,ensure_ascii=False,indent=2)+'\n')
print(json.dumps(receipt,ensure_ascii=False,indent=2))
