// Code generated by tools/collections-gen/gen.ts; DO NOT EDIT.
//
// ⭐ GH#998 —— 這一份是**推導**出來的，來源只有一個：
//   packages/shared/src/content/schema/index.ts 的 COLLECTIONS（第〇·四守則：值只有一個住處）。
//
//   pnpm collections:build   # 改了 COLLECTIONS 之後重新產生
//   pnpm collections:check   # 逐位元組比對（唯讀；接在 skills:check 裡）
//
// ⚠️ 刻意沒有產生時間戳（與 caps:export 同一個理由：時鐘欄位會讓 --check 永遠不相等）。
// ⚠️ TestKnownCollectionsMatchTheSharedSchemaTable（validate_test.go）仍然獨立讀 index.ts
//   再比一次 —— 它是「改了 index.ts 卻沒跑產生器」時 go-platform CI 上的最後一道。

package contentoverlay

// KnownCollections is the closed set of collections an overlay doc may target:
// exactly the keys of COLLECTIONS in packages/shared/src/content/schema/index.ts,
// sorted so the rejection message is stable.
var KnownCollections = []string{
	// ability@1 · Abilities
	"abilities",
	// template@1 · Ability Templates
	"ability-templates",
	// arena@1 · Arenas
	"arenas",
	// augment@1 · Augments
	"augments",
	// champion@1 · Champions
	"champions",
	// config@1 · Config
	"config",
	// item@1 · Items
	"items",
	// loot-table@1 · Loot Tables
	"loot-tables",
	// map@1 · Maps
	"maps",
	// model@1 · Models
	"models",
	// projectile@1 · Projectiles
	"projectiles",
	// skin@1 · Skins
	"skins",
	// status-effect@1 · Status Effects
	"status-effects",
	// vfx@1 · VFX
	"vfx",
	// vfx-script@1 · VFX Scripts
	"vfx-scripts",
	// vfx-subtype@1 · VFX Subtypes
	"vfx-subtypes",
}
