from pathlib import Path
from datetime import datetime,timezone
import collections,hashlib,json,shutil

BASE=Path('/Users/Takuro/Dropbox/我的 Mac (Moriya.local)/Documents/ABxVFX_EDIT/GGD-Asset-Library/intake/public-models-20260910')
CONTROL=BASE/'fate-unlimited-codes-workflow-control-20260910'
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def save(p,d):p.write_text(json.dumps(d,ensure_ascii=False,indent=2)+'\n')
packages=[]
for platform,folder,names in [
 ('unknown','fate-unlimited-codes-psp-first-batch',['gamebanana-zero-lancer','gamebanana-bgm-dnf']),
 ('PS2','fate-unlimited-codes-ps2-first-batch',['spritedatabase-archer','spritedatabase-shirou','spritedatabase-saber'])]:
 for name in names:
  root=BASE/folder/name;acq=json.loads((root/'acquisition.json').read_text());archive=Path(acq['path']);frozen=(root/'files.sha256.json').exists()
  r={'localRoot':str(root),'sourcePage':acq['sourcePage'],'downloadUrl':acq['downloadUrl'],'sourcePlatform':platform,'status':'complete-frozen' if frozen else 'download-in-progress','archive':{'path':str(archive),'bytesObserved':archive.stat().st_size,'sha256':acq.get('sha256') if acq.get('completeDownload',acq.get('complete',False)) else None},'acquisitionReceipt':str(root/'acquisition.json')}
  if frozen:
   audio=json.loads((root/'audioFileIndex.json').read_text());candidates=json.loads((root/'candidate-manifest.json').read_text());r.update(sourceId=audio['sourceId'],audioFileIndex={'path':str(root/'audioFileIndex.json'),'sha256':sha(root/'audioFileIndex.json')},candidateManifest={'path':str(root/'candidate-manifest.json'),'sha256':sha(root/'candidate-manifest.json')},fileManifest={'path':str(root/'files.sha256.json'),'sha256':sha(root/'files.sha256.json')},validation={'path':str(root/'validation.json'),'sha256':sha(root/'validation.json')},audioFiles=audio.get('fileCount',len(audio['files'])),uniqueMusicStreams=audio.get('uniqueStreams',0),seconds=audio.get('totalSeconds',audio.get('totalPcmSeconds')),modelCandidates=len(candidates['candidates']))
  else:r['resumeScript']=str(CONTROL/'tooling/ggd-fuc-resume-public-downloads.py')
  packages.append(r)
blocked=[
 {'sourceId':'tmr-fuc-psp-saber','sourcePage':'https://models.spriters-resource.com/psp/fateunlimitedcodes/asset/329721/','author':'HueyLoisTheThird','platform':'PSP','status':'blocked-403','reason':'Normal public download returned HTTP 403; stopped, no archive acquired.','advertisedFormats':['DAE','PNG']},
 {'sourceId':'sketchfab-fuc-rider2','sourcePage':'https://sketchfab.com/3d-models/psp-fate-unlimited-codes-rider-2-a7ace135df8146958854f01c0b5c9484','author':'pve771309','platform':'PSP','status':'blocked-403','reason':'Public model page returned 403; no viewer/API resource extraction attempted.'},
 {'sourceId':'sakai-fuc-caster-mod','sourcePage':'https://saikai0.blogspot.com/2015/07/caster-fate-unlimited-code.html','author':'Ivan LL','platform':'PSP (author description); GTA SA port','status':'link-gate-no-archive','reason':'Three ordinary author links all redirected to the same Linkvertise page; no actual original file URL or archive acquired. No hidden-link decoding or gate bypass.','authorArchivePassword':'Author publishes a normal archive password; not needed because no archive obtained.','sourceTerms':'Author asks share original post, no reupload/repost; recorded, not treated as broad redistribution rights.'},
 {'sourceId':'zenhax-fuc-fpk-sample','sourcePage':'https://zenhax.com/viewtopic.php@t=8190.html','author':'BloodRaynare / aluigi','platform':'unknown','status':'attachment-not-preserved','reason':'Post states FUC FPK sample was provided, but current archived HTML contains no attachment or download link.'},
 {'sourceId':'vgtimes-fuc-bazett-mod','sourcePage':'https://vgtimes.com/games/sifu/files/54375-fate-characters-kirei-and-bazett.html','author':'Anonymous; rehost listing by Flixx','platform':'unknown; Sifu target','status':'blocked-403','reason':'Ordinary download link returned 403; no archive obtained.'},
 {'sourceId':'tsr-fuc-ps2-voices','sourcePage':'https://sounds.spriters-resource.com/playstation_2/fateunlimitedcodes/asset/442789/','platform':'PS2','status':'blocked-403','reason':'Page returned 403, stopped. Independent Sprite Database author packages handled separately.'},
 {'sourceId':'101soundboards-fuc-ps2','sourcePage':'https://www.101soundboards.com/boards/1592193-fate-unlimited-codes-jpn-playstation-2-artoria-pendragon-saber-voice','platform':'PS2','status':'blocked-403','reason':'Normal board fetch returned 403, stopped; cached clip counts not treated as acquired.'},
]
hd=BASE/'fate-unlimited-codes-psp-first-batch/github-unlimitedcodes-hd';tree=json.loads((hd/'source-tree.json').read_text());blobs=[e for e in tree['tree'] if e['type']=='blob'];partial=next((hd/'original').glob('*.zip'))
hdrow={'sourceId':'github-fuc-psp-hd-textures','sourcePage':'https://github.com/Fate-AI-HD-Team/UnlimitedCodes-HD','author':'Fate-AI-HD-Team','sourcePlatform':'PSP','commit':'e1e6846ffbb4aa97b1510ac69712980f3b68fce2','status':'download-incomplete','expectedFiles':len(blobs),'expectedFileBytes':sum(e['size'] for e in blobs),'sourceExtensionCounts':dict(collections.Counter(Path(e['path']).suffix.lower() for e in blobs)),'partialArchive':{'path':str(partial),'bytes':partial.stat().st_size,'sha256':sha(partial),'usable':False},'downloadReceipts':[str(hd/'download-result.json'),str(hd/'git-download-result.json')],'resumeScript':str(CONTROL/'tooling/ggd-fuc-download-hd-tree.py'),'reason':'ZIP and normal Git transport ended with HTTP/2 stream CANCEL/early EOF. Full tree metadata is not an acquisition.','assetScope':'Texture supplementary pack only; no meshes, skeletons, animations or audio in published tree.'}
report={'schema':'ggd.independent-source-workflow-handoff@1','snapshotAt':datetime.now(timezone.utc).isoformat(),'workflow':'Fate/unlimited codes PSP with separate PS2 supplementary sources','status':'bounded-first-batch-delivered-native-library-still-missing','owner':'playstation_character_sources','centralIndexOwner':'root','localUse':'Frozen packages are ready for local indexing without waiting for S3.','packages':packages,'supplementaryTextureSource':hdrow,'blockedSources':blocked,'nativePspGaps':{'directNativeModelPackages':0,'originalSkeletons':0,'nativeAnimationClips':0,'nativeVfx':0,'nativeAudioPackages':0,'reason':'No reusable local Fate FPK/GMO/game source located; public complete native pack not obtained.','localScanEvidence':str(CONTROL/'tooling/ggd-fuc-local-source-search.json')},'formatPreparation':{'source':'https://github.com/shadow-nero/FPKCodes','pinnedCommit':'2b18af9390ca80eddee47ab7c4affbaf82a873c8','format':'16-byte header, 48-byte entries with 36-byte name and offset/compressed/uncompressed sizes, Eighting PRS','extractor':str(CONTROL/'tooling/extract_fate_fpk.py'),'validation':str(CONTROL/'tooling/ggd-fuc-fpk-synthetic-validation.json'),'realGameCompatibility':'unverified; no native FPK sample acquired','safety':'Read-only extraction only; no EBOOT patching, DRM, ROM download or game execution.'},'activeDownloadAtSnapshot':{'execSessions':[],'completedSession':95055,'exitCode':0,'files':['spritedatabase-shirou','spritedatabase-saber'],'action':'Original downloads completed; no background Fate download remains. HD tree resumable source script is prepared but not started.'},'publication':{'centralRepoEdited':False,'gitCommitOrPush':False,'awsOperation':False,'modelDefaultsChanged':False}}
stamp=datetime.now(timezone.utc).strftime('%Y%m%dT%H%M%SZ');out=CONTROL/('handoff-'+stamp+'.json');assert not out.exists();save(out,report)
copy=Path('/private/tmp/ggd-fate-unlimited-codes-report.json');save(copy,report)
print(json.dumps({'report':str(out),'sha256':sha(out),'completePackages':[p.get('sourceId') for p in packages if p['status']=='complete-frozen'],'pending':[p['localRoot'] for p in packages if p['status']!='complete-frozen']},ensure_ascii=False,indent=2))
