from pathlib import Path
import json,hashlib,shutil,datetime
root=Path('GGD-Asset-Library/intake/public-models-20260910/kof-author-models-round20').resolve()
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def save(p,x):p.write_text(json.dumps(x,ensure_ascii=False,indent=2)+'\n')
tools=[Path('/private/tmp/ggd-kof-drive-download.py'),Path('/private/tmp/ggd-kof-round20-extract.py'),Path('GGD-hero-model-options/tools/hero-model-library/extract_public_sources.py'),Path('/private/tmp/ggd-kof-fbx-inspect.py'),Path('/private/tmp/ggd-kof-round20-textures.py'),Path('/private/tmp/ggd-kof-round20-freeze-raw.py')]
receipts=[]
for sid,character,hero,authorurl in [('mai-xv-raw','Mai Shiranui','community-review-03-20260907','https://www.deviantart.com/whitemagesunny/art/The-King-of-Fighters-XV-Mai-Shiranui-974127482'),('iori-xv-raw','Iori Yagami','community-review-02-20260907','https://www.deviantart.com/whitemagesunny/art/The-King-of-Fighters-XV-Iori-Yagami-1227665754')]:
 r=root/sid;sourceid='kof-xv-'+('mai' if sid.startswith('mai') else 'iori')+'-whitemagesunny-raw';assert not (r/'source-manifest.json').exists()
 t=r/'tools';t.mkdir()
 for p in tools:shutil.copy2(p,t/p.name)
 for kind in ['gdrive','author']:
  src=root/'source-pages'/(sid+'-'+kind+'.html')
  if src.exists():shutil.copy2(src,r/('source-'+kind+'.html'))
 report=json.loads((r/'extraction-validation.json').read_text());fbx=json.loads((r/'fbx-analysis.json').read_text())['files'][0];tex=json.loads((r/'texture-validation.json').read_text());dl=json.loads((r/'download-final.json').read_text());model=r/fbx['sourcePath'];archive=r/report['archive']['path']
 assert dl['status']=='downloaded-rar' and sha(archive)==dl['sha256'];assert fbx['actionCount']==0
 for f in report['files']:assert sha(r/f['path'])==f['sha256']
 limits=['FBX import texture bindings are placeholder material names; all imported images remain unresolved until mapped to the 12 supplied TGA files.','sample_pbr_e3.dds environment/reflection reference is not supplied; do not invent a substitute as original source data.','No original gameplay animation, voice/SFX, or standalone VFX files are included in this model-only archive.','No GLB conversion, shader fidelity review, game runtime testing or backend selection acceptance has been performed.','Existing manually approved Mai proxy default is preserved; this is an additional candidate only.']
 if sid.startswith('mai'):limits.append('Blender import reported Materials mapping type NoMappingInformation; per-material assignments require inspection during conversion.')
 candidate={'candidateId':sourceid,'sourceId':sourceid,'character':character,'heroIds':[hero],'sourceGame':'The King of Fighters XV','sourcePlatform':'unknown-original-platform','platformEvidence':'Publisher names KOF XV; the game installation platform and patch are not specified. Publication date is not treated as game release or asset version.','sourceUrl':authorurl,'author':'WhiteMageSunny','sourceClass':'canonical-game-raw-export','nativeModel':fbx['sourcePath'],'nativeModelBytes':model.stat().st_size,'nativeModelSha256':sha(model),'nativeFormat':'FBX 7700','meshCount':fbx['meshObjectCount'],'vertices':fbx['vertices'],'triangles':fbx['triangles'],'boneCounts':[x['bones'] for x in fbx['armatures']],'maxVertexInfluences':max(x['maxVertexInfluences'] for x in fbx['meshObjects']),'sourceSkeleton':'Original game rig according to author; bone counts and all-vertex skinning verified by readonly FBX import.','textureCount':12,'animationCount':0,'vfxCount':0,'audioCount':0,'readyStage':'pending-standardization','runtimeReady':False,'backendSelectionVerified':False,'defaultChanged':False,'candidateMustBeRetained':True,'originalBytesPreserved':True,'limitations':limits}
 source={'schema':'ggd.acquired-model-source@1','sourceId':sourceid,'character':character,'sourceGame':'The King of Fighters XV','sourceGamePlatform':'unknown-original-platform','sourceUrl':authorurl,'downloadPage':dl['publicPage'],'uploader':'WhiteMageSunny','acquisitionChannel':'original author public raw export via Google Drive','publisherStatedContents':['FBX model','TGA textures','original game rig'],'classification':'original-game extracted model exported to FBX; original game claim belongs to author, FBX/rig/texture structure verified locally','status':'complete-acquired-extracted','sourcePackage':report['archive'],'modelCandidates':[candidate],'nativeAnimations':{'count':0,'evidence':'FBX imported with use_anim=True; no Actions. Archive contains only model/texture and optional desktop.ini.'},'vfx':{'count':0},'voice':{'count':0},'sfx':{'count':0},'audioFileIndex':None,'textureValidation':'texture-validation.json','modelAnalysis':'fbx-analysis.json','extractionValidation':'extraction-validation.json','rights':{'originalOwner':'SNK','authorStatement':'Property of SNK; author says they do not own original content. Raw archive offered via public Drive link; separate enhanced Blend available via Patreon was not acquired.','clearance':'not inferred'},'limitations':limits,'blenderInvocation':'Use python -P with the existing isolated bpy runtime; autoexec and online access disabled. Initial no-P attempt was affected by an unrelated /private/tmp/inspect.py; no source files changed.'}
 save(r/'source-manifest.json',source)
 files=[{'path':p.relative_to(r).as_posix(),'bytes':p.stat().st_size,'sha256':sha(p)} for p in sorted(r.rglob('*')) if p.is_file()]
 now=datetime.datetime.now(datetime.timezone.utc).strftime('%Y%m%dT%H%M%S%fZ');delivery=r/('delivery-'+now+'.json');save(delivery,{'schema':'ggd.immutable-local-source-delivery@1','localRoot':str(r),'sourceId':sourceid,'createdAt':now,'sourceManifest':'source-manifest.json','files':files,'fileCount':len(files),'totalBytes':sum(x['bytes'] for x in files),'freeze':'complete immutable referenced file set','runtimeSelectable':False,'nativeGameAnimations':0,'audioFileIndex':None})
 entry={'id':sourceid,'target':'KOF XV／'+character+'／原作者 FBX + TGA + 遊戲骨架原包','heroIds':[hero],'ownerEntryIds':[],'url':authorurl,'downloadUrl':dl['publicPage'],'uploader':'WhiteMageSunny','format':'FBX 7700 / 12 TGA','accessStatus':'public-direct-download','acquisitionStatus':'downloaded-verified','readiness':'pending-standardization','purchaseDecision':'hold-purchase-review-free-source','defaultEligible':False,'resourceRole':'character-model-collection','localPath':str(r),'sourceGame':'The King of Fighters XV','platform':'unknown-original-platform','selectionClass':'canonical-game','discoveryChannel':'original-author-public-raw-export','assetKinds':['model','texture','skeleton'],'modelCandidates':[candidate],'candidateManifest':{'path':'source-manifest.json','sha256':sha(r/'source-manifest.json')},'filesManifest':{'path':delivery.name,'sha256':sha(delivery)},'files':[report['archive']],'sourceLicense':source['rights']['authorStatement'],'publicationStatus':'local-only-not-uploaded','backendIntegration':{'required':True,'state':'pending-standardization','selectionVerified':False},'verification':f"原包{archive.stat().st_size} bytes，SHA與完整解包逐檔紀錄可查；{fbx['meshObjectCount']} mesh／{fbx['triangles']} triangles／{candidate['boneCounts'][0]}骨、全部頂點權重、最多4；12 TGA皆完整解碼。0原作動作/音訊/獨立VFX；FBX圖片引用待重綁，未GLB/後台驗收，無預設變更。",'backup':{'status':'not-uploaded','readbackVerified':False},'audioFileIndex':None}
 save(r/'public-source-entry.json',entry)
 receipts.append({'sourceId':sourceid,'localRoot':str(r),'entryPath':str(r/'public-source-entry.json'),'entrySha256':sha(r/'public-source-entry.json'),'deliveryPath':str(delivery),'deliverySha256':sha(delivery),'archivePath':str(archive),'archiveSha256':sha(archive),'nativeModelPath':str(model),'nativeModelSha256':sha(model),'meshCount':candidate['meshCount'],'vertices':candidate['vertices'],'triangles':candidate['triangles'],'bones':candidate['boneCounts'][0],'nativeAnimations':0,'audioCount':0,'textureCount':12,'gitEligibleFiles':['public-source-entry.json','source-manifest.json','fbx-analysis.json','texture-validation.json']+['tools/'+p.name for p in tools]})
save(Path('/private/tmp/ggd-kof-round20-raw-models-receipt.json'),receipts);print(json.dumps(receipts,ensure_ascii=False,indent=2))
