/**
 * groundMaterials — the manifest for the arena floor PBR sets in
 * content/assets/textures/ground/, generated by
 * `pnpm tsx apps/client/scripts/gen-ground.ts`.
 *
 * Task #80: the floor used to be a flat one-colour disc with a SQUARE GRID of
 * KayKit `floor_tile_large.glb` instances hard-clipped to the zone circle —
 * which can only ever produce a stair-stepped rim, and had no texture on it at
 * all. These sets are the material half of the fix.
 *
 * This module is deliberately Babylon-FREE: it is paths, colour-space facts and
 * pure arithmetic, so it can be unit-tested and so the mesh rebuild can bind it
 * however it likes. Nothing here creates a material.
 *
 * ── HOW THE TWO LAYERS FIT TOGETHER ────────────────────────────────────────
 * `albedo` / `normal` / `orm` TILE, one repeat per TILE_WORLD_SIZE world units
 * (use `detailUvScale()`). `macro` does NOT tile — stretch it across the zone
 * exactly once (uScale = vScale = 1, centred on the disc). The macro layer is
 * what stops the eye from finding the repeat: every large-scale feature on the
 * floor comes from it and is therefore unique per position, while the only
 * repeating content is too fine-grained to fingerprint.
 */
import {
  DEFAULT_GROUND_STYLE,
  isGroundStyleId,
  type GroundStyleId,
} from "@ggd/shared/content/schema/groundStyle";
import { withContentVersion } from "../content/assetVersion";

/** Where the generated sets are served from (vite dev + prod nginx both map
 *  /content onto the repo `content/` directory). */
export const GROUND_TEXTURE_BASE = "/content/assets/textures/ground";

/** World units covered by one repeat of the detail maps. Must stay in step with
 *  TILE_WORLD_SIZE in apps/client/scripts/texgen/styles.ts. */
export const TILE_WORLD_SIZE = 4;

/**
 * The generated sets. ⭐ GH#342 — one set per `groundStyle`, **identically
 * named**, so this module no longer keeps a second list of style names.
 *
 * Before #342 there was a hand-written `STYLE_TO_SET` map here whose only
 * non-identity row was `wood → stone` (「no arena asks for wood, don't ship
 * 700 KB of planks nobody loads」). That row was a silent downgrade waiting to
 * happen: the day an arena DID ask for wood it would have got flagstone and
 * nothing would have said so. The rule is now structural instead —
 * `GROUND_STYLE_IDS` is the only list, every id has a painter, and
 * `groundMaterials.test.ts` fails if a set's PNGs are not on disk.
 */
export type GroundTextureSet = GroundStyleId;

/**
 * ArenaDef `groundStyle` → generated set. Unknown / absent → the schema default.
 * ⚠️ Unknown is only reachable from hand-edited or future content; the schema
 * already rejects it, so this is a last-resort floor, not a mapping table.
 */
export function groundTextureSet(groundStyle: string | undefined): GroundTextureSet {
  return isGroundStyleId(groundStyle) ? groundStyle : DEFAULT_GROUND_STYLE;
}

export interface GroundTextureUrls {
  /** base colour — **sRGB / gamma space** (Babylon's default for a texture) */
  albedo: string;
  /** tangent-space normal, OpenGL/glTF +Y up — **LINEAR** (`gammaSpace = false`) */
  normal: string;
  /** R = ambient occlusion, G = roughness, B = metallic — **LINEAR** */
  orm: string;
  /** arena-wide variation, Babylon detailMap packing — **LINEAR** */
  macro: string;
}

/**
 * The four map URLs for a ground set, stamped with the content cache key.
 * `?h=<contentVersion>` is what flips nginx from `no-cache` to `public,
 * max-age=31536000, immutable` (nginx.conf `map $arg_h $content_cache`); the
 * ground sets are 2,940,212 B across 17 files and are re-fetched on every arena
 * build without it. A no-op before the content manifest lands.
 */
export function groundTextureUrls(set: GroundTextureSet): GroundTextureUrls {
  const dir = `${GROUND_TEXTURE_BASE}/${set}`;
  return {
    albedo: withContentVersion(`${dir}/albedo.png`),
    normal: withContentVersion(`${dir}/normal.png`),
    orm: withContentVersion(`${dir}/orm.png`),
    macro: withContentVersion(`${dir}/macro.png`),
  };
}

/**
 * uScale/vScale for the DETAIL maps on a ground disc of the given boundary
 * radius, so one texture repeat covers TILE_WORLD_SIZE world units regardless
 * of zone size. Babylon's built-in disc/cylinder UVs span the mesh 0..1, so the
 * scale is simply the number of repeats across the diameter. Pure — testable.
 */
export function detailUvScale(boundaryRadius: number): number {
  return (boundaryRadius * 2) / TILE_WORLD_SIZE;
}

/**
 * How to bind these maps. Recorded here because two of these facts are NOT
 * guessable and silently produce wrong-looking ground if assumed.
 *
 * 1. COLOUR SPACE. Only `albedo` is gamma-space. `normal`, `orm` and `macro`
 *    carry data, not colour, and MUST be constructed with `noMipmap=false,
 *    invertY=false` and then `texture.gammaSpace = false` — otherwise every
 *    roughness and normal value is silently gamma-decoded and the floor turns
 *    shiny and over-embossed.
 *
 * 2. `orm` is the glTF ORM packing, so on a PBRMaterial set
 *    `metallicTexture = orm` plus
 *      useAmbientOcclusionFromMetallicTextureRed = true
 *      useRoughnessFromMetallicTextureGreen     = true
 *      useMetallnessFromMetallicTextureBlue     = true
 *      useRoughnessFromMetallicTextureAlpha     = false
 *
 * 3. `macro` goes on `material.detailMap` with `isEnabled = true`. Babylon's
 *    detail-map channel order is NOT the intuitive one — VERIFIED against the
 *    shipped shader source of @babylonjs/core 7.54.3, not from memory:
 *      bumpFragment.js           `detailColor.wy*2.0-1.0`  → normal XY = A, G
 *      pbrBlockAlbedoOpacity.js  `detailColor.r`           → albedo detail = R
 *      pbrBlockReflectivity.js   `detailColor.b`           → roughness detail = B
 *    i.e. R = albedo, G = normal.y, B = roughness, A = normal.x, 128 neutral.
 *    Note the albedo detail is applied SQUARED — `albedo *= (2*mix(0.5,R,lvl))²`
 *    — which is why the generator keeps R inside 0.4…0.6.
 *
 *    The detail map needs its own UV set/scale (uScale = vScale = 1) so it does
 *    NOT inherit the tiled detail scaling.
 */
export const GROUND_BLEND_LEVELS = {
  /** detailMap.diffuseBlendLevel — full strength; amplitude lives in the map */
  diffuse: 1.0,
  /** detailMap.roughnessBlendLevel */
  roughness: 0.8,
  /** detailMap.bumpLevel — macro normal is gentle arena dishing, not detail */
  bump: 0.6,
} as const;
