from pathlib import Path
import json,hashlib,datetime,shutil
ROOT=Path('/Users/Takuro/Dropbox/我的 Mac (Moriya.local)/Documents/ABxVFX_EDIT');p=ROOT/'GGD-Asset-Library/intake/public-models-20260910/parallel-community-lina-rays-300-retarget';now=datetime.datetime.now(datetime.timezone.utc).isoformat();sha=lambda f:hashlib.sha256(Path(f).read_bytes()).hexdigest();dump=lambda f,j:Path(f).write_text(json.dumps(j,ensure_ascii=False,indent=2)+'\n');entry=lambda f:{'path':str(Path(f).relative_to(p)),'bytes':Path(f).stat().st_size,'sha256':sha(f)}
pr=json.loads((p/'retarget-proof-resampled-120hz.json').read_text());pres=json.loads((p/'evidence/target-preservation.json').read_text());foot=json.loads((p/'evidence/dense-foot-audit-v3.json').read_text());prior=json.loads(Path('/private/tmp/ggd-parallel-lina-hand-review-report.json').read_text())['sources'][0];upstream=[]
for c in prior['modelCandidates']:
 f=Path(c['localPath']);upstream.append({'candidateId':c['candidateId'],'path':str(f),'expectedSha256':c['file']['sha256'],'sha256Now':sha(f),'unchanged':sha(f)==c['file']['sha256']})
assert all(x['unchanged'] for x in upstream);dump(p/'evidence/upstream-eight-candidates-preservation.json',upstream)
reviewedV3=['rays-retarget-idle-front-000.png','rays-retarget-idle-side-000.png','rays-retarget-run-front-000.png','rays-retarget-run-side-000.png','rays-retarget-run-side-250.png','rays-retarget-run-side-500.png','rays-retarget-run-side-750.png','rays-retarget-run-front-500.png']
reviewedV2=['300-lina-idle-front-000.png','rays-retarget-idle-front-000.png','300-lina-run-front-000.png','rays-retarget-run-front-000.png','rays-retarget-run-front-250.png','rays-retarget-run-front-500.png','rays-retarget-run-front-750.png','rays-retarget-run-side-000.png','rays-retarget-idle-side-000.png','300-lina-run-front-250.png','300-lina-run-side-250.png','rays-retarget-run-side-250.png','rays-retarget-run-side-500.png','rays-retarget-run-side-750.png']
limitations=['No native Rays animation; all two clips are 300英雄動作重綁到Rays模型. No walk clip is available in existing GLB or native metadata.','Native JUMPX FPS is unknown. Existing GGD GLB durations are preserved; 120 Hz is derived processing and Babylon 60 fps is an importer convention, not verified native timing.','240 Hz boot-vertex audit still finds run right boot -1.18 mm below ground; idle left boot stays roughly 1.4 cm above ground.','Run loop foot-position gaps remain 10.1 cm left / 6.3 cm right; endpoint repair not performed.','Run is in-place with no gameplay velocity; planted-foot locking and sliding are not solved. Near-contact samples can move horizontally up to roughly 20 m/s under the existing very fast clip tempo.','Only short near-ground contacts and visually elevated run phases remain after constant grounding. This is a review sample, not production locomotion.','No transfer of limb axial twist or separate finger animation; selected relaxed hand meshes are rigid wrist children. No target toe joint; source toe orientation drives target boot.','Unmapped hair/cape/accessory joints preserve local rest. Large static cape silhouette during running is visible and lacks source secondary motion.','Sparse visual inspection covers 22 images across baseline/source and final snapshots, not every frame. Dense geometry audit checks feet, not whole-body self collision.','Assimp readback confirms parsing/counts only; renderer/CPU skin calculations are used for skin-space grounding, not Assimp static bounds.','No game runtime, backend selection, production default, or gameplay locomotion acceptance.']
visual={'schema':'ggd-retarget-visual-review@1','createdAt':now,'renderer':'Babylon.js 7.54.3 actual GLB animation playback in independent local headless Chrome','sourceComparison':'Source 300 GLB idle/run and initial retarget captured separately at 8 phases from front/side. Final V3 repeats target at same phases.','actualAnimationGroupsPlayed':True,'v2PngCount':64,'v3PngCount':32,'recordedWebmCount':6,'finalPreviewMp4Count':2,'visuallyInspectedImages':[str(p/'evidence/playback-v2'/n) for n in reviewedV2]+[str(p/'evidence/playback-v3'/n) for n in reviewedV3],'visualFindings':['Face, clothes, textures, shoulder armor, limb proportions and selected single pair of hands remain coherent in inspected phases.','No obvious whole-limb joint inversion or incompatible skeleton collapse is visible in inspected front/side poses.','Idle has slight lateral foot movement and unequal sole height. Run keeps forward lean and stride pattern but visibly floats during several phases; cape remains broad and rigid.'],'denseFootAudit':[{k:v for k,v in r.items() if k!='frames'} for r in foot],'runtimeReady':False,'footPlantPass':False,'loopContinuityPass':False,'limitations':limitations}
dump(p/'visual-review.json',visual)
modelFile=Path(pr['output']);candidate={'candidateId':'community.slayers-tales-of-rays.lina00-hands-a.300heroes-retarget-review','sourceCandidateId':'community.slayers-tales-of-rays.lina00-hands-a','sourceId':p.name,'upstreamSourceId':'parallel-community-slayers-lina-hand-review','label':'莉娜 lina00 放鬆手型 — 300英雄 idle/run 動作重綁試作（待腳步與接縫修復）','nativeCharacter':'Lina Inverse','heroIds':['godie-h020','godie-hjai'],'resourceRole':'character-body-retarget-review-sample','sourceClass':'original-game-body-with-cross-game-retargeted-animation','sourceUrl':'https://open3dlab.com/project/b8113b97-01b8-4a89-ba62-6b4c7d75ffee/','author':'Ceruleancast / Meowth for Smash; original model ripping credited to Kittyinhiding and ArkDelgato; local GGD retarget study','sourceGame':'Tales of the Rays','sourcePlatform':'Mobile (Android/iOS)','sourceWork':'Slayers','animationSourceGame':'300英雄','animationSourceId':'300heroes:46','animationProvenanceLabel':'300英雄動作重綁到Rays模型','nativeAnimationFps':'unknown','localPath':str(modelFile),'file':entry(modelFile),'format':'glb','bodyModelCount':1,'meshNodes':3,'meshPrimitives':5,'triangles':pres['triangles'],'joints':69,'retargetedMajorJoints':19,'embeddedTextures':3,'distinctEmbeddedTexturePayloads':2,'nativeRaysAnimationClips':0,'derivedAnimationClips':2,'sourceWalkAvailable':False,'audioFiles':0,'sceneScale':.01,'nominalRestHeightMeters':1.55758,'canonicalCharacterHeightClaim':False,'selection':{'handVariant':'a','left':'HandLa.013','right':'HandRa.013','visibleLeftHandMeshes':1,'visibleRightHandMeshes':1},'animations':[{'name':c['outputClip'],'sourceClip':c['sourceClip'],'durationSeconds':c['duration'],'sourceKeyCount':len(c['sourceKeyTimes']),'derivedKeyCount':len(c['outputSampleTimes']),'nativeRaysAnimation':False,'groundCorrectionMeters':c['constantGroundOffsetMeters']} for c in pr['clips']],'rootMotion':{'horizontal':'in-place; source root XZ trajectory discarded','vertical':'source root Y delta relative to source rest, multiplied by leg-length ratio 1.8731744117095663','grounding':'constant per-clip vertical translation, derived processing; 120 Hz minima plus 2 mm margin; no IK','sourceDurationPreserved':True,'originalRunRelabeledWalk':False},'validation':{'khronosErrors':0,'khronosWarnings':0,'khronosInfos':1,'khronosInfo':'FB_ngon_encoding unsupported by validator','khronosTruncated':False,'assimpReadback':True,'geometryWeightsTexturesAndInverseBindMatricesUnchanged':True,'actualBabylonPlayback':True,'visualReview':'bounded phase snapshots and dense foot audit','runtimeReady':False,'footPlantPass':False,'loopContinuityPass':False},'existsLocal':True,'readiness':'review-sample-needs-foot-contact-loop-repair','backendSelectableVerified':False,'eligibleForAutomaticDefault':False,'runtimeReady':False,'manualDefaultsChanged':False,'limitations':limitations}
intermediates=[{'file':entry(f),'resourceRole':'audit-baseline-not-distinct-character','automaticallySelectable':False,'notes':('same dense retarget rotations, source-scaled root bob, zero grounding offset' if 'ungrounded' in f.name else 'earlier prototype; retained for comparison and reproducibility')} for f in sorted((p/'candidates').glob('*.glb')) if f!=modelFile]
dump(p/'model-candidates.json',{'schema':'ggd-local-model-candidates@1','generatedAt':now,'candidates':[candidate],'auditIntermediates':intermediates,'noDefaultChanges':True})
dump(p/'audio-index.json',{'schema':'ggd-source-audio-index@1','sourceId':p.name,'groups':[],'playableVoiceFiles':0,'nativeAudioFiles':0,'note':'This retarget batch downloads no new audio. Browser playback videos have no game audio and are validation evidence only. Previous SSBU Lina audio remains in its own frozen source index.'})
md=['# 莉娜 Rays × 300英雄：重綁樣本驗收\n','本批交付 **1 個待修復的重綁候選、2 段衍生動作**。主要骨架能對應並實際播放，但跑步腳步與循環接縫未達正式遊戲使用要求；`runtimeReady=false`，不改後台預設。原 8 個手型 GLB、300 英雄 GLB／原始 JUMPX 均未修改。\n','模型來自 Tales of the Rays 的 lina00、手型 a；動作必須標為 **「300英雄動作重綁到Rays模型」**。這不是 Rays 原生動畫。來源有 idle / run，沒有 walk。JUMPX 原生 FPS 未知，只保留既有 GGD 300 GLB 的時間長度。\n',f'候選：[GLB](<{modelFile}>)。檢索入口：[model-candidates.json](<{p/"model-candidates.json"}>)，完整限制：[visual-review.json](<{p/"visual-review.json"}>)。\n','| 動作 | 長度 | 加工 | 結果 |\n|---|---:|---|---|','| bat_idle | 1.21875 秒 | 120 Hz 加原關鍵幀；整段下移 0.995 cm | 右腳約 0.2 cm、左腳約 1.4 cm 離地；仍有 <1 cm 水平晃動 |','| single_run | 0.40625 秒 | 120 Hz 加原關鍵幀；整段上移 6.589 cm | 右腳最深穿地 1.18 mm；循環足部差左 10.1 cm／右 6.3 cm；腳滑未解決 |\n','公尺換算僅在骨架根節點套用 0.01，名義靜止高度約 1.558 m，並非宣稱官方身高。水平根位置保持原地；垂直起伏用來源根 Y 差乘腿長比 1.87317，再加每段常數地面修正。沒有加 IK、沒有補造原作動作、沒有生成向前軌跡。\n','重新取樣與地面修正都屬衍生加工。四份 GLB 包含最早 prototype、原關鍵幀 stable-torso、120 Hz 修正版，以及相同 120 Hz 動作但零地面偏移的 ungrounded-control；三個非主候選（prototype、stable-torso、ungrounded-control）在索引明列為 audit intermediates，不能算成四個角色。\n',f'逐幀差值：[v2-v3-per-frame-difference.json](<{p/"evidence/v2-v3-per-frame-difference.json"}>)；来源根位移：[root-motion-trace.json](<{p/"evidence/root-motion-trace.json"}>)；来源路径／SHA：[source-provenance.json](<{p/"evidence/source-provenance.json"}>)。\n','原始 300 关键帧版在插值间最低约穿地 7.7 cm；密集重取样后降至 1.18 mm，但数值不能掩盖跑步接触时间短、漂浮及循环接缝。因此它是可审查的技术样本，还不能交给移动系统当作已验收成品。\n','实际 Babylon 播放与逐相位截图已保存。最终两段 WebM 分别解码 77 / 78 帧，帧哈希均不同；另有便于打开的 MP4 副本。画面检视覆盖 22 张 source/baseline/final 图，未声称逐张审核全部 96 张。\n',f'[待机影片](<{p/"evidence/playback-v3/rays-retarget-idle-playback.mp4"}>) · [跑步影片](<{p/"evidence/playback-v3/rays-retarget-run-playback.mp4"}>)\n',f'![待機正面]({p/"evidence/playback-v3/rays-retarget-idle-front-000.png"})\n',f'![跑步側面]({p/"evidence/playback-v3/rays-retarget-run-side-000.png"})\n','貼圖、頂點、UV、權重、逆綁定矩陣及保留手型的二進位原始資料皆完整未改；主要骨架 19 個關節重綁，原 69 joints 全保留。Khronos 0 errors / 0 warnings，1 項不支援 FB_ngon_encoding 的資訊；Assimp 成功讀回。結構檢查不能證明脚步、披風或遊戲執行品質。\n','髮絲、披風與附件未移植次級動態；披風在跑步時呈寬而僵硬的形狀。未移植肢體軸向扭轉；手指是單一手型剛性部件；沒有目標腳趾骨，暫以來源 toe 方位驅動靴子。\n','骨骼映射依世界空間肢體方向重新推導目標局部旋轉，不直接複製同名局部 quaternion。來源雙腿父節點是 Spine，Rays 為 Pelvis；來源鎖骨在 Neck 下，Rays 在 Spine2 下。Rays Pelvis／Spine1 同位置，所以用 Pelvis→Spine2 校準軀幹方向。\n','| Rays 關節 | Rays 父節點 | 300 關節 | 300 父節點 | 方法 |\n|---|---|---|---|---|']
md += [f"| {m['target']} | {m['targetParent']} | {m['source']} | {m['sourceParent']} | {m['method']} |" for m in pr['mappedJoints']]
md += ['\n本輪未改中央文件、Git、S3、角色預設；只交付獨立凍結資料夾。來源條件繼承原 Slayers 來源包，未取得額外授權或改變既有作者署名。\n']
(p/'REVIEW.md').write_text('\n'.join(md))
# Cache files are ours, not source artifacts. Keep all source/model/evidence files intact.
if (p/'scripts/__pycache__').exists():shutil.rmtree(p/'scripts/__pycache__')
shutil.copyfile('/private/tmp/ggd-lina-retarget-freeze.py',p/'scripts/ggd-lina-retarget-freeze.py')
files=[entry(f) for f in sorted(p.rglob('*')) if f.is_file() and f.name not in ['all-files.sha256.jsonl','SHA256SUMS','source-report.json']]
(p/'all-files.sha256.jsonl').write_text(''.join(json.dumps(x,ensure_ascii=False)+'\n' for x in files));(p/'SHA256SUMS').write_text(''.join(x['sha256']+'  '+x['path']+'\n' for x in files))
src={'id':p.name,'title':'Lina Rays × 300 heroes idle/run retarget review sample','sourceUrl':candidate['sourceUrl'],'upstreamSourceId':'parallel-community-slayers-lina-hand-review','localRoot':str(p),'localRootStable':True,'status':'frozen-retarget-review-sample-foot-contact-and-loop-repair-required','candidateCount':1,'distinctCharacterBodies':1,'totalGlbFiles':4,'auditIntermediateGlbFiles':3,'nativeRaysAnimationClips':0,'derivedAnimationClips':2,'sourceWalkAvailable':False,'nativeAnimationFps':'unknown','audioFiles':0,'downloadedNewAssets':False,'modelCandidateIndexPath':str(p/'model-candidates.json'),'modelCandidateIndexSha256':sha(p/'model-candidates.json'),'visualReviewPath':str(p/'visual-review.json'),'visualReviewSha256':sha(p/'visual-review.json'),'audioIndexPath':str(p/'audio-index.json'),'audioIndexSha256':sha(p/'audio-index.json'),'allFilesManifestPath':str(p/'all-files.sha256.jsonl'),'allFilesManifestSha256':sha(p/'all-files.sha256.jsonl'),'manifestRows':len(files),'manifestAssetBytes':sum(x['bytes'] for x in files),'modelCandidates':[candidate],'auditIntermediates':intermediates,'runtimeReady':False,'backendSelectableVerified':False,'sharedIndexesChanged':False,'gitChanged':False,'s3Uploaded':False,'manualDefaultsChanged':False,'sourceFilesPreserved':True,'eightHandVariantsPreserved':True,'limitations':limitations}
report={'schema':'ggd-parallel-source-acquisition-report@1','generatedAt':now,'sources':[src],'sharedIndexesChanged':False,'gitChanged':False,'s3Uploaded':False,'pending':['Foot contact and loop endpoint repair, then gameplay locomotion / velocity testing. Preserve provenance and do not label as Rays-native animation.']};dump(p/'source-report.json',report);dump('/private/tmp/ggd-parallel-lina-retarget-report.json',report)
# Verify every fixed manifest row immediately.
for x in files:
 f=p/x['path'];assert f.stat().st_size==x['bytes'] and sha(f)==x['sha256'],x['path']
allNow=[f for f in p.rglob('*') if f.is_file()];print(json.dumps({'report':'/private/tmp/ggd-parallel-lina-retarget-report.json','reportSha256':sha('/private/tmp/ggd-parallel-lina-retarget-report.json'),'filesIncludingManifestsAndReport':len(allNow),'bytesIncludingManifestsAndReport':sum(f.stat().st_size for f in allNow),'manifestRows':len(files),'manifestSha256':sha(p/'all-files.sha256.jsonl'),'candidateSha256':sha(modelFile)},ensure_ascii=False,indent=2))
