from pathlib import Path
import sys,json,copy,hashlib,ast,struct,shutil,subprocess,math
import numpy as np
ROOT=Path('/Users/Takuro/Dropbox/我的 Mac (Moriya.local)/Documents/ABxVFX_EDIT');base=ROOT/'GGD-Asset-Library/intake/public-models-20260910';p=base/'parallel-community-lina-rays-300-retarget';sys.path.insert(0,str(p/'scripts'));import glb_io as glb,retarget_math as rm
sha=lambda f:hashlib.sha256(Path(f).read_bytes()).hexdigest()
v2=json.loads((p/'retarget-proof-stable-torso.json').read_text());v3=json.loads((p/'retarget-proof-resampled-120hz.json').read_text());target=glb.read(v3['targetModel']);model=glb.read(v3['output']);sj=model.gltf;world,parents=rm.globals_of(sj);names={n['name']:i for i,n in enumerate(sj['nodes'])};outj=copy.deepcopy(sj);binary=bytearray(model.bin)
# Preserve a separate ungrounded control with exactly the same dense rotations and root bob.
for clip,pr in zip(outj['animations'],v3['clips']):
 c=next(c for c in clip['channels'] if c['target']['path']=='translation');a=outj['accessors'][clip['samplers'][c['sampler']]['output']];view=outj['bufferViews'][a['bufferView']];start=view.get('byteOffset',0)+a.get('byteOffset',0);vals=np.array(model.accessor_values(clip['samplers'][c['sampler']]['output'])).reshape(-1,3);localDelta=(np.linalg.inv(world[parents[names['Pelvis']]])@np.array([0,pr['constantGroundOffsetMeters'],0,0]))[:3];vals-=localDelta;binary[start:start+vals.size*4]=np.asarray(vals,dtype='<f4').tobytes();a['min']=vals.min(axis=0).tolist();a['max']=vals.max(axis=0).tolist()
outj['asset']['generator']='GGD ungrounded audit control: 300 heroes to Rays retarget; not runtime candidate';ungrounded=p/'candidates/lina00-hands-a-300-idle-run-resampled-ungrounded-control.glb';glb.write(str(ungrounded),outj,bytes(binary))
# Target original binary payload and all original accessors/mesh/skin/image/material definitions survive byte-for-byte.
preservation={'targetSourcePath':v3['targetModel'],'targetSourceSha256Now':sha(v3['targetModel']),'targetMatchesAcquisitionSha256':sha(v3['targetModel'])==v3['targetSha256'],'sourceAnimationSha256Now':sha(v3['sourceModel']),'sourceAnimationMatchesInputSha256':sha(v3['sourceModel'])==v3['sourceSha256'],'originalBinaryPayloadUnchanged':model.bin[:len(target.bin)]==target.bin,'originalBinaryPayloadBytes':len(target.bin),'originalAccessorsUnchanged':sj['accessors'][:len(target.gltf['accessors'])]==target.gltf['accessors'],'allOriginalBufferViewsUnchanged':sj['bufferViews'][:len(target.gltf['bufferViews'])]==target.gltf['bufferViews'],'unchangedDefinitions':{k:sj.get(k)==target.gltf.get(k) for k in ['meshes','skins','images','textures','materials','samplers']},'nodeNamesAndHierarchyUnchanged':[(n.get('name'),n.get('children')) for n in sj['nodes']]==[(n.get('name'),n.get('children')) for n in target.gltf['nodes']],'targetJointCount':len(sj['skins'][0]['joints']),'activeMeshNodes':[{k:n[k] for k in ['name','mesh','skin'] if k in n} for n in sj['nodes'] if 'mesh'in n],'embeddedImageSha256':[hashlib.sha256(model.view_bytes(i['bufferView'])).hexdigest() for i in sj['images']],'triangles':model.triangles(),'sceneScale':sj['nodes'][0]['scale']}
(p/'evidence/target-preservation.json').write_text(json.dumps(preservation,ensure_ascii=False,indent=2)+'\n')
# Root strategy and frame-by-frame correction receipt. Read original source and both outputs without executing conversion.
tree=ast.parse(Path('/private/tmp/ggd-lina-retarget.py').read_text());fn=next(n for n in tree.body if isinstance(n,ast.FunctionDef) and n.name=='sample_animation');code=ast.unparse(fn);line=next(s for s in code.splitlines() if s.strip().startswith('trsrows ='));code=code.replace(line,'    trsrows = copy.deepcopy(sj["nodes"])');exec(code)
source=glb.read(v3['sourceModel']);sj=source.gltf;restSource,_=rm.globals_of(sj);sourceNames={n['name']:i for i,n in enumerate(sj['nodes'])};sourceRoot=sourceNames['Bip01'];rootTrace=[]
audit2=json.loads((p/'evidence/dense-foot-audit.json').read_text());audit3=json.loads((p/'evidence/dense-foot-audit-v3.json').read_text())
for pr,c2,c3 in zip(v3['clips'],v2['clips'],audit3):
 animation=next(a for a in sj['animations'] if a['name']==pr['sourceClip']);rows=[]
 for row in c3['frames']:
  t=row['seconds'];w=sample_animation(animation,t);rows.append({'seconds':t,'sourceRootWorldXYZ':w[sourceRoot][:3,3].tolist(),'sourceRootVerticalDelta':float(w[sourceRoot][1,3]-restSource[sourceRoot][1,3]),'targetScaledVerticalDeltaMeters':float((w[sourceRoot][1,3]-restSource[sourceRoot][1,3])*v3['legLengthRatio']),'targetConstantGroundingCorrectionMeters':pr['constantGroundOffsetMeters'],'targetV3MinusV2ConstantPelvisYMeters':pr['constantGroundOffsetMeters']-c2['constantGroundOffsetMeters'],'horizontalRootTranslationTransferred':False,'ikApplied':False})
 rootTrace.append({'sourceClip':pr['sourceClip'],'outputClip':pr['outputClip'],'nativeFps':'unknown','sourceGlbDurationSeconds':pr['duration'],'samplingHz':240,'rows':rows})
(p/'evidence/root-motion-trace.json').write_text(json.dumps(rootTrace,indent=2)+'\n')
frameDelta=[]
for a,b in zip(audit2,audit3):
 assert len(a['frames'])==len(b['frames']);rows=[]
 for x,y in zip(a['frames'],b['frames']):
  assert x['seconds']==y['seconds'];r={'seconds':x['seconds']}
  for side in 'LR':r[side]={'v2MinY':x[side]['minY'],'v3MinY':y[side]['minY'],'deltaMinY':y[side]['minY']-x[side]['minY'],'deltaSoleCentroidXYZ':(np.array(y[side]['soleCentroid'])-np.array(x[side]['soleCentroid'])).tolist()}
  rows.append(r)
 frameDelta.append({'clip':a['clip'],'sampleHz':240,'v2':'original key times with one constant ground correction','v3':'120Hz plus original key times; source interpolation evaluated again; new constant grounding with 2mm sampled safety margin','warning':'Per-frame differences include nonlinear retarget resampling, not only vertical grounding. Neither output adds foot IK or repairs loop endpoints.','frames':rows})
(p/'evidence/v2-v3-per-frame-difference.json').write_text(json.dumps(frameDelta,indent=2)+'\n')
sourceFiles=[Path(v3['sourceModel']),Path(v3['targetModel']),ROOT/'GGD-hero-model-options/content/models/community.body.08f7a7de95c4beb47b77a27b49e04db9eefd8192f6e5952b.json',ROOT/'outputs/game-asset-library-20260907/300heroes/raw/data/character/roleaction/046.x',ROOT/'outputs/game-asset-library-20260907/300heroes/models/data/character/roleaction/046/model.json',ROOT/'outputs/game-asset-library-20260907/300heroes/models/data/character/roleaction/046/animation-data.bin'];native=json.loads(sourceFiles[-2].read_text());sources={'files':[{'path':str(f),'bytes':f.stat().st_size,'sha256':sha(f)} for f in sourceFiles],'nativeAnimationNote':native['animation_note'],'nativeAnimationFps':'unknown','nativeSourceClipCount':len(native['clips']),'nativeSourceWalkClips':[c for c in native['clips'] if 'walk'in c['name']],'usedSourceClips':[c for c in native['clips'] if c['name'] in ['bat_idle','single_run']],'animationProvenance':'The output uses the existing 300heroes GGD GLB sampling/timing, not a new raw JUMPX decode. Existing GLB durations are preserved; unknown native FPS is not asserted as verified.'};(p/'evidence/source-provenance.json').write_text(json.dumps(sources,ensure_ascii=False,indent=2)+'\n')
videos=[]
for f in sorted((p/'evidence/playback-v3').glob('*.webm')):
 meta=subprocess.run(['ffprobe','-v','error','-count_frames','-show_streams','-show_format','-of','json',str(f)],capture_output=True,text=True,check=True);m=json.loads(meta.stdout);check=subprocess.run(['ffmpeg','-v','error','-i',str(f),'-f','framemd5','-'],capture_output=True,text=True,check=True);hashes=[x.split(',')[-1].strip() for x in check.stdout.splitlines() if x and not x.startswith('#')];(p/'evidence'/('v3-'+f.stem+'.framemd5.txt')).write_text(check.stdout);videos.append({'file':str(f),'bytes':f.stat().st_size,'sha256':sha(f),'probe':m,'decodedFrames':len(hashes),'distinctDecodedFrameHashes':len(set(hashes)),'allFramesDecodedSuccessfully':True})
(p/'evidence/playback-v3-video-validation.json').write_text(json.dumps(videos,indent=2)+'\n')
for f in ['ggd-lina-retarget-stable-torso.py','ggd-lina-retarget-foot-audit-v3.py','ggd-lina-retarget-render-server-v3.py','ggd-lina-retarget-delivery-audit.py']:shutil.copyfile('/private/tmp/'+f,p/'scripts'/f)
print(json.dumps({'preservation':preservation,'videos':[(Path(x['file']).name,x['decodedFrames'],x['distinctDecodedFrameHashes']) for x in videos],'groundingOffsets':[(c['sourceClip'],c['constantGroundOffsetMeters']) for c in v3['clips']],'sourceFiles':sources['files']},indent=2))
