from pathlib import Path
import json,hashlib
ROOT=Path(__file__).resolve().parents[1];OLD=ROOT.parent/'priority-naofumi-canonical-20260910'
def read(p):return json.loads(Path(p).read_text())
def rec(p):
 p=Path(p).resolve();b=p.read_bytes();return {'path':str(p),'bytes':len(b),'sha256':hashlib.sha256(b).hexdigest()}
rt=ROOT/'runtime-v2';receipt=read(rt/'receipt.json');motion=read(rt/'motion.json');render=read(ROOT/'render-runtime-v2/render-proof.json');diff=read(ROOT/'alpha-only-diff.json');native=read(ROOT/'native-audit/native-structure-and-decoder.json');modes=read(ROOT/'native-audit/dragonff-mode-comparison.json');old=read(OLD/'candidate-manifest.json');issues=read(rt/'khronos-unlimited.json')['issues']
assert diff['binaryChunkByteIdentical'] and len(diff['jsonChanges'])==4 and all(d['path'].endswith('/alphaMode') for d in diff['jsonChanges'])
assert all(m['matchesSelectedNativePositionUVMaterialLoopMultiset'] for m in modes['modes'])
assert not issues['numErrors'] and not issues['numWarnings'] and not issues['truncated']
quality={'schema':'ggd-model-visual-gate@1','visualAcceptance':'sampled-views-pass','sharedContractPassed':True,'issueResolved':'Incorrect BLEND for natively opaque DFF/TXD materials; source UV/texture mismatch hypothesis disproved by native/importer and alpha-only controlled comparisons','primaryImages':[rec(ROOT/'render-runtime-v2'/f) for f in ['ggd-procedural-idle-front-start.png','ggd-procedural-idle-side-middle.png','ggd-procedural-idle-back-middle.png','ggd-procedural-run-front-middle.png']],'reviewScope':'14 actual WebGL samples, front/side/back body and selected run frame manually reviewed; native motions0; gameplay acceptance pending','priorFailedCandidateRetained':str(OLD),'engineOrCentralChanges':False}
(rt/'quality-gate.json').write_text(json.dumps(quality,ensure_ascii=False,indent=2)+'\n')
candidate={'schema':'ggd-naofumi-canonical-v2-handoff@1','heroId':'b2-naofumi','candidateId':'naofumi-dff-community-opaque-corrected-v2-20260910','resourceRole':'character-body','sourceClass':'community-mod','source':old['source'],'nativeOriginals':old['nativeOriginals'],'originalLOD':old['parentLODInput'],'supersedesReviewBlock':{'report':rec('/private/tmp/ggd-priority-naofumi-canonical-report.json'),'oldRuntime':str(OLD/'runtime-v1'),'retained':True},'runtimeDirectory':str(rt),'runtimeReady':True,'selectionEligibility':'ready-for-parent-registration; this report does not change a default','files':{p.name:rec(p) for p in sorted(rt.iterdir()) if p.is_file()},'modelDoc':read(rt/'model.json'),'nativeAnimationCount':0,'proceduralAnimationCount':6,'animationProvenance':'Preserved six GGD authored procedural fallback clips from v1; no native game motion claimed','clipDetails':receipt['preparation']['clipDetails'],'bones':motion['bones'],'triangles':receipt['metrics']['triangles'],'drawPrimitives':receipt['metrics']['drawPrimitives'],'textureCount':4,'maxAnimationChannels':12,'khronos':issues,'sharedPrepareAndVerifyPassed':True,'stationaryClips':motion['stationaryClips'],'all8InfluencesPreserved':True,'all4TextureRGBAAndSpecularPreserved':True,'alphaOnlyDiff':rec(ROOT/'alpha-only-diff.json'),'sourceMaterialIndexAudit':rec(ROOT/'native-audit/dragonff-mode-comparison.json'),'independentNativeDecoderAudit':rec(ROOT/'native-audit/native-structure-and-decoder.json'),'rootCauseDocument':rec(ROOT/'ROOT_CAUSE.md'),'visualEvidence':{'directory':str(ROOT/'render-runtime-v2'),'pngCount':14,'proof':rec(ROOT/'render-runtime-v2/render-proof.json'),'allTexturesReady':all(t['ready'] for t in render['textures']),'sampledVisualAcceptance':'pass'},'warnings':receipt['warnings'],'limitations':['Six procedural fallbacks, no native source motions.','Run amplitude0.7; no original timing, root velocity, foot IK or cloth physics.','Authored floor correction at30Hz keys does not prove zero interpolation penetration or zero foot sliding.','Native RenderWare reflection plugins are not fully reproduced; inherited KHR_materials_specular values are preserved.','Backend modelVersions registration, production deployment and gameplay mechanics acceptance remain parent integration tasks.'],'noCentralMutation':True,'noGitMutation':True,'noS3Mutation':True}
(ROOT/'candidate-manifest.json').write_text(json.dumps(candidate,ensure_ascii=False,indent=2)+'\n')
(ROOT/'audio-file-index.json').write_text(json.dumps({'schema':'ggd-audio-file-index@1','files':[],'source':'No new audio; original static DFF/TXD source retention referenced by candidate manifest'},indent=2)+'\n')
rows=[rec(p)|{'relativePath':str(p.relative_to(ROOT))} for p in sorted(ROOT.rglob('*')) if p.is_file() and p.name!='file-manifest.json']
(ROOT/'file-manifest.json').write_text(json.dumps({'schema':'ggd-file-manifest@1','files':rows},ensure_ascii=False,indent=2)+'\n')
report={'schema':'ggd-priority-naofumi-v2-report@1','frozen':True,'root':str(ROOT),'candidateManifest':rec(ROOT/'candidate-manifest.json'),'fileManifest':rec(ROOT/'file-manifest.json'),'runtimeDirectory':str(rt),'body':rec(rt/'body.glb'),'model':rec(rt/'model.json'),'sharedContractPassed':True,'khronosErrors':0,'khronosWarnings':0,'sampledVisualAcceptance':'pass','resolvedRootCause':'Natively opaque materials were incorrectly exported BLEND; only four alphaMode values changed, BIN unchanged','nativeClips':0,'proceduralClips':6,'allFileCount':len(rows)+1,'allBytes':sum(x['bytes'] for x in rows)+(ROOT/'file-manifest.json').stat().st_size}
target=Path('/private/tmp/ggd-priority-naofumi-v2-report.json');target.write_text(json.dumps(report,ensure_ascii=False,indent=2)+'\n');print(json.dumps(rec(target)))
