import sys
sys.path=[p for p in sys.path if p!='/private/tmp']
from pathlib import Path
import json,hashlib,datetime,shutil
root=Path(sys.argv[1]).resolve()
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
a=json.loads((root/'source-analysis.json').read_text());download=json.loads((root/'download-receipt.json').read_text());assert download['publisherSha256Verified'] and sha(root/'original/Ash.blend')==download['expectedSha256']
source_preview=root/'preview-render-source-left-hair.json';sp=json.loads(source_preview.read_text());sp['schema']='ggd-native-blend-preview-render@1';sp['sourceBlendSha256']=sp.pop('sourceGlbSha256');source_preview.write_text(json.dumps(sp,indent=2)+'\n')
review=dict(schema='ggd-model-visual-review@1',status='needs-material-and-rest-pose-review',sourceReference='previews/source-left-hair/front.png',inspectedGlbViews=['previews/'+v+'/'+view+'.png' for v in ['left-hair','right-hair'] for view in ['front','back','three-quarter']],observations=['Both GLB variants retain a coherent full character body and the source red coat appearance.','The native Blender front preview shows more visible face and finer hair strands; the GLB fringe appears more opaque and covers more face.','GLB boots show bright reflective patches not apparent in the source preview.','Exact source-to-GLB appearance parity is not accepted; material translation and current-versus-rest pose need further review.'],causesConfirmed=False,runtimeReady=False,deformationAccepted=False)
(root/'visual-review.json').write_text(json.dumps(review,ensure_ascii=False,indent=2)+'\n')
candidates=[]
for variant in ['left-hair','right-hair']:
 v=json.loads((root/'converted'/variant/'validation.json').read_text());c=json.loads((root/'converted'/variant/'conversion.json').read_text());assert sha(root/c['model'])==v['sha256'];assert v['skins'] and v['embeddedImages'] and not v['animations']
 candidates.append(dict(candidateId='kof-xv-ash-crimson-open3dlab-'+variant,sourceId='kof-open3dlab-ash-xv',character='Ash Crimson',heroIds=[],sourceGame='The King of Fighters XV',sourcePlatform='unknown-original-platform',platformEvidence='Author identifies KOF XV; original game installation platform is not specified.',sourceUrl='https://open3dlab.com/project/21f68f68-b705-46ab-9a72-88b68a9fa246/',author='Anthony; original XPS model credited to MichiFreddy35',sourceClass='mod-community-port',variant=variant,model=c['model'],bytes=v['bytes'],sha256=v['sha256'],readyStage='standard-glb-candidate-needs-appearance-review',meshCount=v['meshes'],skinCount=v['skins'],jointCounts=v['skinJointCounts'],animationCount=0,sourceStaticPoseActions=len(a['actions']),textureCount=len(v['embeddedImages']),sourceSkeleton='community-Rigify: 972 source bones, GLB deform hierarchy 258 joints',maxVertexInfluences=v['maxVertexInfluences'],runtimeReady=False,backendSelectionVerified=False,manualVisualReview=review['status'],visualReviewPath='visual-review.json',defaultChanged=False,candidateMustBeRetained=True,originalBytesPreserved=True,limitations=c['limitations']+review['observations'][1:]))
cm=root/'candidate-manifest.json'
with cm.open('x') as f:f.write(json.dumps(dict(schema='ggd.model-candidates.intake@1',localRoot=str(root),candidates=candidates),ensure_ascii=False,indent=2)+'\n')
tools=root/'tools';tools.mkdir()
for n in ['ggd-kof-convert-ash-blend.py','ggd-kof-convert-ash-deform-variants.py','ggd-kof-glb-validate.py','ggd-kof-render-glb-preview.py','ggd-kof-render-source-preview.py','ggd-kof-freeze-model-variants.py']:shutil.copy2(Path('/private/tmp')/n,tools/n)
logs=root/'conversion-logs';logs.mkdir()
for n in ['ggd-kof-ash-deform-conversion.log','ggd-kof-ash-left-preview.log','ggd-kof-ash-right-preview.log','ggd-kof-ash-source-preview.log']:shutil.copy2(Path('/private/tmp')/n,logs/n)
now=datetime.datetime.now(datetime.timezone.utc);files=[dict(path=p.relative_to(root).as_posix(),bytes=p.stat().st_size,sha256=sha(p)) for p in sorted(root.rglob('*')) if p.is_file() and 'deliveries' not in p.relative_to(root).parts]
totals=dict(completeSourcePackages=1,standardGlbCandidates=2,sourcePackedTextures=len(a['nativeTextures']),sourceStaticPoseActions=len(a['actions']),gameplayAnimationClips=0,sourceAudioDatablocks=len(a['sounds']),backendReadyModels=0,appearanceAcceptedModels=0)
delivery=dict(schema='ggd-immutable-local-model-delivery@1',createdAt=now.isoformat(),sourceId='kof-open3dlab-ash-xv',localRoot=str(root),deliveryFrozen=True,candidateManifest=dict(path=cm.relative_to(root).as_posix(),sha256=sha(cm)),candidates=candidates,files=files,allFiles=files,totals=totals,sourceUrl=candidates[0]['sourceUrl'],author=candidates[0]['author'],channel='model-sharing-community-public-free-mirror',sourceLicense='Uploader-declared CC BY-NC-ND 4.0; license metadata unverified',defaultChanged=False,readinessGaps=review['observations'][1:],notes=['Complete source blend and all 15 original packed textures preserved byte for byte.','Both hairstyle variants are indexed as candidates and must remain discoverable; neither is accepted for automatic default/published GGD use yet.','Initial full-control-rig/static-pose GLB under diagnostics is not a selectable ready model.','Three source one-frame pose actions remain in original blend and are not counted as gameplay animation library clips.','No source embedded script or Rigify UI script was executed.'])
p=root/'deliveries'/('local-model-delivery-'+now.strftime('%Y%m%dT%H%M%S%fZ')+'.json');p.parent.mkdir()
with p.open('x') as f:f.write(json.dumps(delivery,ensure_ascii=False,indent=2)+'\n')
r=dict(localRoot=str(root),manifestPath=str(p),manifestSha256=sha(p),candidateManifestPath=str(cm),candidateManifestSha256=sha(cm),**totals);Path('/private/tmp/ggd-kof-ash-model-delivery-receipt.json').write_text(json.dumps(r,ensure_ascii=False,indent=2)+'\n');print(json.dumps(r,ensure_ascii=False,indent=2))
