import assert from 'node:assert/strict';
import {readFileSync,writeFileSync,mkdirSync,copyFileSync,existsSync} from 'node:fs';
import {join,dirname} from 'node:path';
import {createHash} from 'node:crypto';
import {createRequire} from 'node:module';
const repo=process.cwd(),out=join(repo,'../outputs/haga-native-visibility-20260910');
const {inspectModelUpload}=await import(join(repo,'packages/shared/src/content/modelUpload/inspect.ts'));
const {prepareUploadedHeroModel,verifyUploadedHeroModel,heroModelBudgetIssues}=await import(join(repo,'packages/shared/src/content/modelUpload/heroModel.ts'));
const {ModelVersions}=await import(join(repo,'apps/content-api/src/modelVersions.ts'));
const {zModelVersionCommand}=await import(join(repo,'packages/shared/src/content/schema/championModelVersions.ts'));
const {effectiveYawOffsetDeg}=await import(join(repo,'packages/shared/src/content/glbYaw.ts'));
const {zModelDoc}=await import(join(repo,'packages/shared/src/content/schema/model.ts'));
const req=createRequire(join(repo,'packages/shared/package.json')),validator=req('gltf-validator');
const read=(p:string)=>JSON.parse(readFileSync(p,'utf8')),put=(p:string,d:any)=>writeFileSync(p,JSON.stringify(d,null,2)+'\n',{flag:'wx'}),sha=(b:Uint8Array)=>createHash('sha256').update(b).digest('hex');
const candidate=new Uint8Array(readFileSync(join(out,'converted-v1/body.glb'))),doc=read(join(repo,'content/models/ou99.495015-standard.json'));
const inspection=await inspectModelUpload(candidate),selections=Object.fromEntries(Object.entries(doc.clipMap).map(([state,name])=>[state,inspection.clips.findIndex((c:any)=>c.name===name)]));
const upload=await prepareUploadedHeroModel(candidate,selections,effectiveYawOffsetDeg(doc));await verifyUploadedHeroModel(upload.model,upload.bytes);
const budget=heroModelBudgetIssues(inspection);assert.deepEqual(budget.errors,[]);
const body={bytes:candidate,inspected:inspection,model:{sha256:sha(candidate)},warnings:budget.warnings};
const document=zModelDoc.parse({...doc,id:'ou99.495015-native-visibility-v1',glbPath:`assets/models/community/${body.model.sha256}.glb`});
const full=await validator.validateBytes(body.bytes,{uri:'body.glb',maxIssues:0,writeTimestamp:false,externalResourceFunction:async()=>{throw Error('External resource')}});
assert.equal(full.issues.numErrors,0);assert.equal(full.issues.truncated,false);
const runtime=join(out,'runtime-v1');mkdirSync(runtime);writeFileSync(join(runtime,'body.glb'),body.bytes,{flag:'wx'});put(join(runtime,'model.json'),document);put(join(runtime,'khronos-unlimited.json'),full);
const stage=join(out,'backend-prepare-content');mkdirSync(stage);for(const sub of ['champions','models'])mkdirSync(join(stage,sub));
function copyModel(key:string){const original=join(repo,'content/models',key+'.json'),target=join(stage,'models',key+'.json');if(existsSync(target))return;const d=read(original);copyFileSync(original,target);const dest=join(stage,d.glbPath);mkdirSync(dirname(dest),{recursive:true});copyFileSync(join(repo,'content',d.glbPath),dest);}
const heroId='b2-haga',hf=join(repo,'content/champions',heroId+'.json'),hero=read(hf);copyFileSync(hf,join(stage,'champions',heroId+'.json'));copyModel(hero.modelKey);for(const version of hero.modelVersions??[])copyModel(version.modelKey);
put(join(stage,'models',document.id+'.json'),document);const dest=join(stage,document.glbPath);mkdirSync(dirname(dest),{recursive:true});writeFileSync(dest,body.bytes,{flag:'wx'});
const workflow=read(join(repo,'materials/hero-model-library/workflow-model-options.json'));
const option=workflow.heroes.find((h:any)=>h.id===heroId).options.find((o:any)=>o.sourceModelKey==='ou99.495015-standard');assert.ok(option);
const service=new ModelVersions(stage),state=service.state(heroId),source=option.source;
const command=zModelVersionCommand.parse({action:'register',expectedHash:state.expectedHash,sourceModelKey:document.id,label:option.label+'（原生顯隱修復 v1）',source,automaticEligible:true});
const prepared=await service.prepare(heroId,command);
put(join(runtime,'backend-prepare-receipt.json'),{schema:'ggd-backend-model-version-prepare@1',method:'Actual ModelVersions.prepare using isolated copies; writeArtifacts never called',stageRoot:stage,sourceHeroSha256:sha(readFileSync(hf)),command,preparedChampion:prepared.champion,artifacts:prepared.artifacts.map((a:any)=>({document:a.doc,version:a.version,bytes:a.bytes.length,sha256:sha(a.bytes)})),centralWrites:false});
put(join(runtime,'receipt.json'),{schema:'ggd-library-body-ready@1',document,sha256:sha(body.bytes),documentSha256:sha(readFileSync(join(runtime,'model.json'))),metrics:{triangles:body.inspected.triangles,drawPrimitives:body.inspected.meshes,textures:body.inspected.textures},clips:body.inspected.clips,warnings:body.warnings,khronos:{errors:full.issues.numErrors,warnings:full.issues.numWarnings,infos:full.issues.numInfos},nativeAnimationCount:13,proceduralAnimationCount:0,sharedInspectAndBudget:true,sixStateUploadPrepareAndVerify:{sha256:sha(upload.bytes),clipCount:upload.inspected.clips.length,notUsedAsRegisteredBody:true},backendPrepare:true,visualAcceptance:'pending',source});
console.log(JSON.stringify({sha256:sha(body.bytes),metrics:body.inspected.triangles,clips:body.inspected.clips.length,validator:full.issues}));
