from pathlib import Path
import hashlib,json,datetime,shutil
root=Path('GGD-Asset-Library/intake/public-models-20260910/kof-author-models-round20').resolve();r=root/'mai-xv-sfm'
def write(p,obj):p.write_text(json.dumps(obj,indent=2,ensure_ascii=False)+'\n')
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
assert not (r/'source-manifest.json').exists()
shutil.copy2(root/'source-pages/mai-xv-sfmlab.html',r/'source-page.html')
shutil.copy2(Path('/private/tmp/ggd-kof-round20-extract.py'),r/'extraction-tool.py')
source={'schema':'ggd.acquired-model-source@1','sourceId':'kof-xv-mai-sfmlab-lordscrub-v1','character':'不知火舞 / Mai Shiranui','sourceGame':'The King of Fighters XV','sourceGamePlatform':'not specified by publisher','artifactTarget':'Source Filmmaker','acquisitionChannel':'author public model library (SFMLab)','author':'lordscrub','originalPortAuthor':'EnlightendShadow','sourceUrl':'https://sfmlab.com/project/96ca7f93-ac69-4a4e-a8ec-1f6617a7c40c/','upstreamUrl':'https://www.deviantart.com/enlightendshadow/art/KOFXV-Mai-EnlightendShadow-907248683','classification':'original-game model converted/modified for SFM; not unmodified raw game export','status':'complete-acquired-extracted','modelCandidates':[{'id':'kof-xv-mai-lordscrub-sfm','parts':['extracted-v1/KOF15/Models/mai/kof_xv_mai_body.mdl','extracted-v1/KOF15/Models/mai/kof_xv_mai_head.mdl'],'nativeFormat':'Source MDL49/VVD/VTX','bodyBones':152,'headBones':80,'bodyVerticesLOD0':42059,'headVerticesLOD0':26034,'runtimeSelectable':False,'standardConversion':'pending root workflow','defaultChange':False}],'nativeAnimations':{'count':0,'singleFramePoses':2,'evidence':'both MDL embedded @idle animation descriptors are 1 frame at 30 FPS'},'vfx':{'count':0},'sfx':{'count':0},'voice':{'count':0},'audioFileIndex':None,'textures':{'pngFiles':9,'vtfFiles':9,'note':'PNG and VTF may encode matching textures; 18 files are not 18 distinct materials'},'limitations':['Publisher says fan is absent.','Publisher says back-of-outfit flower pattern is missing in the SFM setup.','Publisher warns jaw is two parts.','No native gameplay animations, VFX, SFX or voice included.','No GGD runtime/visual acceptance performed.'],'rights':{'publisherLabel':'CC0 selected on SFMLab; site warns license unverified and fan-art rights may apply','originalOwner':'SNK','clearance':'not inferred'},'validationReport':'extraction-validation.json','headerAnalysis':'source-motion-mesh-header-analysis.json','retrievalNotes':['download-attempt-1 captured a normal mirror landing HTML, relocated as mirror-landing-1.html; it is not an archive.','download-attempt-2 obtained actual ZIP, expected size 90764853, libarchive whole-file read succeeded.']}
write(r/'source-manifest.json',source)
files=[{'path':p.relative_to(r).as_posix(),'bytes':p.stat().st_size,'sha256':sha(p)} for p in sorted(r.rglob('*')) if p.is_file()]
t=datetime.datetime.now(datetime.timezone.utc).strftime('%Y%m%dT%H%M%S%fZ');delivery={'schema':'ggd.immutable-local-source-delivery@1','createdAt':t,'localRoot':str(r),'sourceId':source['sourceId'],'sourceManifest':'source-manifest.json','files':files,'fileCount':len(files),'totalBytes':sum(x['bytes'] for x in files),'freeze':'complete; referenced paths must not be modified','runtimeSelectable':False,'nativeGameAnimations':0,'audioFileIndex':None}
p=r/('delivery-'+t+'.json');write(p,delivery);receipt={'localRoot':str(r),'deliveryPath':str(p),'deliverySha256':sha(p),'sourceManifestSha256':sha(r/'source-manifest.json'),'archiveSha256':sha(r/'raw/KOFVX_Mai_OFHXLWK.zip'),'fileCount':len(files),'bytes':delivery['totalBytes']};q=Path('/private/tmp/ggd-kof-round20-mai-sfm-receipt.json');write(q,receipt);print(json.dumps(receipt,indent=2))
