import hashlib,json,shutil
from pathlib import Path
R=Path('/Users/Takuro/Dropbox/我的 Mac (Moriya.local)/Documents/ABxVFX_EDIT/outputs/priority-ou99-residual-geometry-audit-20260910')
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def put(p,d):
 with p.open('x')as f:f.write(json.dumps(d,ensure_ascii=False,indent=2)+'\n')
inputs=json.loads((R/'input-manifest.json').read_text());render=json.loads((R/'render/render-proof.json').read_text());findings=[]
notes={
'ou99.458777-standard-v3':{'classification':'source-authored-held-accessory','ruleResult':'second-skeleton false positive for this pinned primitive','visualIdentification':'手持螺旋燈器／法器，有吊環與螺旋結構，四個取樣姿勢隨手持動作移動；不是另一個角色身體。','nativeEvidence':'Native geoset0; source texture JD-JINGDIAN-SYW_wing_4.blp; weights91.1% JD-Bone017-QQ136183818 and8.9% JD-Bip001 Prop1-QQ136183818; no GEOA hiding entry.','recommendation':'保留prim0及兩個原生道具骨。不要填hiddenPrimitives或剔除。後續若要讓閘辨識已審附件，应添加具GLB SHA/primitive index/vertex count/骨名證據的附件分類，不能全面忽略second-skeleton。'},
'ou99.474258-standard':{'classification':'source-authored-held-weapon','ruleResult':'second-skeleton false positive for this pinned primitive','visualIdentification':'右手附近的紅黑長刃武器；整隻與部件分離視圖均可識別武器柄與尖刃，動作取樣帶動武器。不是另一個角色身體。','nativeEvidence':'Native geoset3; texture eff\\Axixn2.blp; weights on Bone091(93.1%), Bone036/034/035, independent root bone_new1; no GEOA hiding entry.','recommendation':'保留prim3及武器支鏈。不要填hiddenPrimitives或僅因獨立骨架根刪除。後續可用GLB SHA和精確primitive證據作受審附件分類；維持其他未知second-skeleton告警。'},
'ou99.495015-standard':{'classification':'confirmed-source-decay-gore-visibility-loss','ruleResult':'gore-joint + floor-slab true positive','visualIdentification':'派大星代理模型旁邊的薄扁血肉平面／凸起碎片，與手持捕網是不同primitive。idle/run/cast/death畫面均可看見殘留。','nativeEvidence':'Native patrick2.mdx geoset2 exactly49vertices/22triangles, texture Textures\\gutz.blp, 100%gutz00. KGAO step interpolation0/globalSeq-1; every relevant Stand/Stand Ready/Walk/Attack/Spell/Death source interval has peakalpha0, only Decay Flesh/Decay Bone peakalpha1.','recommendation':'這是原W3X GEOA顯隱未轉入GLB的真缺陷。保留完整原件與舊frozen版本；另外建立新body版本，按來源顯隱修復。若runtime只用現行六態（均native alpha0），可在新版本精確宣告hiddenPrimitives:[2]；若要重用Decay素材，应另保留該geoset/狀態，不永久破壞原素材。不要隱藏其他網子／手腳，也不要原地改frozen版本。'}
}
for row in inputs:
 key=row['originalModelKey'];p=Path(row['glb']);assert sha(p)==row['sha256'];assert sha(Path(row['modelDocument']))==row['modelDocumentSha256'];n=json.loads((R/key/'native-geoset-proof.json').read_text());prim=row['primitives'][row['suspectPrimitive']];renderrow=next(x for x in render['proof']if x['key']==key.replace('.','-'));assert len(renderrow['images'])==8 and all(x['ready']for x in renderrow['textures']);f={'modelKey':key,'targetHero':row['targetName'],'primitive':row['suspectPrimitive'],'glb':row['glb'],'glbSha256':row['sha256'],'modelDocument':row['modelDocument'],'modelDocumentSha256':row['modelDocumentSha256'],'vertices':prim['vertices'],'triangles':prim['triangles'],'localBindBounds':prim['bbox'],'materialIndex':prim['materialIndex'],'nativeArchive':n['nativeArchive'],'nativeArchiveSha256':n['nativeArchiveSha256'],'nativeMdxMember':n['nativeMember'],'nativeMdxSha256':n['nativeMdxSha256'],'sourceGeoset':n['mdxGeosetMatch']['nativeGeosetIndex'],'nativeTriangleVertexTriplesIdentical':n['mdxGeosetMatch']['sameTriangleVertexTriples'],'nativeToGlbAffineMaxError':n['mdxGeosetMatch']['affinePositionMaxError'],'structureEvidence':str(R/key/'structure.json'),'nativeEvidenceFile':str(R/key/'native-geoset-proof.json'),'textureEvidence':str(R/key/'suspect-material-original-image.png'),'contactSheet':str(R/'render'/(key.replace('.','-')+'-contact.png')),'screenshots':[{**im,'path':str(R/'render'/im['name']),'sha256':sha(R/'render'/im['name'])}for im in renderrow['images']],**notes[key]};findings.append(f)
report={'schema':'ggd-ou99-residual-geometry-review@1','frozen':True,'scope':'Only3specific flagged primitives; raw file read/MDX analysis/diagnostic WebGL. No central/model/frozen/gate modifications.','localRoot':str(R),'counts':{'reviewedPrimitives':3,'sourceAuthoredAccessories':2,'confirmedDecayGoreDefects':1,'rawWebglScreenshots':24},'findings':findings,'centralWrites':False,'frozenModelOrDocModified':False,'gateModified':False,'partsHiddenInShippedModel':False,'diagnosticIsolation':'Target-only pictures change in-memory visibility only, expressly to identify the flagged part; source bytes/model docs are unchanged.','fullModelVisualAcceptance':False,'buildGateCleared':False,'limitations':['Onlythe3requestedprimitiveflagsareadjudicated;otherDoraemon/airborneflagsinmodels:checkremainoutside scope.','Four native clips per model sampled at60%, not exhaustive gameplay or fullmotionqualityacceptance.','Original target hero proxy/identity metadata remains unchanged.','MDX GEOA is parsed from exact local archive member; no Warcraft III game was executed.']};put(R/'review.json',report)
(R/'README.md').write_text('''# 三件 OU99 殘留幾何定點審查

| 模型／部件 | 判定 | 處理建議 |
| --- | --- | --- |
| 凱亞爾相似代理 `ou99.458777-standard-v3` prim0，1789v／988tri | 手持螺旋燈器／法器。獨立Prop1兩骨支鏈造成second-skeleton誤報；原geoset無GEOA隱藏 | 保留附件，不填hiddenPrimitives。後續使用精確SHA／primitive的已審附件分類，不能全面取消規則 |
| 楓相似代理 `ou99.474258-standard` prim3，597v／740tri | 紅黑長刃武器。獨立Bone091／bone_new1支鏈造成second-skeleton誤報；原geoset無GEOA隱藏 | 保留武器，不填hiddenPrimitives；後續以精確附件證據處理分類 |
| 羽賀相似代理 `ou99.495015-standard` prim2，49v／22tri | 原W3X腐爛血肉。100%gutz00、Textures\\gutz.blp、扁平旁置。native GEOA只在Decay Flesh/Bone可見，現行六態都應隱藏；GLB顯隱資料遺失 | 保留原始來源和舊frozen。另做新body版本的來源顯隱修復；現行六態可在新版本精確宣告hiddenPrimitives:[2]。不要隱藏網子或改舊版 |

review.json含全部GLB／doc／原MDX SHA、geoset匹配、骨權重、精確材質與來源動畫alpha。三件均比對原MDX三角頂點索引完全相同，位置仿射最大誤差低於1.2e-7，因此可把原GEOA和部件對應到目前GLB，並非僅看名稱推測。

render/保留完整模型及目標部件單獨放大的idle/run/cast/death（各60%時點），共24張實際WebGL；三張contact比較圖便於定位。單獨部件視圖只在診斷瀏覽器記憶體中暫時隔離，沒有更改出貨模型、文件、frozen版本或閘。此審查不代表全部模型／動作已完成視覺驗收，也沒有讓models:check轉綠。其他哆啦A夢及airborne告警不在本輪範圍。
''')
for p in ['/private/tmp/ggd-ou99-residual-geometry-audit.py','/private/tmp/ggd-ou99-residual-native-proof.py','/private/tmp/ggd-ou99-residual-contact-sheets.py',__file__]:shutil.copy2(p,R/'tools'/Path(p).name)
files=[{'path':p.relative_to(R).as_posix(),'bytes':p.stat().st_size,'sha256':sha(p)}for p in sorted(R.rglob('*'))if p.is_file()];put(R/'file-manifest.json',{'schema':'ggd-file-manifest@1','localRoot':str(R),'immutable':True,'files':files,'excludes':['file-manifest.json']})
entry={'schema':'ggd-ou99-residual-review-handoff@1','frozen':True,'report':str(R/'review.json'),'reportSha256':sha(R/'review.json'),'fileManifest':str(R/'file-manifest.json'),'fileManifestSha256':sha(R/'file-manifest.json'),'filesIncludingManifest':len(files)+1,'summary':'Two held accessory/weapon false positives; one confirmed original decay-gore visibility loss; no modifications or all-model acceptance claim.'};put(Path('/private/tmp/ggd-ou99-residual-geometry-review.json'),entry);print(json.dumps(entry,ensure_ascii=False,indent=2))
