#!/usr/bin/env python3
"""Build source-only candidate/audio receipts in a NEW downloaded Astralym intake."""
from pathlib import Path
import argparse,json,hashlib,subprocess
p=argparse.ArgumentParser();p.add_argument('root',type=Path);p.add_argument('--workspace',type=Path,required=True);a=p.parse_args();r=a.root.resolve();ws=a.workspace.resolve()
def put(name,d):
 with (r/name).open('x') as f:json.dump(d,f,ensure_ascii=False,indent=2);f.write('\n')
def sha(path):return hashlib.sha256(path.read_bytes()).hexdigest()
model=json.loads((r/'analysis/model-analysis.json').read_text());assets=json.loads((r/'evidence/opgg-asset-receipts.json').read_text());aud=json.loads((r/'evidence/audio-probe.json').read_text());textures=[]
for x in assets:
 assert x['acquired'] and sha(r/x['path'])==x['sha256']
 if x['path'].endswith('.webp'):
  info=json.loads(subprocess.check_output(['/usr/local/bin/ffprobe','-v','error','-show_streams','-of','json',str(r/x['path'])]))['streams'][0]
  textures.append({**x,'width':info['width'],'height':info['height']})
audio=[]
for x in aud:
 assert sha(r/x['path'])==x['sha256'];s=x['probe']['streams'][0]
 dec=subprocess.run(['/usr/local/bin/ffmpeg','-v','error','-i',str(r/x['path']),'-f','null','-'],capture_output=True,text=True)
 assert dec.returncode==0,dec.stderr
 audio.append({k:x[k] for k in ['path','bytes','sha256','sourceUrl','label']}|{'seconds':float(x['probe']['format']['duration']),'format':'mp3','codec':s['codec_name'],'channels':s['channels'],'sampleRate':int(s['sample_rate']),'fullDecodePassed':True,'decodeDiagnostics':dec.stderr,'audioCategory':'sound-effect','classification':'nonverbal-pal-cry-source-labelled','character':'Astralym / 枯星龍','nativeCharacterId':'WorldTreeDragon','heroIds':[],'sourceIsSynthetic':False,'reportedLanguage':'nonverbal','speakerVerified':False,'listeningReviewComplete':False,'gameOriginEvidence':'Source page says extracted from Palworld game audio bank; exact original bank/build not delivered.'})
modelId='opgg-palworld-astralym-2026081102';audioId='gamevault-palworld-astralym-audio'
put('audioFileIndex.json',{'schema':'ggd.source-audio-file-index@1','sourceId':audioId,'localRoot':str(r),'files':audio})
put('model-audioFileIndex.json',{'schema':'ggd.source-audio-file-index@1','sourceId':modelId,'localRoot':str(r),'files':[],'reason':'Model-only source shares backup with separately attributed Gamevault MP3 source; do not auto-count those as OP.GG audio.'})
limitations=['Game-derived web export, not original Unreal container; source game platform/build not verified.','Original GLB requires EXT_meshopt_compression; lossless decoded analytical copy retains identical nodes/skins/animation structure.','Three raw NORMAL format validator errors: normalized SHORT without KHR_mesh_quantization; standardization pending.','External material recipe plus all 9 WebP files retained; standalone GLB has no embedded images. Original shader equivalence/visual validation pending.','58 clips retained; only 57 show changing values. HaloCutter_Loop_Ring is a static pose.','Ring-named animations are not proof of separately acquired particle/VFX systems; no standalone VFX package.','No registered GGD hero ID found by exact Astralym/WorldTreeDragon/枯星龍 search at audit time; heroIds remain empty.']
candidate={'id':modelId+'.body','candidateId':modelId+'.body','sourceId':modelId,'character':'枯星龍 / Astralym','aliases':['Astralym','枯星龍','WorldTreeDragon'],'sourceWork':'Palworld / 幻獸帕魯','sourceGame':'Palworld','sourcePlatform':'unknown; web game-derived export','sourceClass':'original-game-extraction-community-repackage','heroIds':[],'resourceRole':'character-body','readiness':'acquired-rigged-animated-source-pending-standardization','defaultEligible':False,'sourceModel':str(r/'original/model.glb'),'sourceModelBytes':model['source']['bytes'],'sourceModelSha256':model['source']['sha256'],'decodedAnalyticalModel':str(r/'derived/model-decoded.glb'),'meshCount':1,'primitiveCount':3,'triangleCount':23928,'boneCount':145,'materialCount':3,'textureCount':9,'nativeAnimationCount':57,'animationClipCount':58,'staticPoseClipCount':1,'audioCount':0,'vfxCount':0,'textures':textures,'animations':[{'name':x['name'],'seconds':x['seconds'],'channels':x['channelCount'],'changingChannels':x['changingChannels']} for x in model['animations']],'modelAnalysisPath':str(r/'analysis/model-analysis.json'),'backendIntegration':{'required':True,'state':'pending-standardization','selectionVerified':False},'limitations':limitations}
put('model-candidates.json',{'schema':'ggd.source-model-candidates@1','sourceId':modelId,'candidates':[candidate]})
common={'heroIds':[],'ownerEntryIds':[],'accessStatus':'public-direct-download','acquisitionStatus':'downloaded-verified','defaultEligible':False,'sourceGame':'Palworld','sourceWork':'Palworld / 幻獸帕魯','localPath':str(r.relative_to(ws)),'license':'Original Palworld assets copyright Pocketpair. No explicit redistribution/reuse license found on the observed source pages; not labelled free licensed.','publicationStatus':'local-frozen-s3-backup-pending','purchaseDecision':'hold-purchase-review-acquired-source','reportedLanguage':'nonverbal','platform':'unknown game build/platform; public web export','sourceClass':'original-game-extraction-community-repackage','selectionClass':'original-game'}
s1=common|{'id':modelId,'target':'Palworld 枯星龍 Astralym／骨架模型＋58動畫條目＋9貼圖','url':'https://op.gg/zh-tw/palworld/pals/astralym','author':'OP.GG (web exporter); Pocketpair (original game assets)','downloadUrl':'https://s-stats-platform-cdn.op.gg/palworld/models/pals/WorldTreeDragon/model.glb?v=2026081102','manifestUrl':'https://s-stats-platform-cdn.op.gg/palworld/models/pals/WorldTreeDragon/materials.json?v=2026081102','sourceVersion':'OP.GG revision 2026081102; source manifest v3','readiness':'pending-standardization','assetKinds':['model','skeleton','animation','material','texture'],'modelCount':1,'modelCandidates':[candidate],'modelCandidateIndexPath':str(r/'model-candidates.json'),'nativeAnimationCount':57,'animationClipCount':58,'audioCount':0,'audioFileIndex':{'reportPath':'model-audioFileIndex.json','reportSha256':sha(r/'model-audioFileIndex.json')},'limitations':limitations}
s2=common|{'id':audioId,'target':'Palworld 枯星龍 Astralym／六種非語言叫聲','url':'https://palworld.gamevault.in/paldex/astralym/','author':'Gamevault (audio exporter); Pocketpair (original game assets)','readiness':'local-audio-decode-verified-listening-pending','assetKinds':['audio','sound-effect'],'modelCount':0,'audioCount':6,'audioSeconds':sum(x['seconds'] for x in audio),'audioCategory':'sound-effect','sourceIsSynthetic':False,'audioFileIndex':{'reportPath':'audioFileIndex.json','reportSha256':sha(r/'audioFileIndex.json')},'audioGroups':[{'id':'astralym-cries','name':'枯星龍 Astralym 非語言叫聲','heroIds':[],'pathPrefixes':[x['path'] for x in audio],'audioCategory':'sound-effect','reportedLanguage':'nonverbal','sourceIsSynthetic':False,'classificationEvidence':'Six named cry buttons on the Astralym soundboard; no per-clip listening claim.'}],'limitations':['Source soundboard identity and emotion labels retained; listening validation pending.','No original native Wwise bank obtained; MP3 files are web-exported game audio.','Protected Gamevault model pointer was not decrypted, requested or bypassed; model acquired from independent public OP.GG route.','No spoken Japanese dialogue; these are nonverbal creature cries and excluded from speech synthesis by sound-effect classification.']}
put('source-entries.json',{'schema':'ggd.public-source-proposal@1','publicSources':[s1,s2]})
put('analysis/source-routes.json',{'identity':{'name':'枯星龍','english':'Astralym','nativeId':'WorldTreeDragon','paldex':204,'excludedWrongIdentities':['Xenolord','Xenogard'],'evidence':['https://paldb.cc/tw/Astralym','https://op.gg/zh-tw/palworld/pals/astralym','https://palworld.gamevault.in/paldex/astralym/']},'routes':[{'source':'OP.GG','status':'actual-files-acquired','evidence':'evidence/opgg-astralym.html → public 3D viewer JS → original/materials.json → model.glb + all texture keys','receipt':'evidence/opgg-asset-receipts.json'},{'source':'Gamevault soundboard','status':'actual-six-mp3-acquired','receipt':'evidence/audio-download-receipts.json'},{'source':'Gamevault model viewer','status':'not-requested-protected-pointer','evidence':'public page model=protected:13070d1867762ca61787f90fe5ec2c18; no decoding/protected endpoint requested'},{'source':'ShinyPenguin older Daedream','status':'existing-local-receipts-inspected-no-repeat-download','reason':'Different Pal; not treated as Astralym source.'}],'tools':[{'url':'https://raw.githubusercontent.com/zeux/meshoptimizer/v0.25/js/meshopt_decoder.js','path':'tools/meshopt_decoder.cjs','sha256':sha(r/'tools/meshopt_decoder.cjs'),'license':'MIT; tools/meshoptimizer-LICENSE.md'}]})
print(json.dumps({'sources':[modelId,audioId],'audioFiles':len(audio),'audioSeconds':sum(x['seconds'] for x in audio),'candidate':'model-candidates.json','sourceEntries':'source-entries.json'},ensure_ascii=False))
