/**
 * 🧾 **collection 清單只有一個住處** —— GH#998。
 *
 * `packages/shared/src/content/schema/index.ts` 的 `COLLECTIONS` 是 collection 集合的
 * **唯一來源**。`apps/platform/internal/contentoverlay/validate.go` 曾經手抄一份
 * `KnownCollections`（「Go 跑不了 Zod」），⭐ 而那份手抄以**完全相同的形狀**壞過三次：
 *
 * | 次 | collection | 後果 |
 * |---|---|---|
 * | 1 | `maps`（GH#328） | overlay 拒絕一個合法的 collection，漏了 13 天 |
 * | 2 | `vfx-scripts`（GH#838） | 後台**存不進任何演出腳本** |
 * | 3 | `vfx-subtypes`（GH#990） | CI go-platform 紅（這一次是閘先叫，⛔ 不是玩家先遇到） |
 *
 * ⇒ 第〇·四守則（值只有一個住處）＋ 第〇·七守則的「一行接線」病：
 *    ⭐ 每加一個 collection 就要在 Go 那邊補一行 ⇒ 正解是讓那一行**自動推導**。
 *
 * 這一支把 TS 的 `COLLECTIONS` 推導成 Go 的 `collections_gen.go`：
 *
 *   pnpm collections:build     # 重新產生（改了 COLLECTIONS 之後跑這一行）
 *   pnpm collections:check     # 逐位元組比對（唯讀；接在 skills:check 裡）
 *
 * ── ⭐ 兩道閘，⛔ 不是一道 ───────────────────────────────────────────────────
 *  · `--check`（這裡）：重算一次再逐位元組比對，過期就回非零並**指名**缺哪一個／多哪一個。
 *  · `TestKnownCollectionsMatchTheSharedSchemaTable`（validate_test.go）：Go 那邊
 *    **獨立**用正則讀 index.ts 再比一次 —— 它是「改了 index.ts 卻沒跑產生器」時
 *    在 go-platform CI 上的最後一道。⛔ 不要因為有了產生器就刪它。
 *
 * ── ⚠️ 刻意沒有產生時間戳 ────────────────────────────────────────────────────
 * 與 `caps:export` 同一個理由：任何隨時鐘變動的欄位都會讓逐位元組比對永遠不相等，
 * 於是 `--check` 只能被放寬成模糊比對 —— 而一條被放寬的閘等於沒有閘。
 *
 * ── ⚠️ 輸出要是 gofmt 正典 ──────────────────────────────────────────────────
 * ⛔ 這一支**不呼叫 gofmt**：`skills:check` 在 CI 的 contract job 跑，那台只有 node。
 * ⇒ 樣板本身寫成 gofmt 不會動的形狀（tab 縮排、⛔ 沒有需要對齊的行尾註解、
 *    ⛔ 不把說明附在宣告正上方當 doc comment —— gofmt 1.19+ 會重排 doc comment）。
 *
 * ── 校準（⛔ 不是給日常用的）───────────────────────────────────────────────
 *   npx tsx tools/collections-gen/gen.ts --check --source <另一份 index.ts>
 * `--source` 讓突變驗證可以拿一份「多了假 collection」的夾具跑 `--check`，
 * ⛔ 不必去動 shared 的 index.ts（18 條 lane 併行時那是別人的讀端）。
 */
// ggd:writes apps/platform/internal/contentoverlay/collections_gen.go
import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { join, resolve } from "node:path";
import { pathToFileURL } from "node:url";
import { createRequire } from "node:module";

const ROOT = resolve(__dirname, "../..");

/**
 * ⛔ 同一棵樹（與 `tools/config-decor/gen.ts` 同一個理由）：在 worktree lane 裡
 * `require.resolve("@ggd/shared/…")` 會解到主 checkout，而 `ROOT` 是這棵樹 ——
 * 讀「別棵樹的 schema」寫「這棵樹的 Go」會得到一份兩棵樹混出來的產物。
 */
const requireFromTree = createRequire(pathToFileURL(join(ROOT, "tools/")).href);

const SOURCE_REL = "packages/shared/src/content/schema/index.ts";
const OUT_REL = "apps/platform/internal/contentoverlay/collections_gen.go";
const OUT = join(ROOT, OUT_REL);

interface CollectionSpecLike {
  schemaTag: string;
  label: string;
}

function loadCollections(sourcePath: string): Array<{ name: string; schemaTag: string; label: string }> {
  const mod = requireFromTree(sourcePath) as { COLLECTIONS?: Record<string, CollectionSpecLike> };
  const table = mod.COLLECTIONS;
  if (!table || typeof table !== "object") {
    throw new Error(`⛔ ${sourcePath} 沒有 export COLLECTIONS —— 來源的形狀變了，修這支產生器`);
  }
  const rows = Object.entries(table).map(([name, spec]) => ({
    name,
    schemaTag: String(spec?.schemaTag ?? ""),
    label: String(spec?.label ?? ""),
  }));
  // ⭐ 量尺先自證：解析回太少就**紅**，⛔ 不是安靜地寫出一份幾乎空的 Go 清單
  //    （validate_test.go 的同一個判準：`require.GreaterOrEqual(len(fromTS), 10)`）。
  if (rows.length < 10) {
    throw new Error(`⛔ 只解析到 ${rows.length} 個 collection（${rows.map((r) => r.name).join(", ")}）—— 來源的形狀變了，修這支產生器`);
  }
  for (const r of rows) {
    // Go 字串字面值裡不可以有需要轉義的東西；collection 名同時也是 content/ 底下的目錄名。
    if (!/^[a-z][a-z0-9-]{0,31}$/.test(r.name)) {
      throw new Error(`⛔ collection 名「${r.name}」不合 ^[a-z][a-z0-9-]{0,31}$ —— validate_test.go 的正則也讀不到它`);
    }
    if (/["\\\n]/.test(r.schemaTag) || /["\\\n]/.test(r.label)) {
      throw new Error(`⛔ ${r.name} 的 schemaTag/label 含引號或反斜線 —— 進不了 Go 註解`);
    }
  }
  // 排序：Go 那邊的拒絕訊息要穩定（validate.go 檔頭逐字「Sorted so the rejection message is stable」）。
  rows.sort((a, b) => (a.name < b.name ? -1 : a.name > b.name ? 1 : 0));
  return rows;
}

function render(rows: ReturnType<typeof loadCollections>): string {
  const L: string[] = [];
  L.push("// Code generated by tools/collections-gen/gen.ts; DO NOT EDIT.");
  L.push("//");
  L.push("// ⭐ GH#998 —— 這一份是**推導**出來的，來源只有一個：");
  L.push(`//   ${SOURCE_REL} 的 COLLECTIONS（第〇·四守則：值只有一個住處）。`);
  L.push("//");
  L.push("//   pnpm collections:build   # 改了 COLLECTIONS 之後重新產生");
  L.push("//   pnpm collections:check   # 逐位元組比對（唯讀；接在 skills:check 裡）");
  L.push("//");
  L.push("// ⚠️ 刻意沒有產生時間戳（與 caps:export 同一個理由：時鐘欄位會讓 --check 永遠不相等）。");
  L.push("// ⚠️ TestKnownCollectionsMatchTheSharedSchemaTable（validate_test.go）仍然獨立讀 index.ts");
  L.push("//   再比一次 —— 它是「改了 index.ts 卻沒跑產生器」時 go-platform CI 上的最後一道。");
  L.push("");
  L.push("package contentoverlay");
  L.push("");
  L.push("// KnownCollections is the closed set of collections an overlay doc may target:");
  L.push(`// exactly the keys of COLLECTIONS in ${SOURCE_REL},`);
  L.push("// sorted so the rejection message is stable.");
  L.push("var KnownCollections = []string{");
  for (const r of rows) {
    L.push(`\t// ${r.schemaTag} · ${r.label}`);
    L.push(`\t"${r.name}",`);
  }
  L.push("}");
  L.push("");
  return L.join("\n");
}

/** 把磁碟上那一份 Go 檔裡的清單讀回來 —— 只為了在 `--check` 紅的時候**指名**差在哪一個。 */
function parseGoList(text: string): string[] {
  const start = text.indexOf("var KnownCollections = []string{");
  if (start < 0) return [];
  const end = text.indexOf("\n}", start);
  const block = end < 0 ? text.slice(start) : text.slice(start, end);
  return [...block.matchAll(/^\t"([^"]+)",$/gm)].map((m) => m[1]!);
}

function main(): void {
  const argv = process.argv.slice(2);
  const srcIdx = argv.indexOf("--source");
  const sourcePath = srcIdx >= 0 ? resolve(argv[srcIdx + 1] ?? "") : join(ROOT, SOURCE_REL);
  if (srcIdx >= 0 && !existsSync(sourcePath)) {
    console.error(`⛔ --source 指到的檔不存在：${sourcePath}`);
    process.exit(2);
  }
  const rows = loadCollections(sourcePath);
  const want = render(rows);

  if (argv.includes("--check")) {
    if (!existsSync(OUT)) {
      console.error(`✗ collections:check —— 產物不存在：${OUT_REL}\n  → 跑 pnpm collections:build 然後 git add ${OUT_REL}`);
      process.exit(1);
    }
    const have = readFileSync(OUT, "utf8");
    if (have === want) {
      console.log(`collections:check OK（${rows.length} 個 collection · ${OUT_REL}）`);
      return;
    }
    const tsSet = rows.map((r) => r.name);
    const goSet = parseGoList(have);
    const missing = tsSet.filter((n) => !goSet.includes(n));
    const extra = goSet.filter((n) => !tsSet.includes(n));
    const lines = [`✗ collections:check —— ${OUT_REL} **過期**（與 ${SOURCE_REL} 的 COLLECTIONS 對不上）`];
    if (missing.length) lines.push(`  缺（TS 有、Go 沒有）：${missing.join(", ")}`);
    if (extra.length) lines.push(`  多（Go 有、TS 沒有）：${extra.join(", ")}`);
    if (!missing.length && !extra.length) lines.push("  集合一致，但位元組不同（檔頭／註解／順序）—— 一樣是過期");
    lines.push(`  → 跑 pnpm collections:build 然後 git add ${OUT_REL}`);
    lines.push("  ⛔ 不要手改 collections_gen.go —— 它是產物；改來源（index.ts 的 COLLECTIONS）再重生成。");
    console.error(lines.join("\n"));
    process.exit(1);
  }

  writeFileSync(OUT, want);
  console.log(`✓ collections:build 寫出 ${OUT_REL}（${rows.length} 個 collection）`);
}

main();
