#!/usr/bin/env tsx
/**
 * role-classify — READ-ONLY. Proposes a role for every champion in
 * content/champions and prints a reviewable report. It never writes to
 * content/; the backfill is a separate, deliberate step that happens only
 * after a human has signed off on this output.
 *
 *   pnpm --filter @ggd/role-classify role:report
 *   tsx tools/role-classify/src/cli.ts --md > docs/role-proposal.md
 *   tsx tools/role-classify/src/cli.ts --explain godie-hpb1
 */
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import { extractFeatures } from "./features";
import { classifyAll, type Verdict } from "./classify";
import { ROLES, ROLE_BLURB, type Role } from "./roles";
import { CALIBRATION } from "./calibration";

const REPO_ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "../../..");

const argv = process.argv.slice(2);
const asMarkdown = argv.includes("--md");
const explainIdx = argv.indexOf("--explain");
const explainId = explainIdx >= 0 ? argv[explainIdx + 1] : undefined;

const verdicts = classifyAll(extractFeatures(REPO_ROOT));
const byId = new Map(verdicts.map((v) => [v.features.id, v]));

function pad(s: string, width: number): string {
  // CJK glyphs occupy two terminal columns; count them as such so the table
  // does not shear on the 113 Chinese champion names.
  let w = 0;
  for (const ch of s) w += /[⺀-鿿＀-｠]/.test(ch) ? 2 : 1;
  return s + " ".repeat(Math.max(0, width - w));
}

function truncate(s: string, max: number): string {
  return s.length <= max ? s : s.slice(0, max - 1) + "…";
}

function topReasons(v: Verdict, n: number): string {
  return v.evidence
    .filter((e) => e.role === v.role && Number.isFinite(e.points) && e.points > 0)
    .sort((a, b) => b.points - a.points)
    .slice(0, n)
    .map((e) => e.reason)
    .join("; ");
}

// --- --explain <id>: one champion, full score sheet -----------------------
if (explainId) {
  const v = byId.get(explainId);
  if (!v) {
    console.error(`no such champion: ${explainId}`);
    process.exit(1);
  }
  const f = v.features;
  console.log(`${f.id}  ${f.name}`);
  console.log(`  current role : ${f.currentRole}`);
  console.log(`  proposed     : ${v.role}  (margin ${v.margin.toFixed(2)}, ${v.confidence} confidence)`);
  console.log(`  attackType   : ${f.attackType} (range ${f.range})`);
  console.log(`  primary attr : ${f.primaryAttr ?? "unknown"}${f.primaryAttrInferred ? " (inferred)" : ""}` +
    `  STR ${f.strGrowth} / AGI ${f.agiGrowth} / INT ${f.intGrowth}`);
  console.log(`  stats        : hp ${f.hp} (+${f.hpGrowth}) mana ${f.mana} ad ${f.ad} (+${f.adGrowth}) armor ${f.armor} as ${f.attackSpeed} ms ${f.moveSpeed}`);
  console.log(`  kit          : dmg ${f.nDamage} (${f.nMagicDamage}m/${f.nPhysicalDamage}p) heal ${f.nHeal} shield ${f.nShield} cc ${f.nCc} (${f.nHardCc} hard) dash ${f.nDash} peak ${f.peakDamage}`);
  console.log(`  playstyle    : ${f.playstyle ?? "—"}`);
  console.log(`  keywords     : ${f.keywords.join(", ") || "—"}`);
  console.log("\n  scores:");
  for (const r of [...ROLES].sort((a, b) => v.scores[b] - v.scores[a])) {
    console.log(`    ${pad(r, 10)} ${v.scores[r].toFixed(2)}`);
  }
  console.log("\n  evidence:");
  for (const e of v.evidence) {
    console.log(`    ${pad(e.role, 10)} ${(e.points >= 0 ? "+" : "") + e.points.toFixed(2).padStart(6)}  ${e.reason}`);
  }
  process.exit(0);
}

// --- summary ---------------------------------------------------------------
// Only the imported docs are proposals; the hand-authored stand-ins are held.
const proposals = verdicts.filter((v) => v.features.imported);
const held = verdicts.filter((v) => !v.features.imported);

const counts = Object.fromEntries(ROLES.map((r) => [r, 0])) as Record<Role, number>;
const crossTab = new Map<string, number>();
for (const v of proposals) {
  counts[v.role]++;
  const key = `${v.role}|${v.features.attackType}`;
  crossTab.set(key, (crossTab.get(key) ?? 0) + 1);
}
const lowConfidence = proposals.filter((v) => v.confidence === "low");

/** Is the proposed role a pure function of attackType (the bug we are fixing)? */
const rolesPerAttackType = new Map<string, Set<Role>>();
for (const v of proposals) {
  const s = rolesPerAttackType.get(v.features.attackType) ?? new Set<Role>();
  s.add(v.role);
  rolesPerAttackType.set(v.features.attackType, s);
}

if (asMarkdown) {
  console.log("# Proposed champion role taxonomy\n");
  console.log("Generated by `tools/role-classify` — **read-only proposal**, no content doc was modified.\n");
  console.log("## Taxonomy\n");
  for (const r of ROLES) console.log(`- \`${r}\` — ${ROLE_BLURB[r]}`);
  console.log("\n## Distribution\n");
  console.log("| role | total | melee | ranged |");
  console.log("| --- | ---: | ---: | ---: |");
  for (const r of ROLES) {
    console.log(`| ${r} | ${counts[r]} | ${crossTab.get(`${r}|melee`) ?? 0} | ${crossTab.get(`${r}|ranged`) ?? 0} |`);
  }
  for (const [atk, set] of rolesPerAttackType) {
    console.log(`\n\`${atk}\` spans ${set.size} roles — ${[...set].join(", ")}.`);
  }
  console.log(
    `\n${lowConfidence.length} of ${proposals.length} are low-confidence (top-two margin < 1.0) and want a human eye before the backfill.\n`,
  );

  console.log("## Calibration\n");
  console.log("Labels a human read off the kit during task #47, before this classifier existed.\n");
  console.log("| id | expected | proposed | agree | rationale for the expected label |");
  console.log("| --- | --- | --- | :-: | --- |");
  for (const cse of CALIBRATION) {
    const v = byId.get(cse.id);
    if (!v) continue;
    console.log(
      `| \`${cse.id}\` | ${cse.expected} | ${v.role} | ${v.role === cse.expected ? "✓" : "✗"} | ${cse.rationale} |`,
    );
  }

  console.log("\n## Held out\n");
  console.log("Hand-authored CC0 stand-ins. They already carry curated roles and the backfill must not touch them.\n");
  console.log("| id | authored | model says | note |");
  console.log("| --- | --- | --- | --- |");
  for (const v of held) {
    console.log(
      `| \`${v.features.id}\` | ${v.features.currentRole} | ${v.role} | stats sit outside the imported bands (armor ${v.features.armor} vs imported p85 of 10) |`,
    );
  }

  console.log("\n## Per-champion proposal\n");
  console.log("| id | name | atk | attr | hp | now | proposed | conf | why |");
  console.log("| --- | --- | --- | --- | ---: | --- | --- | --- | --- |");
  for (const v of proposals) {
    const f = v.features;
    console.log(
      `| \`${f.id}\` | ${f.name} | ${f.attackType} | ${f.primaryAttr ?? "?"}${f.primaryAttrInferred ? "~" : ""} | ${f.hp} | ${f.currentRole} | **${v.role}** | ${v.confidence} | ${truncate(topReasons(v, 3), 90)} |`,
    );
  }
} else {
  console.log(`\nROLE PROPOSAL — ${verdicts.length} champions, read-only (no content doc written)\n`);
  console.log(pad("id", 14) + pad("name", 26) + pad("atk", 8) + pad("attr", 6) + pad("hp", 6) + pad("now", 10) + pad("proposed", 11) + pad("conf", 8) + "why");
  console.log("─".repeat(150));
  for (const v of verdicts) {
    const f = v.features;
    console.log(
      pad(f.id, 14) +
        pad(truncate(f.name, 22), 26) +
        pad(f.attackType, 8) +
        pad((f.primaryAttr ?? "?") + (f.primaryAttrInferred ? "~" : ""), 6) +
        pad(String(f.hp), 6) +
        pad(f.currentRole, 10) +
        pad(v.role, 11) +
        pad(v.confidence, 8) +
        truncate(topReasons(v, 2), 60),
    );
  }

  console.log("\n" + "─".repeat(150));
  console.log(`DISTRIBUTION (${proposals.length} imported champions; ${held.length} hand-authored held out)`);
  for (const r of ROLES) {
    const m = crossTab.get(`${r}|melee`) ?? 0;
    const g = crossTab.get(`${r}|ranged`) ?? 0;
    console.log(`  ${pad(r, 11)} ${String(counts[r]).padStart(3)}   (${m} melee / ${g} ranged)   ${ROLE_BLURB[r]}`);
  }
  console.log(`\n  distinct roles     : ${ROLES.filter((r) => counts[r] > 0).length}/${ROLES.length}`);
  for (const [atk, set] of rolesPerAttackType) {
    console.log(`  ${pad(atk, 19)}: ${set.size} distinct roles — ${[...set].join(", ")}`);
  }
  console.log(`  low confidence     : ${lowConfidence.length}/${proposals.length} (top-two margin < 1.0)`);
  console.log(`                       ${lowConfidence.map((v) => v.features.id).join(", ") || "none"}`);

  console.log("\nCALIBRATION — labels a human read off the kit, before this classifier existed");
  let hits = 0;
  for (const cse of CALIBRATION) {
    const v = byId.get(cse.id);
    if (!v) continue;
    const ok = v.role === cse.expected;
    if (ok) hits++;
    console.log(
      `  ${ok ? "✓" : "✗"} ${pad(cse.id, 14)}${pad(truncate(v.features.name, 20), 24)}expected ${pad(cse.expected, 10)}got ${pad(v.role, 10)}${v.confidence}`,
    );
    if (!ok) console.log(`      ${cse.rationale}`);
  }
  console.log(`  ${hits}/${CALIBRATION.length} agree`);

  console.log("\nHELD OUT — hand-authored roles, never overwritten by the backfill");
  for (const v of held) {
    const agrees = v.role === v.features.currentRole;
    console.log(
      `  ${agrees ? "✓" : "·"} ${pad(v.features.id, 14)}${pad(truncate(v.features.name, 20), 24)}authored ${pad(v.features.currentRole, 10)}model says ${pad(v.role, 10)}${v.confidence}`,
    );
  }
  console.log("\n  `tsx tools/role-classify/src/cli.ts --explain <id>` for one champion's full score sheet.\n");
}
