/**
 * audio/nameVoice — champ-select CONFIRM speaks the champion's 稱號 AND 全名
 * (task #35; the call-out became title+name in task #57).
 *
 * Data contract (`content/assets/audio/voices/names/MANIFEST.json`, generated by
 * `tools/tts-gen/src/build-champ-names.mjs`):
 *
 *   { champions: { [champId]: { zhName, zhTitle, zhFullName, spokenLine, lang,
 *                               voice, segments?, jaTitle, jaName, reading,
 *                               confidence, evidence, clip, voSegments } } }
 *
 * TASK #120 — the CONFIRM call-out is deliberately MIXED-LANGUAGE: the 稱號 is
 * spoken by a CHINESE voice, then the 全名 by a JAPANESE voice (Kyoko), played
 * back-to-back (「[火霧戰士|中文語音] + [夏娜|日文語音]」). Each half is its own clip,
 * listed in `voSegments` (ordered 稱號→全名). This layer plays those clips in
 * sequence on its single reused element. A titleless champion has only the 全名
 * segment; a half a voice could not render is simply absent and we play the rest.
 *
 * `voSegments` is what this layer plays; when it is absent (a pre-#120 manifest)
 * it falls back to the single `clip`. The rest is provenance that keeps the
 * DISPLAY text and the SPOKEN text from drifting — so do NOT reintroduce a
 * "must be Japanese/Kyoko" assumption here.
 *
 * The doc lives under `content/assets/` (NOT `content/config/`) on purpose:
 * `config/*` is a schema-validated, `_index.json`-indexed collection, so a new
 * doc id there would have to land in the shared zod union + every rebuilt index
 * at once. Assets are served verbatim from the same `/content/` mount, so this
 * file is fetched directly and 404s degrade to silence.
 *
 * PLAYBACK IS DELIBERATELY OFF THE WEBAUDIO GRAPH. The name call-out rides its
 * OWN `HTMLAudioElement` (one, reused: a new call-out replaces the previous, so
 * two names can never overlap) instead of `audioSystem.playClip`, which keeps
 * this module additive — it only READS the mixer's public surface
 * (`audioSystem.isUnlocked` / `audioSystem.volumes()` and the pure
 * `effectiveGain`) for the unlock + master/SFX mute/volume state, and never
 * touches the AudioSystem or its buses.
 *
 * Gates, in order: no champId → mixer still autoplay-locked → master or SFX
 * muted → the same champion inside the ~1 s double-fire guard. Any of them is a
 * silent `false`; the mute gate deliberately does NOT burn the guard.
 */
import { AUDIO_CONTENT_BASE, audioSystem, shouldSilenceAudio } from "./AudioSystem";
import { effectiveGain, type VolumeState } from "./audioSelect";
import { grantRoundEndVoice } from "./roundEndVoice";
import { withContentVersion } from "../content/assetVersion";

/** Path of the generated name-VO manifest, relative to the content mount. */
export const NAME_VO_MANIFEST_PATH = "assets/audio/voices/names/MANIFEST.json";
/** Directory the per-champion clips live in (fallback path derivation). */
export const NAME_VO_CLIP_DIR = "assets/audio/voices/names";
/**
 * task #139 — the per-champion famous-quote (名言) pack. Generated by
 * `tools/tts-gen/src/build-champ-quotes.mjs`, keyed by champion id:
 *   { quotes: { [champId]: { jpQuote, romaji, zhGloss, gender, clip, … } } }
 * On CONFIRM the quote clip is played as a THIRD segment, right after the
 * 稱號→全名 call-out; the champ-select profile also DISPLAYS the line. Lives
 * under `content/assets/` (served verbatim, 404 → silence) for the same reason
 * the names manifest does — see the module header.
 */
export const QUOTE_VO_MANIFEST_PATH = "assets/audio/voices/quotes/quotes.json";
/** Directory the per-champion quote clips live in (fallback path derivation). */
export const QUOTE_VO_CLIP_DIR = "assets/audio/voices/quotes";
/** Re-confirming the SAME champion inside this window is a no-op (double-fire). */
export const NAME_VO_GUARD_MS = 1000;
/** Clip gain, multiplied onto the master × SFX mixer level. */
export const NAME_VO_GAIN = 0.95;

/** How sure we are the Japanese reading is the canonical one. */
export type NameConfidence = "high" | "medium" | "low";

/**
 * One half of the mixed-language call-out (task #120): a normalized, content-
 * relative clip path plus which half it is. `part` is informational; playback
 * order is the array order (稱號 first, 全名 second).
 */
export interface ChampionNameVoSegment {
  part: string;
  clip: string;
}

export interface ChampionNameEntry {
  /** the authored Chinese champion name, whole string incl. 稱號 (review aid) */
  zhName: string;
  /**
   * EXACTLY what the clip says: 稱號, a beat, then 全名. "‖" separates fragments
   * spoken by different voices. Empty only on pre-#57 (name-only) manifests.
   */
  spokenLine: string;
  /** the katakana 全名; EMPTY for the English-named champions (Sela, Thorne, …) */
  jaName: string;
  /** romaji of the Japanese fragments (review aid) */
  reading: string;
  confidence: NameConfidence;
  evidence: string;
  /** content-relative mp3 path — the canonical single call-out (pre-#120 fallback) */
  clip: string;
  /**
   * task #120 — the mixed-language 稱號→全名 clips, in play order. Empty when the
   * manifest predates #120 (playback then falls back to `clip`).
   */
  voSegments: ChampionNameVoSegment[];
}

export interface ChampionNamesManifest {
  champions: Record<string, ChampionNameEntry>;
}

function str(v: unknown): string {
  return typeof v === "string" ? v : "";
}

/** Tolerant parse of the name manifest; null = not usable (→ silence). */
export function championNamesFromDoc(doc: unknown): ChampionNamesManifest | null {
  if (!doc || typeof doc !== "object") return null;
  const champs = (doc as { champions?: unknown }).champions;
  if (!champs || typeof champs !== "object") return null;
  const out: Record<string, ChampionNameEntry> = {};
  for (const [id, raw] of Object.entries(champs as Record<string, unknown>)) {
    if (!raw || typeof raw !== "object") continue;
    const o = raw as Record<string, unknown>;
    const spokenLine = str(o["spokenLine"]);
    const jaName = str(o["jaName"]);
    const voSegments = voSegmentsFromRaw(o["voSegments"]);
    // An entry with NOTHING to say is dropped. `voSegments` is the #120 authority
    // (the clips actually played); `spokenLine` is the #57 authority (the four
    // English-named call-outs carry no jaName, so gating on jaName alone would
    // silently drop them); `jaName` on its own still admits pre-#57 name-only
    // manifests. Any one of the three keeps the entry.
    if (!spokenLine && !jaName && voSegments.length === 0) continue;
    const confidence = o["confidence"];
    out[id] = {
      zhName: str(o["zhName"]),
      spokenLine,
      jaName,
      reading: str(o["reading"]),
      confidence:
        confidence === "high" || confidence === "medium" || confidence === "low"
          ? confidence
          : "low",
      evidence: str(o["evidence"]),
      clip: str(o["clip"]) || `${NAME_VO_CLIP_DIR}/${id}.mp3`,
      voSegments,
    };
  }
  return { champions: out };
}

/**
 * Tolerant parse of a `voSegments` array (task #120). Keeps only entries with a
 * usable clip path, normalized onto the content mount, preserving order. A junk
 * or absent value yields `[]` (→ the single-clip fallback path).
 */
function voSegmentsFromRaw(raw: unknown): ChampionNameVoSegment[] {
  if (!Array.isArray(raw)) return [];
  const out: ChampionNameVoSegment[] = [];
  for (const item of raw) {
    if (!item || typeof item !== "object") continue;
    const o = item as Record<string, unknown>;
    const clip = normalizeNameClipPath(str(o["clip"]));
    if (!clip) continue;
    out.push({ part: str(o["part"]), clip });
  }
  return out;
}

/**
 * Normalize a manifest clip path onto the content mount ("assets/…"): strips a
 * leading "/content/", "content/" or bare "/" so both spellings resolve to the
 * same URL. (Same normalization the champion-voice layer applies.)
 */
export function normalizeNameClipPath(path: string | null | undefined): string | null {
  if (typeof path !== "string") return null;
  let s = path.trim();
  if (s.startsWith("/content/")) s = s.slice("/content/".length);
  else if (s.startsWith("content/")) s = s.slice("content/".length);
  else if (s.startsWith("/")) s = s.slice(1);
  return s.length > 0 ? s : null;
}

/** Clip path for a champion: the manifest entry, else null (unmapped = silent). */
export function nameClipFor(
  manifest: ChampionNamesManifest | null,
  champId: string,
): string | null {
  const entry = manifest?.champions[champId];
  if (!entry) return null;
  return normalizeNameClipPath(entry.clip) ?? `${NAME_VO_CLIP_DIR}/${champId}.mp3`;
}

/**
 * The ordered clip paths to play for a champion's CONFIRM call-out (task #120):
 * the 稱號 half then the 全名 half. Falls back to the single canonical `clip`
 * when the entry carries no `voSegments` (a pre-#120 manifest). Returns `[]` for
 * an unmapped champion (→ silence). Never throws.
 */
export function nameSegmentsFor(
  manifest: ChampionNamesManifest | null,
  champId: string,
): string[] {
  const entry = manifest?.champions[champId];
  if (!entry) return [];
  if (entry.voSegments.length > 0) return entry.voSegments.map((s) => s.clip);
  const single = nameClipFor(manifest, champId);
  return single ? [single] : [];
}

// ── task #139: the per-champion famous-quote (名言) pack ──────────────────────

export type QuoteGender = "male" | "female" | "neutral";

/** One champion's quote: the spoken/displayed line plus its rendered clip. */
export interface ChampionQuoteEntry {
  /** the champion display name this quote was authored for (review aid) */
  name: string;
  /** source character / franchise (review aid) */
  character: string;
  /** drives the VO voice: female/neutral → Kyoko, male → a clean male voice */
  gender: QuoteGender;
  /** the spoken Japanese line — also shown in the profile */
  jpQuote: string;
  /** romaji of jpQuote (review aid) */
  romaji: string;
  /** Traditional-Chinese gloss, shown under the Japanese line */
  zhGloss: string;
  /** provenance; false = a coined/惡搞 line rather than a canonical quote */
  real: boolean;
  /** content-relative mp3 path of the quote clip */
  clip: string;
}

export interface ChampionQuotesManifest {
  quotes: Record<string, ChampionQuoteEntry>;
}

/** Tolerant parse of the quote manifest; null = not usable (→ no quote). */
export function championQuotesFromDoc(doc: unknown): ChampionQuotesManifest | null {
  if (!doc || typeof doc !== "object") return null;
  const raw = (doc as { quotes?: unknown }).quotes;
  if (!raw || typeof raw !== "object") return null;
  const out: Record<string, ChampionQuoteEntry> = {};
  for (const [id, v] of Object.entries(raw as Record<string, unknown>)) {
    if (!v || typeof v !== "object") continue;
    const o = v as Record<string, unknown>;
    const jpQuote = str(o["jpQuote"]);
    // An entry with nothing to say/show is dropped (no clip, no display).
    if (!jpQuote) continue;
    const g = o["gender"];
    out[id] = {
      name: str(o["name"]),
      character: str(o["character"]),
      gender: g === "male" || g === "female" || g === "neutral" ? g : "neutral",
      jpQuote,
      romaji: str(o["romaji"]),
      zhGloss: str(o["zhGloss"]),
      // real defaults TRUE; only an explicit `false` marks a coined line.
      real: o["real"] !== false,
      clip: normalizeNameClipPath(str(o["clip"])) ?? `${QUOTE_VO_CLIP_DIR}/${id}.mp3`,
    };
  }
  return { quotes: out };
}

/** The quote entry for a champion, or null when unmapped (silent + no display). */
export function quoteEntryFor(
  manifest: ChampionQuotesManifest | null,
  champId: string,
): ChampionQuoteEntry | null {
  return manifest?.quotes[champId] ?? null;
}

/** The quote CLIP path for a champion, normalized onto the mount, else null. */
export function quoteClipFor(
  manifest: ChampionQuotesManifest | null,
  champId: string,
): string | null {
  const entry = manifest?.quotes[champId];
  if (!entry) return null;
  return normalizeNameClipPath(entry.clip) ?? `${QUOTE_VO_CLIP_DIR}/${champId}.mp3`;
}

/** The slice of the mixer this layer READS (the process AudioSystem satisfies it). */
export interface NameVoiceAudioPort {
  readonly isUnlocked: boolean;
  volumes(): VolumeState;
}

/** The slice of HTMLAudioElement this layer uses (stubbed in tests). */
export interface NameVoiceElement {
  src: string;
  volume: number;
  currentTime: number;
  /** fired when the current clip finishes — drives the 稱號→全名 chain (task #120) */
  onended: (() => void) | null;
  play(): Promise<void> | void;
  pause(): void;
}

function defaultFetch(url: string): Promise<Response> {
  if (typeof fetch !== "function") return Promise.reject(new Error("no fetch"));
  return fetch(url);
}

/** `new Audio()` when the DOM has it; null in node/vitest (→ silent no-op). */
function defaultCreateAudio(): NameVoiceElement | null {
  try {
    const g = globalThis as unknown as { Audio?: new () => HTMLAudioElement };
    return g.Audio ? (new g.Audio() as unknown as NameVoiceElement) : null;
  } catch {
    return null;
  }
}

export interface ChampionNameVoiceOptions {
  audio?: NameVoiceAudioPort;
  /** content mount base, default AUDIO_CONTENT_BASE ("/content/") */
  baseUrl?: string;
  fetchFn?: (url: string) => Promise<Response>;
  /** ms clock for the double-fire guard */
  now?: () => number;
  guardMs?: number;
  gain?: number;
  createAudio?: () => NameVoiceElement | null;
  warn?: (msg: string, err?: unknown) => void;
  /**
   * Force test-mode silence (task #62). When omitted the gate is read from the
   * environment via `shouldSilenceAudio()`. Silent ⇒ the reused `new Audio()`
   * element is never created, so `play()` no-ops exactly like the no-DOM path.
   */
  silent?: boolean;
}

export class ChampionNameVoice {
  private readonly audio: NameVoiceAudioPort;
  private readonly baseUrl: string;
  private readonly fetchFn: (url: string) => Promise<Response>;
  private readonly now: () => number;
  private readonly guardMs: number;
  private readonly gain: number;
  private readonly createAudio: () => NameVoiceElement | null;
  private readonly warn: (msg: string, err?: unknown) => void;
  /** test-mode silence gate (task #62): read once at construction, never sound */
  private readonly silent: boolean;

  private manifestPromise: Promise<ChampionNamesManifest | null> | null = null;
  /** task #139 — the quote pack, loaded once alongside the name manifest. */
  private quotesPromise: Promise<ChampionQuotesManifest | null> | null = null;
  private el: NameVoiceElement | null = null;
  private elCreated = false;
  /**
   * Monotonic id of the current call-out. Every new call-out bumps it, so the
   * 稱號→全名 chain (or a stray play() rejection) from a superseded call-out is
   * ignored instead of playing a half from the previous champion.
   */
  private seq = 0;
  /** champId → last play timestamp (`now()` clock) */
  private readonly lastPlay = new Map<string, number>();

  constructor(opts: ChampionNameVoiceOptions = {}) {
    this.audio = opts.audio ?? audioSystem;
    this.baseUrl = opts.baseUrl ?? AUDIO_CONTENT_BASE;
    this.fetchFn = opts.fetchFn ?? defaultFetch;
    this.now =
      opts.now ?? (() => (typeof performance !== "undefined" ? performance.now() : Date.now()));
    this.guardMs = opts.guardMs ?? NAME_VO_GUARD_MS;
    this.gain = opts.gain ?? NAME_VO_GAIN;
    // task #62: force-silence wins over any injected factory — the out-of-graph
    // `new Audio()` element is never created, so play() no-ops like the no-DOM path.
    this.silent = opts.silent ?? shouldSilenceAudio();
    this.createAudio = this.silent ? () => null : (opts.createAudio ?? defaultCreateAudio);
    this.warn = opts.warn ?? ((msg, err) => console.warn(`[nameVo] ${msg}`, err ?? ""));
  }

  /** Cached single-flight fetch of the manifest; null = missing (silence). */
  load(): Promise<ChampionNamesManifest | null> {
    if (!this.manifestPromise) {
      this.manifestPromise = this.fetchJson(NAME_VO_MANIFEST_PATH).then(championNamesFromDoc);
    }
    return this.manifestPromise;
  }

  /**
   * Cached single-flight fetch of the quote pack (task #139); null = missing
   * (the call-out simply carries no third segment and the profile shows nothing).
   * Warmed by the profile panel on hover, so CONFIRM usually pays no fetch.
   */
  loadQuotes(): Promise<ChampionQuotesManifest | null> {
    if (!this.quotesPromise) {
      this.quotesPromise = this.fetchJson(QUOTE_VO_MANIFEST_PATH).then(championQuotesFromDoc);
    }
    return this.quotesPromise;
  }

  /**
   * Speak `champId`'s mixed-language CONFIRM call-out (task #120): the 稱號 half
   * (a Chinese voice) then the 全名 half (Kyoko), played in order on the single
   * reused element. Returns `true` once the FIRST half has started (the rest
   * follows as each clip ends). Silent `false` when the mixer is autoplay-locked,
   * master/SFX is muted, the same champion is inside the ~1 s guard, the champion
   * has no mapping, or the DOM has no Audio element. The guard slot is reserved
   * SYNCHRONOUSLY (before the async manifest resolution) so a same-tick double
   * confirm can never start two. A champion with only one half plays just that
   * half; a half whose clip is missing is skipped — never a throw.
   *
   * task #139 — the champion's famous quote (名言), when mapped, is appended as a
   * THIRD segment played right after the 全名, using the same sequence + degrade
   * machinery. It is purely additive: no quote ⇒ the call-out is unchanged.
   */
  async play(champId: string): Promise<boolean> {
    if (!champId || !this.audio.isUnlocked) return false;
    const v = this.audio.volumes();
    const volume = effectiveGain(v, "sfx", this.gain);
    if (volume <= 0) return false; // muted: no fetch, no guard burn
    const t = this.now();
    const last = this.lastPlay.get(champId);
    if (last !== undefined && t - last < this.guardMs) return false;
    this.lastPlay.set(champId, t);

    // Both packs are cached single-flight; fetched together so CONFIRM never
    // pays two serial round-trips. Either being missing degrades gracefully.
    const [manifest, quotes, pack] = await Promise.all([
      this.load(),
      this.loadQuotes(),
      this.loadPack(),
    ]);
    const clips = nameSegmentsFor(manifest, champId);
    // task #139 — the champion's famous quote plays as the FINAL segment, after
    // the 稱號→全名 call-out. A champion with no quote just gets the call-out; a
    // champion mapped ONLY in the quote pack still speaks its line.
    //
    // GH#744 — for the seven `voiceClass: cry` champions that segment is the
    // champion's own CRY out of the generated voice pack instead of a `say`
    // render of a sentence the character cannot speak (`_voice-casting.md` §8.3:
    // keep the 名言 TEXT on screen, play the cry). Everyone else, and any cry
    // champion whose pack cry is absent, gets `quoteClip` unchanged.
    const tailClip = confirmTailClip(champId, quoteClipFor(quotes, champId), pack);
    if (tailClip) clips.push(tailClip);
    if (clips.length === 0) return false;
    const el = this.element();
    if (!el) return false;

    return this.playSequence(el, clips, volume, champId);
  }

  /**
   * task #139 — play ONLY a champion's famous quote (名言) clip, with no 稱號→全名
   * call-out. Reuses the SAME gates and single reused element as `play`: mixer
   * autoplay-lock, master/SFX mute (no fetch, no guard burn), and a per-champion
   * ~1 s double-fire guard — under a SEPARATE `quote:` key so a settlement / round
   * quote can never collide with (or be suppressed by) a champ-select call-out
   * for the same champion. Returns `true` once the clip was handed to `play()`;
   * silent `false` when the mixer is locked, muted, the same champion is inside
   * the guard, the champion has no quote clip yet (the pack only covers part of
   * the roster), or the DOM has no Audio element. Never throws.
   *
   * Used at the two post-match beats that are NOT the confirm call-out: the
   * match-victory settlement (the LOCAL champion, win-only) and each round-end
   * settlement (the round's rank-1 champion, the SAME clip on every client).
   */
  async playQuote(champId: string, opts: { gain?: number } = {}): Promise<boolean> {
    if (!champId || !this.audio.isUnlocked) return false;
    // GH#527 —— 名言是 macOS `say` 產的 **TTS**（`tools/tts-gen/src/build-champ-quotes.mjs`
    // 的 Kyoko / Otoya），也就是 owner 2026-08-22 說的「機械語音」。回合結束那一拍
    // 開著時它要問過 `roundEndVoice`；⛔ 其餘每一個呼叫端（比賽結束的結算、選角
    // 確認、點自己的英雄）那一拍是關著的 ⇒ 永遠 true ⇒ 行為逐位元不變。
    if (!grantRoundEndVoice("machine", champId)) return false;
    const volume = effectiveGain(this.audio.volumes(), "sfx", opts.gain ?? this.gain);
    if (volume <= 0) return false; // muted: no fetch, no guard burn
    const t = this.now();
    const key = `quote:${champId}`;
    const last = this.lastPlay.get(key);
    if (last !== undefined && t - last < this.guardMs) return false;
    this.lastPlay.set(key, t);

    const quotes = await this.loadQuotes();
    const clip = quoteClipFor(quotes, champId);
    if (!clip) return false; // champion has no quote yet → silent skip
    const el = this.element();
    if (!el) return false;
    return this.playSequence(el, [clip], volume, champId);
  }

  /**
   * Play `clips` in order on the single reused element, chaining each to the
   * next on its `onended`. A new call-out (a fresh `seq`) supersedes any chain
   * still in flight, so the 稱號 of one champion can never be followed by the 全名
   * of another. A rejected clip advances to the next rather than stranding the
   * rest. Returns `true` when the first clip was handed to `play()`.
   */
  private playSequence(
    el: NameVoiceElement,
    clips: string[],
    volume: number,
    champId: string,
  ): boolean {
    const mySeq = ++this.seq;
    try {
      el.pause(); // a new call-out replaces the previous one — never two voices
      el.onended = null;
    } catch (err) {
      this.warn(`reset failed for ${champId} (silent)`, err);
    }
    let idx = -1;

    const advance = (): void => {
      if (mySeq !== this.seq) return; // a newer call-out took over
      idx += 1;
      if (idx >= clips.length) {
        el.onended = null;
        return;
      }
      const here = idx;
      // Chain to the next half only while more remain; the last clip ends silent.
      el.onended = idx < clips.length - 1 ? advance : null;
      try {
        el.src = this.url(clips[here]!);
        el.currentTime = 0;
        el.volume = volume;
        const p = el.play();
        if (p && typeof (p as Promise<void>).catch === "function") {
          void (p as Promise<void>).catch((err: unknown) => {
            this.warn(`playback blocked for ${champId} (silent)`, err);
            // A half that will not play should not strand the rest; but only if
            // we are still on it and no newer call-out has taken over.
            if (mySeq === this.seq && idx === here) advance();
          });
        }
      } catch (err) {
        this.warn(`playback failed for ${champId} (silent)`, err);
        if (mySeq === this.seq && idx === here) advance();
      }
    };

    advance();
    return true;
  }

  /** Lazily create the single reused element (once — null result is cached). */
  private element(): NameVoiceElement | null {
    if (!this.elCreated) {
      this.elCreated = true;
      this.el = this.createAudio();
    }
    return this.el;
  }

  /**
   * GH#70 —— 語音 URL 要帶 `?h=<contentVersion>`。
   *
   * ⚠️ 這條路徑在 `93bacb58`（「actually cache the 73 MB」）被**漏掉了**：那一筆
   * 只改了 AssetManager / AudioSystem.urlFor / groundMaterials / icons 四處，而
   * 名言與稱號走的是 `HTMLAudioElement`，不經過 `AudioSystem.urlFor`。edge 端
   * `map $arg_h $content_cache` 把空的 `$arg_h` 映射成 `no-cache`，所以
   * names + quotes + voice-taunt 這 830 個檔（11.1 MB）每次載入都 revalidate。
   *
   * `withContentVersion` 在 manifest 落地前是 no-op，所以測試注入的 baseUrl 與
   * 任何 pre-boot 的 clip 逐位元不變 —— 與 `AudioSystem.urlFor` 完全同一個作法。
   */
  private url(path: string): string {
    const url = this.baseUrl.endsWith("/") ? this.baseUrl + path : `${this.baseUrl}/${path}`;
    return withContentVersion(url);
  }

  /** Fetch a JSON doc under the content mount; null on 404 / bad JSON / error. */
  private async fetchJson(path: string): Promise<unknown> {
    try {
      const res = await this.fetchFn(this.url(path));
      if (!res.ok) return null; // 404 = pack not generated — silence
      return (await res.json()) as unknown;
    } catch (err) {
      this.warn(`${path} failed to load (silent)`, err);
      return null;
    }
  }

  /**
   * GH#583 —— **停掉正在講的那一句**（名言最長量到 9.99s）。
   *
   * ⚠️ 這一層走 `HTMLAudioElement`，⛔ 不在 WebAudio 圖上 ⇒ `stopSustainedSfx()` /
   * `stopAllVoices()` / 場景切換**逐位元都碰不到它**。在這支之前，回合結算的名言會
   * 整句講完、跨過商店、跨過離開房間、跨進練習模式，而**沒有任何按鈕停得掉**。
   *
   * ⛔ 只 bump `seq` 不夠 —— `seq` 只擋得住**下一段**，擋不住**正在響的那一段**，
   * 而正在響的那一段正是這條缺陷的形狀。所以一定要 `pause()`。
   */
  cancel(): void {
    this.seq += 1;
    try {
      if (this.el) {
        this.el.onended = null;
        this.el.pause();
      }
    } catch (err) {
      this.warn("cancel failed (silent)", err);
    }
  }

  /** Drop the cached manifests + guards (tests / content live-reload). */
  reset(): void {
    this.manifestPromise = null;
    this.quotesPromise = null;
    this.lastPlay.clear();
  }
}

/** Process-wide name-VO layer, reading the process-wide mixer state. */
export const championNameVoice = new ChampionNameVoice();

/** Warm the name manifest (cached; safe to call from any boot path). */
export function loadChampionNames(): Promise<ChampionNamesManifest | null> {
  return championNameVoice.load();
}

/**
 * Warm + read the quote pack (task #139), cached single-flight. The champ-select
 * profile panel calls this to DISPLAY a champion's line; warming it here also
 * spares the first CONFIRM the fetch. Null when the pack is missing.
 */
export function loadChampionQuotes(): Promise<ChampionQuotesManifest | null> {
  return championNameVoice.loadQuotes();
}

/** Speak a champion's Japanese full name (see ChampionNameVoice.play). */
export function playChampionNameVo(champId: string): Promise<boolean> {
  return championNameVoice.play(champId);
}

/**
 * task #139 — play a champion's famous quote (名言) clip ALONE (no call-out), for
 * the settlement + round-end beats. See ChampionNameVoice.playQuote. `opts.gain`
 * overrides the default clip gain (still multiplied by the master × SFX level).
 * Fire-and-forget + self-gating: a missing clip / locked / muted mixer is a
 * silent `false`, never a throw.
 */
export function playChampionQuote(champId: string, opts?: { gain?: number }): Promise<boolean> {
  return championNameVoice.playQuote(champId, opts);
}
