from pathlib import Path
import json, hashlib, shutil
import numpy as np
ROOT=Path('/Users/Takuro/Dropbox/我的 Mac (Moriya.local)/Documents/ABxVFX_EDIT/GGD-Asset-Library/intake/public-models-20260910')
DST=ROOT/'parallel-community-lina-ggd-compatibility'
SOURCE=ROOT/'parallel-community-lina-rays-300-retarget-footloop-v2/evidence/footloop-dense-audit-960hz.json'
run=json.loads(SOURCE.read_text())[1]; v=run['variants']['processed']; frames=v['frames']; t=np.array([f['seconds'] for f in frames]); step=float(t[1]-t[0]); result={'source':str(SOURCE),'sourceSha256':hashlib.sha256(SOURCE.read_bytes()).hexdigest(),'sourceGlbSha256':v['sha256'],'units':'meters and seconds, standalone source GLB normalization from footloop-v2, playback 1x, external entity speed 4.5224146092674875 m/s','sampleHz':960,'caveat':'Sampled numerical inspection, not continuous extrema. Horizontal central derivative uses one frame on either side; event duration includes half sample either side and is resolution dependent. Core mask excludes samples whose adjacent frame is outside contact. These are pose-processing quality metrics, not GGD runtime ground/scale acceptance.','feet':{}}
for foot in ['L','R']:
 p=np.array([f[foot]['plantWorldCentroid'] for f in frames]); contact=np.array([f[foot]['scheduledCoreContact'] for f in frames]); core=contact.copy(); core[1:-1]&=contact[:-2]&contact[2:]; speed=np.linalg.norm(np.gradient(p,t,axis=0)[:,[0,2]],axis=1); peak=int(np.argmax(np.where(core,speed,-1))); events={}
 for threshold in [.1,.5,1.0]:
  indices=np.flatnonzero(core&(speed>threshold)); groups=np.split(indices,np.flatnonzero(np.diff(indices)>1)+1) if len(indices) else []; out=[]
  for g in groups:
   a,b=int(g[0]),int(g[-1]); left=max(0,a-1); right=min(len(t)-1,b+1); delta=p[right]-p[left]; out.append({'sampleIndices':[a,b],'sampleCentersSeconds':[float(t[a]),float(t[b])],'durationWithHalfStepEachSideSeconds':float((b-a+1)*step),'centralDerivativeSupportSeconds':[float(t[left]),float(t[right])],'supportDurationSeconds':float(t[right]-t[left]),'supportDeltaXYZMeters':delta.tolist(),'supportNetHorizontalDisplacementMeters':float(np.linalg.norm(delta[[0,2]])),'supportHorizontalPathLengthMeters':float(np.linalg.norm(np.diff(p[left:right+1][:,[0,2]],axis=0),axis=1).sum()),'peakMps':float(speed[g].max())})
  events[str(threshold)]=out
 ids=np.flatnonzero(core); cp=p[ids]; span=cp.max(axis=0)-cp.min(axis=0)
 result['feet'][foot]={'peakIndex':peak,'peakSeconds':float(t[peak]),'peakPhase':float(frames[peak]['phase']),'peakHorizontalWorldSpeedMps':float(speed[peak]),'coreContactWorldRangeXYZMeters':span.tolist(),'rangeCaveat':'Range aggregates disconnected contact windows; right foot wraps across the cycle and its large Z range includes external entity travel, so this range is not a slide metric. Threshold event displacement is local to its listed derivative support.','coreContactHorizontalBoundingDiagonalMeters':float(np.linalg.norm(span[[0,2]])),'coreContactMaxBootY':max(frames[i][foot]['minY'] for i in ids),'thresholdEventsMps':events,'peakNeighborhood':[{'index':j,'seconds':float(t[j]),'core':bool(core[j]),'speedMps':float(speed[j]),'worldCentroid':p[j].tolist(),'bootMinY':frames[j][foot]['minY']} for j in range(max(0,peak-5),min(len(t),peak+6))]}
result['frameTimes']={'30fpsSeconds':1/30,'60fpsSeconds':1/60,'warning':'A short sub-frame displacement can still change the sampled visible pose; duration alone is not a visual pass.'}
(DST/'evidence/left-foot-spike.json').write_text(json.dumps(result,indent=2)+'\n');shutil.copyfile('/private/tmp/ggd-lina-compat-foot-spike.py',DST/'scripts/ggd-lina-compat-foot-spike.py');print(json.dumps({k:{'peak':f['peakHorizontalWorldSpeedMps'],'eventsAbovePoint1':f['thresholdEventsMps']['0.1'],'range':f['coreContactWorldRangeXYZMeters']} for k,f in result['feet'].items()},indent=2))
