#!/usr/bin/env python3
"""gen_readme_lists.py — write the roster / ability / item lists INTO README.md.

WHY THIS EXISTS. The owner wants the full lists in the README itself, not
linked away to another file. Hand-written they would be wrong within a week
(see docs/champions.csv — nothing generates it, nothing checks it, and it has
been drifting from content/ ever since). So the lists live in the README but
NOTHING HUMAN WRITES THEM: this script owns three marker-delimited regions and
rewrites only the text between them.

    <!-- BEGIN GENERATED:roster -->    …    <!-- END GENERATED:roster -->
    <!-- BEGIN GENERATED:abilities --> …    <!-- END GENERATED:abilities -->
    <!-- BEGIN GENERATED:items -->     …    <!-- END GENERATED:items -->

Every hand-written word outside those markers is preserved byte for byte. If a
marker pair is missing the block is APPENDED at the end of the file, so the
first run bootstraps itself and later runs are in-place edits.

WHAT IT READS: nothing but content/ and the operator whitelist — the loader is
`build_context()` in gen_reference.py, shared with the docs/reference/*.md
generator so the two can never disagree.

WHAT IT WRITES: README.md, between the markers, and nothing else.

Run it with `pnpm docs:readme` from the repo root, or directly:
  python3 tools/reference/gen_readme_lists.py

Flags:
  --check   exit 1 if the README is stale (for CI / a pre-commit hook); writes nothing.

Stdlib only, deterministic, idempotent: two runs produce a byte-identical
README. There is no timestamp in the output — the contentVersion is the
freshness stamp, exactly as in tools/status/gen_status.py and gen_reference.py.
"""

import os
import re
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

import gen_reference as G  # noqa: E402  — sibling module, same directory

REPO = G.REPO
README = os.path.join(REPO, "README.md")

CMD = "pnpm docs:readme"
SCRIPT = "tools/reference/gen_readme_lists.py"

# Truncation limits, in CHARACTERS. These exist because a markdown table cell
# that runs to 300 characters destroys the whole table's readability — and these
# tables now live in the README, where readability is the entire point.
# Almost every value here is CJK, which renders double-width, so a 40-char cell
# is already ~80 columns wide. Keep these low. The full untruncated text is one
# click away in the codex (http://localhost:39527/#codex).
LIMIT_CHAMPION_DESC = 40
LIMIT_ABILITY_EFFECT = 50
LIMIT_ITEM_STATS = 52
LIMIT_ITEM_PASSIVE = 28

BLOCKS = ("roster", "abilities", "items")


# ---------------------------------------------------------------------------
# marker splicing
# ---------------------------------------------------------------------------

def markers(name):
    return (f"<!-- BEGIN GENERATED:{name} -->", f"<!-- END GENERATED:{name} -->")


def splice(text, name, body):
    """Replace the text between the marker pair with `body`.

    Returns (new_text, "replaced" | "appended"). Missing markers are appended at
    the end of the file — that is how the first run bootstraps. A BEGIN without
    its END (or the pair in the wrong order) is a hand-edit accident, not
    something to guess at, so it aborts."""
    begin, end = markers(name)
    n_begin, n_end = text.count(begin), text.count(end)
    if n_begin > 1 or n_end > 1:
        sys.exit(f"README.md has {n_begin} BEGIN / {n_end} END markers for '{name}' — expected at most 1 of each")
    if n_begin != n_end:
        sys.exit(f"README.md has an unmatched marker for '{name}' (BEGIN={n_begin}, END={n_end}) — fix it by hand")

    block = f"{begin}\n{body.rstrip()}\n{end}"
    if n_begin == 0:
        sep = "" if text.endswith("\n\n") else ("\n" if text.endswith("\n") else "\n\n")
        return text + sep + block + "\n", "appended"

    i = text.index(begin)
    j = text.index(end, i)
    if j < i:
        sys.exit(f"README.md has END before BEGIN for '{name}' — fix it by hand")
    return text[:i] + block + text[j + len(end):], "replaced"


# ---------------------------------------------------------------------------
# shared block chrome
# ---------------------------------------------------------------------------

def open_details(summary):
    return ["<details>", f"<summary>{summary}</summary>", ""]


def close_details(ctx, extra=None):
    """Every block ends with the same small italic provenance line, OUTSIDE the
    <details> so it is still visible when the block is collapsed."""
    L = ["</details>", ""]
    tail = f"*generated by `{CMD}`, from contentVersion `{ctx['contentVersion']}`."
    if extra:
        tail += f" {extra}"
    L.append(tail + " 手動編輯這三段之間的任何字都會在下次重新產生時被覆蓋。*")
    return L


def note(lines):
    # ">" alone, never "> " — a trailing space on a blank quote line is invisible
    # churn that makes the next diff noisy for no reason.
    return [("> " + l if l else ">") for l in lines] + [""]


# ---------------------------------------------------------------------------
# roster
# ---------------------------------------------------------------------------

ROSTER_HEAD = [
    "| id | 全名 | 稱號 | role | 攻擊 | 一句話說明 | 技能 id（Q W E R EX） |",
    "|---|---|---|---|---|---|---|",
]


def roster_row(c):
    title, full = G.split_champion_name(c.get("name", ""))
    abils = c.get("abilities") or {}
    ids = []
    for slot in ("Q", "W", "E", "R"):
        a = abils.get(slot)
        if isinstance(a, dict) and a.get("id"):
            ids.append(f"`{a['id']}`")
    if c.get("exAbility"):
        ids.append(f"`{c['exAbility']}`")
    return "| {id} | {full} | {title} | {role} | {atk} | {desc} | {abils} |".format(
        id=f"`{c['id']}`",
        full=G.cell(full),
        title=G.cell(title),
        role=G.cell(c.get("role")),
        atk="近戰" if c.get("attackType") == "melee" else "遠程",
        desc=G.cell(G.one_line(c.get("description"), LIMIT_CHAMPION_DESC) or "—"),
        abils=" ".join(ids) if ids else "—",
    )


def gen_roster(ctx):
    champs = ctx["champions"]
    open_ids = ctx["open_champions"]
    open_rows = [c for c in champs if c["id"] in open_ids]
    closed_rows = [c for c in champs if c["id"] not in open_ids]

    L = open_details(
        f"<b>英雄名冊 / Champion roster</b> — 全部 {len(champs)} 名英雄"
        f"（開放 {len(open_rows)} · 未開放 {len(closed_rows)}）"
    )
    L += note([
        "開放名單是**營運策展狀態**，不是程式常數：真相在 `data/curation/whitelist.json`，"
        "由 platform 的 `GET /api/v1/curation/whitelist` 提供、由 game-server 在建房時執行。"
        f"來源：{ctx['whitelist_note']}",
        "",
        "`稱號` / `全名` 是從 `name` 欄位拆出來的（慣例 `稱號 - 全名`），champion doc 上"
        "**沒有**獨立的稱號欄位；不符慣例的顯示 `—`。`名言` 也不在 champion doc 裡。",
        "",
        f"⚠️ `一句話說明` 取自 `description` 並**截斷到 {LIMIT_CHAMPION_DESC} 字**，結尾的 `…` "
        "是產生器加的、不是原文的一部分（表格可讀性所需，見產生器頂端的說明）。"
        "要完整描述請開 <http://localhost:39527/#codex> 或直接讀 `content/champions/<id>.json`。"
        "沒有 `description` 的顯示 `—`。",
    ])

    L.append(f"#### 開放名單 OPEN roster（{len(open_rows)}）")
    L.append("")
    L.append("選角畫面看得到、bot 也會抽到的就是這些。")
    L.append("")
    L += ROSTER_HEAD
    L += [roster_row(c) for c in open_rows]
    L.append("")

    L.append(f"#### 未開放 not in the open roster（{len(closed_rows)}）")
    L.append("")
    L.append("文件存在、資料完整，但白名單沒放行，所以選不到。")
    L.append("")
    L += ROSTER_HEAD
    L += [roster_row(c) for c in closed_rows]
    L.append("")

    L += close_details(ctx, f"共 {len(champs)} 列。")
    return "\n".join(L), len(champs)


# ---------------------------------------------------------------------------
# abilities — grouped by champion so each block reads as a KIT, not a flat dump
# ---------------------------------------------------------------------------

ABILITY_HEAD = [
    "| slot | id | 名稱 | 型態 | 短效果 |",
    "|---|---|---|---|---|",
]


def ability_row(a):
    tag = G.desc_tag(a.get("description"))
    is_passive = bool(a.get("passive")) or tag == "被動"
    eff = G.one_line(a.get("description"), LIMIT_ABILITY_EFFECT) or G.effect_summary(a) or "—"
    return "| {slot} | {id} | {name} | {kind} | {eff} |".format(
        slot=a.get("slot") or "?",
        id=f"`{a['id']}`",
        name=G.cell(a.get("name")),
        kind="被動" if is_passive else G.cell(tag or "主動"),
        eff=G.cell(eff),
    )


def gen_abilities(ctx):
    abils = ctx["abilities"]
    owner_of = ctx["ability_owner"]
    open_champ = ctx["open_champions"]

    by_owner = {}
    orphans = []
    for a in abils:
        owner = owner_of.get(a["id"])
        if owner is None:
            orphans.append(a)
        else:
            by_owner.setdefault(owner, []).append(a)

    counts = {}
    for a in abils:
        counts[a.get("slot")] = counts.get(a.get("slot"), 0) + 1
    census = " · ".join(f"{s} {counts.get(s, 0)}" for s in ("Q", "W", "E", "R", "EX"))

    champs = ctx["champions"]
    # Open kits first — those are the ones a reader is actually looking up.
    ordered = ([c for c in champs if c["id"] in open_champ]
               + [c for c in champs if c["id"] not in open_champ])

    L = open_details(
        f"<b>技能總表 / Ability reference</b> — 全部 {len(abils)} 個技能"
        f"，依英雄分組（{len(by_owner)} 套技能組）"
    )
    L += note([
        f"每個英雄每個 slot 一份：{census}。開放名單內的英雄排在前面。",
        "",
        "`slot` 只有 Q/W/E/R/EX 五種 —— **被動不是一個 slot**，它掛在某個 QWER 技能上"
        "（`型態` 欄標「被動」的就是）；全樹沒有任何 `xx-00` 被動技能文件。"
        "`型態` 取自描述開頭的 w3x 分類標記，沒有標記的顯示「主動」。",
        "",
        "數值是 `content/` 的**原始值**，未套用 `combat-env` 全域倍率 —— 遊戲內顯示的一律是"
        "乘算後的最終值，所以畫面上的冷卻／傷害跟這裡不會相同。那是預期行為。",
        "",
        f"⚠️ `短效果` 取自 `description` 並**截斷到 {LIMIT_ABILITY_EFFECT} 字**，結尾的 `…` "
        "是產生器加的、不是原文的一部分。完整文字在 <http://localhost:39527/#codex> "
        "或 `content/abilities/<id>.json`；沒有 `description` 的會退回一行自動摘要。",
    ])

    for c in ordered:
        kit = sorted(by_owner.get(c["id"], []),
                     key=lambda a: (G.SLOT_ORDER.get(a.get("slot"), 9), a["id"]))
        if not kit:
            continue
        _title, full = G.split_champion_name(c.get("name", ""))
        mark = "✅ 開放" if c["id"] in open_champ else "— 未開放"
        L.append(f"**`{c['id']}` {G.cell(full)}** · {G.cell(c.get('role'))} · {mark} · {len(kit)} 技")
        L.append("")
        L += ABILITY_HEAD
        L += [ability_row(a) for a in kit]
        L.append("")

    if orphans:
        L.append(f"**（無主）沒有任何 champion doc 引用（{len(orphans)}）**")
        L.append("")
        L += ABILITY_HEAD
        L += [ability_row(a) for a in sorted(orphans, key=lambda a: a["id"])]
        L.append("")

    L += close_details(ctx, f"共 {len(abils)} 列。")
    return "\n".join(L), len(abils)


# ---------------------------------------------------------------------------
# items
# ---------------------------------------------------------------------------

ITEM_HEAD = [
    "| id | 名稱 | 價格 | tier | 傳說池 | 開放 | 屬性 modifiers | 被動 |",
    "|---|---|---|---|---|---|---|---|",
]


def gen_items(ctx):
    items = ctx["items"]
    legendary = ctx["legendary_pool"]
    open_items = ctx["open_items"]

    def has_effect(i):
        return bool(i.get("modifiers")) or bool(i.get("passive"))

    def shop_label(i):
        if i["id"] in G.SERVICE_IDS:
            return "服務"
        if i["id"] in legendary:
            return "傳說"
        cost = i.get("cost")
        if cost == G.TIER_PRICE["SIMPLE"] and has_effect(i):
            return "簡易"
        if cost == G.TIER_PRICE["POWERFUL"] and has_effect(i):
            return "強力"
        return "未上架"

    def price(i):
        if i["id"] in legendary:
            return "無價格"
        cost = i.get("cost")
        return f"{cost}g" if isinstance(cost, (int, float)) else "—"

    def row(i):
        return "| {id} | {name} | {price} | T{tier} | {leg} | {open_} | {stats} | {passive} |".format(
            id=f"`{i['id']}`",
            name=G.cell(i.get("name")),
            price=price(i),
            tier=i.get("tier"),
            leg="✅" if i["id"] in legendary else "—",
            open_="✅" if i["id"] in open_items else "—",
            stats=G.cell(G.truncate(G.fmt_modifiers(i), LIMIT_ITEM_STATS)),
            passive=G.cell(G.truncate(G.fmt_passive(i), LIMIT_ITEM_PASSIVE)),
        )

    services = [i for i in items if i["id"] in G.SERVICE_IDS]
    simple = [i for i in items if shop_label(i) == "簡易"]
    powerful = [i for i in items if shop_label(i) == "強力"]
    legend = [i for i in items if i["id"] in legendary]
    listed = {i["id"] for i in services + simple + powerful + legend}
    rest = [i for i in items if i["id"] not in listed]

    L = open_details(
        f"<b>道具總表 / Item reference</b> — 全部 {len(items)} 件道具"
        # Every bucket must appear here: a reader who leaves the <details>
        # collapsed sees ONLY this line, so a breakdown that does not sum to
        # len(items) is a lie. services used to be missing (70+25+117 = 212).
        f"（商店上架 {len(simple) + len(powerful)} · 傳說池 {len(legend)}"
        f" · 商店服務 {len(services)} · 未上架 {len(rest)}）"
    )
    L += note([
        "只有兩種價格：**簡易 300g**、**強力 1200g**"
        "（`packages/shared/src/sim/economy/itemTiers.ts:43-46`）。**傳說沒有價格**，"
        "只能靠三選一卡或 2400g 的傳說寶玉抽到。背包 6 格、賣出退 40%。",
        "",
        "「可買」的判定是**同時**滿足：價格等於某個階梯價 **且** 真的有效果"
        "（有 `modifiers` 或 `passive`）—— 有幾件 1200g 的 WC3 製作書沒有效果，因此不上架。",
        "",
        "`tier` 欄是 doc 上的 1..5 分級，那是 w3x 匯入的遺留欄位，**與價格階梯無關**。"
        "`暴擊率` / `暴擊傷害` / `吸血` 的 flat 值是**小數比例**（`+0.17` 就是 17%）；"
        "標了 `%` 的才是 `pctAdd`。",
        "",
        f"⚠️ `屬性 modifiers` 截斷到 {LIMIT_ITEM_STATS} 字、`被動` 截斷到 "
        f"{LIMIT_ITEM_PASSIVE} 字，結尾的 `…` 是產生器加的、不是原文的一部分。"
        "完整內容在 <http://localhost:39527/#codex> 或 `content/items/<id>.json`。",
    ])

    for title, rows, blurb in (
        (f"商店服務 services（{len(services)}）", services,
         "真的是 `item@1` 文件，但 `buyItem` 在進背包路徑前就攔截它們：不佔格、可重複買。"),
        (f"簡易 SIMPLE 300g（{len(simple)}）", simple, None),
        (f"強力 POWERFUL 1200g（{len(powerful)}）", powerful, None),
        (f"傳說池 legendary pool（{len(legend)}）", legend,
         f"`content/loot-tables/{G.LEGENDARY_POOL_TABLE}.json`，等權重抽取。買不到，"
         "只能從第 5 回合的武器三選一或傳說寶玉取得。"),
        (f"未上架 not purchasable（{len(rest)}）", rest,
         "價格不在階梯上、或沒有任何效果。留著是為了 w3x 對照與未來策展，不會出現在商店。"),
    ):
        L.append(f"#### {title}")
        L.append("")
        if blurb:
            L.append(blurb)
            L.append("")
        L += ITEM_HEAD
        L += [row(i) for i in rows]
        L.append("")

    missing = sorted(i for i in legendary if i not in {x["id"] for x in items})
    if missing:
        L.append("> ⚠️ 傳說池引用了不存在的道具 id：" + ", ".join(f"`{m}`" for m in missing))
        L.append("")

    L += close_details(ctx, f"共 {len(items)} 列。")
    return "\n".join(L), len(items)


# ---------------------------------------------------------------------------

GENERATORS = {"roster": gen_roster, "abilities": gen_abilities, "items": gen_items}


def render(ctx):
    """name -> (body, rows), in the fixed BLOCKS order."""
    return {name: GENERATORS[name](ctx) for name in BLOCKS}


def main():
    check_only = "--check" in sys.argv[1:]

    if not os.path.exists(README):
        sys.exit(f"missing {README}")
    with open(README, encoding="utf-8") as f:
        original = f.read()

    ctx = G.build_context()
    rendered = render(ctx)

    text = original
    actions = {}
    for name in BLOCKS:
        body, _rows = rendered[name]
        text, actions[name] = splice(text, name, body)

    if check_only:
        if text != original:
            stale = ", ".join(f"{n}({a})" for n, a in actions.items())
            sys.exit(f"README.md is stale — run `{CMD}` (blocks: {stale})")
        print(f"README.md is up to date with contentVersion {ctx['contentVersion']}")
        return

    changed = text != original
    if changed:
        with open(README, "w", encoding="utf-8") as f:
            f.write(text)

    print(f"contentVersion {ctx['contentVersion']}")
    for name in BLOCKS:
        _body, rows = rendered[name]
        print(f"  {name:<10} {rows:>4} rows  ({actions[name]})")
    print(f"{'wrote' if changed else 'unchanged'} {os.path.relpath(README, REPO)}"
          f" — {len(text.splitlines())} lines total")


if __name__ == "__main__":
    main()
