from pathlib import Path
import argparse,json,hashlib,struct
p=argparse.ArgumentParser();p.add_argument('source',type=Path);p.add_argument('output',type=Path);p.add_argument('--repo',type=Path,required=True);a=p.parse_args();src=a.source.resolve();r=a.output.resolve();repo=a.repo.resolve()
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def ref(p):return {'path':str(p),'bytes':p.stat().st_size,'sha256':sha(p)}
def read(p):return json.loads(p.read_text())
def put(name,x):
 with (r/name).open('x') as f:json.dump(x,f,ensure_ascii=False,indent=2);f.write('\n')
full=read(r/'conversion-receipt.json');normal=read(r/'idle-walk-256/receipt.json');analysis=read(src/'analysis/model-analysis.json');model=r/'astralym-material-bound.glb';normalized=r/'idle-walk-256/astralym-idle-walk-256.glb';render=read(r/'validation/babylon/render-proof.json');render256=read(r/'validation/babylon-idle-walk-256-final/render-proof.json');assert render['animationGroupCount']==58 and len(render['samples'])==174;assert render256['animationGroupCount']==2 and len(render256['samples'])==6;assert normal['budget']['errors']==[]
assert all(t['ready'] for t in render['textures']) and all(t['ready'] for t in render256['textures'])
put('motion-library.json',{'schema':'ggd.native-motion-library@1','character':'Astralym / 枯星龍','nativeId':'WorldTreeDragon','sourceId':'opgg-palworld-astralym-2026081102','nativeSource':ref(src/'original/model.glb'),'materialBoundLibrary':ref(model),'skeletonJoints':145,'animationTimeUnit':'seconds in glTF; original Unreal FPS/build not independently obtained','clips':[{'index':c['index'],'name':c['name'],'seconds':c['seconds'],'channels':c['channelCount'],'changingChannels':c['changingChannels'],'classification':'time-changing-source-motion' if c['changingChannels'] else 'fixed-pose-source-clip','sourceModelPath':str(model),'sourceModelSha256':sha(model),'standaloneFile':False,'native':True,'retargeted':False,'procedural':False,'sampleDetailPath':str(src/'analysis/model-analysis.json')} for c in analysis['animations']],'summary':{'storedClips':58,'movingClips':57,'fixedPoses':1},'ggdFullLibraryImport':'blocked by JSON 4,753,652 > 4,194,304 bytes; no gate changes','selectedImportableSubset':ref(normalized)})
variants=[('full58','astralym-material-bound.glb','material-bound-full-library-json-over-current-upload-limit',58,'validation/khronos-full.json','validation/babylon/render-proof.json'),('idle-walk-hd','idle-walk/astralym-idle-walk.glb','shared-inspection-passed-texture-budget-exceeded',2,'idle-walk/khronos-full.json','validation/babylon-idle-walk/render-proof.json'),('idle-walk-256','idle-walk-256/astralym-idle-walk-256.glb','shared-inspection-and-budget-passed-not-registered',2,'idle-walk-256/khronos-full.json','validation/babylon-idle-walk-256-final/render-proof.json')]
candidates=[]
for name,path,state,clips,khr,bab in variants:
 val=read(r/khr);candidates.append({'id':'opgg-palworld-astralym-2026081102.'+name,'character':'Astralym / 枯星龍','heroIds':[],'sourceId':'opgg-palworld-astralym-2026081102','model':ref(r/path),'readiness':state,'nativeClipCount':clips,'all58LibraryPreserved':True,'textures':9,'triangles':23928,'joints':145,'drawPrimitives':3,'defaultEligible':False,'automaticEligible':False,'backendRegistered':False,'validator':ref(r/khr)|{'errors':val['issues']['numErrors'],'warnings':val['issues']['numWarnings'],'truncated':val['issues']['truncated']},'babylonProof':ref(r/bab),'motionLibrary':str(r/'motion-library.json')})
put('model-candidates.json',{'schema':'ggd.astralym.material-candidates@1','candidates':candidates})
# Retain exact shared implementation pins as repeatability evidence.
shared=[repo/'packages/shared/src/content/modelUpload'/n for n in ['inspect.ts','glb.ts','budget.ts','normalize.ts','heroModel.ts']]+[repo/'apps/content-api/src/resizeImage.node.ts']
put('shared-toolchain.json',{'files':[ref(p) for p in shared],'dependencies':['Existing repo node_modules: gltf-validator@2.0.0-dev.3.10; BabylonJS7.54.3; esbuild0.28.1; tsx','Python with Pillow; ffmpeg/ffprobe','Local Chrome headless with SwiftShader; isolated temporary profiles'],'acquiredAssetCodeExecuted':False})
frozen=read(src/'file-manifest.json')
for f in frozen['files']:
 p=src/f['path'];assert p.stat().st_size==f['bytes'] and sha(p)==f['sha256'],str(p)
put('source-unchanged-proof.json',{'sourceFrozenManifest':ref(src/'file-manifest.json'),'all86SourceFilesUnchanged':True,'checkedFiles':len(frozen['files'])})
put('delivery.json',{'schema':'ggd.astralym.material-delivery@1','localRoot':str(r),'sourceRoot':str(src),'sourceId':'opgg-palworld-astralym-2026081102','preferredCandidate':ref(normalized),'full58MaterialBoundLibrary':ref(model),'modelCandidates':ref(r/'model-candidates.json'),'motionLibrary':ref(r/'motion-library.json'),'nativeAnimations':57,'storedAnimationEntries':58,'nativeIdleWalkOnlyInPreferredCandidate':True,'all9ImagesEmbedded':True,'preferredInspectionAndBudget':'passed with triangle/channel warnings','preferredKhronos':{'errors':0,'warnings':2,'truncated':False},'babylon':{'fullClips':58,'fullSamplePoints':174,'fullScreenshots':6,'preferredClips':2,'preferredSamplePoints':6,'preferredScreenshots':2,'allTexturesReady':True},'visualReview':'Full-resolution Idle, Walk and Supernova_Start screenshots inspected: full body, eyes and cyan emissive texture present; no whole-model breakup. Final256 screenshots reviewed separately in visual-review.json.','limitations':['Not a six-state ready hero; no heroId or fake death authored.','Full58 JSON exceeds GGD 4MiB upload limit; preserved as full motion source plus index.','Native nonroot skinned mesh and generated tangent warnings remain.','Source ninth SSS image is embedded and mapped in provenance extras; source multiplier [0,0,0], no guessed nonzero scattering.','Source eye tiny alphaTest/depth bias and Unreal clearcoat profile are not fully representable by this standard material mapping.'],'centralEdits':False,'gitWrites':False,'s3Writes':False,'filesManifest':'file-manifest.json'})
print(json.dumps({'delivery':str(r/'delivery.json'),'candidate':ref(normalized),'sourceUnchanged':True},ensure_ascii=False,indent=2))
