import assert from'node:assert/strict';import{readFileSync,writeFileSync,mkdirSync}from'node:fs';import{join,resolve}from'node:path';import{createRequire}from'node:module';import{createHash}from'node:crypto';
const[rr,oo]=process.argv.slice(2),repo=resolve(rr),root=resolve(oo),out=join(root,'idle-walk-256');mkdirSync(out);const source=join(root,'idle-walk/astralym-idle-walk.glb'),raw=new Uint8Array(readFileSync(source));
const{normalizeUploadedModel}=await import(join(repo,'packages/shared/src/content/modelUpload/normalize.ts'));const{resizeImageWithFfmpeg}=await import(join(repo,'apps/content-api/src/resizeImage.node.ts'));const{inspectModelUpload}=await import(join(repo,'packages/shared/src/content/modelUpload/inspect.ts'));const{heroModelBudgetIssues}=await import(join(repo,'packages/shared/src/content/modelUpload/heroModel.ts'));const{parseUploadGlb}=await import(join(repo,'packages/shared/src/content/modelUpload/glb.ts'));
const before=parseUploadGlb(raw),normalized=await normalizeUploadedModel(raw,{resizeImage:resizeImageWithFfmpeg}),after=parseUploadGlb(normalized.bytes),sha=(b:Uint8Array)=>createHash('sha256').update(b).digest('hex');
assert.deepEqual(before.json.nodes,after.json.nodes);assert.deepEqual(before.json.skins,after.json.skins);assert.deepEqual(before.json.meshes,after.json.meshes);assert.deepEqual(before.json.animations,after.json.animations);assert.equal(before.json.accessors.length,after.json.accessors.length);
const dims={SCALAR:1,VEC2:2,VEC3:3,VEC4:4,MAT4:16},sizes={5120:1,5121:1,5122:2,5123:2,5125:4,5126:4};
function data(p:any,id:number){const a=p.json.accessors[id],v=p.json.bufferViews[a.bufferView];assert(!a.sparse);const width=(dims as any)[a.type]*(sizes as any)[a.componentType],stride=v.byteStride??width,at=(v.byteOffset??0)+(a.byteOffset??0),b=new Uint8Array(width*a.count);for(let i=0;i<a.count;i++)b.set(p.bin.subarray(at+i*stride,at+i*stride+width),i*width);return b;}
for(let i=0;i<before.json.accessors.length;i++)assert.equal(sha(data(before,i)),sha(data(after,i)),'accessor '+i);
const inspection=await inspectModelUpload(normalized.bytes),budget=heroModelBudgetIssues(inspection),validator=createRequire(join(repo,'packages/shared/package.json'))('gltf-validator'),report=await validator.validateBytes(normalized.bytes,{uri:'astralym-idle-walk-256.glb',maxIssues:0,writeTimestamp:false});assert.equal(report.issues.numErrors,0);assert.equal(report.issues.truncated,false);assert.equal(budget.errors.length,0);
const put=(name:string,x:any)=>writeFileSync(join(out,name),JSON.stringify(x,null,2)+'\n',{flag:'wx'});writeFileSync(join(out,'astralym-idle-walk-256.glb'),normalized.bytes,{flag:'wx'});put('khronos-full.json',report);
const receipt={schema:'ggd-existing-normalizer-native-subset@1',source:{path:source,bytes:raw.length,sha256:sha(raw)},output:{path:join(out,'astralym-idle-walk-256.glb'),bytes:normalized.bytes.length,sha256:sha(normalized.bytes)},normalization:normalized.report,proof:{allAccessorSampleBytesIdentical:true,accessorCount:before.json.accessors.length,nodesSkinsMeshesAnimationsStructurallyIdentical:true,sourceClips:['Idle','Walk'],full58LibraryStillPreserved:true,retargetedOrProceduralClips:0},inspection:{triangles:inspection.triangles,drawPrimitives:inspection.meshes,joints:inspection.json.skins?.map(s=>s.joints.length),clips:inspection.clips,textures:inspection.textures},budget,khronos:{errors:report.issues.numErrors,warnings:report.issues.numWarnings,infos:report.issues.numInfos,truncated:report.issues.truncated},readiness:'shared-inspection-and-budget-passed; native Idle/Walk only; no hero definition or backend registration',modelVersionsPrepare:false};put('receipt.json',receipt);console.log(JSON.stringify({...receipt,inspection:{...receipt.inspection,textures:receipt.inspection.textures.length}},null,2));
