#!/usr/bin/env node
/**
 * Convert the AI-generated icon set to WebP at ICON_EDGE² and repoint every
 * content doc that references it. Idempotent and re-runnable: a second run is a
 * no-op, and a run after a fresh icon-gen batch converts only the new files.
 *
 * WHY: gzip is provably useless on PNG (measured 0.4% on this set), so nginx
 * cannot compress these no matter how gzip_types is configured — re-encoding is
 * the only lever that exists for the 16 MB the icon set costs. Nothing in the app
 * displays an icon larger than 54 CSS px (the login marquee portrait), i.e. 108
 * device px at DPR 2, so 128² is the smallest size that is still oversampled
 * everywhere it is used.
 *
 * SELECTION: files are picked by pixel dimensions read straight out of the PNG
 * IHDR — anything wider than ICON_EDGE. That cleanly selects the 169 AI-generated
 * 256² icons and never touches the 113 legacy 64² w3x icons, which are 1.13 MB
 * total, carry the alpha the ability-bar tiles rely on, and would gain nothing.
 *
 * ORIGINALS: the source PNG is archived to ARCHIVE_DIR before it is removed. That
 * directory is gitignored (`/data/**`), so it is a local working copy — the
 * durable copy is git history, where all 282 icons are committed. Regenerating
 * instead of restoring means re-running tools/icon-gen/local/batch.py against the
 * local Stable Diffusion pipeline, which is NOT deterministic across model and
 * driver versions: it would produce new art, not these images. Restore from the
 * archive or from git, never by regenerating.
 *
 * Usage:
 *   node tools/icon-gen/convert-webp.mjs [--dry-run] [--quality N] [--edge N]
 */
import { execFileSync } from "node:child_process";
import { existsSync, mkdirSync, readdirSync, readFileSync, statSync, unlinkSync, writeFileSync, copyFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const HERE = dirname(fileURLToPath(import.meta.url));
const REPO = join(HERE, "../..");
const ICON_DIR = join(REPO, "content/assets/icons");
const DOC_COLLECTIONS = ["champions", "abilities", "items"];

const args = process.argv.slice(2);
const flag = (name, fallback) => {
  const i = args.indexOf(name);
  return i === -1 ? fallback : Number(args[i + 1]);
};
const DRY = args.includes("--dry-run");
const EDGE = flag("--edge", 128);
const QUALITY = flag("--quality", 90);
const ARCHIVE_DIR = join(REPO, "data/icon-src-original");

/** PNG dimensions from the IHDR chunk (bytes 16..24). No image library needed. */
function pngSize(file) {
  const buf = readFileSync(file);
  if (buf.length < 24 || buf.readUInt32BE(0) !== 0x89504e47) return null;
  return { width: buf.readUInt32BE(16), height: buf.readUInt32BE(20) };
}

/**
 * Value of a PNG tEXt chunk, walking the chunk list. tools/icon-gen/local/batch.py
 * stamps `ggd_iconmethod` here to mark "generated by the current method"; WebP
 * cannot carry an arbitrary text key, so the marker has to move to a sidecar or
 * the next batch run treats all 169 icons as missing and re-renders them — hours
 * of GPU time producing NEW art that no longer matches what was approved.
 */
function pngText(buf, key) {
  let off = 8;
  while (off + 8 <= buf.length) {
    const len = buf.readUInt32BE(off);
    const type = buf.toString("latin1", off + 4, off + 8);
    if (type === "IEND") break;
    if (type === "tEXt") {
      const data = buf.subarray(off + 8, off + 8 + len);
      const nul = data.indexOf(0);
      if (nul !== -1 && data.toString("latin1", 0, nul) === key) {
        return data.toString("latin1", nul + 1);
      }
    }
    off += 12 + len;
  }
  return null;
}

const MARKER_KEY = "ggd_iconmethod";
const markerFor = (iconPath) => `${iconPath}.method`;

function iconFamilies() {
  return readdirSync(ICON_DIR).filter((d) => statSync(join(ICON_DIR, d)).isDirectory());
}

// ---- 1. select ------------------------------------------------------------
const targets = [];
for (const family of iconFamilies()) {
  for (const name of readdirSync(join(ICON_DIR, family))) {
    if (!name.endsWith(".png")) continue;
    const abs = join(ICON_DIR, family, name);
    const size = pngSize(abs);
    if (!size || size.width <= EDGE) continue; // legacy 64² set stays PNG
    targets.push({ family, name, abs, size, id: name.slice(0, -4) });
  }
}

const beforeBytes = targets.reduce((s, t) => s + statSync(t.abs).size, 0);
if (targets.length === 0) {
  // Not an early exit: the marker reconcile below still has work to do.
  console.log(`nothing to convert — no PNG wider than ${EDGE}px under content/assets/icons`);
} else {
  console.log(
    `converting ${targets.length} icons -> WebP ${EDGE}x${EDGE} q${QUALITY}` +
      `  (${beforeBytes.toLocaleString()} B before)${DRY ? "  [DRY RUN]" : ""}`,
  );
}

// ---- 2. encode ------------------------------------------------------------
/** content-relative "assets/icons/<family>/<id>.png" -> "...<id>.webp" */
const rewrites = new Map();
let afterBytes = 0;

for (const t of targets) {
  const outAbs = join(ICON_DIR, t.family, `${t.id}.webp`);
  const from = `assets/icons/${t.family}/${t.id}.png`;
  const to = `assets/icons/${t.family}/${t.id}.webp`;
  rewrites.set(from, to);

  if (DRY) continue;

  const archived = join(ARCHIVE_DIR, t.family, t.name);
  mkdirSync(dirname(archived), { recursive: true });
  if (!existsSync(archived)) copyFileSync(t.abs, archived);

  const marker = pngText(readFileSync(t.abs), MARKER_KEY);
  execFileSync("cwebp", ["-quiet", "-q", String(QUALITY), "-resize", String(EDGE), String(EDGE), t.abs, "-o", outAbs]);
  if (marker !== null) writeFileSync(markerFor(outAbs), `${marker}\n`);
  afterBytes += statSync(outAbs).size;
  unlinkSync(t.abs);
}

// ---- 2b. reconcile generator markers -------------------------------------
// Self-healing: carry the tEXt marker off any archived original whose WebP is
// missing its sidecar (e.g. converted before this step existed).
let markersBackfilled = 0;
if (!DRY && existsSync(ARCHIVE_DIR)) {
  for (const family of readdirSync(ARCHIVE_DIR)) {
    const famDir = join(ARCHIVE_DIR, family);
    if (!statSync(famDir).isDirectory()) continue;
    for (const name of readdirSync(famDir)) {
      if (!name.endsWith(".png")) continue;
      const webp = join(ICON_DIR, family, `${name.slice(0, -4)}.webp`);
      if (!existsSync(webp) || existsSync(markerFor(webp))) continue;
      const marker = pngText(readFileSync(join(famDir, name)), MARKER_KEY);
      if (marker === null) continue;
      writeFileSync(markerFor(webp), `${marker}\n`);
      markersBackfilled += 1;
    }
  }
}
if (markersBackfilled) console.log(`generator markers backfilled: ${markersBackfilled}`);

// ---- 3. repoint the docs --------------------------------------------------
// Driven off the converted-file map only, never a blanket regex: a bare
// s/.png/.webp/ over content/ would also corrupt model paths, texture paths and
// prose. Replaces the whole quoted literal so JSON formatting is untouched.
let docsChanged = 0;
let refsChanged = 0;
for (const collection of DOC_COLLECTIONS) {
  const dir = join(REPO, "content", collection);
  if (!existsSync(dir)) continue;
  for (const file of readdirSync(dir)) {
    if (!file.endsWith(".json") || file.startsWith("_")) continue;
    const abs = join(dir, file);
    const before = readFileSync(abs, "utf-8");
    let after = before;
    for (const [from, to] of rewrites) {
      const needle = `"${from}"`;
      if (!after.includes(needle)) continue;
      refsChanged += after.split(needle).length - 1;
      after = after.split(needle).join(`"${to}"`);
    }
    if (after === before) continue;
    docsChanged += 1;
    if (!DRY) writeFileSync(abs, after);
  }
}

const pct = beforeBytes ? ((afterBytes / beforeBytes) * 100).toFixed(2) : "0";
if (docsChanged) console.log(`docs repointed: ${docsChanged} files, ${refsChanged} icon refs`);
if (!DRY && targets.length > 0) {
  console.log(
    `bytes: ${beforeBytes.toLocaleString()} -> ${afterBytes.toLocaleString()} ` +
      `(${pct}% of raw, saved ${(beforeBytes - afterBytes).toLocaleString()} B)`,
  );
  console.log(`originals archived to ${ARCHIVE_DIR} (gitignored; durable copy is git history)`);
  console.log("next: pnpm content:build");
}
