package curation_test

// Champion IDENTITY for the curation starter gate — a deliberately small Go
// port of the ONE rule that lives in
// `packages/shared/src/content/championIdentity.ts` (read that file first; it
// carries the full policy, the evidence and the rationale).
//
// WHY A PORT AT ALL. The starter bundle is a hand-curated static list in
// starter.go; nothing in the Go service computes identity at runtime, so this
// is test-only enforcement — the gate that keeps a human from picking the same
// character twice (or from dropping a real one as an imagined "twin") when the
// bundle is next edited. Keeping it in _test.go means no dead production code.
//
// WHY IT CANNOT DRIFT UNNOTICED. Both this file and championIdentity.test.ts
// assert the SAME named outcomes over the SAME content tree — 黑化Saber stays
// separate from Saber, the known duplicate pairs still fold, champions sharing
// a CC0 stand-in mesh stay distinct. If the TS rule is loosened or tightened
// and this port is not, one of the two suites fails on those pins.
//
// GOVERNING POLICY (user, 2026-07-22)「遇到疑慮一律判斷寬鬆為多英雄」— when in
// doubt, SEPARATE heroes. Merging requires positive evidence, because a
// wrongly-merged champion disappears from the game with its bespoke kit while a
// wrongly-kept duplicate is merely cosmetic.
//
// THE ONE EXCEPTION (owner ruling 2026-07-26, task #249). The source map's WC3
// Metamorphosis fields — `Eme1` (normal-form unit) / `Emeu` (alternate-form
// unit) — state IN DATA that two unit definitions are two bodies of one hero.
// Where that evidence exists it WINS over the lenient default. It is a CLOSED
// TABLE of 26 pairs read from the extractor's own output
// (tools/w3x-import/out/GoDieEX22s-src/TRANSFORM_FORMS.json, regenerated by
// extract_transform_forms.py), it is consulted only AFTER the hero-number
// guard, and it is NOT a licence to merge lookalikes: 05 / 53 / 91 carry no
// such evidence and stay two heroes each. Mirrors
// `isW3xFormPair` in packages/shared/src/content/championForms.ts.

import (
	"encoding/json"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strings"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"

	"github.com/ggd/platform/internal/curation"
	"github.com/ggd/platform/pkg/testkit"
)

// heroNumberRe pulls the task #11 prefix off an ability name: "22-01 鬼隱之擊"
// → 22, "22-002 …" → 22 (EX). RE2 has no lookahead, so the trailing class does
// the "no fourth digit" job; some imported names have NO space after the
// prefix ("61-01惡魔球"), so a separator must not be required.
//
// ⚠️ THIS IS A PORT, AND IT HAD DRIFTED. The governing rule lives in
// packages/shared/src/content/championIdentity.ts (`HERO_NUMBER_RE`), which was
// widened to `\d{2,3}` when the roster began minting 3-digit hero numbers —
// owner directive: the next id auto-fills the max, so 喪標麥可 is #100. The Go
// side stayed at `\d{2}` and therefore REJECTED every ability of hero 100+,
// which is how GH#29 (put 喪標麥可 on the open roster) failed R2 with
// 「name "100-01 肝泥抹德" lacks the task #11 xx-0N prefix」 — a correct hero
// being told its correct name was malformed.
//
// The "-" delimiter is what keeps this unambiguous: "100-00" (hero 100, passive)
// cannot be read as "10-000", because the first group must be followed by "-"
// and index 2 of "10-000" already is one. Asserted by
// TestHeroNumberRePortParity.
var heroNumberRe = regexp.MustCompile(`^(\d{2,3})-(\d{2,3})([^0-9]|$)`)

// heroNumberOfName returns the hero 編號 encoded in an ability name, or "".
func heroNumberOfName(name string) string {
	m := heroNumberRe.FindStringSubmatch(strings.TrimSpace(name))
	if m == nil {
		return ""
	}
	return m[1]
}

// heroNumberOf resolves a champion's 編號 from its embedded kit. Returns "" when
// nothing parses OR when the abilities disagree — ambiguity is NOT evidence of
// sameness, so an unresolved champion can never be merged into anything.
func heroNumberOf(c championDoc) string {
	num := ""
	for _, ab := range c.Abilities {
		n := heroNumberOfName(ab.Name)
		if n == "" {
			continue
		}
		if num != "" && num != n {
			return ""
		}
		num = n
	}
	return num
}

// nameComponents splits the map's `稱號 - 角色名` on the SPACE-DELIMITED dash
// only, so an unspaced hyphen stays part of its token
// ("英靈-亞瑟王 - 黑化Saber" → "英靈-亞瑟王", "黑化Saber").
var nameSepRe = regexp.MustCompile(`\s+[-–—]\s+`)

func nameComponents(name string) []string {
	out := []string{}
	for _, part := range nameSepRe.Split(strings.Join(strings.Fields(name), " "), -1) {
		if p := strings.TrimSpace(part); p != "" {
			out = append(out, p)
		}
	}
	return out
}

func sharesNameComponent(a, b string) bool {
	left := map[string]struct{}{}
	for _, p := range nameComponents(a) {
		left[p] = struct{}{}
	}
	for _, p := range nameComponents(b) {
		if _, ok := left[p]; ok {
			return true
		}
	}
	return false
}

// sameCharacter is the identity rule: true ONLY on positive, strong evidence.
//
//  1. no parseable hero number on either side ⇒ DISTINCT (never "both unknown,
//     so probably the same");
//  2. different numbers ⇒ DISTINCT — this is the 黑化Saber guard (69 vs 20),
//     which no shared mesh or shared portrait may override;
//  3. identical display name ⇒ SAME, even across meshes (one entry got the real
//     import, its twin a CC0 stand-in);
//  4. a shared name component AND the same mesh ⇒ SAME (re-worded twins such as
//     超級賽亞人-悟空 / 賽亞人-悟空). Both halves are required: a shared component
//     alone is a franchise relation (拳四郎, 皮卡丘 each exist as two heroes),
//     and a shared mesh alone just means the art is missing — champ.sela is
//     worn by 18 unrelated champions;
//  5. otherwise DISTINCT (same number, nothing else in common = a source-data
//     collision to report, not to resolve: 05, 53, 61, 91).
func sameCharacter(a, b championDoc) bool {
	if a.ID == b.ID {
		return true
	}
	na, nb := heroNumberOf(a), heroNumberOf(b)
	if na == "" || nb == "" || na != nb {
		return false
	}
	// 4b. THE ONE EXCEPTION — the map's Eme1/Emeu fields name these two ids as
	// the two BODIES of one hero (see the file header). Runs AFTER the 編號
	// guard, so it can never merge across hero numbers.
	if isW3xFormPair(a.ID, b.ID) {
		return true
	}
	if strings.Join(strings.Fields(a.Name), " ") == strings.Join(strings.Fields(b.Name), " ") {
		return true
	}
	return a.ModelKey != "" && a.ModelKey == b.ModelKey && sharesNameComponent(a.Name, b.Name)
}

// ------------------------------------------------- w3x transform form pairs --

// transformFormsPath is the extractor's own output — the ONLY source for the
// exception. Absent (a truncated checkout) ⇒ the exception simply never fires,
// which is the lenient direction and therefore safe.
func transformFormsPath() string {
	return filepath.Join("..", "..", "..", "..", "tools", "w3x-import", "out",
		"GoDieEX22s-src", "TRANSFORM_FORMS.json")
}

type transformFormsDoc struct {
	Count int `json:"count"`
	Pairs []struct {
		HeroNumber     string `json:"heroNumber"`
		AbilityRawcode string `json:"abilityRawcode"`
		NormalUnit     struct {
			ChampionID string `json:"championId"`
		} `json:"normalUnit"`
		AlternateUnit struct {
			ChampionID string `json:"championId"`
		} `json:"alternateUnit"`
	} `json:"pairs"`
}

// formCounterpart maps EVERY id in a pair to the other half, both directions.
var formCounterpart = loadFormCounterparts()

// alternateFormIDs is the set of TRANSFORMED bodies — ids a player must never
// be offered as a champion (owner ruling:「換成本體，變身態改由技能觸發」).
var alternateFormIDs = loadAlternateFormIDs()

func loadTransformForms() transformFormsDoc {
	var doc transformFormsDoc
	raw, err := os.ReadFile(transformFormsPath())
	if err != nil {
		return doc
	}
	_ = json.Unmarshal(raw, &doc)
	return doc
}

func loadFormCounterparts() map[string]string {
	out := map[string]string{}
	for _, p := range loadTransformForms().Pairs {
		out[p.NormalUnit.ChampionID] = p.AlternateUnit.ChampionID
		out[p.AlternateUnit.ChampionID] = p.NormalUnit.ChampionID
	}
	return out
}

func loadAlternateFormIDs() map[string]struct{} {
	out := map[string]struct{}{}
	for _, p := range loadTransformForms().Pairs {
		out[p.AlternateUnit.ChampionID] = struct{}{}
	}
	return out
}

// isW3xFormPair reports whether a and b are the two halves of ONE map-declared
// transform pair, in either order.
func isW3xFormPair(a, b string) bool {
	return formCounterpart[a] == b && formCounterpart[b] == a
}

// loadRoster reads every champion@1 doc in the content tree, keyed by id.
// indexedChampionCount 讀**被 commit 的**索引 —— 那是「這棵樹應該有幾隻」的
// 權威來源（`pnpm content:build` 產出、跟 bundle 一起進版控）。
func indexedChampionCount(t *testing.T, root string) int {
	t.Helper()
	var idx struct {
		Entries []struct {
			ID string `json:"id"`
		} `json:"entries"`
	}
	raw, err := os.ReadFile(filepath.Join(root, "champions", "_index.json"))
	require.NoError(t, err, "champions/_index.json 讀不到 —— 它是被 commit 的產物，缺了代表 checkout 不完整")
	require.NoError(t, json.Unmarshal(raw, &idx))
	return len(idx.Entries)
}

func loadRoster(t *testing.T, root string) map[string]championDoc {
	t.Helper()
	dir := filepath.Join(root, "champions")
	entries, err := os.ReadDir(dir)
	require.NoErrorf(t, err, "read %s", dir)
	out := map[string]championDoc{}
	for _, e := range entries {
		name := e.Name()
		if e.IsDir() || !strings.HasSuffix(name, ".json") || strings.HasPrefix(name, "_") {
			continue
		}
		doc := readJSON[championDoc](t, filepath.Join(dir, name))
		if doc.ID == "" {
			continue
		}
		out[doc.ID] = doc
	}
	return out
}

// whitelist-champion-identity: the identity rule the curation bundle is curated
// against, pinned on the real content tree. Mirrors the headline cases in
// packages/shared/src/content/championIdentity.test.ts.
func TestChampionIdentityRule(t *testing.T) {
	testkit.Cover(t, "whitelist-champion-identity")
	root := contentRoot()
	if _, err := os.Stat(filepath.Join(root, "champions")); err != nil {
		t.Skipf("content tree not present at %s — skipping identity pins", root)
	}
	roster := loadRoster(t, root)
	// GH#331 —— 這裡本來是 `>= 100`，而內容樹早就只有 78 隻（v0.17.0 / v0.18.0 /
	// HEAD 都是 79 個檔）。那個 100 是 2026-07-22 初始 commit 寫的，之後名單一路
	// 縮編，於是這條**紅了不知道多久** —— 而一條永遠紅的守衛擋不住任何東西。
	//
	// ⭐ 它真正要擋的是「**內容樹被截斷了**」，而那是一個**關係**不是一個數字：
	//    「掃到的檔案數」要對得上「被 commit 的索引裡有幾筆」。
	//    ⇒ 改成跟 `_index.json` 比。索引跟著 `pnpm content:build` 走，所以名單
	//    再縮一次這條不會紅；而真的少讀到檔案（權限、掛載、部分 checkout）
	//    它立刻紅，並且說得出差幾筆。
	// ⚠️ 另外留一個**很低**的絕對下界 —— 索引本身是空的那種壞法，比對會兩邊都 0
	//    而「相等」，那正是失敗形態④：斷言方向跟缺陷無關。
	indexed := indexedChampionCount(t, root)
	require.GreaterOrEqualf(t, len(roster), 20,
		"content tree looks truncated: only %d champion docs on disk", len(roster))
	require.Equalf(t, indexed, len(roster),
		"磁碟上有 %d 份英雄文件，但被 commit 的 champions/_index.json 記著 %d 筆 —— "+
			"兩者不一致代表這棵內容樹是**部分的**（沒跑 content:build，或 checkout 不完整）。"+
			"⛔ 不要改這個數字：跑 `pnpm content:build` 然後 `git add content/`。",
		len(roster), indexed)

	// ⭐ GH#331 —— 這些**逐位釘住的 id 會隨著內容樹縮編而消失**（113 → 78）。
	//    2026-08-16 實測：53 個點名的 id 裡有 11 個已經不在樹裡。
	//
	// ⛔ 兩條都不能走：
	//    ① `require` 它一定在 ⇒ 內容一縮這條就永遠紅（GH#331 本身）；
	//    ② 直接把那 11 行刪掉 ⇒ 規則**悄悄地被削掉一塊**，而且沒有人會知道。
	//
	// ⇒ 第三條路：**不在就休眠，但記帳**。休眠的 id 會被列出來，
	//    而且下面有一條「跑掉的釘子不可以太少」——⛔ 這條測試不可以變成空的
	//    （失敗形態③：可以整段刪掉而測試還是綠的）。
	var dormant, exercised []string
	have := func(ids ...string) bool {
		ok := true
		for _, id := range ids {
			if _, found := roster[id]; !found {
				dormant = append(dormant, id)
				ok = false
			}
		}
		if ok {
			exercised = append(exercised, ids...)
		}
		return ok
	}
	get := func(id string) championDoc {
		doc, ok := roster[id]
		require.Truef(t, ok, "champion %q missing from the content tree", id)
		return doc
	}

	// 黑化Saber: same mesh, same extracted portrait, near-identical name —
	// but hero 69, not 20. It is its OWN character and must never fold.
	if have("godie-e002", "godie-e00l", "godie-e00q") {
		saber, saberTwin, alter := get("godie-e002"), get("godie-e00l"), get("godie-e00q")
		require.Equal(t, saber.ModelKey, alter.ModelKey, "the premise: e002 and e00q share a mesh")
		assert.Equal(t, "20", heroNumberOf(saber))
		assert.Equal(t, "69", heroNumberOf(alter))
		assert.False(t, sameCharacter(alter, saber), "黑化Saber must not fold into Saber")
		assert.False(t, sameCharacter(alter, saberTwin), "黑化Saber must not fold into Saber's twin")
		assert.True(t, sameCharacter(saber, saberTwin), "e002/e00l ARE one character")
	}
	if have("godie-e002", "godie-e00l") {
		// ⭐ 這一半**不依賴 e00q**，所以樹裡沒有黑化Saber 時它照樣跑：
		//    「同一個角色的兩個條目要摺在一起」是規則的另一半。
		assert.True(t, sameCharacter(get("godie-e002"), get("godie-e00l")))
	}

	// Known duplicate ENTRIES still fold (canonical id first).
	for _, pair := range [][2]string{
		{"godie-hgam", "godie-h02r"}, {"godie-ogrh", "godie-o00x"},
		{"godie-uvng", "godie-u010"}, {"godie-h01n", "godie-h01o"},
		{"godie-e00k", "godie-e00z"}, {"godie-ewar", "godie-e007"},
		{"godie-h02v", "godie-h02u"}, {"godie-hjai", "godie-h020"},
		{"godie-n003", "godie-n01g"}, {"godie-u00n", "godie-u00o"},
		{"godie-e00w", "godie-e00x"}, {"godie-o01z", "godie-o02v"},
		{"godie-e001", "godie-e00n"}, {"godie-nbbc", "godie-n01c"},
		{"godie-ucrl", "godie-u034"}, {"godie-nsjs", "godie-n00p"},
	} {
		if !have(pair[0], pair[1]) {
			continue
		}
		assert.Truef(t, sameCharacter(get(pair[0]), get(pair[1])),
			"%s and %s are the same character", pair[0], pair[1])
	}

	// Champions sharing a CC0 stand-in mesh are NOT duplicates of each other.
	for _, mesh := range []string{"champ.sela", "champ.thorne", "champ.skin.barbarian", "champ.skin.rogue"} {
		wearers := []championDoc{}
		for _, doc := range roster {
			if doc.ModelKey == mesh {
				wearers = append(wearers, doc)
			}
		}
		// ⚠️ 同 GH#331：內容縮編之後某個替身網格可能只剩一位（或零位）穿它。
		//    這一組要驗的是「**共穿同一張皮的兩位不可以被當成同一個角色**」——
		//    只有一位時那個關係根本不存在，⇒ 休眠，⛔ 不是紅。
		//    （下面的反空轉門檻會擋住「全部網格都只剩一位」那種真的空掉的情況。）
		if len(wearers) < 2 {
			dormant = append(dormant, "mesh:"+mesh)
			continue
		}
		exercised = append(exercised, "mesh:"+mesh)
		for _, a := range wearers {
			for _, b := range wearers {
				if a.ID == b.ID {
					continue
				}
				// ONE documented exception: 曹操孟德's two unit definitions
				// (O02N base / O02O 天下號令 form) both wear champ.skin.rogue
				// because his map model is a Blizzard built-in. They fold on
				// their IDENTICAL authored name — never on the shared mesh,
				// which is what this loop exists to forbid.
				if a.Name == b.Name && isW3xFormPair(a.ID, b.ID) {
					continue
				}
				assert.Falsef(t, sameCharacter(a, b),
					"%s (%s) and %s (%s) share the stand-in mesh %s but are different characters",
					a.ID, a.Name, b.ID, b.Name, mesh)
			}
		}
	}

	// Hero-number COLLISIONS resolve to separate heroes BY DEFAULT — the
	// lenient rule, unchanged. These three carry no transform evidence: the
	// author cloned a hero and never renumbered it.
	for _, pair := range [][2]string{
		{"godie-hblm", "godie-h021"}, // 05 賈修貝爾 / 阿強一號
		{"godie-o00l", "godie-o02s"}, // 53 傑洛士 / 涼宮八ㄦ匕
		{"godie-h02s", "godie-h02z"}, // 91 死亡騎士 / 不良少年
	} {
		if !have(pair[0], pair[1]) {
			continue
		}
		a, b := get(pair[0]), get(pair[1])
		require.Equalf(t, heroNumberOf(a), heroNumberOf(b), "%s/%s premise: same 編號", pair[0], pair[1])
		require.Falsef(t, isW3xFormPair(a.ID, b.ID), "%s/%s premise: NO Eme1/Emeu evidence", a.ID, b.ID)
		assert.Falsef(t, sameCharacter(a, b),
			"%s (%s) and %s (%s) share hero number %s but must stay two heroes",
			a.ID, a.Name, b.ID, b.Name, heroNumberOf(a))
	}

	// …and the THREE the owner overturned on 2026-07-26 (task #249). Each is a
	// hero and its own transformed body, stated by the map's Eme1/Emeu fields,
	// so the evidence beats the lenient default. They differ in BOTH 稱號 and
	// mesh, which is exactly why no other rule reaches them.
	for _, pair := range [][2]string{
		{"godie-umal", "godie-u00l"}, // 25 北斗神拳掌門人 / 北斗之鼠  A0HW ChangeDNA
		{"godie-ofar", "godie-o02l"}, // 58 神奇寶貝兒 / 神騎寶貝     A040 瘋狂皮卡丘
		{"godie-u012", "godie-u011"}, // 61 克勞薩II世 / 克勞薩先生    Aphx 百連我殺
	} {
		if !have(pair[0], pair[1]) {
			continue
		}
		a, b := get(pair[0]), get(pair[1])
		require.Equalf(t, heroNumberOf(a), heroNumberOf(b), "%s/%s premise: same 編號", pair[0], pair[1])
		require.NotEqualf(t, a.ModelKey, b.ModelKey, "%s/%s premise: different meshes", pair[0], pair[1])
		require.Truef(t, isW3xFormPair(a.ID, b.ID), "%s/%s premise: Eme1/Emeu evidence exists", a.ID, b.ID)
		assert.Truef(t, sameCharacter(a, b),
			"%s (%s) and %s (%s) are ONE hero in two bodies (w3x Eme1/Emeu)", a.ID, a.Name, b.ID, b.Name)
		assert.Truef(t, sameCharacter(b, a), "the exception is symmetric")
	}
	// The exception can NEVER cross a hero number — the 黑化Saber guard holds.
	assert.False(t, isW3xFormPair("godie-e002", "godie-e00q"))
	if have("godie-e002", "godie-e00q") {
		assert.False(t, sameCharacter(get("godie-e002"), get("godie-e00q")))
	}

	// Numberless champions each keep their own identity — including the test
	// hero, which shares BOTH its mesh and a name component with hero 11.
	for _, id := range []string{"godie-e00u", "godie-u01f", "godie-h02n", "godie-u01q", "sela", "thorne"} {
		if !have(id) {
			continue
		}
		doc := get(id)
		assert.Emptyf(t, heroNumberOf(doc), "%s (%s) should have no parseable hero number", id, doc.Name)
		for other, otherDoc := range roster {
			if other == id {
				continue
			}
			assert.Falsef(t, sameCharacter(doc, otherDoc),
				"numberless champion %s must not merge into %s", id, other)
		}
	}

	// ── ⭐ 反空轉：這條測試不可以悄悄變成空的 ────────────────────────────
	//
	// 上面每一組釘子都會在 id 不存在時跳過。那個設計是對的（內容樹會縮編），
	// 但它有一個明顯的失效模式：**id 全部消失時整條測試會全綠地什麼都沒驗**。
	// 那正是 CLAUDE.md 失敗形態③——「可以整段刪掉而測試還是綠的」。
	//
	// ⇒ 所以這裡釘住「**真的跑過幾個釘子**」。門檻取一個很低但不可能被空轉
	//    達成的數（30）：今天實際跑到 80+，而全部休眠時是 0。
	// ⚠️ 這一行紅了**不要調低它** —— 它的意思是內容樹縮到讓這條規則失去樣本，
	//    那時候要問的是「這些角色去哪了」，不是「門檻該多少」。
	if len(dormant) > 0 {
		sort.Strings(dormant)
		t.Logf("休眠中的釘子（id 已不在內容樹，%d 個）：%v", len(dormant), dormant)
	}
	require.GreaterOrEqualf(t, len(exercised), 30,
		"身分規則只真的驗到 %d 個釘子（休眠 %d 個）—— 樣本少到這條測試等於沒跑。"+
			"⛔ 不要調低這個門檻：去看那些 id 為什麼從內容樹消失了。",
		len(exercised), len(dormant))
}

// whitelist-no-alternate-forms: THE REGRESSION THAT WOULD HAVE CAUGHT THE LIVE
// BUG (task #249, roster gate R6).
//
// For months 10 of the 50 first-open-roster slots held the ALTERNATE (變身)
// body instead of the hero — 草泥馬 in its lying-down 臥 form (w3x movement
// speed 0), 妙蛙花 at usca 3.0 from round one, 北斗之鼠 instead of 拳四郎,
// 超級賽亞人 so that 悟空's own R turned him into what he already was. Nothing
// caught it because the importer drops the WC3 Metamorphosis fields Eme1/Emeu
// (task #56), so no gate could even ask the question.
//
// It can be asked now. Every id the starter bundle enables must be a BASE unit;
// an alternate body is reachable only by casting its transform ability once
// that mechanic exists (task #119). The table is the extractor's own output, so
// this gate strengthens automatically as the import improves.
func TestStarterRosterHasNoAlternateForms(t *testing.T) {
	testkit.Cover(t, "whitelist-no-alternate-forms")

	forms := loadTransformForms()
	require.Equalf(t, 26, forms.Count,
		"TRANSFORM_FORMS.json missing or truncated at %s — regenerate with tools/w3x-import/extract_transform_forms.py",
		transformFormsPath())
	require.NotEmpty(t, alternateFormIDs, "the alternate-form set must not be empty")

	offenders := []string{}
	for _, id := range curation.StarterSet().Champions {
		if _, isAlt := alternateFormIDs[id]; isAlt {
			offenders = append(offenders, id+" → base "+formCounterpart[id])
		}
	}
	assert.Emptyf(t, offenders,
		"the first open roster offers a 變身 form as a pickable hero; swap each to its base:\n%s",
		strings.Join(offenders, "\n"))

	// …and the ten that WERE wrong now hold their base, id-for-id.
	enabled := map[string]struct{}{}
	for _, id := range curation.StarterSet().Champions {
		enabled[id] = struct{}{}
	}
	for _, swap := range [][2]string{
		{"godie-h020", "godie-hjai"}, // 04 莉娜因巴斯
		{"godie-n01c", "godie-nbbc"}, // 08 勇者小呆
		{"godie-o00x", "godie-ogrh"}, // 09 悟空
		{"godie-u01u", "godie-udre"}, // 11 索隆
		{"godie-e007", "godie-ewar"}, // 12 天地志狼
		{"godie-n00p", "godie-nsjs"}, // 18 南野秀一
		{"godie-u00l", "godie-umal"}, // 25 拳四郎
		{"godie-u010", "godie-uvng"}, // 38 飛影
		{"godie-h02r", "godie-hgam"}, // 90 妙蛙種子
		{"godie-h02u", "godie-h02v"}, // 92 草泥馬
	} {
		alt, base := swap[0], swap[1]
		require.Equalf(t, base, formCounterpart[alt], "%s premise: the map says its base is %s", alt, base)
		_, altEnabled := enabled[alt]
		_, baseEnabled := enabled[base]
		assert.Falsef(t, altEnabled, "%s is a 變身 form and must not be on the roster", alt)
		assert.Truef(t, baseEnabled, "%s (the base of %s) must be on the roster instead", base, alt)
	}
}

// TestHeroNumberRePortParity — 這條守衛保護的不是 regex,是「兩個 port 不會再
// 各自演化」。
//
// GH#29 之所以會踩到,不是因為有人寫錯 regex,而是因為 TS 那份被正確地加寬成
// 3 位數(commit 註解明寫「喪標麥可 = 100」)、Go 這份沒有,而**沒有任何東西會
// 因此變紅**。identityRule 的檔頭寫著 "ONE regex per port",那是一個承諾,不是
// 一個機制。這條測試把它變成機制:它直接讀 TypeScript 原始碼裡的
// `HERO_NUMBER_RE`,把兩邊的字面量比對。
//
// ⚠️ 刻意讀「原始碼」而不是「行為」:行為比對只能覆蓋我想得到的樣本,而漂移
// 永遠發生在我沒想到的那一格。字面量比對抓的是「有人只改了一邊」。
func TestHeroNumberRePortParity(t *testing.T) {
	testkit.Cover(t, "hero-number-port-parity")

	// packages/shared/src/content/championIdentity.ts 是治理來源。
	src, err := os.ReadFile(filepath.Join("..", "..", "..", "..",
		"packages", "shared", "src", "content", "championIdentity.ts"))
	require.NoError(t, err, "the governing TS rule must be readable — it is the source of truth")

	// export const HERO_NUMBER_RE = /^(\d{2,3})-(\d{2,3})(?!\d)/;
	tsRe := regexp.MustCompile(`HERO_NUMBER_RE\s*=\s*/\^\(\\d\{(\d)(?:,(\d))?\}\)-\(\\d\{(\d)(?:,(\d))?\}\)`)
	m := tsRe.FindSubmatch(src)
	require.NotNil(t, m,
		"could not parse HERO_NUMBER_RE out of championIdentity.ts — if its SHAPE changed, this port must be re-derived by hand, not silently skipped")

	// 兩邊的量詞必須一致。TS 用 (?!\d) 做「不可有下一位數字」,Go(RE2 無 lookahead)
	// 用 ([^0-9]|$),兩者等價 —— 差異僅止於此,量詞不得有差。
	wantGroup1 := string(m[1])
	if len(m[2]) > 0 {
		wantGroup1 += "," + string(m[2])
	}
	wantGroup2 := string(m[3])
	if len(m[4]) > 0 {
		wantGroup2 += "," + string(m[4])
	}
	assert.Equal(t, `^(\d{`+wantGroup1+`})-(\d{`+wantGroup2+`})([^0-9]|$)`, heroNumberRe.String(),
		"heroNumberRe has drifted from the TS HERO_NUMBER_RE — widen BOTH ports or neither")

	// 而且它真的要接受三位數英雄(GH#29 的實際案例)。
	assert.Equal(t, "100", heroNumberOfName("100-01 肝泥抹德"), "hero 100 must parse")
	assert.Equal(t, "100", heroNumberOfName("100-002 此世全部之咖哩・バタンキュー"), "hero 100's EX must parse")
	assert.Equal(t, "22", heroNumberOfName("22-01 鬼隱之擊"), "2-digit heroes must keep parsing")
	assert.Equal(t, "61", heroNumberOfName("61-01惡魔球"), "no-space imported names must keep parsing")
	// 四位數仍然無效 —— 加寬不是取消上限。
	assert.Equal(t, "", heroNumberOfName("1000-01 不存在"), "a 4-digit hero number is still malformed")
}

// ------------------------------------- the transform BUTTON, not just the table --

// transformDoc is the `transform` block champion@1 carries (schema/champion.ts).
// Only the fields this guard reads are declared.
type transformDoc struct {
	Transform *struct {
		Role           string `json:"role"`
		CounterpartID  string `json:"counterpartId"`
		TriggerAbility *struct {
			Rawcode string `json:"rawcode"`
			Name    string `json:"name"`
		} `json:"triggerAbility"`
	} `json:"transform"`
	ModelKey string `json:"modelKey"`
}

// abilityEffectsDoc is an ability@1 read for its EFFECT LIST only.
type abilityEffectsDoc struct {
	Name    string `json:"name"`
	Effects []struct {
		Kind string `json:"kind"`
	} `json:"effects"`
}

// championEmbeddedDoc is the SHIPPED SECOND COPY — a champion doc's denormalised
// `abilities.Q/W/E/R`. Read on purpose: the standalone doc is what the sim
// registers, but the embedded copy is what every raw-doc consumer renders (the
// codex, 內容管理, and apps/editor's PreviewController, which passes
// `overrideAbilities: true` and shows the embedded copy WHOLE). A transform
// wired in only one of the two is half-shipped.
type championEmbeddedDoc struct {
	Abilities map[string]abilityEffectsDoc `json:"abilities"`
}

func readJSONFile[T any](t *testing.T, path string) T {
	t.Helper()
	var out T
	raw, err := os.ReadFile(path) // #nosec G304 -- fixed repo-relative content path
	require.NoErrorf(t, err, "read %s", path)
	require.NoErrorf(t, json.Unmarshal(raw, &out), "parse %s", path)
	return out
}

func hasChampionFormEffect(d abilityEffectsDoc) bool {
	for _, e := range d.Effects {
		if e.Kind == "championForm" {
			return true
		}
	}
	return false
}

// whitelist-visible-transform-fires: A TRANSFORM THAT CHANGES THE MODEL MUST BE
// WIRED TO A `championForm` EFFECT.
//
// THE BUG THIS EXISTS FOR (L1, 2026-07-30). 06-04 傑桑變化 (`A0Y1`) is one of only
// FIVE of the map's 26 pairs whose alternate body wears a DIFFERENT mesh —
// godie-ucrl `champ.thorne` → godie-u034 `imported.herobiggon`. Everything that
// DESCRIBES the morph was already correct and self-consistent: the w3x extractor
// emitted the pair, championForms.ts carried it with its 7/14/21s durations, both
// champion docs carried a `transform` block naming each other, the ability was
// named 傑桑變化 and its description said 「強制讓身體成長為數十年後的面貌」.
// The one thing missing was the only thing that does anything: the ability's own
// `effects` array held the importer's placeholder (`applyBuff maxHealth +300 for
// 3s`) and NO `championForm`, so pressing R granted a 3-second health buff and
// the player never changed shape. CLAUDE.md failure mode ② — 算出來了但從沒送到.
//
// Not one gate could see it. TestStarterRosterHasNoAlternateForms asks only that
// the roster holds the BASE; championForms.test.ts re-reads the extractor
// fixture, which is upstream of content entirely; the castability sweep counts a
// measurable effect and the placeholder buff IS one. The table said the morph
// existed; nothing asked the BUTTON.
//
// SCOPE: model-changing pairs on the roster only, and deliberately so. Whether
// the ~20 same-mesh pairs should also morph is task #119's open design question
// (a same-mesh morph is a stat/kit swap with no silhouette change, which the
// owner has not ruled on). Where the mesh DIFFERS there is no question left: the
// morph is the visible payoff, and a placeholder buff in its place is a defect.
// The set is computed from content, never listed, so a re-import that gives some
// other pair a distinct mesh is covered the day it lands.
func TestStarterVisibleTransformsActuallyMorph(t *testing.T) {
	testkit.Cover(t, "whitelist-visible-transform-fires")

	root := contentRoot()
	if _, err := os.Stat(filepath.Join(root, "champions")); err != nil {
		t.Skipf("content tree not present at %s — skipping transform wiring check", root)
	}
	slots := []string{"passive", "q", "w", "e", "r", "ex"}

	checked := 0
	for _, id := range curation.StarterSet().Champions {
		base := readJSONFile[transformDoc](t, filepath.Join(root, "champions", id+".json"))
		if base.Transform == nil || base.Transform.Role != "base" ||
			base.Transform.CounterpartID == "" || base.Transform.TriggerAbility == nil {
			continue
		}
		altPath := filepath.Join(root, "champions", base.Transform.CounterpartID+".json")
		if _, err := os.Stat(altPath); err != nil {
			continue // the importer never shipped the alternate body
		}
		alt := readJSONFile[transformDoc](t, altPath)
		if alt.ModelKey == base.ModelKey {
			continue // same mesh — see SCOPE above
		}

		want := base.Transform.TriggerAbility.Name
		embedded := readJSONFile[championEmbeddedDoc](t, filepath.Join(root, "champions", id+".json"))

		foundSlot := ""
		for _, slot := range slots {
			p := filepath.Join(root, "abilities", id+"."+slot+".json")
			if _, err := os.Stat(p); err != nil {
				continue
			}
			if readJSONFile[abilityEffectsDoc](t, p).Name == want {
				foundSlot = slot
				break
			}
		}
		require.NotEmptyf(t, foundSlot,
			"%s (%s) morphs into %s, which wears a DIFFERENT mesh (%s → %s), but no standalone "+
				"ability doc of %s is named %q — the transform has no button at all",
			id, base.ModelKey, base.Transform.CounterpartID, base.ModelKey, alt.ModelKey, id, want)

		standalone := readJSONFile[abilityEffectsDoc](t,
			filepath.Join(root, "abilities", id+"."+foundSlot+".json"))
		assert.Truef(t, hasChampionFormEffect(standalone),
			"content/abilities/%s.%s.json (%s, rawcode %s) carries NO `championForm` effect, so pressing it "+
				"CANNOT change the body — and this pair is one where the change is VISIBLE (%s → %s). "+
				"Add {\"kind\":\"championForm\",\"to\":\"alternate\",\"durationSec\":<rank-1 ahdu>} "+
				"(or \"toggle\" for a w3x toggle). This is exactly how 06-04 傑桑變化 shipped inert.",
			id, foundSlot, want, base.Transform.TriggerAbility.Rawcode, base.ModelKey, alt.ModelKey)

		if mirror, ok := embedded.Abilities[strings.ToUpper(foundSlot)]; ok {
			assert.Truef(t, hasChampionFormEffect(mirror),
				"content/champions/%s.json abilities.%s (the SHIPPED SECOND COPY) has no `championForm` "+
					"while the standalone doc does — the codex, 內容管理 and the editor preview all render "+
					"this copy, so they would show a transform ability that does something else",
				id, strings.ToUpper(foundSlot))
		}
		checked++
	}

	// The set must not be able to empty itself: a rename of `modelKey`, of the
	// `transform` block, or of the trigger name would make every loop body above
	// `continue` and leave a green suite asserting nothing (CLAUDE.md failure
	// mode ③). Four model-changing pairs are on the roster today —— #06 傑富力士,
	// #18 南野秀一, #25 拳四郎, #58 皮卡丘. #61 百連我殺 is a fifth pair in the map
	// but its base godie-u012 is not on the roster.
	require.GreaterOrEqualf(t, checked, 4,
		"only %d model-changing transform pair(s) were reachable from the roster — expected at least 4. "+
			"Either a champion was dropped, or the `transform`/`modelKey`/triggerAbility shape this guard "+
			"reads has changed and it is now checking nothing",
		checked)
}
