package curation_test

// Champion IDENTITY for the curation starter gate — a deliberately small Go
// port of the ONE rule that lives in
// `packages/shared/src/content/championIdentity.ts` (read that file first; it
// carries the full policy, the evidence and the rationale).
//
// WHY A PORT AT ALL. The starter bundle is a hand-curated static list in
// starter.go; nothing in the Go service computes identity at runtime, so this
// is test-only enforcement — the gate that keeps a human from picking the same
// character twice (or from dropping a real one as an imagined "twin") when the
// bundle is next edited. Keeping it in _test.go means no dead production code.
//
// WHY IT CANNOT DRIFT UNNOTICED. Both this file and championIdentity.test.ts
// assert the SAME named outcomes over the SAME content tree — 黑化Saber stays
// separate from Saber, the known duplicate pairs still fold, champions sharing
// a CC0 stand-in mesh stay distinct. If the TS rule is loosened or tightened
// and this port is not, one of the two suites fails on those pins.
//
// GOVERNING POLICY (user, 2026-07-22)「遇到疑慮一律判斷寬鬆為多英雄」— when in
// doubt, SEPARATE heroes. Merging requires positive evidence, because a
// wrongly-merged champion disappears from the game with its bespoke kit while a
// wrongly-kept duplicate is merely cosmetic.
//
// THE ONE EXCEPTION (owner ruling 2026-07-26, task #249). The source map's WC3
// Metamorphosis fields — `Eme1` (normal-form unit) / `Emeu` (alternate-form
// unit) — state IN DATA that two unit definitions are two bodies of one hero.
// Where that evidence exists it WINS over the lenient default. It is a CLOSED
// TABLE of 26 pairs read from the extractor's own output
// (tools/w3x-import/out/GoDieEX22s-src/TRANSFORM_FORMS.json, regenerated by
// extract_transform_forms.py), it is consulted only AFTER the hero-number
// guard, and it is NOT a licence to merge lookalikes: 05 / 53 / 91 carry no
// such evidence and stay two heroes each. Mirrors
// `isW3xFormPair` in packages/shared/src/content/championForms.ts.

import (
	"encoding/json"
	"os"
	"path/filepath"
	"regexp"
	"strings"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"

	"github.com/ggd/platform/internal/curation"
	"github.com/ggd/platform/pkg/testkit"
)

// heroNumberRe pulls the task #11 prefix off an ability name: "22-01 鬼隱之擊"
// → 22, "22-002 …" → 22 (EX). RE2 has no lookahead, so the trailing class does
// the "no fourth digit" job; some imported names have NO space after the
// prefix ("61-01惡魔球"), so a separator must not be required.
//
// ⚠️ THIS IS A PORT, AND IT HAD DRIFTED. The governing rule lives in
// packages/shared/src/content/championIdentity.ts (`HERO_NUMBER_RE`), which was
// widened to `\d{2,3}` when the roster began minting 3-digit hero numbers —
// owner directive: the next id auto-fills the max, so 喪標麥可 is #100. The Go
// side stayed at `\d{2}` and therefore REJECTED every ability of hero 100+,
// which is how GH#29 (put 喪標麥可 on the open roster) failed R2 with
// 「name "100-01 肝泥抹德" lacks the task #11 xx-0N prefix」 — a correct hero
// being told its correct name was malformed.
//
// The "-" delimiter is what keeps this unambiguous: "100-00" (hero 100, passive)
// cannot be read as "10-000", because the first group must be followed by "-"
// and index 2 of "10-000" already is one. Asserted by
// TestHeroNumberRePortParity.
var heroNumberRe = regexp.MustCompile(`^(\d{2,3})-(\d{2,3})([^0-9]|$)`)

// heroNumberOfName returns the hero 編號 encoded in an ability name, or "".
func heroNumberOfName(name string) string {
	m := heroNumberRe.FindStringSubmatch(strings.TrimSpace(name))
	if m == nil {
		return ""
	}
	return m[1]
}

// heroNumberOf resolves a champion's 編號 from its embedded kit. Returns "" when
// nothing parses OR when the abilities disagree — ambiguity is NOT evidence of
// sameness, so an unresolved champion can never be merged into anything.
func heroNumberOf(c championDoc) string {
	num := ""
	for _, ab := range c.Abilities {
		n := heroNumberOfName(ab.Name)
		if n == "" {
			continue
		}
		if num != "" && num != n {
			return ""
		}
		num = n
	}
	return num
}

// nameComponents splits the map's `稱號 - 角色名` on the SPACE-DELIMITED dash
// only, so an unspaced hyphen stays part of its token
// ("英靈-亞瑟王 - 黑化Saber" → "英靈-亞瑟王", "黑化Saber").
var nameSepRe = regexp.MustCompile(`\s+[-–—]\s+`)

func nameComponents(name string) []string {
	out := []string{}
	for _, part := range nameSepRe.Split(strings.Join(strings.Fields(name), " "), -1) {
		if p := strings.TrimSpace(part); p != "" {
			out = append(out, p)
		}
	}
	return out
}

func sharesNameComponent(a, b string) bool {
	left := map[string]struct{}{}
	for _, p := range nameComponents(a) {
		left[p] = struct{}{}
	}
	for _, p := range nameComponents(b) {
		if _, ok := left[p]; ok {
			return true
		}
	}
	return false
}

// sameCharacter is the identity rule: true ONLY on positive, strong evidence.
//
//  1. no parseable hero number on either side ⇒ DISTINCT (never "both unknown,
//     so probably the same");
//  2. different numbers ⇒ DISTINCT — this is the 黑化Saber guard (69 vs 20),
//     which no shared mesh or shared portrait may override;
//  3. identical display name ⇒ SAME, even across meshes (one entry got the real
//     import, its twin a CC0 stand-in);
//  4. a shared name component AND the same mesh ⇒ SAME (re-worded twins such as
//     超級賽亞人-悟空 / 賽亞人-悟空). Both halves are required: a shared component
//     alone is a franchise relation (拳四郎, 皮卡丘 each exist as two heroes),
//     and a shared mesh alone just means the art is missing — champ.sela is
//     worn by 18 unrelated champions;
//  5. otherwise DISTINCT (same number, nothing else in common = a source-data
//     collision to report, not to resolve: 05, 53, 61, 91).
func sameCharacter(a, b championDoc) bool {
	if a.ID == b.ID {
		return true
	}
	na, nb := heroNumberOf(a), heroNumberOf(b)
	if na == "" || nb == "" || na != nb {
		return false
	}
	// 4b. THE ONE EXCEPTION — the map's Eme1/Emeu fields name these two ids as
	// the two BODIES of one hero (see the file header). Runs AFTER the 編號
	// guard, so it can never merge across hero numbers.
	if isW3xFormPair(a.ID, b.ID) {
		return true
	}
	if strings.Join(strings.Fields(a.Name), " ") == strings.Join(strings.Fields(b.Name), " ") {
		return true
	}
	return a.ModelKey != "" && a.ModelKey == b.ModelKey && sharesNameComponent(a.Name, b.Name)
}

// ------------------------------------------------- w3x transform form pairs --

// transformFormsPath is the extractor's own output — the ONLY source for the
// exception. Absent (a truncated checkout) ⇒ the exception simply never fires,
// which is the lenient direction and therefore safe.
func transformFormsPath() string {
	return filepath.Join("..", "..", "..", "..", "tools", "w3x-import", "out",
		"GoDieEX22s-src", "TRANSFORM_FORMS.json")
}

type transformFormsDoc struct {
	Count int `json:"count"`
	Pairs []struct {
		HeroNumber     string `json:"heroNumber"`
		AbilityRawcode string `json:"abilityRawcode"`
		NormalUnit     struct {
			ChampionID string `json:"championId"`
		} `json:"normalUnit"`
		AlternateUnit struct {
			ChampionID string `json:"championId"`
		} `json:"alternateUnit"`
	} `json:"pairs"`
}

// formCounterpart maps EVERY id in a pair to the other half, both directions.
var formCounterpart = loadFormCounterparts()

// alternateFormIDs is the set of TRANSFORMED bodies — ids a player must never
// be offered as a champion (owner ruling:「換成本體，變身態改由技能觸發」).
var alternateFormIDs = loadAlternateFormIDs()

func loadTransformForms() transformFormsDoc {
	var doc transformFormsDoc
	raw, err := os.ReadFile(transformFormsPath())
	if err != nil {
		return doc
	}
	_ = json.Unmarshal(raw, &doc)
	return doc
}

func loadFormCounterparts() map[string]string {
	out := map[string]string{}
	for _, p := range loadTransformForms().Pairs {
		out[p.NormalUnit.ChampionID] = p.AlternateUnit.ChampionID
		out[p.AlternateUnit.ChampionID] = p.NormalUnit.ChampionID
	}
	return out
}

func loadAlternateFormIDs() map[string]struct{} {
	out := map[string]struct{}{}
	for _, p := range loadTransformForms().Pairs {
		out[p.AlternateUnit.ChampionID] = struct{}{}
	}
	return out
}

// isW3xFormPair reports whether a and b are the two halves of ONE map-declared
// transform pair, in either order.
func isW3xFormPair(a, b string) bool {
	return formCounterpart[a] == b && formCounterpart[b] == a
}

// loadRoster reads every champion@1 doc in the content tree, keyed by id.
func loadRoster(t *testing.T, root string) map[string]championDoc {
	t.Helper()
	dir := filepath.Join(root, "champions")
	entries, err := os.ReadDir(dir)
	require.NoErrorf(t, err, "read %s", dir)
	out := map[string]championDoc{}
	for _, e := range entries {
		name := e.Name()
		if e.IsDir() || !strings.HasSuffix(name, ".json") || strings.HasPrefix(name, "_") {
			continue
		}
		doc := readJSON[championDoc](t, filepath.Join(dir, name))
		if doc.ID == "" {
			continue
		}
		out[doc.ID] = doc
	}
	return out
}

// whitelist-champion-identity: the identity rule the curation bundle is curated
// against, pinned on the real content tree. Mirrors the headline cases in
// packages/shared/src/content/championIdentity.test.ts.
func TestChampionIdentityRule(t *testing.T) {
	testkit.Cover(t, "whitelist-champion-identity")
	root := contentRoot()
	if _, err := os.Stat(filepath.Join(root, "champions")); err != nil {
		t.Skipf("content tree not present at %s — skipping identity pins", root)
	}
	roster := loadRoster(t, root)
	require.GreaterOrEqual(t, len(roster), 100, "content tree looks truncated")

	get := func(id string) championDoc {
		doc, ok := roster[id]
		require.Truef(t, ok, "champion %q missing from the content tree", id)
		return doc
	}

	// 黑化Saber: same mesh, same extracted portrait, near-identical name —
	// but hero 69, not 20. It is its OWN character and must never fold.
	saber, saberTwin, alter := get("godie-e002"), get("godie-e00l"), get("godie-e00q")
	require.Equal(t, saber.ModelKey, alter.ModelKey, "the premise: e002 and e00q share a mesh")
	assert.Equal(t, "20", heroNumberOf(saber))
	assert.Equal(t, "69", heroNumberOf(alter))
	assert.False(t, sameCharacter(alter, saber), "黑化Saber must not fold into Saber")
	assert.False(t, sameCharacter(alter, saberTwin), "黑化Saber must not fold into Saber's twin")
	assert.True(t, sameCharacter(saber, saberTwin), "e002/e00l ARE one character")

	// Known duplicate ENTRIES still fold (canonical id first).
	for _, pair := range [][2]string{
		{"godie-hgam", "godie-h02r"}, {"godie-ogrh", "godie-o00x"},
		{"godie-uvng", "godie-u010"}, {"godie-h01n", "godie-h01o"},
		{"godie-e00k", "godie-e00z"}, {"godie-ewar", "godie-e007"},
		{"godie-h02v", "godie-h02u"}, {"godie-hjai", "godie-h020"},
		{"godie-n003", "godie-n01g"}, {"godie-u00n", "godie-u00o"},
		{"godie-e00w", "godie-e00x"}, {"godie-o01z", "godie-o02v"},
		{"godie-e001", "godie-e00n"}, {"godie-nbbc", "godie-n01c"},
		{"godie-ucrl", "godie-u034"}, {"godie-nsjs", "godie-n00p"},
	} {
		assert.Truef(t, sameCharacter(get(pair[0]), get(pair[1])),
			"%s and %s are the same character", pair[0], pair[1])
	}

	// Champions sharing a CC0 stand-in mesh are NOT duplicates of each other.
	for _, mesh := range []string{"champ.sela", "champ.thorne", "champ.skin.barbarian", "champ.skin.rogue"} {
		wearers := []championDoc{}
		for _, doc := range roster {
			if doc.ModelKey == mesh {
				wearers = append(wearers, doc)
			}
		}
		require.Greaterf(t, len(wearers), 1, "%s should be worn by several champions", mesh)
		for _, a := range wearers {
			for _, b := range wearers {
				if a.ID == b.ID {
					continue
				}
				// ONE documented exception: 曹操孟德's two unit definitions
				// (O02N base / O02O 天下號令 form) both wear champ.skin.rogue
				// because his map model is a Blizzard built-in. They fold on
				// their IDENTICAL authored name — never on the shared mesh,
				// which is what this loop exists to forbid.
				if a.Name == b.Name && isW3xFormPair(a.ID, b.ID) {
					continue
				}
				assert.Falsef(t, sameCharacter(a, b),
					"%s (%s) and %s (%s) share the stand-in mesh %s but are different characters",
					a.ID, a.Name, b.ID, b.Name, mesh)
			}
		}
	}

	// Hero-number COLLISIONS resolve to separate heroes BY DEFAULT — the
	// lenient rule, unchanged. These three carry no transform evidence: the
	// author cloned a hero and never renumbered it.
	for _, pair := range [][2]string{
		{"godie-hblm", "godie-h021"}, // 05 賈修貝爾 / 阿強一號
		{"godie-o00l", "godie-o02s"}, // 53 傑洛士 / 涼宮八ㄦ匕
		{"godie-h02s", "godie-h02z"}, // 91 死亡騎士 / 不良少年
	} {
		a, b := get(pair[0]), get(pair[1])
		require.Equalf(t, heroNumberOf(a), heroNumberOf(b), "%s/%s premise: same 編號", pair[0], pair[1])
		require.Falsef(t, isW3xFormPair(a.ID, b.ID), "%s/%s premise: NO Eme1/Emeu evidence", a.ID, b.ID)
		assert.Falsef(t, sameCharacter(a, b),
			"%s (%s) and %s (%s) share hero number %s but must stay two heroes",
			a.ID, a.Name, b.ID, b.Name, heroNumberOf(a))
	}

	// …and the THREE the owner overturned on 2026-07-26 (task #249). Each is a
	// hero and its own transformed body, stated by the map's Eme1/Emeu fields,
	// so the evidence beats the lenient default. They differ in BOTH 稱號 and
	// mesh, which is exactly why no other rule reaches them.
	for _, pair := range [][2]string{
		{"godie-umal", "godie-u00l"}, // 25 北斗神拳掌門人 / 北斗之鼠  A0HW ChangeDNA
		{"godie-ofar", "godie-o02l"}, // 58 神奇寶貝兒 / 神騎寶貝     A040 瘋狂皮卡丘
		{"godie-u012", "godie-u011"}, // 61 克勞薩II世 / 克勞薩先生    Aphx 百連我殺
	} {
		a, b := get(pair[0]), get(pair[1])
		require.Equalf(t, heroNumberOf(a), heroNumberOf(b), "%s/%s premise: same 編號", pair[0], pair[1])
		require.NotEqualf(t, a.ModelKey, b.ModelKey, "%s/%s premise: different meshes", pair[0], pair[1])
		require.Truef(t, isW3xFormPair(a.ID, b.ID), "%s/%s premise: Eme1/Emeu evidence exists", a.ID, b.ID)
		assert.Truef(t, sameCharacter(a, b),
			"%s (%s) and %s (%s) are ONE hero in two bodies (w3x Eme1/Emeu)", a.ID, a.Name, b.ID, b.Name)
		assert.Truef(t, sameCharacter(b, a), "the exception is symmetric")
	}
	// The exception can NEVER cross a hero number — the 黑化Saber guard holds.
	assert.False(t, isW3xFormPair("godie-e002", "godie-e00q"))
	assert.False(t, sameCharacter(get("godie-e002"), get("godie-e00q")))

	// Numberless champions each keep their own identity — including the test
	// hero, which shares BOTH its mesh and a name component with hero 11.
	for _, id := range []string{"godie-e00u", "godie-u01f", "godie-h02n", "godie-u01q", "sela", "thorne"} {
		doc := get(id)
		assert.Emptyf(t, heroNumberOf(doc), "%s (%s) should have no parseable hero number", id, doc.Name)
		for other, otherDoc := range roster {
			if other == id {
				continue
			}
			assert.Falsef(t, sameCharacter(doc, otherDoc),
				"numberless champion %s must not merge into %s", id, other)
		}
	}
}

// whitelist-no-alternate-forms: THE REGRESSION THAT WOULD HAVE CAUGHT THE LIVE
// BUG (task #249, roster gate R6).
//
// For months 10 of the 50 first-open-roster slots held the ALTERNATE (變身)
// body instead of the hero — 草泥馬 in its lying-down 臥 form (w3x movement
// speed 0), 妙蛙花 at usca 3.0 from round one, 北斗之鼠 instead of 拳四郎,
// 超級賽亞人 so that 悟空's own R turned him into what he already was. Nothing
// caught it because the importer drops the WC3 Metamorphosis fields Eme1/Emeu
// (task #56), so no gate could even ask the question.
//
// It can be asked now. Every id the starter bundle enables must be a BASE unit;
// an alternate body is reachable only by casting its transform ability once
// that mechanic exists (task #119). The table is the extractor's own output, so
// this gate strengthens automatically as the import improves.
func TestStarterRosterHasNoAlternateForms(t *testing.T) {
	testkit.Cover(t, "whitelist-no-alternate-forms")

	forms := loadTransformForms()
	require.Equalf(t, 26, forms.Count,
		"TRANSFORM_FORMS.json missing or truncated at %s — regenerate with tools/w3x-import/extract_transform_forms.py",
		transformFormsPath())
	require.NotEmpty(t, alternateFormIDs, "the alternate-form set must not be empty")

	offenders := []string{}
	for _, id := range curation.StarterSet().Champions {
		if _, isAlt := alternateFormIDs[id]; isAlt {
			offenders = append(offenders, id+" → base "+formCounterpart[id])
		}
	}
	assert.Emptyf(t, offenders,
		"the first open roster offers a 變身 form as a pickable hero; swap each to its base:\n%s",
		strings.Join(offenders, "\n"))

	// …and the ten that WERE wrong now hold their base, id-for-id.
	enabled := map[string]struct{}{}
	for _, id := range curation.StarterSet().Champions {
		enabled[id] = struct{}{}
	}
	for _, swap := range [][2]string{
		{"godie-h020", "godie-hjai"}, // 04 莉娜因巴斯
		{"godie-n01c", "godie-nbbc"}, // 08 勇者小呆
		{"godie-o00x", "godie-ogrh"}, // 09 悟空
		{"godie-u01u", "godie-udre"}, // 11 索隆
		{"godie-e007", "godie-ewar"}, // 12 天地志狼
		{"godie-n00p", "godie-nsjs"}, // 18 南野秀一
		{"godie-u00l", "godie-umal"}, // 25 拳四郎
		{"godie-u010", "godie-uvng"}, // 38 飛影
		{"godie-h02r", "godie-hgam"}, // 90 妙蛙種子
		{"godie-h02u", "godie-h02v"}, // 92 草泥馬
	} {
		alt, base := swap[0], swap[1]
		require.Equalf(t, base, formCounterpart[alt], "%s premise: the map says its base is %s", alt, base)
		_, altEnabled := enabled[alt]
		_, baseEnabled := enabled[base]
		assert.Falsef(t, altEnabled, "%s is a 變身 form and must not be on the roster", alt)
		assert.Truef(t, baseEnabled, "%s (the base of %s) must be on the roster instead", base, alt)
	}
}

// TestHeroNumberRePortParity — 這條守衛保護的不是 regex,是「兩個 port 不會再
// 各自演化」。
//
// GH#29 之所以會踩到,不是因為有人寫錯 regex,而是因為 TS 那份被正確地加寬成
// 3 位數(commit 註解明寫「喪標麥可 = 100」)、Go 這份沒有,而**沒有任何東西會
// 因此變紅**。identityRule 的檔頭寫著 "ONE regex per port",那是一個承諾,不是
// 一個機制。這條測試把它變成機制:它直接讀 TypeScript 原始碼裡的
// `HERO_NUMBER_RE`,把兩邊的字面量比對。
//
// ⚠️ 刻意讀「原始碼」而不是「行為」:行為比對只能覆蓋我想得到的樣本,而漂移
// 永遠發生在我沒想到的那一格。字面量比對抓的是「有人只改了一邊」。
func TestHeroNumberRePortParity(t *testing.T) {
	testkit.Cover(t, "hero-number-port-parity")

	// packages/shared/src/content/championIdentity.ts 是治理來源。
	src, err := os.ReadFile(filepath.Join("..", "..", "..", "..",
		"packages", "shared", "src", "content", "championIdentity.ts"))
	require.NoError(t, err, "the governing TS rule must be readable — it is the source of truth")

	// export const HERO_NUMBER_RE = /^(\d{2,3})-(\d{2,3})(?!\d)/;
	tsRe := regexp.MustCompile(`HERO_NUMBER_RE\s*=\s*/\^\(\\d\{(\d)(?:,(\d))?\}\)-\(\\d\{(\d)(?:,(\d))?\}\)`)
	m := tsRe.FindSubmatch(src)
	require.NotNil(t, m,
		"could not parse HERO_NUMBER_RE out of championIdentity.ts — if its SHAPE changed, this port must be re-derived by hand, not silently skipped")

	// 兩邊的量詞必須一致。TS 用 (?!\d) 做「不可有下一位數字」,Go(RE2 無 lookahead)
	// 用 ([^0-9]|$),兩者等價 —— 差異僅止於此,量詞不得有差。
	wantGroup1 := string(m[1])
	if len(m[2]) > 0 {
		wantGroup1 += "," + string(m[2])
	}
	wantGroup2 := string(m[3])
	if len(m[4]) > 0 {
		wantGroup2 += "," + string(m[4])
	}
	assert.Equal(t, `^(\d{`+wantGroup1+`})-(\d{`+wantGroup2+`})([^0-9]|$)`, heroNumberRe.String(),
		"heroNumberRe has drifted from the TS HERO_NUMBER_RE — widen BOTH ports or neither")

	// 而且它真的要接受三位數英雄(GH#29 的實際案例)。
	assert.Equal(t, "100", heroNumberOfName("100-01 肝泥抹德"), "hero 100 must parse")
	assert.Equal(t, "100", heroNumberOfName("100-002 此世全部之咖哩・バタンキュー"), "hero 100's EX must parse")
	assert.Equal(t, "22", heroNumberOfName("22-01 鬼隱之擊"), "2-digit heroes must keep parsing")
	assert.Equal(t, "61", heroNumberOfName("61-01惡魔球"), "no-space imported names must keep parsing")
	// 四位數仍然無效 —— 加寬不是取消上限。
	assert.Equal(t, "", heroNumberOfName("1000-01 不存在"), "a 4-digit hero number is still malformed")
}
