#!/usr/bin/env python3
"""Freeze and inspect an Infinity Strash full-game container delivery safely.

This intentionally performs no extraction and does not invoke an Unreal tool.
It records the exact supplied pakchunk containers, verifies an optional
``MANIFEST.sha256`` generated by ``shasum -a 256``, and identifies only the
container features that can be proven from their bytes.  A PAK footer signature
does not prove that its index is unencrypted or that its payload can be decoded.
The produced record is therefore an acquisition and compatibility gate, never a
model, animation, VFX, audio, voice, or runtime-readiness claim.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import re
import struct
from pathlib import Path


PAK_MAGIC = 0x5A6F12E1
PRIMARY_NAMES = ("pakchunk0-WindowsClient.pak", "pakchunk1-WindowsClient.pak")
CONTAINER_NAME = re.compile(r"^pakchunk[0-9]+-WindowsClient\.(?:pak|utoc|ucas|sig)$")
MANIFEST_LINE = re.compile(r"^([0-9a-fA-F]{64})\s+\*?([^/\\]+)$")
MAX_MANIFEST_BYTES = 1024 * 1024
TAIL_SCAN_BYTES = 64 * 1024


def sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as stream:
        for block in iter(lambda: stream.read(1024 * 1024), b""):
            digest.update(block)
    return digest.hexdigest()


def require_regular(path: Path, root: Path) -> None:
    if path.is_symlink() or not path.is_file() or path.resolve().parent != root:
        raise ValueError("delivery member must be a direct, regular, non-symlink file: " + path.name)


def parse_manifest(path: Path) -> dict[str, str]:
    if path.stat().st_size > MAX_MANIFEST_BYTES:
        raise ValueError("MANIFEST.sha256 exceeds the safety limit")
    rows: dict[str, str] = {}
    for number, raw in enumerate(path.read_text(encoding="utf-8").splitlines(), start=1):
        if not raw.strip():
            continue
        match = MANIFEST_LINE.fullmatch(raw.strip())
        if not match:
            raise ValueError(f"invalid MANIFEST.sha256 line {number}")
        digest, name = match.group(1).lower(), match.group(2)
        if name in rows:
            raise ValueError("duplicate MANIFEST.sha256 filename: " + name)
        rows[name] = digest
    if not rows:
        raise ValueError("MANIFEST.sha256 has no entries")
    return rows


def pak_footer_candidates(path: Path) -> list[dict[str, int | bool]]:
    """Return structurally plausible legacy PAK footer locations without parsing the index."""
    size = path.stat().st_size
    if size < 44:
        return []
    with path.open("rb") as stream:
        stream.seek(max(0, size - TAIL_SCAN_BYTES))
        tail = stream.read()
    base = size - len(tail)
    magic = struct.pack("<I", PAK_MAGIC)
    found: list[dict[str, int | bool]] = []
    start = 0
    while True:
        index = tail.find(magic, start)
        if index < 0:
            break
        absolute = base + index
        if absolute + 44 <= size:
            _, version, index_offset, index_size = struct.unpack_from("<IIQQ", tail, index)
            valid = 1 <= version <= 20 and 0 <= index_offset < absolute and 0 < index_size <= absolute - index_offset
            if valid:
                found.append({"offset": absolute, "version": version, "indexOffset": index_offset,
                              "indexSize": index_size, "indexBoundsPlausible": True})
        start = index + 1
    return found


def probe(path: Path) -> dict[str, object]:
    suffix = path.suffix.lower()
    if suffix == ".pak":
        footers = pak_footer_candidates(path)
        return {
            "kind": "unreal-pak" if footers else "opaque-pak-or-unrecognized-container",
            "legacyPakFooterCandidates": footers,
            "legacyPlainUnpackEligible": False,
            "unpackState": "not-attempted",
            "compatibilityNote": (
                "A plausible PAK footer was found, but index encryption, compression methods, and UE version "
                "have not been established; do not call the legacy unpacker automatically."
                if footers else
                "No supported legacy PAK footer was found in the bounded tail scan; retain as an opaque original container."
            ),
        }
    head = path.read_bytes()[:16]
    if suffix == ".utoc":
        return {"kind": "iostore-utoc" if head[:4] == b"-io-" else "opaque-utoc",
                "headerHex": head.hex(), "unpackState": "not-attempted",
                "compatibilityNote": "IoStore payload extraction needs its matching .ucas file and a separately verified toolchain."}
    if suffix == ".ucas":
        return {"kind": "iostore-ucas", "headerHex": head.hex(), "unpackState": "not-attempted",
                "compatibilityNote": "UCAS is retained with its matching UTOC; no extraction was attempted."}
    return {"kind": "signature-sidecar", "headerHex": head.hex(), "unpackState": "not-applicable"}


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("delivery", type=Path, help="Directory containing the unmodified pakchunk files.")
    parser.add_argument("output", type=Path, help="New directory in which to write delivery-inspection.json.")
    args = parser.parse_args()
    delivery, output = args.delivery.resolve(), args.output.resolve()
    if not delivery.is_dir() or delivery.is_symlink():
        raise ValueError("delivery must be a real directory")
    if output.exists():
        raise ValueError("output must be new for an immutable inspection stage")
    if output.is_relative_to(delivery):
        raise ValueError("output cannot be inside the delivery")

    all_members = sorted(delivery.iterdir(), key=lambda item: item.name)
    containers = [member for member in all_members if CONTAINER_NAME.fullmatch(member.name)]
    by_name = {member.name: member for member in containers}
    missing = [name for name in PRIMARY_NAMES if name not in by_name]
    if missing:
        raise ValueError("missing required primary containers: " + ", ".join(missing))
    for member in containers:
        require_regular(member, delivery)
    manifest_path = delivery / "MANIFEST.sha256"
    if manifest_path.exists():
        require_regular(manifest_path, delivery)
        manifest_hashes: dict[str, str] | None = parse_manifest(manifest_path)
    else:
        manifest_hashes = None

    records = []
    for member in containers:
        digest = sha256(member)
        expected = manifest_hashes.get(member.name) if manifest_hashes is not None else None
        if expected is not None and expected != digest:
            raise ValueError("MANIFEST.sha256 mismatch: " + member.name)
        records.append({"name": member.name, "bytes": member.stat().st_size, "sha256": digest,
                        "manifestSha256": expected, "manifestVerified": expected == digest if expected else None,
                        "probe": probe(member)})
    if manifest_hashes is not None:
        unknown = sorted(set(manifest_hashes) - set(by_name))
        if unknown:
            raise ValueError("MANIFEST.sha256 names not supplied as recognized containers: " + ", ".join(unknown))

    result = {
        "schema": "ggd-infinity-strash-full-game-delivery-inspection@1",
        "sourceWork": "Infinity Strash: DRAGON QUEST The Adventure of Dai",
        "sourcePlatform": "Windows game installation; user-provided original containers",
        "primaryContainersRequired": list(PRIMARY_NAMES),
        "primaryContainersPresent": True,
        "providedManifest": {"present": manifest_hashes is not None,
                             "sha256": sha256(manifest_path) if manifest_hashes is not None else None,
                             "allProvidedEntriesVerified": all(row["manifestVerified"] is True for row in records) if manifest_hashes else None},
        "containers": records,
        "extractionState": "not-attempted",
        "assetState": "raw-original-containers-verified-only",
        "gaps": [
            "No Unreal asset index, model, skeleton, animation, VFX, audio, or voice payload has been extracted by this stage.",
            "The report does not establish encryption, compression, license, redistributability, or backend runtime compatibility.",
            "A separate format-specific extractor must be selected only after the preserved container evidence is reviewed.",
        ],
    }
    output.mkdir(parents=True)
    target = output / "delivery-inspection.json"
    target.write_text(json.dumps(result, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    print(json.dumps({"output": str(target), "containerCount": len(records),
                      "manifestPresent": manifest_hashes is not None,
                      "primaryContainersPresent": True}, ensure_ascii=False))
    return 0


if __name__ == "__main__":
    try:
        raise SystemExit(main())
    except (OSError, UnicodeError, ValueError, struct.error) as error:
        raise SystemExit("error: " + str(error))
