/**
 * codexCoverage — 圖示覆蓋率 (task #97): how many champion / ability / item
 * icons EXIST against how many are actually NEEDED.
 *
 * WHY IT EXISTS. The user asked for it in exactly these terms:
 * 「生成必要 英雄、技能、武器道具 icon 是否能給我一個即時的數量進度條，讓我知道你
 * 真的有在作事而不是忘了」 — the point is VERIFICATION, not decoration. So every
 * number below is DERIVED, never asserted:
 *
 *   • the DENOMINATOR is the live length of each collection as fetched from
 *     /content by whichever page is counting (the codex's ui/codex/codexData.ts,
 *     後台管理's assets/useIconTracking.ts). Nothing here may carry a size — the
 *     `codex-no-baked-content` gate fails the build if a literal one appears,
 *     and that gate is load-bearing for this module in particular: a progress
 *     bar with a typed-in total is worse than no progress bar at all.
 *   • the NUMERATOR is the `icon` field each fetched doc declares, minus the
 *     paths the background icon-byte scan (codexIcons.ts) could not actually
 *     fetch. A doc that declares art the server cannot serve is NOT covered.
 *
 * NEEDS AN ICON vs DELIBERATELY EXCLUDED. The user also ruled that entries
 * obviously not meant for play get no art (「明顯不是提供使用的(ex.空描述)就不需要
 * 了」). TASK #72 OWNS THAT CLASSIFICATION, and this module does not re-derive a
 * word of it: the verdict is read through `codexPlan.ts` — #72's own reader for
 * its own artifact, `content/config/icon-plan.json`, regenerated by
 * `tools/icon-gen/src/plan.py`. Three states come back and they are NOT the
 * same thing, which is exactly why the bar has to show them apart:
 *
 *   DROPPED  a decision — never generate. Leaves the DENOMINATOR entirely.
 *   BLOCKED  a held gate (third-party IP) — still needed, still counted, but
 *            not work anyone can do yet. Its own band, its own colour.
 *   BACKLOG  the honest remainder. This is what the bar is a bar OF.
 *
 * Until the plan exists the bar counts every icon-less entry as needed and says
 * so. `candidate*` is an opt-in what-if using the codex's own pre-existing
 * broken-data predicates (ui/codex/codexIssues.ts: `no-description`,
 * `name-equals-id`) —
 * labelled as a guess, never the default, and always beaten by a real plan, so
 * it cannot quietly diverge from #72's answer.
 *
 * Pure and total: no fetch, no React, no clock. The React hooks do the I/O —
 * the codex's own `apps/client/src/ui/codex/useIconCoverage.ts` and 後台管理's
 * `apps/admin/src/assets/useIconTracking.ts` — and the tests drive these
 * functions directly, so the numbers in the tests are the numbers on the page.
 *
 * WHY THIS FILE IS IN packages/shared AND NOT ui/codex, where it was written:
 * two pages now count icons — the in-game codex bar and 後台管理's ICON 生成追蹤
 * (task #102) — and a second implementation of "how many icons are missing"
 * would diverge from this one within a day, leaving both numbers worthless.
 * Both apps already depend on @ggd/shared, so one definition can serve both.
 * The `codex-no-baked-content` gate (apps/client/src/ui/codex/codexLive.test.ts)
 * scans this directory too: moving out of ui/codex did not move out of reach.
 */
import type { CodexPlan } from "./codexPlan";
import type { CodexData, CodexKind } from "./codexTypes";

/** Display order the user named them in: 英雄 / 技能 / 武器道具. */
export const COVERAGE_KINDS: readonly CodexKind[] = ["champion", "ability", "item"];

/** kind → the content collection it lives in (same mapping the loader uses). */
export const COVERAGE_COLLECTION: Readonly<Record<CodexKind, string>> = {
  champion: "champions",
  ability: "abilities",
  item: "items",
};


// ---------------------------------------------------------------------------
// the unit of measurement
// ---------------------------------------------------------------------------

/**
 * One entry reduced to just what coverage needs. Deliberately tiny: the live
 * rescan re-reads changed docs and swaps these in without disturbing the
 * browsing data the page is rendering from.
 */
export interface CoverageEntry {
  readonly kind: CodexKind;
  readonly id: string;
  /** the `icon` path the doc declares; null when it declares none */
  readonly icon: string | null;
  /** no usable `description` — the first half of #72's exclusion rule */
  readonly emptyDescription: boolean;
  /** display name fell back to the id — the second half */
  readonly nameEqualsId: boolean;
}

export function coverageKey(kind: CodexKind, id: string): string {
  return `${kind}/${id}`;
}

function asRecord(v: unknown): Record<string, unknown> | null {
  return typeof v === "object" && v !== null && !Array.isArray(v) ? (v as Record<string, unknown>) : null;
}
function nonEmpty(v: unknown): string | null {
  return typeof v === "string" && v !== "" ? v : null;
}

/** Reduce a loaded codex to coverage entries — zero extra requests. */
export function coverageEntries(data: CodexData): CoverageEntry[] {
  const out: CoverageEntry[] = [];
  for (const c of data.champions) {
    out.push({
      kind: "champion",
      id: c.id,
      icon: c.icon,
      emptyDescription: c.description === null,
      nameEqualsId: c.name === c.id,
    });
  }
  for (const a of data.abilities) {
    out.push({
      kind: "ability",
      id: a.id,
      icon: a.icon,
      emptyDescription: a.description === null,
      nameEqualsId: a.name === a.id,
    });
  }
  for (const i of data.items) {
    out.push({
      kind: "item",
      id: i.id,
      icon: i.icon,
      emptyDescription: i.description === null,
      nameEqualsId: i.name === i.id,
    });
  }
  return out;
}

/**
 * Read one raw doc (as re-fetched by the live rescan) into a coverage entry.
 * Same tolerance as codexData's normalisers: a broken doc still counts, it just
 * counts as having no icon.
 */
export function coverageEntryFromDoc(kind: CodexKind, id: string, raw: unknown): CoverageEntry {
  const doc = asRecord(raw) ?? {};
  return {
    kind,
    id,
    icon: nonEmpty(doc["icon"]),
    emptyDescription: nonEmpty(doc["description"]) === null,
    nameEqualsId: (nonEmpty(doc["name"]) ?? id) === id,
  };
}

// ---------------------------------------------------------------------------
// #72's published classification — READ, NOT RE-DERIVED
// ---------------------------------------------------------------------------
//
// There is no parser here on purpose. `codexPlan.ts` is task #72's own reader
// for task #72's own artifact; duplicating it would be exactly the second,
// divergent definition of "which entries need art" that this task must not
// create. All that lives here is the ARITHMETIC over its verdict.

/** Was this entry dropped by the plan (a decision, not a gap)? */
export function isDropped(plan: CodexPlan | null, id: string): boolean {
  return plan !== null && plan.dropReason.has(id);
}

/** Is this entry blocked by the plan (needed, but gated — e.g. third-party IP)? */
export function isBlocked(plan: CodexPlan | null, id: string): boolean {
  return plan !== null && plan.blockReason.has(id);
}

// ---------------------------------------------------------------------------
// the sums
// ---------------------------------------------------------------------------

export interface CoverageBucket {
  /** entries in this collection, live */
  readonly total: number;
  /** DROPPED by the plan — a decision; leaves the denominator entirely */
  readonly excluded: number;
  /** total − excluded: the real denominator */
  readonly needed: number;
  /** needed entries whose declared icon actually resolves */
  readonly covered: number;
  /** needed − covered */
  readonly missing: number;
  /** subset of `missing` that DECLARES an icon the mount cannot serve */
  readonly broken: number;
  /** subset of `missing` the plan BLOCKS (held gate, e.g. third-party IP) */
  readonly blocked: number;
  /** missing − blocked: what generation can actually work on right now */
  readonly backlog: number;
  /** covered / needed × 100; 100 when nothing is needed */
  readonly percent: number;
}

export type ExclusionSource = "plan" | "candidate" | "none";

export interface IconCoverage {
  readonly byKind: Readonly<Record<CodexKind, CoverageBucket>>;
  readonly all: CoverageBucket;
  readonly exclusionSource: ExclusionSource;
  /** how many entries the local what-if rule WOULD exclude (hint only) */
  readonly candidateTotal: number;
  /** what the plan itself claims, for a side-by-side against the measurement */
  readonly planCounts: CodexPlan["counts"] | null;
  readonly planTemplateVersion: string | null;
  /**
   * The plan was generated against a different number of documents than we just
   * loaded — it is stale, so its exclusions may be too. Surfaced, never hidden.
   */
  readonly planStale: boolean;
}

export interface ComputeCoverageInput {
  readonly entries: readonly CoverageEntry[];
  /** #72's published verdict (codexPlan.ts); null until it lands */
  readonly plan?: CodexPlan | null;
  /** opt-in what-if using the codex's existing broken-data predicates */
  readonly applyCandidates?: boolean;
  /** icon paths the byte scan could not fetch (codexIcons.failed) */
  readonly failedIcons?: ReadonlySet<string>;
}

interface Tally {
  total: number;
  excluded: number;
  covered: number;
  broken: number;
  blocked: number;
}

function newTally(): Tally {
  return { total: 0, excluded: 0, covered: 0, broken: 0, blocked: 0 };
}

function seal(t: Tally): CoverageBucket {
  const needed = t.total - t.excluded;
  const covered = Math.min(t.covered, needed);
  const missing = Math.max(0, needed - covered);
  const blocked = Math.min(t.blocked, missing);
  return {
    total: t.total,
    excluded: t.excluded,
    needed,
    covered,
    missing,
    broken: t.broken,
    blocked,
    backlog: missing - blocked,
    percent: needed === 0 ? 100 : (covered / needed) * 100,
  };
}

/** The local what-if rule — mirrors codexIssues' `no-description` / `name-equals-id`. */
export function isCandidateExclusion(e: CoverageEntry): boolean {
  return e.emptyDescription || e.nameEqualsId;
}

export function computeIconCoverage(input: ComputeCoverageInput): IconCoverage {
  const { entries, plan = null, applyCandidates = false, failedIcons } = input;
  const tallies: Record<CodexKind, Tally> = {
    champion: newTally(),
    ability: newTally(),
    item: newTally(),
  };
  const sum = newTally();
  let candidateTotal = 0;

  for (const e of entries) {
    const t = tallies[e.kind];
    t.total++;
    sum.total++;
    if (isCandidateExclusion(e)) candidateTotal++;

    const excluded = plan ? isDropped(plan, e.id) : applyCandidates && isCandidateExclusion(e);
    if (excluded) {
      t.excluded++;
      sum.excluded++;
      continue;
    }

    if (e.icon !== null && !(failedIcons?.has(e.icon) ?? false)) {
      t.covered++;
      sum.covered++;
      continue;
    }
    if (e.icon !== null) {
      t.broken++;
      sum.broken++;
    }
    if (isBlocked(plan, e.id)) {
      t.blocked++;
      sum.blocked++;
    }
  }

  return {
    byKind: {
      champion: seal(tallies.champion),
      ability: seal(tallies.ability),
      item: seal(tallies.item),
    },
    all: seal(sum),
    exclusionSource: plan ? "plan" : applyCandidates ? "candidate" : "none",
    candidateTotal,
    planCounts: plan?.counts ?? null,
    planTemplateVersion: plan?.templateVersion ?? null,
    planStale: plan !== null && sum.total > 0 && plan.counts.docs !== sum.total,
  };
}

// ---------------------------------------------------------------------------
// the live rescan (pure half)
// ---------------------------------------------------------------------------

/**
 * One row of a collection's `_index.json`. The `hash` is what makes the live
 * bar cheap: it is a stable hash of the PARSED doc (fsStore.hashDoc), so
 * writing an `icon` field changes it while a reformat does not. Polling the
 * three index files is 3 requests; only the docs whose hash moved get re-read.
 */
export interface IndexRow {
  readonly kind: CodexKind;
  readonly id: string;
  readonly path: string;
  readonly hash: string;
}

/** What the rescan carries between polls. */
export interface CoverageScan {
  readonly entries: readonly CoverageEntry[];
  /** coverageKey → the index hash already reconciled into `entries` */
  readonly hashes: ReadonlyMap<string, string>;
}

export function scanFromEntries(entries: readonly CoverageEntry[]): CoverageScan {
  return { entries, hashes: new Map() };
}

/** Read `{entries:[{id,path,hash}]}` off a fetched `_index.json`. */
export function parseIndexRows(kind: CodexKind, raw: unknown): IndexRow[] {
  const list = asRecord(raw)?.["entries"];
  if (!Array.isArray(list)) return [];
  const out: IndexRow[] = [];
  for (const row of list) {
    const rec = asRecord(row);
    const id = rec ? nonEmpty(rec["id"]) : null;
    const path = rec ? nonEmpty(rec["path"]) : null;
    const hash = rec ? nonEmpty(rec["hash"]) : null;
    if (id && path && hash) out.push({ kind, id, path, hash });
  }
  return out;
}

export interface DiffResult {
  /** pruned scan — entries whose id vanished from the index are dropped */
  readonly scan: CoverageScan;
  /** docs that must be re-read before their coverage can be trusted */
  readonly stale: readonly IndexRow[];
}

/**
 * Reconcile a freshly polled index against the last scan.
 *
 * FIRST POLL IS FREE: an entry the codex load already produced adopts its index
 * hash without a re-read (we have the doc's icon field already), so opening the
 * page costs 3 extra requests, not one per document.
 *
 * `kinds` lists the collections whose index actually came back. A collection
 * that failed to fetch is left completely alone — a network blip must never
 * read as "every icon disappeared".
 */
export function diffScan(
  prev: CoverageScan,
  rows: readonly IndexRow[],
  kinds: readonly CodexKind[],
): DiffResult {
  const seen = new Set(kinds);
  const byKey = new Map<string, IndexRow>();
  for (const r of rows) byKey.set(coverageKey(r.kind, r.id), r);

  const known = new Map<string, CoverageEntry>();
  for (const e of prev.entries) known.set(coverageKey(e.kind, e.id), e);

  const entries: CoverageEntry[] = [];
  for (const e of prev.entries) {
    const key = coverageKey(e.kind, e.id);
    if (!seen.has(e.kind) || byKey.has(key)) entries.push(e);
  }

  const hashes = new Map<string, string>();
  const stale: IndexRow[] = [];
  for (const [key, row] of byKey) {
    const priorHash = prev.hashes.get(key);
    if (priorHash === row.hash) {
      hashes.set(key, row.hash);
      continue;
    }
    if (priorHash === undefined && known.has(key)) {
      // first sighting of a doc the codex load already read — adopt, don't refetch
      hashes.set(key, row.hash);
      continue;
    }
    stale.push(row);
    if (priorHash !== undefined) hashes.set(key, priorHash);
  }
  // keep hashes for kinds whose index did not come back this round
  for (const [key, hash] of prev.hashes) {
    const kind = key.slice(0, key.indexOf("/")) as CodexKind;
    if (!seen.has(kind) && !hashes.has(key)) hashes.set(key, hash);
  }
  return { scan: { entries, hashes }, stale };
}

/** Fold re-read docs back in, marking their index hash as reconciled. */
export function mergeDocs(
  prev: CoverageScan,
  updates: readonly { readonly row: IndexRow; readonly doc: unknown }[],
): CoverageScan {
  if (updates.length === 0) return prev;
  const byKey = new Map<string, CoverageEntry>();
  for (const e of prev.entries) byKey.set(coverageKey(e.kind, e.id), e);
  const hashes = new Map(prev.hashes);
  for (const { row, doc } of updates) {
    const key = coverageKey(row.kind, row.id);
    byKey.set(key, coverageEntryFromDoc(row.kind, row.id, doc));
    hashes.set(key, row.hash);
  }
  return { entries: [...byKey.values()], hashes };
}
