from pathlib import Path
import json,hashlib,struct,datetime,collections
from PIL import Image
ROOT=Path(__file__).resolve().parents[1]
NOW=datetime.datetime.now(datetime.timezone.utc).isoformat()
def save(rel,obj):
 (ROOT/rel).write_text(json.dumps(obj,ensure_ascii=False,indent=2)+'\n')
def meta(rel):
 p=ROOT/rel; b=p.read_bytes();return {'path':str(p),'relativePath':rel,'bytes':len(b),'sha256':hashlib.sha256(b).hexdigest(),'existsLocal':True}
def read(rel):return json.loads((ROOT/rel).read_text())
fbx=read('analysis/static-analysis.json');op=read('analysis/opgg-static-analysis.json');audio=read('analysis/audio-probe.json');mat=read('original/opgg/materials.json')
ALIASES=['空渦龍','空涡龙','Jetragon','JetDragon','SK_JetDragon','ジェッドラン']
fbxid='mediafire-shinypenguin-palworld-jetragon';opid='opgg-palworld-jetragon';audioid='gamevault-palworld-jetragon-cries'
urls={'author':'https://www.reddit.com/r/Palworld/comments/1ajwntw/3d_models_from_in_game/','folder':'https://www.mediafire.com/folder/n1qka5sixonyc/Palworld','fbx':'https://www.mediafire.com/file/rue35xbygpqvgrr/jetdragon.fbx/file','opgg':'https://op.gg/zh-tw/palworld/pals/jetragon','opggBase':'https://s-stats-platform-cdn.op.gg/palworld/models/pals/JetDragon','audio':'https://palworld.gamevault.in/paldex/jetragon/'}
textureRows=[]
for p in sorted((ROOT/'original/opgg/materials').glob('*.webp')):
 with Image.open(p) as im:
  im.load(); x=meta(str(p.relative_to(ROOT)));x.update({'format':im.format,'width':im.width,'height':im.height,'mode':im.mode,'decodedPixelSha256':hashlib.sha256(im.tobytes()).hexdigest(),'decodePassed':True,'crcScope':'WebP RIFF has no stored ZIP/PNG-style CRC; complete decoder read and SHA-256 verified.'});textureRows.append(x)
refs={v for m in mat['materials'].values() for k,v in m.items() if k.endswith('Texture') and isinstance(v,str)}
assert refs=={x['relativePath'].removeprefix('original/opgg/') for x in textureRows};assert len(textureRows)==8
save('analysis/opgg-textures.json',{'schema':'ggd.texture-source-verification@1','allMaterialReferencesPresent':True,'textures':textureRows})
clipRows=[{k:v for k,v in c.items() if k!='tracks'} for c in op['animations']]
save('animation-index.json',{'schema':'ggd.character-animation-index@1','character':'空渦龍 / Jetragon','sourceId':opid,'sourceUrl':urls['opgg'],'sourceModel':meta('original/opgg/model.glb'),'declaredAndStoredClipCount':29,'uniqueDecodedTrackSignatureCount':28,'duplicateClipContentGroups':op['duplicateClipContentGroups'],'proceduralAnimationCount':0,'sourceNativeAnimationContainerAcquired':False,'provenance':'Source-supplied game-named clips in public exported GLB; original Unreal animation containers and FPS metadata were not supplied. No invented/retargeted/resampled motion.','decodedVerification':{'accessorCount':4731,'allAccessorValuesFinite':True,'allTimesNondecreasing':True,'allClipsVary':True},'clips':clipRows,'detailedTrackEvidencePath':str(ROOT/'analysis/opgg-static-analysis.json'),'durationSumSecondsIncludingDuplicateEntry':op['sumClipDurations']})
common={'character':'空渦龍 / Jetragon','aliases':ALIASES,'sourceWork':'Palworld / 幻獸帕魯','sourceGame':'Palworld','sourcePlatform':'Public extracted/exported asset; exact game platform/build unknown','heroIds':[],'resourceRole':'character-body','automaticEligible':False,'defaultEligible':False,'backendIntegration':'pending-standardization','proceduralAnimationCount':0,'renderVerified':False,'ggdReady':False,'runtimeSelectable':False}
def candidate(cid,sid,rel,**extra):
 x=dict(common);x.update({'id':cid,'candidateId':cid,'sourceId':sid,'sourceModel':str(ROOT/rel),'sourceModelBytes':meta(rel)['bytes'],'sourceModelSha256':meta(rel)['sha256'],'format':Path(rel).suffix[1:],'existsLocal':True,'sourceClass':'original-game-extraction-community-repackage',**extra});return x
fbxbase={'meshCount':1,'triangleCount':8468,'nativeVertexCount':5097,'boneCount':65,'materialCount':3,'textureCount':7,'nativeAnimationCount':0,'audioCount':0,'vfxCount':0,'modelAnalysisPath':str(ROOT/'analysis/static-analysis.json'),'texturesIndexPath':str(ROOT/'analysis/static-analysis.json'),'texturePaths':[x['path'] for x in fbx['textures']],'sourceUrl':urls['author'],'downloadPageUrl':urls['fbx']}
opbase={'meshCount':1,'drawPrimitiveCount':3,'triangleCount':8468,'exportedVertexCount':sum(x['vertices'] for x in op['meshes']),'boneCount':75,'materialCount':3,'textureCount':8,'imagesEmbeddedInGlb':0,'nativeAnimationCount':29,'uniqueAnimationContentCount':28,'audioCount':0,'vfxCount':0,'modelAnalysisPath':str(ROOT/'analysis/opgg-static-analysis.json'),'texturesIndexPath':str(ROOT/'analysis/opgg-textures.json'),'materialsPath':str(ROOT/'original/opgg/materials.json'),'animationIndexPath':str(ROOT/'animation-index.json'),'sourceUrl':urls['opgg'],'materialBinding':'External 8 WebP and pal-lit/clearcoat/jewel/subsurface shader parameters retained; not baked into GLB.'}
candidates=[candidate(fbxid+'.fbx',fbxid,'original/jetdragon.fbx',**fbxbase,readiness='acquired-rigged-source-pending-standardization',sourceClass='original-game-extraction-author-blender-repackage',limitations=['Source has 0 AnimationStack/AnimationCurve objects.','Source four weight rows sum about0.9686275; retain original.','FBX 2024-03-05 public upload date; not asserted latest game build.']),candidate(fbxid+'.assimp-diagnostic-v1',fbxid,'converted-assimp-v1/body.glb',**fbxbase,readiness='diagnostic-invalid-preserved',derived=True,khronos={'errors':16,'warnings':4,'receipt':str(ROOT/'converted-assimp-v1/khronos.json')},limitations=['Original Assimp output retained; 12 inverse-bind affine roundoff errors and four non-normalized weights.']),candidate(fbxid+'.reserve-v2',fbxid,'converted-reserve-v2/body.glb',**fbxbase,readiness='reserve-pending-ggd-standardization',derived=True,khronos={'errors':0,'warnings':4,'receipt':str(ROOT/'converted-reserve-v2/khronos.json')},derivationReceiptPath=str(ROOT/'converted-reserve-v2/normalization-receipt.json'),limitations=['Four weight rows normalized; twelve IBM affine bottom values corrected within1.2e-7.','Original 65 bones, all7 embedded PNG and specular materials retained. No new animation.','Four generated tangent/skinned hierarchy warnings and no GGD or render acceptance.']),candidate(opid+'.original-glb',opid,'original/opgg/model.glb',**opbase,readiness='acquired-animated-source-pending-material-binding',limitations=['Requires EXT_meshopt_compression.','Original source omitted required KHR_mesh_quantization declaration for int16 normals.','29 stored clips; Carrying and Carrying_Start are identical decoded tracks (28 unique).']),candidate(opid+'.decoded-v1',opid,'decoded/jetragon-meshopt-decoded.glb',**opbase,readiness='diagnostic-decoded-pending-extension-declaration',derived=True,limitations=['Meshopt views decoded with existing Blender5.2 codec; original clip sample values retained.','Three validation errors from missing KHR_mesh_quantization declaration retained as diagnostic.']),candidate(opid+'.decoded-declared-v2',opid,'decoded/jetragon-quantization-declared.glb',**opbase,readiness='reserve-pending-material-binding-and-ggd-standardization',derived=True,khronos={'errors':0,'warnings':1,'infos':3,'receipt':str(ROOT/'analysis/opgg-declared-khronos.json')},derivationReceiptPath=str(ROOT/'analysis/quantization-declaration.json'),limitations=['Added correct KHR_mesh_quantization declaration only; decoded BIN byte-identical to previous file.','One skinned hierarchy warning and3 unusedUV infos because external textures are not yet bound.','75 bones, shader translation, runtime state mapping, GGD texture/geometry limits and actual animation render remain unverified.'])]
save('model-candidates.json',{'schema':'ggd.character-model-candidates@1','character':'空渦龍 / Jetragon','aliases':ALIASES,'independentModelSourceCount':2,'acquiredDistinctCharacterCount':1,'candidateFileCount':len(candidates),'candidates':candidates,'notDefaultPolicy':'All source/derived files retained. Each eligible standardized future variant must remain an independently selectable backend option; no current default or central mutation.'})
audioRows=[]
for x in audio['files']:
 p=Path(x['output']);stream=next(s for s in x['probe']['streams'] if s['codec_type']=='audio');row=meta(str(p.relative_to(ROOT)));row.update({'id':audioid+'.'+p.stem,'sourceId':audioid,'character':'空渦龍 / Jetragon','label':x['label'],'sourceUrl':urls['audio'],'downloadUrl':x['url'],'audioCategory':'sound-effect','voiceType':'nonverbal-pal-cry','reportedLanguage':'nonlinguistic','spokenDialogueConfirmed':False,'speechText':None,'sourceContainsSynthetic':'unknown','voiceSynthesisInputEligible':False,'voiceSynthesisExclusionReason':'Nonverbal creature cries, no verified spoken language/transcript; do not use as human speech training input.','codec':stream['codec_name'],'sampleRate':int(stream['sample_rate']),'channels':stream['channels'],'durationSeconds':float(x['probe']['format']['duration']),'decodeToNullPassed':x['decodeToNullPassed'],'listeningReviewPassed':False,'provenance':'Public GameVault MP3 export, site says game audio bank source; original Wwise container not acquired.'});audioRows.append(row)
save('audio-index.json',{'schema':'ggd.character-audio-index@1','character':'空渦龍 / Jetragon','audioCount':len(audioRows),'bankCount':0,'spokenDialogueCount':0,'durationSeconds':sum(x['durationSeconds'] for x in audioRows),'files':audioRows,'audioGroups':[{'id':audioid,'audioCategory':'sound-effect','voiceType':'nonverbal-pal-cry','sourceContainsSynthetic':'unknown','fileIds':[x['id'] for x in audioRows]}],'limitations':['Six labels from public page: Normal/Joy/Anger/Sorrow/Pain/Death; no separate voiced sentences, original Wwise bank, BGM or attack VFX obtained.','Full MP3 decoding passed; human listening/timing integration not completed.']})
checks={'identity':'空渦龍 = Jetragon / internal JetDragon; exact OP.GG page and returned palId/model names agree.','nameEvidenceUrl':urls['opgg'],'normalPublicDownloads':True,'noAccessBypass':True,'rejectedSources':[{'url':urls['audio'],'resource':'protected model marker in public viewer config','status':'not-attempted-no-download','reason':'Protected model reference not resolved; public MP3 downloads are independent.'}],'sourceAuthorLicense':'No explicit asset reuse license found on public source; Pocketpair game asset attribution retained; no CC0 claim.','noGameImageOrKeysAcquired':True}
save('acquisition.json',{'schema':'ggd.source-acquisition@1','checkedAt':NOW,'identityAliases':ALIASES,'sourceUrls':urls,'checks':checks,'originalFiles':[meta('original/jetdragon.fbx'),meta('original/opgg/model.glb'),meta('original/opgg/materials.json')]+[meta(x['relativePath']) for x in textureRows]+[meta(x['relativePath']) for x in audioRows],'upstreamFbxHashMatches':fbx['sourceSha256']=='d88b1553e5318de0f34ddb40e6d4785ed44a525c43a05a5b81dc1275679d3bf3','resourceCounts':{'modelSources':2,'characters':1,'modelCandidateFiles':6,'fbxBones':65,'opggBones':75,'sourceAnimationEntries':29,'uniqueAnimationContents':28,'fbxPng':7,'opggWebp':8,'cryMp3':6,'standaloneVfx':0,'spokenDialogue':0},'status':'acquired-statically-verified-pending-runtime-standardization'})
sourceEntries=[]
for sid,label,url,author in [(fbxid,'空渦龍 Jetragon FBX／7貼圖',urls['author'],'ShinyPenguin'),(opid,'空渦龍 Jetragon GLB／75骨／29動作／8貼圖',urls['opgg'],'OP.GG asset viewer'),(audioid,'空渦龍 Jetragon 6種叫聲MP3',urls['audio'],'Palworld GameVault')]:
 group=[x for x in candidates if x['sourceId']==sid]
 x={'id':sid,'target':label,'heroIds':[],'ownerEntryIds':[],'url':url,'uploader':author,'author':author,'format':'MP3' if sid==audioid else 'FBX / PNG / derived GLB' if sid==fbxid else 'GLB / WebP / external material JSON','accessStatus':'public-direct-download','checkedAt':NOW,'acquisitionStatus':'downloaded-verified','readiness':'reserved-pending-standardization','resourceRole':'audio-supplement' if sid==audioid else 'character-body','assetKinds':['audio','sound-effect'] if sid==audioid else ['model','skeleton','texture','material']+(['animation'] if sid==opid else []),'defaultEligible':False,'automaticEligible':False,'selectionClass':'original-game','sourceClass':'original-game-audio-community-export' if sid==audioid else 'original-game-extraction-community-repackage','purchaseDecision':'hold-purchase-review-acquired-source','discoveryChannel':'public-community-author-share' if sid==fbxid else 'public-game-database-viewer','platform':'Original game platform/build not supplied; source-native container not obtained.','sourceGame':'Palworld','sourceWork':'Palworld / 幻獸帕魯','localPath':str(ROOT),'modelCount':0 if sid==audioid else 1,'modelCandidates':group,'modelCandidateIndexPath':str(ROOT/'model-candidates.json'),'audioIndexPath':str(ROOT/'audio-index.json'),'nativeAnimationCount':29 if sid==opid else 0,'uniqueAnimationContentCount':28 if sid==opid else 0,'audioCount':6 if sid==audioid else 0,'publicationStatus':'local-frozen-before-s3-backup','s3BackupReceiptPath':'/private/tmp/ggd-jetragon-source-s3-backup.json','backendIntegration':{'status':'pending-standardization','runtimeSelectable':False,'defaultChanged':False},'license':checks['sourceAuthorLicense'],'limitations':checks}
 if sid==fbxid:x['downloadPageUrl']=urls['fbx'];x['files']=[meta('original/jetdragon.fbx')]
 if sid==opid:x['downloadUrl']=urls['opggBase']+'/model.glb';x['files']=[meta('original/opgg/model.glb'),meta('original/opgg/materials.json')]+textureRows
 if sid==audioid:x['files']=audioRows;x['audioGroups']=[{'id':audioid,'audioCategory':'sound-effect','voiceType':'nonverbal-pal-cry','sourceContainsSynthetic':'unknown','files':audioRows}]
 sourceEntries.append(x)
save('source-entries.json',{'schema':'ggd.public-source-delivery@1','publicSources':sourceEntries})
backlog={'id':'community:palworld-jetragon','name':'空渦龍 / Jetragon','work':'Palworld / 幻獸帕魯','aliases':ALIASES,'sourceIds':[fbxid,opid,audioid],'modelCandidates':[{'id':x['id'],'library':'public-community','path':x['sourceModel'],'bytes':x['sourceModelBytes'],'sha256':x['sourceModelSha256'],'format':x['format'],'readiness':x['readiness'],'existsLocal':True,'resourceRole':x['resourceRole'],'sourceId':x['sourceId'],'boneCount':x['boneCount'],'textureCount':x['textureCount'],'nativeAnimationCount':x['nativeAnimationCount'],'sourceUrl':x['sourceUrl'],'defaultEligible':False} for x in candidates],'mappedHeroIds':[],'identityHeroIds':[],'proxyUseHeroIds':[],'possibleIdentityHeroIds':[],'designStatus':'not-defined','noDesignReason':'Exact confirmed Jetragon/JetDragon/空渦龍 aliases checked against current content/champions; no champion definition found at acquisition time. Re-evaluate on later generated backlog updates.','evidence':{'identitySourceUrl':urls['opgg'],'sourceManifestPalId':'JetDragon','bodyMeshName':'SK_JetDragon','actualFilesVerified':True,'animationIndexPath':str(ROOT/'animation-index.json'),'audioIndexPath':str(ROOT/'audio-index.json'),'modelIndexPath':str(ROOT/'model-candidates.json'),'statusIsAcquisitionSnapshot':True},'limitations':['Pending material/runtime/animation visual acceptance; source files are reserved candidates, not a shipped GGD hero.','29 source entries contain28 distinct decoded track signatures.','6 nonverbal MP3 cries, no spoken dialogue or standaloneVFX.'],'backupReceiptPath':'/private/tmp/ggd-jetragon-source-s3-backup.json'}
save('design-backlog-entry.json',backlog)
readme='''# 空渦龍 / Jetragon / JetDragon 來源交付

本資料夾僅為來源與轉換儲備；未改中央索引、後台預設或 Git。

- `source-entries.json`：3筆可追加 publicSources（ShinyPenguin FBX、OP.GG模型動作、GameVault叫聲）。
- `model-candidates.json`：2個獨立來源的6檔候選/診斷版本全保留；1名角色，不重複灌角色數。
- `animation-index.json`：29個實存來源動作、28種唯一decoded track內容；Carrying與Carrying_Start同內容。未補造程序化動作，非直接取得Unreal原容器。
- `audio-index.json`：6個MP3非語句叫聲，總8.285034秒；不是角色朗讀台詞，未標為可直接做人聲合成訓練輸入。
- `original/jetdragon.fbx`：2024年作者分享，65骨、8468三角形、7張原PNG、0動作。原始權重保留。
- `converted-reserve-v2/body.glb`：保留全貼圖和specular，僅修4筆權重及12筆IBM浮點誤差；Khronos0error/4warnings。
- `original/opgg/`：75骨、8468三角形、29動作GLB＋8WebP＋完整shader材料設定。全部從頁面公開baseUrl正常GET；沒有登入或解保護。
- `decoded/jetragon-quantization-declared.glb`：meshopt解碼並補正來源漏宣告的KHR_mesh_quantization，BIN內容、骨架、原動作樣本未重綁/重取樣。Khronos0error/1warning/3info；仍須外部材質綁定與GGD驗收。

檔案通過可解碼與SHA檢查，不等於貼圖shader外觀、腳滑、runtime行為或模型上架已驗收。兩個來源65與75骨架不同，不應直接互套動作。獨立VFX/原Wwise bank/人聲台詞未取得；GameVault protected模型未嘗試解析。全部來源/中間檔留本機與S3 legacy備份，未通過成品檢查的不得自動選用。
'''
(ROOT/'README.md').write_text(readme)
print(json.dumps({'sources':len(sourceEntries),'candidateFiles':len(candidates),'animations':len(clipRows),'uniqueAnimationContents':28,'textures':len(fbx['textures'])+len(textureRows),'audio':len(audioRows),'audioSeconds':sum(x['durationSeconds'] for x in audioRows),'root':str(ROOT)},ensure_ascii=False))
