from pathlib import Path
import collections,datetime,hashlib,json,shutil
R=Path('/Users/Takuro/Dropbox/我的 Mac (Moriya.local)/Documents/ABxVFX_EDIT/GGD-Asset-Library/intake/public-models-20260910/fate-unlimited-codes-texture-recovery-batch6')
assert not (R/'control/handoff.json').exists()
D=R/'receipts'
def put(p,x):p.write_text(json.dumps(x,ensure_ascii=False,indent=2)+'\n')
snapshots=[]
for name in ['initial','patch-1']:
 t=json.loads((D/('author-'+name+'-tree.json')).read_text());c=json.loads((D/('author-'+name+'-commit.json')).read_text());blobs=[x for x in t['tree'] if x['type']=='blob'];formats=dict(collections.Counter(Path(x['path']).suffix for x in blobs))
 snapshots.append({'label':name,'commit':c['sha'],'canonicalRootTreeSha':c['commit']['tree']['sha'],'treeResponseSha':t['sha'],'treeEndpointUsedCommitTreeish':True,'treeTruncated':t.get('truncated',False),'gitBlobs':len(blobs),'formats':formats,'nonTextureBlobs':[x for x in blobs if Path(x['path']).suffix not in ['.png','.ini']],'nativeModelMotionMatches':[],'commitReceipt':str((D/('author-'+name+'-commit.json')).relative_to(R)),'treeReceipt':str((D/('author-'+name+'-tree.json')).relative_to(R))})
assert all(not x['treeTruncated'] for x in snapshots)
forks=json.loads((D/'author-forks.json').read_text());branches=json.loads((D/'author-branches.json').read_text());releases=json.loads((D/'author-releases.json').read_text())
put(R/'author-native-source-followup.json',{'schema':'ggd.author-source-followup@1','checkedAt':datetime.datetime.now(datetime.timezone.utc).isoformat(),'target':'Fate/unlimited codes same-version PSP native assets','routes':[{'url':'https://github.com/UdienZebeer/Fate-UC-HD','type':'source-author-public-repository','status':'public-history-and-file-trees-read','finding':'Initial upload describes character renders; v2 commit fixes portrait hair placement. No original native game package is linked in the available descriptions.','branches':[{'name':x['name'],'commit':x['commit']['sha']} for x in branches],'releaseCount':len(releases),'snapshotDetails':snapshots},{'url':'https://forums.ppsspp.org/showthread.php?tid=25691','type':'public-author-forum-explanation','authorLabel':'Threule','status':'full-thread-readable-HTTP-200','finding':'Author describes logos, character renders and magic-circle texture replacements for NPUH10009. Asks others for higher-resolution texture extraction. No matching native model or animation archive linked in the thread.','scopeNote':'The referenced GitHub author identity relationship is not assumed. Historical Vita mention does not prove a separate Vita asset source.','rawReceipt':'receipts/ppsspp-author-thread.html','knownDeadDownload':'https://github.com/Threule/Fate-UC-HD','deadLinkRetried':False}],'forkCatalog':[{'repository':x['full_name'],'sourceUrl':x['html_url'],'lastPush':x['pushed_at'],'description':x['description'],'acquired':False,'status':'metadata-only-not-a-new-native-source'} for x in forks],'newNativeAssetDownloadLinks':[],'newNativeAssetFiles':0,'conclusion':'Author history, public description and alternate branch provide texture-only evidence. This does not rule out unrelated public native sources.','previousRejectedEntrypointsRetried':False,'rawReceipts':['author-receipts.json','history-tree-receipts.json','history-commit-receipts.json']})
(R/'control/tooling').mkdir(parents=True,exist_ok=True)
for filename in ['ggd-fuc-batch6-process.py','ggd-fuc-batch6-author-audit.py','ggd-fuc-batch6-build-author-report.py']:
 shutil.copyfile(Path('/private/tmp')/filename,R/'control/tooling'/filename)
put(R/'control/transfer-method.json',{'sameUrl':'https://codeload.github.com/UdienZebeer/Fate-UC-HD/zip/c8c2d52b60856913d6d81ee0cba5533cc1a098a6','firstAttempt':'Copied frozen partial to new intake, normal curl --continue-at -','rangeResult':'curl 33: server does not support byte ranges','fallback':'one ordinary full GET with --http1.1 --fail --location --max-time 900 --max-filesize 67108864; no retry loop','originalPartialPreserved':True,'previousBatchChanged':False,'authenticationOrProtectionBypassed':False})
print('author follow-up written; no native source link found')
