#!/usr/bin/env python3
"""Freeze hashes and visual comparison evidence; does not register or publish assets."""
import argparse,json,pathlib,hashlib,shutil,numpy as np
from PIL import Image
p=argparse.ArgumentParser();p.add_argument('root',type=pathlib.Path);p.add_argument('--replay',type=pathlib.Path,required=True);a=p.parse_args();root=a.root.resolve();replay=a.replay.resolve()
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def meta(p):return {'absolutePath':str(p),'bytes':p.stat().st_size,'sha256':sha(p)}
def save(p,d):p.write_text(json.dumps(d,ensure_ascii=False,indent=2)+'\n')
comparisons=[];props=[]
for prop in ['handheld','back']:
 final=root/'outputs'/prop/'component.glb';native=root/'intermediate'/prop/'source-materials.glb';assert sha(final)==sha(replay/'outputs'/prop/'component.glb');assert sha(native)==sha(replay/'intermediate'/prop/'source-materials.glb')
 dirname='webgl-handheld-256-r2' if prop=='handheld' else 'webgl-back-256';render=root/'evidence'/dirname;baseline=root/'evidence'/('webgl-'+prop+'-native')
 for d,model in [(render,final),(baseline,native)]:
  run=json.loads((d/'run.json').read_text());proof=json.loads((d/'proof.json').read_text());assert run['sourceSha256']==sha(model) and run['complete'] and run['proofExists'] and not run['errorExists'];assert all(t['ready'] for t in proof['textures']) and proof['meshCount']==2 and proof['animationGroups']==proof['skeletons']==0
 for view in ['face-a','face-b','isometric']:
  p0=baseline/(view+'.png');p1=render/(view+'.png');x=np.asarray(Image.open(p0).convert('RGB'),float);y=np.asarray(Image.open(p1).convert('RGB'),float);assert x.shape==y.shape==(800,800,3);diff=np.abs(x-y);bg=y[0,0];mask=np.max(np.abs(y-bg),axis=2)>8;assert mask.sum()>5000
  comparisons.append({'prop':prop,'view':view,'native':meta(p0),'normalized256':meta(p1),'foregroundPixels':int(mask.sum()),'wholeImageMeanAbsoluteError255':float(diff.mean()),'foregroundMeanAbsoluteError255':float(diff[mask].mean()),'foregroundP95ChannelError255':float(np.percentile(diff[mask],95)),'scope':'High-resolution portable GLB versus same geometry/materials after current GGD image reduction; not comparison against Daz renderer.'})
 val=json.loads((root/'outputs'/prop/'validation.json').read_text());props.append({'id':'dai-shinteo-v2-sword-'+prop+'-256-v1','nameZh':'達伊之劍（手持獨立元件）' if prop=='handheld' else '達伊之劍（背劍獨立元件）','originalName':'Sword of Dai' if prop=='handheld' else 'Sword of Dai Back','sourceId':'patreon-shinteo-dai-daz-v2','workZh':'勇者鬥惡龍 達伊的大冒險','sourceClass':'community-mod-adaptation','sourceGame':'JUMP FORCE folder-labelled Daz adaptation; original-game extraction fidelity unverified','sourceVersion':'Shinteo Daz V2 / 2022-05-20','platform':'Daz Studio G8M/G8.1M adaptation; prop geometry has no body dependency','sourceUrl':'https://www.patreon.com/posts/dai-for-g8m-and-66623597','component':meta(final),'nativeStage':meta(native),'triangles':1854,'drawPrimitives':2,'embeddedImages':7,'textureMaxEdge':256,'skins':0,'nativeAnimations':0,'proceduralAnimations':0,'vfx':0,'audio':0,'heroIds':[],'defaultEligible':False,'backendRegistration':False,'gitPath':None,'s3Uri':None,'status':'converted-current-contract-valid-local-visual-review; awaiting integration acceptance','validation':meta(root/'outputs'/prop/'validation.json'),'visualProof':meta(render/'proof.json'),'visualReview':{'reviewedBy':'Codex visual inspection','scope':'Full handheld front/back; back front/isometric; compared handheld native-resolution view. Silhouette, blade, grip, guard and red details visible. Remaining views retained for parent review.','renderedViewsPerStage':3,'allTexturesReady':True,'sourceDazRendererParity':False,'heroAttachmentFitVerified':False},'rebuildByteIdentical':True,'limitations':['Daz Iray layered gloss is represented using supported glTF PBR + KHR_materials_specular; exact source shader parity remains unverified.','Source has no explicit normals; source Smooth Angle is used to reconstruct normals. Tangent-space normal parity still requires an independent Daz render comparison.','Native pivot and metric scale preserved; fitting/attaching to a GGD character has not been performed.','No full character body, humanoid skeleton, native animation, VFX, audio, hero binding or default model included.']})
save(root/'evidence/visual-comparison.json',{'schema':'ggd.dai-prop-texture-reduction-comparison@1','images':comparisons})
rebuild={'schema':'ggd.dai-prop-deterministic-rebuild@1','firstRoot':str(root),'secondRoot':str(replay),'outputs':[{'prop':x['id'],'nativeSha256':x['nativeStage']['sha256'],'normalizedSha256':x['component']['sha256'],'nativeAndNormalizedBothByteIdentical':True} for x in props]};save(root/'evidence/rebuild-verification.json',rebuild)
delivery={'schema':'ggd.dai-rigid-props-delivery@1','sourceArchiveSha256':'b2f64413b3abe50773bc57b08ff19f7dbf28d76257801edd13524f9e0cb44434','localRoot':str(root),'props':props,'summary':{'independentWeaponComponents':2,'fullCharacterBodies':0,'animations':0,'vfx':0,'audio':0,'backendRegistered':0,'deployed':0},'sourceGeometryVerification':meta(root/'evidence/source-geometry-verification.json'),'rebuildVerification':meta(root/'evidence/rebuild-verification.json'),'noCentralChanges':True,'awsCalls':0,'networkPublication':False};save(root/'delivery.json',delivery)
# Backup reproducible converter and dependencies; no original/intermediate is removed.
tools=root/'tools';tools.mkdir(exist_ok=False)
for p in pathlib.Path(__file__).parent.iterdir():
 if p.is_file():shutil.copy2(p,tools/p.name)
manifest={'schema':'ggd.dai-rigid-prop-local-stage-sha256@1','root':str(root),'files':[dict(path=str(p.relative_to(root)),bytes=p.stat().st_size,sha256=sha(p)) for p in sorted(root.rglob('*')) if p.is_file() and p.name!='files-sha256.json'],'exclusions':['files-sha256.json (self)'],'s3Uploaded':False};save(root/'files-sha256.json',manifest)
print(json.dumps({'delivery':meta(root/'delivery.json'),'manifest':meta(root/'files-sha256.json'),'props':[x['component'] for x in props],'comparisonMean':[{'prop':x['prop'],'view':x['view'],'foregroundMAE':x['foregroundMeanAbsoluteError255']} for x in comparisons]},ensure_ascii=False,indent=2))
