/**
 * creditsData — the attribution ledger the credits page (#credits) renders.
 *
 * The point of these assertions is licence safety, not cosmetics: exactly ONE
 * entry is `mandatory` (a licence REQUIRES it displayed), and that entry is the
 * CC-BY 4.0 login dragon. The old 魔王魂 BGM obligation is gone — all eleven
 * tracks are generated by tools/bgm-gen — so a stray 魔王魂 string here would be
 * a false provenance claim. Everything else is CC0 / attribution-optional and is
 * listed out of courtesy. See content/assets/CREDITS.md (the authoritative record).
 */
import { describe, it, expect } from "vitest";
import { cover } from "@ggd/shared/testkit/cover";
import { CREDITS, COPYRIGHT_LINE } from "./creditsData";

describe("creditsData", () => {
  it("carries the © 2026 Moriyamouse/Adms notice line", () => {
    cover("credits-data");
    expect(COPYRIGHT_LINE).toContain("© 2026");
    expect(COPYRIGHT_LINE).toContain("Moriyamouse/Adms");
  });

  it("lists the mandatory CC-BY 4.0 dragon accurately, and it is the ONLY mandatory entry", () => {
    cover("credits-data");
    const mandatory = CREDITS.filter((c) => c.mandatory);
    expect(mandatory).toHaveLength(1);
    const dragon = mandatory[0]!;
    expect(dragon.title).toContain("Animated Dragon Three Motion Loops");
    expect(dragon.author).toContain("LasquetiSpice");
    expect(dragon.license).toBe("CC-BY 4.0");
    expect(dragon.licenseUrl).toBe("https://creativecommons.org/licenses/by/4.0/");
    expect(dragon.sourceUrl).toContain("sketchfab.com");
    //署名 is a licence CONDITION, not a courtesy — the terms must say so.
    expect(dragon.terms).toContain("署名");
  });

  it("credits KayKit assets as CC0 courtesy (no attribution obligation)", () => {
    cover("credits-data");
    const kaykit = CREDITS.find((c) => c.author.includes("KayKit"));
    expect(kaykit).toBeDefined();
    expect(kaykit!.license).toBe("CC0");
    expect(kaykit!.mandatory).toBe(false);
  });

  it("restates the 効果音ラボ usage terms (AI-training + re-cut prohibitions) though attribution is optional", () => {
    cover("credits-data");
    const lab = CREDITS.find((c) => c.title.includes("効果音ラボ"));
    expect(lab).toBeDefined();
    expect(lab!.mandatory).toBe(false);
    expect(lab!.terms).toContain("AI");
    expect(lab!.terms).toContain("裁切");
  });

  it("lists the self-generated BGM as own work needing no attribution", () => {
    cover("credits-data");
    const bgm = CREDITS.find((c) => c.author.includes("bgm-gen"));
    expect(bgm).toBeDefined();
    expect(bgm!.mandatory).toBe(false);
    expect(bgm!.terms).toContain("無須署名");
  });

  it("no stale 魔王魂 / maou.audio anywhere — that music no longer ships", () => {
    cover("credits-data");
    const blob = JSON.stringify(CREDITS) + COPYRIGHT_LINE;
    expect(blob).not.toContain("魔王魂");
    expect(blob).not.toContain("maou.audio");
  });

  it("is de-duplicated: no two entries share a title", () => {
    cover("credits-data");
    const titles = CREDITS.map((c) => c.title);
    expect(new Set(titles).size).toBe(titles.length);
  });
});
