/**
 * creditsData — every attribution the game owes, as data.
 *
 * ---------------------------------------------------------------------------
 * WHY THIS EXISTS AS A SEPARATE PAGE
 * ---------------------------------------------------------------------------
 * 「版權宣告頁應該是一個連結，跳過去詳細列出說明，而非直接在登入頁直接列出來一長串」.
 * The login footer briefly carried the CC-BY dragon credit inline and it was a
 * wall of text over the artwork. A link is both better looking and perfectly
 * compliant: CC-BY 4.0 asks for attribution "in any reasonable manner" for the
 * medium, and a clearly-labelled link to a page carrying the full credit is the
 * ordinary way to do that on a screen you are meant to look at, not read.
 *
 * ---------------------------------------------------------------------------
 * MANDATORY vs COURTESY — the distinction that matters
 * ---------------------------------------------------------------------------
 * `mandatory: true` means a LICENCE requires this credit to be displayed.
 * Removing one is a licence violation, not a cosmetic edit. Everything else is
 * CC0 or explicitly attribution-optional and is listed out of courtesy and for
 * provenance.
 *
 * Right now there is exactly ONE mandatory entry: the login dragon. It used to
 * be two — the 魔王魂 BGM was the other — but all eleven tracks are now
 * generated by tools/bgm-gen and no 魔王魂 music ships, so that obligation is
 * gone. See content/assets/CREDITS.md, which this file mirrors for the client
 * (that document stays the authoritative record, including the provenance this
 * page does not need to show a player).
 */

export interface CreditEntry {
  /** Section heading in the page. */
  readonly what: string;
  readonly title: string;
  readonly author: string;
  readonly license: string;
  readonly licenseUrl?: string;
  readonly sourceUrl?: string;
  /** true = a licence REQUIRES this to be shown. Do not remove without checking. */
  readonly mandatory: boolean;
  /** Usage terms worth restating to anyone reading, beyond the licence name. */
  readonly terms?: string;
}

export const COPYRIGHT_LINE = "© 2026 Moriyamouse/Adms 糟糕騎士團";

export const CREDITS: readonly CreditEntry[] = [
  {
    what: "登入畫面 巨龍",
    title: "Animated Dragon Three Motion Loops",
    author: "LasquetiSpice",
    license: "CC-BY 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by/4.0/",
    sourceUrl:
      "https://sketchfab.com/3d-models/animated-dragon-three-motion-loops-eca98cf6cd084c1596cecf716e110c29",
    mandatory: true,
    terms: "本作品採用 CC-BY 4.0 授權，署名為授權條件，並非禮貌性標示。",
  },
  {
    what: "角色 / 場景 / 地形模型",
    title: "Character Pack: Adventurers · Dungeon Remastered · Medieval Hexagon Pack",
    author: "Kay Lousberg (KayKit)",
    license: "CC0",
    sourceUrl: "https://kaylousberg.com/",
    mandatory: false,
  },
  {
    what: "音效",
    title: "効果音ラボ",
    author: "効果音ラボ",
    license: "商用可・報告不要",
    sourceUrl: "https://soundeffect-lab.info/",
    mandatory: false,
    terms:
      "依其使用條款：不得用於 AI 學習素材，不得將語音裁切重組成新的語句，需以原始素材完整播放。",
  },
  {
    what: "背景音樂",
    title: "GGD 自製配樂（11 首）",
    author: "本專案 tools/bgm-gen 程式生成",
    license: "本專案自有",
    mandatory: false,
    terms: "全數由種子確定性生成，非第三方素材，無須署名。",
  },
];

/** The one-line label the login footer shows in place of the full list. */
export const CREDITS_LINK_LABEL = "版權聲明";
