/**
 * 鑄技工坊 — runtime param-schema synthesis.
 *
 * A template@1 doc declares its param slots as DATA (`{type,default,min,max,
 * unit,values}`). The editor's form is generated by walking a ZOD SHAPE. This
 * module is the one bridge between the two, and it lives in `shared` — next to
 * `expand()` — on purpose: the form, the pre-save validation and the golden
 * tests then provably agree on what a filled param set looks like, instead of
 * the editor re-deriving its own idea of the shape.
 *
 * `paramsSchemaFor(t)` → `z.object({...})` whose keys are the template's slots.
 * `defaultParamsFor(t)` → the slot defaults, which are the exemplar's MEASURED
 * JASS values (design §2.1) — NOT the form walker's `defaultValueFor`, which
 * would hand back 0 / min / first-enum and silently discard the whole
 *「預設值 = 範本實測」 premise.
 */
import { z } from "zod";
import { zScaling, zStatModifier } from "../schema/common";
import type { ParamSlot, TemplateDoc } from "../schema/template";

/** The Zod shape for ONE slot, before the `.optional()` wrapper. */
function slotSchema(slot: ParamSlot): z.ZodTypeAny {
  switch (slot.type) {
    case "number": {
      let s = z.number();
      // walk.ts reads `_def.checks` for min/max, so a range authored here
      // survives all the way into a clamped NumberField.
      if (slot.min !== undefined) s = s.min(slot.min);
      if (slot.max !== undefined) s = s.max(slot.max);
      // `unit` rides on the description; walk.ts surfaces `description` on the
      // node and only skips descriptions starting with "ref" (those are zRef's).
      return slot.unit !== undefined ? s.describe(`unit:${slot.unit}`) : s;
    }
    case "enum": {
      const values = slot.values ?? [];
      // z.enum needs a non-empty tuple; a values-less enum slot degrades to a
      // plain string rather than throwing at form-render time.
      if (values.length === 0) return z.string();
      return z.enum([values[0]!, ...values.slice(1)] as [string, ...string[]]);
    }
    case "scaling":
      return zScaling;
    case "statModifiers":
      return z.array(zStatModifier);
  }
}

/**
 * template@1 `params` (data) → a Zod object the editor's `walkZod` can render
 * and `safeParse` can validate. Optional slots become `.optional()`.
 */
export function paramsSchemaFor(t: TemplateDoc): z.ZodObject<z.ZodRawShape> {
  const shape: z.ZodRawShape = {};
  for (const [name, slot] of Object.entries(t.params)) {
    const s = slotSchema(slot);
    shape[name] = slot.optional === true ? s.optional() : s;
  }
  // NOT .strict(): `expand()` reads slots by name and ignores extras, so a
  // param left over from an older template version must not hard-fail the form.
  return z.object(shape);
}

/**
 * The measured defaults for every slot that has one. Optional slots ARE
 * included — in the editor a default is a pre-fill suggestion the designer can
 * clear, which is exactly what `has()` in expand.ts treats as "absent".
 */
export function defaultParamsFor(t: TemplateDoc): Record<string, unknown> {
  const out: Record<string, unknown> = {};
  for (const [name, slot] of Object.entries(t.params)) {
    if (slot.default !== undefined) out[name] = structuredCloneish(slot.default);
  }
  return out;
}

/**
 * Deep copy of a JSON-shaped default so two forms opened from the same template
 * can never alias (and mutate) the doc's own default object.
 */
function structuredCloneish<T>(v: T): T {
  if (v === null || typeof v !== "object") return v;
  return JSON.parse(JSON.stringify(v)) as T;
}

/**
 * Slots the sim will ignore because a capability the template `requires` is
 * absent. Purely presentational — the editor greys these and says 「本版不生效」.
 * P1's enabled 8 have no such slots; the drafts are where this bites.
 */
export function describeUnit(slot: ParamSlot): string | undefined {
  switch (slot.unit) {
    case "wc3u":
      return "WC3 距離單位";
    case "s":
      return "秒";
    case "count":
      return "次數";
    case "ratio":
      return "比例 (0-1)";
    default:
      return undefined;
  }
}
