from pathlib import Path
import sys,json,hashlib,datetime,shutil
ROOT=Path('/Users/Takuro/Dropbox/我的 Mac (Moriya.local)/Documents/ABxVFX_EDIT');BASE=ROOT/'GGD-Asset-Library/intake/public-models-20260910';P=BASE/'parallel-community-lina-rays-300-retarget-footloop-v2';OLD=BASE/'parallel-community-lina-rays-300-retarget';sys.path.insert(0,str(P/'scripts'));import glb_io as glb
now=datetime.datetime.now(datetime.timezone.utc).isoformat();sha=lambda f:hashlib.sha256(Path(f).read_bytes()).hexdigest();dump=lambda f,x:Path(f).write_text(json.dumps(x,ensure_ascii=False,indent=2)+'\n');entry=lambda f:{'path':str(Path(f).relative_to(P)),'bytes':Path(f).stat().st_size,'sha256':sha(f)}
pr=json.loads((P/'processing-proof.json').read_text());dense=json.loads((P/'evidence/footloop-dense-audit-960hz.json').read_text());srccompare=json.loads((P/'evidence/source-versus-retarget-foot-comparison.json').read_text());old=glb.read(pr['input']);new=glb.read(pr['output']);modelPath=Path(pr['output']);upstream=[]
for line in (OLD/'all-files.sha256.jsonl').read_text().splitlines():
 row=json.loads(line);f=OLD/row['path'];upstream.append({'path':str(f),'expectedSha256':row['sha256'],'sha256Now':sha(f),'unchanged':sha(f)==row['sha256']})
assert all(r['unchanged'] for r in upstream)
source_provenance=json.loads((OLD/'evidence/source-provenance.json').read_text());sourcechecks=[]
for row in source_provenance['files']:
 f=Path(row['path']);sourcechecks.append({**row,'sha256Now':sha(f),'unchanged':sha(f)==row['sha256']})
assert all(r['unchanged'] for r in sourcechecks)
preservation={'priorFrozenManifestRows':len(upstream),'allPriorFrozenManifestRowsUnchanged':True,'priorInputSha256Matches':sha(pr['input'])==pr['inputSha256'],'originalSourceChecks':sourcechecks,'priorManifestChecks':upstream,'allPriorBinaryPayloadUnchangedPrefix':new.bin[:len(old.bin)]==old.bin,'originalMeshSkinImageMaterialsUnchanged':{k:new.gltf.get(k)==old.gltf.get(k) for k in ['meshes','skins','images','textures','materials','samplers']},'nodeHierarchyUnchanged':[(n.get('name'),n.get('children')) for n in new.gltf['nodes']]==[(n.get('name'),n.get('children')) for n in old.gltf['nodes']],'sameOriginalAccessorDefinitions':new.gltf['accessors'][:len(old.gltf['accessors'])]==old.gltf['accessors'],'allOriginalWeightsAndInverseBindMatricesUnchanged':new.bin[:len(old.bin)]==old.bin};dump(P/'evidence/source-and-mesh-preservation.json',preservation)
differences=[]
for clip in dense:
 prior=clip['variants']['prior']['frames'];processed=clip['variants']['processed']['frames'];rows=[]
 for a,b in zip(prior,processed):
  assert a['seconds']==b['seconds'];r={'seconds':a['seconds'],'phase':a['phase']}
  for side in 'LR':r[side]={'bootMinYBefore':a[side]['minY'],'bootMinYAfter':b[side]['minY'],'bootMinYDelta':b[side]['minY']-a[side]['minY'],'soleCentroidDeltaXYZ':[y-x for x,y in zip(a[side]['soleCentroid'],b[side]['soleCentroid'])],'ankleDeltaXYZ':[y-x for x,y in zip(a[side]['ankle'],b[side]['ankle'])],'scheduledContact':b[side]['scheduledCoreContact']}
  rows.append(r)
 differences.append({'clip':clip['clip'],'sampleRateHz':960,'testActorSpeedMps':clip['speedMps'],'frames':rows})
dump(P/'evidence/processed-versus-prior-per-frame-difference.json',differences)
parameters={'sampling':'480 Hz union prior times; deduplicated after float32 conversion','sourceNativeFps':'unknown','clipDurationsPreserved':True,'idleDurationSeconds':1.21875,'runDurationSeconds':.40625,'loopBlend':{'startPhase':.82,'endPhase':1,'method':'smoothstep crossfade to backwards extrapolation of the first pose using a 1/240 s finite difference; intended seam-velocity matching is approximate and numerically measured','appendedDurationSeconds':0},'ik':{'algorithm':'analytic two-bone hip-knee-foot IK; target bone lengths unchanged','kneePoleWorldDirection':[0,0,1],'ankleReachEpsilonMeters':.00001,'skinBootGroundCorrectionIterations':2,'groundMarginMeters':.002,'idleFootGoal':'constant first-frame ankle XZ, flat first-frame idle foot orientation, grounded actual boot geometry','runFootGoal':'source-inferred stance windows; flat idle boot orientation; linear local backward translation during stance at fitted test speed','runContactPhaseCenters':{'R':.10,'L':.62},'runCoreHalfWidthPhase':.12,'runTransitionWidthPhase':.06},'pelvisAdditionalConstantYShiftMeters':{'idle':-.02,'run':-.06},'worldMotion':{'glb':'in-place; no new XZ root track','previewEntitySpeedMps':pr['testActorSpeedMps'],'speedDerivation':pr['speedFit'],'speedIsCanonicalOrDefault':False,'caution':'Two source legs fit different speeds, approximately 5.47 and 3.58 m/s after scaling; 4.522 is the mean for this bounded test, not a verified game setting.'},'maximumLocalRotationChangeDegrees':{c['sourceClip']:max(v for f in c['frames'] for v in f['localRotationDeltaDegrees'].values()) for c in pr['clips']},'maximumIKUnreachableDistanceMeters':max(f['legs'][s]['ik']['unreachableDistance'] for c in pr['clips'] for f in c['frames'] for s in 'LR')};dump(P/'processing-parameters.json',parameters)
limits=['All motions are 300英雄動作重綁到Rays模型，再作落地與循環加工; 0 native Rays animations and no new walk. Existing GGD 300 GLB durations remain unchanged; native JUMPX FPS is unknown.','Source comparison diagnoses the existing GGD 300 conversion, not the original running game. Native JUMPX was not decoded again, so native-game foot defects are not established.','Foot locking depends on the derived 4.522414609 m/s external actor test speed and configured stance windows. This is not a default gameplay speed; turning, acceleration, other speeds and terrain were not tested.','Run left foot retains a rare 1.995 m/s horizontal contact-speed spike and up to 6.79 mm core-phase boot clearance; IK target reach can miss by up to 10.4 mm.','Run endpoint foot positions close exactly in sampled output; velocity seam remains about 0.118 m/s, not a proven perfect C1 loop.','IK changes lower-body posing materially: maximum local rotation change roughly 21.3 degrees idle / 67.4 degrees run. Do not describe the result as unchanged source motion.','The fixed world +Z knee pole is suitable only for this forward-facing bounded sample; it is not a general turning or arbitrary-animation retarget system.','Hair/cape/accessory secondary animation remains absent. Cape remains visibly broad and rigid; fingers remain the selected single relaxed hand meshes.','960 Hz CPU skin audit proves sampled flat-ground metrics only. Whole-body self collision, arbitrary terrain, game runtime, transitions between clips and backend selection remain unverified.','Structural validator has 0 errors / 0 warnings, plus 43 information messages: 42 intentionally retained unused prior animation accessors and one unsupported FB_ngon_encoding extension.']
reviewed=['processed-idle-front-000.png','processed-idle-side-000.png','processed-run-front-000.png','processed-run-side-000.png','processed-run-side-250.png','processed-run-side-500.png','processed-run-side-750.png','processed-run-front-500.png','processed-worldspeed-actual-frame-1000.png','processed-worldspeed-actual-frame-1500.png','processed-run-side-625.png','processed-run-front-750.png'];visual={'schema':'ggd-derived-footloop-visual-review@1','renderer':'Babylon.js 7.54.3 actual animation group playback in dedicated local headless Chrome','sourceVsPriorComparison':[{'clip':x['clip'],'endpointComparison':x['endpointComparison']} for x in srccompare],'groundMetrics':[{'clip':x['clip'],'testActorSpeedMps':x['speedMps'],'variants':{k:v['feet'] for k,v in x['variants'].items()}} for x in dense],'visuallyReviewedImages':[str(P/'evidence/playback'/n) for n in reviewed],'renderedPhaseImages':64,'imagesExtractedFromActualWorldspeedVideo':2,'actualPlaybackWebmFiles':6,'previewMp4Files':4,'allPlaybackVideos':{'decodedFramesEach':78,'distinctFrameHashesEach':78},'visualFindings':['Single relaxed pair of hands, face, textures and body proportions remain coherent.','Idle feet are fixed and grounded; the additional pelvis drop makes knees visibly more bent.','Run stance feet visibly reach the floor at phases where the earlier sample floated; leg stride remains recognizable.','No obvious new whole-limb inversion appears in the 12 inspected images. Footplant adjustment straightens the front leg during some phases; this is a material pose edit.','The moving-entity playback renders actual Babylon animation and external test translation, with camera following; it does not modify the GLB root motion.'],'runtimeReady':False,'sampledGroundClearancePass':True,'sampledLoopPositionClosurePass':True,'fullFootPlantPass':False,'limitations':limits};dump(P/'visual-review.json',visual)
priorCandidate=json.loads((OLD/'model-candidates.json').read_text())['candidates'][0];candidate={**priorCandidate,'candidateId':'community.slayers-tales-of-rays.lina00-hands-a.300heroes-footplant-loop-review','sourceCandidateId':priorCandidate['candidateId'],'sourceId':P.name,'upstreamSourceId':OLD.name,'label':'莉娜 lina00 放鬆手型 — 300英雄 idle/run 落地與循環加工版（條件式驗證）','resourceRole':'character-body-retarget-footplant-loop-review','animationProvenanceLabel':'300英雄動作重綁到Rays模型，再作落地與循環加工','localPath':str(modelPath),'file':entry(modelPath),'readiness':'review-sample-ground-and-loop-improved-gameplay-pending','runtimeReady':False,'eligibleForAutomaticDefault':False,'backendSelectableVerified':False,'processingParametersPath':str(P/'processing-parameters.json'),'testActorSpeedMps':pr['testActorSpeedMps'],'animations':[{'name':c['outputClip'],'sourceClip':c['sourceClip'],'durationSeconds':c['durationSeconds'],'outputKeys':len(c['outputTimes']),'resamplingHz':c['samplingHz'],'nativeRaysAnimation':False,'durationChanged':False,'seamProcessing':True,'footIKProcessing':True} for c in pr['clips']],'validation':{'khronosErrors':0,'khronosWarnings':0,'khronosInfos':43,'khronosTruncated':False,'assimpReadback':True,'meshWeightsTexturesAndBindMatricesUnchanged':True,'actualBabylonPlayback':True,'sampledGroundClearancePass':True,'sampledLoopPositionClosurePass':True,'contactSlidingImprovedAtSpecifiedTestSpeed':True,'fullFootPlantPass':False,'runtimeReady':False},'limitations':limits}
# Do not retain the earlier rootMotion description as if it describes all subsequent processing.
candidate['rootMotion']={'horizontal':'in-place source-derived retarget; no XZ root track added','vertical':'prior root bob and ground offsets preserved, then pelvis lowered 2 cm idle / 6 cm run; periodic processing of final 18%','footIK':'two-bone IK with flat boot contact windows and per-key actual boot ground correction','externalPreviewEntitySpeedMps':pr['testActorSpeedMps'],'canonicalGameSpeed':False,'sourceDurationsPreserved':True};intermediate=entry(P/'candidates/lina00-hands-a-300-idle-run-footplant-initial-knee-pole.glb');dump(P/'model-candidates.json',{'schema':'ggd-local-model-candidates@1','generatedAt':now,'candidates':[candidate],'auditIntermediates':[{'file':intermediate,'resourceRole':'failed-interpolation-audit-control','automaticallySelectable':False,'reason':'Initial FK-derived knee pole caused up to 3.4 cm between-key penetration despite key-frame contact; superseded by fixed pole and denser sampling.'}],'noDefaultChanges':True});dump(P/'audio-index.json',{'schema':'ggd-source-audio-index@1','sourceId':P.name,'groups':[],'nativeAudioFiles':0,'playableVoiceFiles':0,'note':'No new game audio. Silent validation videos are evidence, not audio assets.'})
md=['# 莉娜 idle/run：落地與循環加工第二版\n','交付 **1 個條件式驗證候選、2 段衍生動作**。960 Hz 幾何檢查已消除本批抽樣內的靴底穿地與循環位置跳差；待機腳步已固定。跑步仍有少數 IK 接觸尖峰及未驗證的遊戲整合條件，所以維持 `runtimeReady=false`，不修改任何預設。\n',f'[主要 GLB](<{modelPath}>) · [候選索引](<{P/"model-candidates.json"}>) · [加工參數](<{P/"processing-parameters.json"}>) · [完整逐幀差值](<{P/"evidence/processed-versus-prior-per-frame-difference.json"}>)\n','**標示必須是「300英雄動作重綁到Rays模型，再作落地與循環加工」**。沒有新增 walk，沒有 Rays 原生動畫，沒有把加工版宣稱為原作原樣擷取。原生 JUMPX FPS 仍未知；兩段長度維持 1.21875 秒／0.40625 秒。\n','既有 GGD 300 GLB 的跑步已包含約 4.98 cm 靴底穿地、左右 6.71／3.82 cm 循環足部差。按 Rays 腿長換算，端點差約 12.58／7.15 cm；前版重綁為 10.07／6.26 cm。因此跑步接縫問題早於本次重綁，但本輪没有重新解碼 JUMPX，不能據此說原生遊戲就有問題。相反地，300 GLB 的 idle 腳步穩定，前版額外近 1 cm 晃動主要來自重綁。\n','| 指標 | 前版 | 本版 |\n|---|---:|---:|','| idle 靴底高度，左／右 | 約 14.1／2.0 mm | 約 2.0／2.0 mm |','| idle 足部水平晃動範圍 | 最大約 9.5 mm | <0.001 mm（浮點誤差量級） |','| run 最低靴底，左／右 | +0.55／−1.24 mm | +1.02／+1.53 mm |','| run 循環足部位置差，左／右 | 100.7／62.6 mm | 0／0 mm |','| run 循環足部速度差，左／右 | 8.45／6.68 m/s | 0.117／0.118 m/s |','| run 指定接地窗足滑 P95，左／右 | 15.45／14.59 m/s | 0.0192／0.00492 m/s |\n','跑步足滑數字以 **4.522414609 m/s 外部角色移速** 計算。這個值是來源兩腿接地階段腳踝相對根位移擬合值的平均（兩腿各約 5.47／3.58 m/s），不是官方移速、不是後台預設。GLB 仍為原地動作；worldspeed 影片只在預覽場景額外移動角色並讓鏡頭跟隨。更換速度、轉彎、加減速與坡地都尚未驗收。\n','仍有例外：左腳接地瞬間足滑最高約 1.995 m/s，接地窗靴底最高約 6.79 mm；IK 最大可達性誤差約 10.4 mm。循環足部位置已接合，但速度還有約 0.118 m/s 差異，不能稱完美平滑循環。\n','加工包含：480 Hz 加前版關鍵時間、float32 去除重複時間；最後 18% 與首段反向外插姿態平滑混合；idle／run 骨盆另下移 2／6 cm；雙骨 IK 使用固定世界 +Z 膝蓋方向；指定跑步接地窗與平放靴子；每關鍵幀兩次實際蒙皮靴底高度校正。完整參數與每關鍵幀旋轉／根位移差均可查詢。\n','姿勢改動不是微小誤差：最大局部關節改動約 idle 21.3°、run 67.4°。站姿膝蓋更彎，跑步部分前腿更直。貼圖、幾何、UV、權重、69 個關節、單一左右手型與逆綁定矩陣未修改。披風和髮絲仍沒有次級動態，跑步披風仍僵硬。\n',f'[待機影片](<{P/"evidence/playback/processed-idle-inplace-playback.mp4"}>) · [原地跑步影片](<{P/"evidence/playback/processed-run-inplace-playback.mp4"}>) · [指定移速跑步影片](<{P/"evidence/playback/processed-run-worldspeed-playback.mp4"}>) · [前版同移速對照](<{P/"evidence/playback/prior-run-worldspeed-playback.mp4"}>)\n',f'![待機]({P/"evidence/playback/processed-idle-front-000.png"})\n',f'![跑步接地]({P/"evidence/playback/processed-run-side-625.png"})\n','實際 Babylon 影片 6 支，每支成功解碼 78 幀且幀哈希全部不同；同相位截圖 64 張，另擷取兩張實際移動影片畫面，本輪實際檢視 12 張。Khronos 0 errors／0 warnings；43 條資訊訊息為保留前版動畫 accessor 及不支援的 FB_ngon_encoding。Assimp 可讀回。\n','前批 150 列 SHA-256 manifest 全部讀回一致；300 來源 GLB、原始 JUMPX、前批原模型都保留。第一個 IK 膝蓋方向實驗雖關鍵幀腳底正常，插值仍穿地最多 3.4 cm，已保存為明示不可選取的對照；本版修正固定膝蓋方向及更密取樣後通過前述幾何檢查。\n','沒有更動中央文件、角色預設、Git、S3 或後台。這是可審查／可繼續調整的獨立來源候選，正式遊戲狀態機、碰撞、地形與操作體感仍待驗收。\n'];(P/'REVIEW.md').write_text('\n'.join(md))
# Save a recoverable description of the earlier knee-pole experiment without running it.
s=(P/'scripts/ggd-lina-footloop-process.py').read_text().replace('pole=np.array([0.,0.,1.])-u*u[2]','pole=K-H-u*np.dot(K-H,u)').replace('d*480)+1','d*240)+1').replace("'samplingHz':480","'samplingHz':240").replace('lina00-hands-a-300-idle-run-footplant-loop-v2.glb','lina00-hands-a-300-idle-run-footplant-initial-knee-pole.glb').replace("P/'processing-proof.json'","P/'evidence/initial-knee-pole-processing-proof.json'");(P/'scripts/reproduce-initial-knee-pole-audit-control.py').write_text(s)
if (P/'scripts/__pycache__').exists():shutil.rmtree(P/'scripts/__pycache__')
shutil.copyfile('/private/tmp/ggd-lina-footloop-freeze.py',P/'scripts/ggd-lina-footloop-freeze.py')
files=[entry(f) for f in sorted(P.rglob('*')) if f.is_file() and f.name not in ['all-files.sha256.jsonl','SHA256SUMS','source-report.json']];(P/'all-files.sha256.jsonl').write_text(''.join(json.dumps(f,ensure_ascii=False)+'\n' for f in files));(P/'SHA256SUMS').write_text(''.join(f['sha256']+'  '+f['path']+'\n' for f in files))
source={'id':P.name,'title':'Lina Rays × 300 heroes derived footplant and loop repair review','sourceUrl':candidate['sourceUrl'],'upstreamSourceId':OLD.name,'localRoot':str(P),'localRootStable':True,'status':'frozen-derived-footplant-loop-review-gameplay-pending','candidateCount':1,'distinctCharacterBodies':1,'totalGlbFiles':2,'auditIntermediateGlbFiles':1,'nativeRaysAnimationClips':0,'derivedAnimationClips':2,'sourceWalkAvailable':False,'nativeAnimationFps':'unknown','audioFiles':0,'downloadedNewAssets':False,'modelCandidateIndexPath':str(P/'model-candidates.json'),'modelCandidateIndexSha256':sha(P/'model-candidates.json'),'visualReviewPath':str(P/'visual-review.json'),'visualReviewSha256':sha(P/'visual-review.json'),'audioIndexPath':str(P/'audio-index.json'),'audioIndexSha256':sha(P/'audio-index.json'),'allFilesManifestPath':str(P/'all-files.sha256.jsonl'),'allFilesManifestSha256':sha(P/'all-files.sha256.jsonl'),'manifestRows':len(files),'manifestAssetBytes':sum(f['bytes'] for f in files),'modelCandidates':[candidate],'runtimeReady':False,'backendSelectableVerified':False,'sharedIndexesChanged':False,'gitChanged':False,'s3Uploaded':False,'manualDefaultsChanged':False,'upstreamFrozenFilesUnchanged':True,'limits':limits}
report={'schema':'ggd-parallel-source-acquisition-report@1','generatedAt':now,'sources':[source],'sharedIndexesChanged':False,'gitChanged':False,'s3Uploaded':False,'pending':['Gameplay locomotion at real movement speeds, turning, terrain, transitions, secondary motion and rare left foot contact spike remain to be reviewed.']};dump(P/'source-report.json',report);dump('/private/tmp/ggd-parallel-lina-footloop-report.json',report)
for row in files:
 f=P/row['path'];assert f.stat().st_size==row['bytes'] and sha(f)==row['sha256']
allfiles=[f for f in P.rglob('*') if f.is_file()];print(json.dumps({'report':'/private/tmp/ggd-parallel-lina-footloop-report.json','reportSha256':sha('/private/tmp/ggd-parallel-lina-footloop-report.json'),'files':len(allfiles),'bytes':sum(f.stat().st_size for f in allfiles),'manifestRows':len(files),'manifestSha256':sha(P/'all-files.sha256.jsonl'),'candidateSha256':sha(modelPath)},ensure_ascii=False,indent=2))
